### ISSUE TITLE
Add Nextcloud specific server side encryption support

### ISSUE THREAD

**Issue by ghost** [ONLYOFFICE/onlyoffice-nextcloud#100]
I will reference this topic of a colective that are using Nextcloud:
https://forum.disroot.org/t/what-do-you-think-about-use-onlyoffice-instead-collabora-online/3132

**Comment by alexanderonlyoffice** [comment]
Hello @ghost, 
We are glad to announce that we added support of encryption with the per-user encryption keys in the latest version of ONLYOFFICE integration application for Nextcloud. Please update the connector and check the functioning of Document Server with Nextcloud.

We would appreciate to get your feedback about this enhancement. It will help us in improving the product.

**Comment by quentinDupont** [comment]
@alexanderonlyoffice  Do you have some news about compatibility between ONLYOFFICE and user encryption ?
I have last Nextcloud HUB II (v23) and last docker Onlyoffice but it doesn't work :cry: 
![image](https://user-images.githubusercontent.com/9005817/147363438-7baa40c3-2dbb-4ec3-a74e-d93f087c2589.png)
