### ISSUE TITLE
Opening shared PDF through Nextcloud Fileviewer works but throws an error message "there is no plugin available to display this file type"

### ISSUE THREAD

**Issue by Mer0me** [ONLYOFFICE/onlyoffice-nextcloud#1001]
Sorry for this long title, but each word is important. :)

Onlyoffice is set to open PDF files on my nextcloud instance. It works perfectly when you open the PDF through a nextcloud internal link (/f/<fileid>), but when the PDF is shared (/s/<filetoken>), the nextcloud viewer claims "there is no plugin available to display this file type" before opening the file very well with onlyoffice.

files_pdfviewer app is disabled.

Is there a way to avoid this error message ?

Nextcloud 29.0.2
OnlyOffice server 8.1
OnlyOffice App 9.2.2

**Comment by alexanderonlyoffice** [comment]
hello @Mer0me, unfortunately, we cannot reproduce the case on our end. Is it possible to get a test account on your instance? If yes, please send the credentials to support@onlyoffice.com with a subject "For technical support 2 Level".

**Comment by Mer0me** [comment]
Hello, you don't need an account as the error message appears for shared PDF.
I've just sent you a link to a shared PDF showing the error message.
I manage two instances of Nextcloud and they both have this behavior.

**Comment by alexanderonlyoffice** [comment]
Ok, thank you. We are analyzing it at the moment. 

Please specify the full list of the apps installed on both of your Nextcloud instances, it might be that some app except files_pdfviewer is affecting it.

**Comment by Mer0me** [comment]
Instance 1 : 

Enabled:
  - activity: 2.21.1
  - admin_audit: 1.19.0
  - calendar: 4.7.6
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - comments: 1.19.0
  - contacts: 6.0.0
  - contactsinteraction: 1.10.0
  - dashboard: 7.9.0
  - dav: 1.30.1
  - deck: 1.13.0
  - drawio: 3.0.2
  - external: 5.4.0
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.0
  - files_downloadlimit: 2.0.0
  - files_external: 1.21.0
  - files_linkeditor: 1.1.20
  - files_mindmap: 0.0.30
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_texteditor: 2.15.1
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - forms: 4.2.4
  - guests: 3.1.0
  - impersonate: 1.16.0
  - integration_giphy: 1.0.10
  - integration_mastodon: 2.0.5
  - integration_openai: 2.0.1
  - integration_openstreetmap: 1.0.12
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - mail: 3.7.1
  - news: 24.0.0
  - nextcloud_announcements: 1.18.0
  - notifications: 2.17.0
  - notify_push: 0.6.12
  - oauth2: 1.17.0
  - onlyoffice: 9.2.2
  - password_policy: 1.19.0
  - passwords: 2024.5.20
  - phonetrack: 0.8.1
  - photos: 2.5.0
  - polls: 7.1.2
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - related_resources: 1.4.0
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - spreed: 19.0.3
  - stt_helper: 1.1.1
  - support: 1.12.0
  - systemtags: 1.19.0
  - tasks: 0.16.0
  - text: 3.10.0
  - theming: 2.4.0
  - thesearchpage: 1.2.7
  - twofactor_backupcodes: 1.18.0
  - updatenotification: 1.19.1
  - user_status: 1.9.0
  - viewer: 2.3.0
  - weather_status: 1.9.0
  - workflowengine: 2.11.0


Instance 2 : 
root@cloud:/var/www/nextcloud# sudo -u www-data php8.1 occ app:list
Enabled:
  - activity: 2.21.1
  - admin_audit: 1.19.0
  - analytics: 4.14.0
  - announcementcenter: 6.8.1
  - calendar: 4.7.6
  - cfg_share_links: 5.1.0
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - comments: 1.19.0
  - contacts: 6.0.0
  - contactsinteraction: 1.10.0
  - dashboard: 7.9.0
  - dav: 1.30.1
  - deck: 1.13.0
  - drawio: 3.0.2
  - external: 5.4.0
  - extract: 1.3.6
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.0
  - files_accesscontrol: 1.19.1
  - files_automatedtagging: 1.19.0
  - files_downloadlimit: 2.0.0
  - files_external: 1.21.0
  - files_linkeditor: 1.1.20
  - files_lock: 29.0.1
  - files_mindmap: 0.0.30
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_texteditor: 2.15.1
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - files_zip: 1.5.0
  - forms: 4.2.4
  - groupfolders: 17.0.1
  - guests: 3.1.0
  - impersonate: 1.16.0
  - integration_giphy: 1.0.10
  - integration_openai: 2.0.1
  - integration_replicate: 3.0.0
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - mail: 3.7.1
  - nextcloud_announcements: 1.18.0
  - notifications: 2.17.0
  - notify_push: 0.6.12
  - oauth2: 1.17.0
  - onlyoffice: 9.2.2
  - password_policy: 1.19.0
  - passwords: 2024.5.10
  - photos: 2.5.0
  - polls: 7.1.1
  - provisioning_api: 1.19.0
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - spreed: 19.0.3
  - systemtags: 1.19.0
  - tables: 0.7.3
  - tasks: 0.16.0
  - text: 3.10.0
  - text_templates: 1.0.5
  - theming: 2.4.0
  - theming_customcss: 1.16.0
  - thesearchpage: 1.2.7
  - twofactor_backupcodes: 1.18.0
  - twofactor_totp: 11.0.0-dev
  - updatenotification: 1.19.1
  - user_ldap: 1.20.0
  - user_status: 1.9.0
  - user_usage_report: 1.13.0
  - viewer: 2.3.0
  - weather_status: 1.9.0
  - workflow_pdf_converter: 1.14.0
  - workflowengine: 2.11.0

**Comment by Mer0me** [comment]
Nevermind, you point me to the right direction. We have customized an application and this was the faulty one.
I'm sorry.

**Comment by Mer0me** [comment]
We have used the file_pdfviewer app as a template for an app displaying eml messages through the nextcloud viewer.
For some reason, this new app seems to react when a PDF is opened by onlyoffice, we have to figure out why. It's a very specific use case, I doubt someone else encounter the problem...

**Comment by alexanderonlyoffice** [comment]
Ok, thank you very much for the clarification.
