### ISSUE TITLE
Encryption with Masterkey OO not working

### ISSUE THREAD

**Issue by ExaconAT** [ONLYOFFICE/onlyoffice-nextcloud#101]
Hello,

i've enabled oo and encryption (with master key) -NC 12.0.04 - i'm not able to open, create & open new OO linked documents.

Secret Key enabled.

Help appreciated

BR

**Comment by alexanderonlyoffice** [comment]
Hello @ExaconAT,
We are glad to announce that we added support of encryption with the per-user encryption keys in the latest version of ONLYOFFICE integration application for Nextcloud. Please update the connector and check the functioning of Document Server with Nextcloud.

We would appreciate to get your feedback about this enhancement. It will help us in improving the product.

**Comment by Tune389** [comment]
> 
> 
> Hello @ExaconAT,
> We are glad to announce that we added support of encryption in the latest version of ONLYOFFICE integration application for Nextcloud. Please update the connector and check the functioning of Document Server with Nextcloud.
> 
> We would appreciate to get your feedback about this enhancement. It will help us in improving the product.

I just did a fresh Install with onlyoffice today and run in this problem. I still get the error "Can not decrypt this file ..." with the new Version 2.4.0.

**Comment by HelenBelova17** [comment]
Hello, @**Tune389**,
Describe your issue step by step and send a screenshot of the error and a screenshot of Server-side encryption page.

**Comment by Tune389** [comment]
> 
> 
> Hello, @**Tune389**,
> Describe your issue step by step and send a screenshot of the error and a screenshot of Server-side encryption page.

There are not many steps - I just open a file with Onlyoffice and the error appears after some seconds loading. After I click "ok" it closes.

Error:
![grafik](https://user-images.githubusercontent.com/4512259/61790051-89726580-ae16-11e9-8376-412113c53779.png)

You mean this page?
![grafik](https://user-images.githubusercontent.com/4512259/61790152-c3dc0280-ae16-11e9-9e30-b701e73fc4c0.png)

**Comment by HelenBelova17** [comment]
@**Tune389** 
From your screenshot I see you using user encription, no master key. ONLYOFFICE can correctly work only with master encryption. We have some problem with user encryption we work on.

**Comment by quentinDupont** [comment]
@HelenBelova17 Do you have some news about compatibility between ONLYOFFICE and user encryption ?
I have last Nextcloud HUB II (v23) and last docker Onlyoffice but it doesn't work :cry: 
![image](https://user-images.githubusercontent.com/9005817/147363371-b371ecfa-0aab-4cc6-90cc-a6427daa40a8.png)
