### ISSUE TITLE
DocumentConversionException Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by rsedlmeier** [ONLYOFFICE/onlyoffice-nextcloud#1012]
Since the upgrade from 28.0.6 to 29 now 29.0.4 I get 1000s of this errors.
It seams to follow a bad conversion error I get right before:

ServerException
Server error: `POST https://mydomain.com/cloud/index.php/apps/documentserver_community/ConvertService.ashx` resulted in a `500 Internal Server Error` response: <!DOCTYPE html> <html class="ng-csp" data-placeholder-focus="false" lang="en" data-locale="en" translate="no" > <head (truncated...)
getConvertedUri: from pdf to jpeg

This is the complete error stack msg of the issue above:
`{"reqId":"EPOdsiCkUhG3r5BrV6CK","level":3,"time":"2024-07-25T07:11:05+00:00","remoteAddr":"185.162.220.32","user":"--","app":"index","method":"POST","url":"/cloud/index.php/apps/documentserver_community/ConvertService.ashx","message":"Segmentation fault (core dumped)\n","userAgent":"Nextcloud Server Crawler","version":"29.0.4.1","exception":{"Exception":"OCA\\DocumentServer\\Document\\DocumentConversionException","Message":"Segmentation fault (core dumped)\n","Code":0,"Trace":[{"file":"/cloud/www/cloud/apps/documentserver_community/lib/DocumentConverter.php","line":125,"function":"run","class":"OCA\\DocumentServer\\Document\\ConverterBinary","type":"->"},{"file":"/cloud/www/cloud/apps/documentserver_community/lib/DocumentConverter.php","line":113,"function":"runCommand","class":"OCA\\DocumentServer\\DocumentConverter","type":"->"},{"file":"/cloud/www/cloud/apps/documentserver_community/lib/DocumentConverter.php","line":49,"function":"convertFiles","class":"OCA\\DocumentServer\\DocumentConverter","type":"->"},{"file":"/cloud/www/cloud/apps/documentserver_community/lib/Document/DocumentStore.php","line":98,"function":"getEditorBinary","class":"OCA\\DocumentServer\\DocumentConverter","type":"->"},{"file":"/cloud/www/cloud/apps/documentserver_community/lib/LocalAppData.php","line":102,"function":"OCA\\DocumentServer\\Document\\{closure}","class":"OCA\\DocumentServer\\Document\\DocumentStore","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/cloud/www/cloud/apps/documentserver_community/lib/Document/DocumentStore.php","line":97,"function":"getReadWriteLocalPath","class":"OCA\\DocumentServer\\LocalAppData","type":"->"},{"file":"/cloud/www/cloud/apps/documentserver_community/lib/Controller/ConvertController.php","line":59,"function":"getDocumentForEditor","class":"OCA\\DocumentServer\\Document\\DocumentStore","type":"->"},{"file":"/cloud/www/cloud/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"convert","class":"OCA\\DocumentServer\\Controller\\ConvertController","type":"->"},{"file":"/cloud/www/cloud/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/cloud/www/cloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/cloud/www/cloud/lib/private/Route/Router.php","line":338,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/cloud/www/cloud/lib/base.php","line":1050,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/cloud/www/cloud/index.php","line":49,"function":"handleRequest","class":"OC","type":"::"}],"File":"/cloud/www/cloud/apps/documentserver_community/lib/Document/ConverterBinary.php","Line":67,"message":"Segmentation fault (core dumped)\n","exception":[],"CustomMessage":"Segmentation fault (core dumped)\n"},"id":"66a21f13be406"}
`

- However, onlyoffice works in a browser using nextcloud.
- I reinstalled the document_server and the issue persists

Does anyone have the same issue and/or idea whats it about?

Thanks, ROland

**Comment by LinneyS** [comment]
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://forum.onlyoffice.com/t/community-document-server-app-in-nextcloud-18/268).

**Comment by rsedlmeier** [comment]
Thanks for the hint and the link

/R

Von: Sergey Linnik ***@***.***>
Gesendet: Donnerstag, 25. Juli 2024 12:15
An: ONLYOFFICE/onlyoffice-nextcloud ***@***.***>
Cc: rsedlmeier ***@***.***>; Author ***@***.***>
Betreff: Re: [ONLYOFFICE/onlyoffice-nextcloud] DocumentConversionException Segmentation fault (core dumped) (Issue #1012)


Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository.

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation guide<https://api.onlyoffice.com/editors/nextcloud>), we will be glad to answer your questions. Please see more info on our forum<https://forum.onlyoffice.com/t/community-document-server-app-in-nextcloud-18/268>.
