### ISSUE TITLE
Failure on editors_check_interval

### ISSUE THREAD

**Issue by kaibae19** [ONLYOFFICE/onlyoffice-nextcloud#1016]
I have an issue with Nextcloud and Onlyoffice where I can successfully connect the editors to Nextcloud via the web GUI, however, it will disconnect after about a day.  Following the commentary related to the previous issues with this similar problem, I have run into the following problem:

NC is installed in non-webroot at: https://server.example.com/cloud
Editors is on a separate server: https://editors.example.com

When connecting the editors through the NC admin web interface, the editors connection is successful:
 
![Screenshot 2024-08-08 at 10 15 53 AM](https://github.com/user-attachments/assets/38d28f4e-c315-4ae1-a484-8fb89e27cfac)

When checking through the occ command, which I assume is what is being run on a cron job daily which causes the break, I receive an error:

```
$ php occ onlyoffice:documentserver --check
Error connection: Error occurred in the document service: Error while downloading the document file to be converted.
```

I see in the access log for the documentserver a double /cloud/cloud/ in the URL webroot on the request which is causing the failure:

`documentserver         | [2024-08-08T17:04:15.057] [ERROR] [localhost] [check_1777374027] [userId] nodeJS - error downloadFile:url=https://box.example.com/cloud/cloud/index.php/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.atHkVhsGc5-AfJg490jv-hDcqpQmJJqLl9fyaJ2dfQE;attempt=3;code:null;connect:null Error: Error response: statusCode:404;`

This is only happening in the CLI and cron runs of this check.  NC is set to add the /cloud webroot in its config.php:

```
  'overwritehost' => 'box.example.com',
  'overwriteprotocol' => 'https',
  'overwritewebroot' => '/cloud',
  'overwrite.cli.url' => 'https://box.example.com/cloud',
```

To work around this issue, I have disabled the editors check interval, however, there seems to be an issue with the way the URL is built perhaps in conjunction with the way that NC is handling the request.  It seems odd that it works correctly in the web GUI, however, the CLI checks on the connector fail.

**Comment by kaibae19** [comment]
Further troubleshooting seems to indicate this is a problem with NC generating the URL.  Disregard

**Comment by rizlas** [comment]
Is this fixed?
