### ISSUE TITLE
Uncaught TypeError: this.Ha.V0 is not a function

### ISSUE THREAD

**Issue by 5P5** [ONLYOFFICE/onlyoffice-nextcloud#1017]
document randomly crashed while editing. 
on trying to re-open shows error dialog: `An error has occurred while opening the file. Press "OK" to return to document list.`

<summary>
console shows js error:
<details>
<pre>
16:36:28.011 Uncaught TypeError: this.Ha.V0 is not a function
    cUb https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:6940
    Rh https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:7924
    Vmf https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all-min.js:1058
    YZd https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all-min.js:1061
    hZb https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all-min.js:1061
    Elc https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all-min.js:1462
    Tqh https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all-min.js:669
    Elc https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all-min.js:1462
    DTe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all-min.js:1461
    JOa https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5108
    isf https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all-min.js:1458
    o$b https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5104
    o$b https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5104
    o$b https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5104
    o$b https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5104
    o$b https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5104
    o$b https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5104
    o$b https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5104
    o$b https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5104
    o$b https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5104
    VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.o$b https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5104
    o$b https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5104
    VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
    setTimeout handler*a/this.VOe https://XXYY.ZZ/apps/documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/word/sdk-all.js:5105
sdk-all.js:6940:422
</pre>
</details>
</summary>

<summary>
nc log error:
<details>
<pre>
Error	documentserver_community	
DocumentConversionException
TypeError: this.Ha.V0 is not a function at ze.Eb.cUb (<anonymous>:18955:422) at mm.Rh (<anonymous>:19939:23) at wa.C.asc_docs_api.asc_nativeApplyChanges2 (<anonymous>:11255:127) Uncaught TypeError: this.Ha.V0 is not a function DoctRenderer:<result><error index="1004" /></result>
Error while applying changes for document 813937455
</pre>
</details>
</summary>

- is this error just caused by the corrupt document?
- how to determine what caused the random crash in the first place?

---
- Community Document Server 0.1.18
- ONLYOFFICE 9.3.0
- nc Version 28.0.8

**Comment by LinneyS** [comment]
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://forum.onlyoffice.com/t/community-document-server-app-in-nextcloud-18/268).
