### ISSUE TITLE
Support Encryption without Master Key

### ISSUE THREAD

**Issue by CordlessWool** [ONLYOFFICE/onlyoffice-nextcloud#102]
Hi,

I see it is now supported encryption with master key. Will there be any option to support encrypted nextcloud instances without master key in near future or why is it only supported with master key?

Because there are other plugins like draw.io, encryption is no problem.
Thanks

**Comment by alexanderonlyoffice** [comment]
Hello @CordlessWool, 
We are glad to announce that we added support of encryption with the per-user encryption keys in the latest version of ONLYOFFICE integration application for Nextcloud. Please update the connector and check the functioning of Document Server with Nextcloud.

We would appreciate to get your feedback about this enhancement. It will help us in improving the product.

**Comment by CordlessWool** [comment]
I configure everything, but when onlyoffice try to open the file it thows an error

`Error: Error response: statusCode:503 ;body:
<!DOCTYPE html>
<html class="ng-csp" data-placeholder-focus="false" lang="en" data-locale="en" >
	<head
 data-requesttoken="">
		<meta charset="utf-8">
		<title>
		Nextcloud		</title>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
		<meta name="apple-itunes-app" content="app-id=1125420102">
		<meta name="theme-color" content="#333333">
		<link rel="icon" href="/core/img/favicon.ico">
		<link rel="apple-touch-icon-precomposed" href="/core/img/favicon-touch.png">
		<link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#333333">
		<link rel="manifest" href="/apps/theming/manifest?v=15">
		<link rel="stylesheet" href="/custom_apps/apporder/css/apporder.css?v=638ee240-15">
<link rel="stylesheet" href="/apps/files_pdfviewer/css/style.css?v=35c36e89-15">
<link rel="stylesheet" href="/core/css/guest.css?v=d90a5ec5-15">
		<script nonce="U0ZoSmNybzBoenI0ZGx2NGJsNUhEbFE1RGo5QW5RdDNXT0pnTWQ4R3BvOD06Q1FJS0ZjTjh5MGk4RXdHM1ZpdHdlV1pvUDJ3eHFHQUFDcm9wV3FWRDRicz0=" defer src="/core/js/dist/main.js?v=d90a5ec5-15"></script>
<script nonce="U0ZoSmNybzBoenI0ZGx2NGJsNUhEbFE1RGo5QW5RdDNXT0pnTWQ4R3BvOD06Q1FJS0ZjTjh5MGk4RXdHM1ZpdHdlV1pvUDJ3eHFHQUFDcm9wV3FWRDRicz0=" defer src="/js/core/merged-template-prepend.js?v=d90a5ec5-15"></script>
<script nonce="U0ZoSmNybzBoenI0ZGx2NGJsNUhEbFE1RGo5QW5RdDNXT0pnTWQ4R3BvOD06Q1FJS0ZjTjh5MGk4RXdHM1ZpdHdlV1pvUDJ3eHFHQUFDcm9wV3FWRDRicz0=" defer src="/core/search/js/search.js?v=d90a5ec5-15"></script>
<script nonce="U0ZoSmNybzBoenI0ZGx2NGJsNUhEbFE1RGo5QW5RdDNXT0pnTWQ4R3BvOD06Q1FJS0ZjTjh5MGk4RXdHM1ZpdHdlV1pvUDJ3eHFHQUFDcm9wV3FWRDRicz0=" defer src="/apps/encryption/js/encryption.js?v=d90a5ec5-15"></script>
<script nonce="U0ZoSmNybzBoenI0ZGx2NGJsNUhEbFE1RGo5QW5RdDNXT0pnTWQ4R3BvOD06Q1FJS0ZjTjh5MGk4RXdHM1ZpdHdlV1pvUDJ3eHFHQUFDcm9wV3FWRDRicz0=" defer src="/core/js/dist/share_backend.js?v=d90a5ec5-15"></script>
<script nonce="U0ZoSmNybzBoenI0ZGx2NGJsNUhEbFE1RGo5QW5RdDNXT0pnTWQ4R3BvOD06Q1FJS0ZjTjh5MGk4RXdHM1ZpdHdlV1pvUDJ3eHFHQUFDcm9wV3FWRDRicz0=" defer src="/custom_apps/apporder/js/apporder.js?v=d90a5ec5-15"></script>
<script nonce="U0ZoSmNybzBoenI0ZGx2NGJsNUhEbFE1RGo5QW5RdDNXT0pnTWQ4R3BvOD06Q1FJS0ZjTjh5MGk4RXdHM1ZpdHdlV1pvUDJ3eHFHQUFDcm9wV3FWRDRicz0=" defer src="/apps/files_pdfviewer/js/previewplugin.js?v=d90a5ec5-15"></script>
<script nonce="U0ZoSmNybzBoenI0ZGx2NGJsNUhEbFE1RGo5QW5RdDNXT0pnTWQ4R3BvOD06Q1FJS0ZjTjh5MGk4RXdHM1ZpdHdlV1pvUDJ3eHFHQUFDcm9wV3FWRDRicz0=" defer src="/apps/files_rightclick/js/script.js?v=d90a5ec5-15"></script>
<script nonce="U0ZoSmNybzBoenI0ZGx2NGJsNUhEbFE1RGo5QW5RdDNXT0pnTWQ4R3BvOD06Q1FJS0ZjTjh5MGk4RXdHM1ZpdHdlV1pvUDJ3eHFHQUFDcm9wV3FWRDRicz0=" defer src="/apps/files_videoplayer/js/main.js?v=d90a5ec5-15"></script>
<script nonce="U0ZoSmNybzBoenI0ZGx2NGJsNUhEbFE1RGo5QW5RdDNXT0pnTWQ4R3BvOD06Q1FJS0ZjTjh5MGk4RXdHM1ZpdHdlV1pvUDJ3eHFHQUFDcm9wV3FWRDRicz0=" defer src="/core/search/js/searchprovider.js?v=d90a5ec5-15"></script>
<script nonce="U0ZoSmNybzBoenI0ZGx2NGJsNUhEbFE1RGo5QW5RdDNXT0pnTWQ4R3BvOD06Q1FJS0ZjTjh5MGk4RXdHM1ZpdHdlV1pvUDJ3eHFHQUFDcm9wV3FWRDRicz0=" defer src="/core/js/files/fileinfo.js?v=d90a5ec5-15"></script>
<script nonce="U0ZoSmNybzBoenI0ZGx2NGJsNUhEbFE1RGo5QW5RdDNXT0pnTWQ4R3BvOD06Q1FJS0ZjTjh5MGk4RXdHM1ZpdHdlV1pvUDJ3eHFHQUFDcm9wV3FWRDRicz0=" defer src="/core/js/files/client.js?v=d90a5ec5-15"></script>
		<link rel="stylesheet" href="/apps/theming/styles?v=15"/><script defer src="/apps/theming/js/theming?v=15" nonce="U0ZoSmNybzBoenI0ZGx2NGJsNUhEbFE1RGo5QW5RdDNXT0pnTWQ4R3BvOD06Q1FJS0ZjTjh5MGk4RXdHM1ZpdHdlV1pvUDJ3eHFHQUFDcm9wV3FWRDRicz0="></script><script defer src="/apps/accessibility/js/accessibility?v=0" nonce="U0ZoSmNybzBoenI0ZGx2NGJsNUhEbFE1RGo5QW5RdDNXT0pnTWQ4R3BvOD06Q1FJS0ZjTjh5MGk4RXdHM1ZpdHdlV1pvUDJ3eHFHQUFDcm9wV3FWRDRicz0="></script>	</head>
	<body id="body-login">
		<noscript>
	<div id="nojavascript">
		<div>
			This application requires JavaScript for correct operation. Please <a href="https://www.enable-javascript.com/" target="_blank" rel="noreferrer noopener">enable JavaScript</a> and reload the page.		</div>
	</div>
</noscript>
				<div class="wrapper">
			<div class="v-align">
									<header role="banner">
						<div id="header">
							<div class="logo">
								<h1 class="hidden-visually">
									Nextcloud								</h1>
															</div>
						</div>
					</header>
								<main>
					<div class="error">
	<h2>Error</h2>
	<ul>
			<li>
			<p>Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.</p>
					</li>
		</ul>
</div>
				</main>
			</div>
		</div>
		<footer role="contentinfo">
			<p class="info">
				<a href="https://nextcloud.com" target="_blank" rel="noreferrer noopener" class="entity-name">Nextcloud</a> – a safe home for all your data			</p>
		</footer>
	</body>
</html>

    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:256:18)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

`

**Comment by alexanderonlyoffice** [comment]
Hello @CordlessWool, please specify some additional information:

1. What is the address you enter when the error appears;
2. Which errors do you see in Nextcloud log?
3. What log did you take the part below from?

> at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:256:18)
> at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:185:22)
> at emitTwo (events.js:126:13)
> at Request.emit (events.js:214:7)
> at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1161:10)
> at emitOne (events.js:116:13)
> at Request.emit (events.js:211:7)
> at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1083:12)
> at Object.onceWrapper (events.js:313:30)
> at emitNone (events.js:111:20)
> at IncomingMessage.emit (events.js:208:7)
> at endReadableNT (_stream_readable.js:1064:12)
> at _combinedTickCallback (internal/process/next_tick.js:139:11)
> at process._tickCallback (internal/process/next_tick.js:181:9)
