### ISSUE TITLE
Reported as not compatible with NC 30.0

### ISSUE THREAD

**Issue by waja** [ONLYOFFICE/onlyoffice-nextcloud#1022]
Hi there,

as Nextcloud 30 was released yesterday, it might be blocking users from upgrading cause onlyoffice-nextcloud is reported as not compatible. Even it looks like there are technical changes needed to make it working with NC 30, looking at #1020.

Thanks, Jan.

**Comment by Ramalama2** [comment]
Same here, i dont want to switch to nextcloud office :-(

**Comment by GVLLIFESTYLE** [comment]
Same here.
I upgraded to nc 30 and since that onlyoffice does not work anymore.
The only way to make it work is to change the content security policy of nextcloud itself, but that destroys all other apps.
I hope there is an update soon.
