### ISSUE TITLE
Compatibility with Default encryption module

### ISSUE THREAD

**Issue by cwm77** [ONLYOFFICE/onlyoffice-nextcloud#103]
While trying to open a Document a Pop-Up plops up “Error” “Download failed” “OK”.

In log file following entry is logged: 
Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.

I assume that compatibility with Default encryption module is not given yet, correct?

Nextcloud  11.0.2 (stable)

**Comment by alexanderonlyoffice** [comment]
Hello! 
We are glad to announce that we added support of encryption with the per-user encryption keys in the latest version of ONLYOFFICE integration application for Nextcloud. Please update the connector and check the functioning of Document Server with Nextcloud.

We would appreciate to get your feedback about this enhancement. It will help us in improving the product.

**Comment by acsfer** [comment]
@alexanderonlyoffice @LinneyS as compatibility with default encryption module has been added, shouldn't the section https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/master/README.md#known-issues be updated too?

**Comment by quentinDupont** [comment]
Hello !
I have the same problem and yet, I'm at the last versions of Nextcloud (version 22), Onlyoffice app 7.1.2 and latest docker image of Community Server..
And we use default encryption module.

Anyone has the same issue ??
