### ISSUE TITLE
Spreadsheet external links

### ISSUE THREAD

**Issue by oohheenn** [ONLYOFFICE/onlyoffice-nextcloud#1036]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

8.1.3.4

### Expected Behavior

Working as indicates this:
https://helpcenter.onlyoffice.com/ONLYOFFICE-Editors/ONLYOFFICE-Spreadsheet-Editor/UsageInstructions/AddExternalLinks.aspx

After the "update", we want to copy any cell value and working normaly.

### Actual Behavior

After "update", if I want to copy a cell value, an error message is show on screen: 
![Error al copiar](https://github.com/user-attachments/assets/f3ab2998-60ef-426e-9cb4-0f6e1abf934e)
The update is correct, is working, but the next action result in a crash.

### Reproduction Steps

Do this steps: https://helpcenter.onlyoffice.com/ONLYOFFICE-Editors/ONLYOFFICE-Spreadsheet-Editor/UsageInstructions/AddExternalLinks.aspx
Update the external links
Try to copy any cell value.

### Additional information

This is on docservice, out.log
[2024-09-25T16:53:45.979] [ERROR] [localhost] [2493280419] [ocpn4gbojyo0_6C4A0D27-DB08-4828-B2A1-XXXXXXX] nodeJS - clientLog: changesError: Error: Uncaught TypeError: pc.replaceAll is not a function

I can update external links, close the spreadsheet, open again, and work correctly.

**Comment by LinneyS** [comment]
Fixed 05cc1e0bdd10d170bf9e4a77ed86a2e7adf8da2b
