### ISSUE TITLE
New Bangla fonts add to onlyoffice-nextcloud issue

### ISSUE THREAD

**Issue by shafiunmiraz0** [ONLYOFFICE/onlyoffice-nextcloud#1037]
Hi, 
I have installed nextcloud aio on k8s cluster. I have used heml charts. I now wanted to add the bangla fonts to it. I experimentally tried to add it in the pods where onlyoffice running. 
https://www.omicronlab.com/bangla-fonts.html
https://www.omicronlab.com/download/fonts/Nikosh.ttf
I added these fonts in the /usr/share/fonts/truetype/msttcorefonts directory.
![image](https://github.com/user-attachments/assets/6ab3890e-f81a-423c-9772-3848cbc70d1e)
and updated the cache but still not working.

**Comment by igwyd** [comment]
Hello @shafiunmiraz0, how is documentserver installed in your cluster? Is this a regular docker container or a cluster setup from our repo https://github.com/ONLYOFFICE/Kubernetes-Docs?

**Comment by shafiunmiraz0** [comment]
Hello,
Thanks for reploying

I have used the helm chart of nextcloud AIO. https://github.com/nextcloud/all-in-one/tree/main/nextcloud-aio-helm-chart
aio-onlyoffice:20241017_085101 this image is in use

**Comment by igwyd** [comment]
This is not our setup and we don't support it. I think you should create an issue in that repository https://github.com/nextcloud/all-in-one/issues. If it is our general docker container (I don’t know what’s there), then you can try installing fonts according to our [guide](https://helpcenter.onlyoffice.com/installation/docs-community-install-fonts-linux.aspx) inside onlyoffice container.
