### ISSUE TITLE
Onlyoffice  to document server does not work

### ISSUE THREAD

**Issue by speefak** [ONLYOFFICE/onlyoffice-nextcloud#1052]
https://SERVERURL/nextcloud/apps/documentserver_community/  thsi casuse file not found error, connection from onyloffice app to communityserver doesnt not work. I reinstalled the apps serveral time but it never works. what have i to enter int he Only office app in the Secre Url an other fields. i try server string but i dont know whis is the correct so i cant check wehere is error is. WHAT HAVE ENTER IN THE OO APP FIELDS ?

**Comment by LinneyS** [comment]
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://forum.onlyoffice.com/t/community-document-server-app-in-nextcloud-18/268).
