### ISSUE TITLE
Shared File Blank Page

### ISSUE THREAD

**Issue by alebeta90** [ONLYOFFICE/onlyoffice-nextcloud#106]
Hello friends,

Nextcloud Version: 14.0.12
ONLYOFFICE: docker image latest

the problem I have, is when someone share a document or a document is created in a shared folder, just the document/folder owner can see it with ONLYOFFICE for others, they can just see a Blank page and a 503 error coming from ONLYOFFICE.

I would like to know if it is a known issue, I had been searching in the closed issues but not luck.

Thanks

**Comment by alebeta90** [comment]
I had a look at the issue #18 and the commit https://github.com/ONLYOFFICE/onlyoffice-nextcloud/commit/3951e2e5a1b67ec3606cdfa1da5b804a57e7d36e

But I'm using the latest version of the plugin in nextcloud and it should not be a problem.

**Comment by alebeta90** [comment]
Screenshot from Nextcloud

![image](https://user-images.githubusercontent.com/11571266/60600785-1ba3c280-9db1-11e9-9832-0e526c79e238.png)

**Comment by LinneyS** [comment]
Hi @alebeta90 
What version number of the plugin are you using?

**Comment by alebeta90** [comment]
Hi @LinneyS 

The version of the plugin in NC is 2.2.1

This version is ok?

thanks for the support

**Comment by alexanderonlyoffice** [comment]
Hello @alebeta90, according to the error in log you installed connector for ownCloud in Nextcloud. Please delete the connector and install the correct one, please refer to this [guide](https://api.onlyoffice.com/editors/nextcloud).

**Comment by alebeta90** [comment]
Hi @LinneyS @alexanderonlyoffice 

Yes the problem was, the version of the app/connector, it was the one for owncloud... "small" mistake. Now it is working properly. 

Sorry for the false alarm and thanks for your time and guidance.
