### ISSUE TITLE
Onlyoffice 5.3.2 reverts language to english

### ISSUE THREAD

**Issue by Omaha2002** [ONLYOFFICE/onlyoffice-nextcloud#108]
After updating Onlyoffice server to 5.3.2 the interface language is English and not the default Nextcloud user language setting anymore. 5.3.1 was working well, interface language of Onlyoffice was the same as the Nextcloud user language setting.

expected behavior:  Interface of Onlyoffice same as Nextcloud user language setting.

**Comment by Omaha2002** [comment]
Upon further inspection I have one server showing this behavior and one doesn't. Both 16.0.1 and onlyoffice 5.3.2.

**Comment by alexanderonlyoffice** [comment]
Hello @Omaha2002, unfortunately, we cannot reproduce the described issue on our side. Could you please make a video or a .gif illustrating the issue.

**Comment by Omaha2002** [comment]
Sure, thank you for the reply:

**Language setting instance 1:**
![language english](https://user-images.githubusercontent.com/3179748/61075734-efc0b680-a41a-11e9-847f-0a2c3214c2b2.png)

**Opening a document in Onlyoffice results in (as expected) english menu:**

![language english-1](https://user-images.githubusercontent.com/3179748/61075776-06ffa400-a41b-11e9-9335-b18bba968109.png)

**Changing language setting instance 1 to dutch:**

![language dutch](https://user-images.githubusercontent.com/3179748/61075832-25659f80-a41b-11e9-981e-3cd481dedcdf.png)

**Opening a document in Onlyoffice still gives an english menu on instance 1:**

![language dutch-1](https://user-images.githubusercontent.com/3179748/61075914-4f1ec680-a41b-11e9-9271-2badb50e7fa6.png)


**Doing exactly the same in a different Nextcloud (both 16.0.3) instance results in expected behavior, dutch menu settings:**

![language dutch-2](https://user-images.githubusercontent.com/3179748/61075974-6bbafe80-a41b-11e9-8588-61737329c053.png)

**Setting the language to German, French or any other language on instance 1 all result in an English menu in Only office. Changing language in instance 2, same version nextcloud results in an Onlyoffice menu in the selected language.**

**Comment by alexanderonlyoffice** [comment]
Hello @Omaha2002, could you please do the following:

1) Open browser's console while opening the editor (choose Network tab) -> Refresh the page -> Send us a screenshot of the page with browser's console opened, if there are any errors; 
2) Open browser's console while opening the editor (choose Console tab) -> Refresh the page -> Send us a screenshot of the page with browser's console opened, if there are any errors.

**Comment by Omaha2002** [comment]
Thank you for your reply, hereby the screenshots:

1:
![image](https://user-images.githubusercontent.com/3179748/61316017-53265c00-a800-11e9-848e-7a143f02306f.png)

2:
![image](https://user-images.githubusercontent.com/3179748/61315956-2d995280-a800-11e9-8909-ccc2634e4245.png)

**Comment by alexanderonlyoffice** [comment]
Hello @Omaha2002, is there a possibility to give us a test account, so we can check ourselves. If yes, please sent us the login credentials to support@onlyoffice.com with a note "For technical support". If no, please do some more screenshots this way:
Open browser console -> Network tab -> use filter bar in console and type in json -> find nl.json and click on it -> click on the header tab in the right screen and make a screenshot -> then click on the review tab and make a screenshot.

**Comment by Omaha2002** [comment]
I've send you a mail Alexander, thank you for your support.

**Comment by alexanderonlyoffice** [comment]
Hello @Omaha2002, we did several tests and we suppose that the reason of the issue is that the simultaneous http requests are blocked for some reason on that server. Unfortunately, we do not know the reason yet. We will keep analyzing the problem.

**Comment by Omaha2002** [comment]
Hi Alexander,

I understand, thing is, it did work. It’s two servers, they both run in the IBM Cloud datacenters in Amsterdam and it’s more or less a production pilot for eventually a large environment where we definitely need more Onlyoffice ;-). I must say I’m impressed with Onlyoffice so my compliments. We are testing now for 6 months and it’s an awesome product in combination with Nextcloud. 

Can I test something on our site? Both servers groningen.network and onlyoffice have their own distinct IP addresses forwarded by the firewall (443 & 80)  to the servers.

Regards,

Jeroen

**Comment by Omaha2002** [comment]
And it seems that only the language isn’t picked up, the rest seems to work perfectly.

**Comment by alexanderonlyoffice** [comment]
Hello @Omaha2002, 

> And it seems that only the language isn’t picked up, the rest seems to work perfectly.

Not only language, we also checked other points, where we use simultaneous requests (for example, equations in spreadsheet editor)

There is a problem and we do not know the reason at the moment, it might also be connected with CORS. We found some information on StackOverflow: [link 1](https://stackoverflow.com/questions/32878613/networkerror-failed-to-execute-send-on-xmlhttprequest) and [link 2](https://stackoverflow.com/questions/20224883/synchronous-cors-xhr-302-redirect-fails-but-asynchronous-works).

**Comment by Omaha2002** [comment]
Is there something else I can test? Could it be a firewall issue? We use a
vayatta firewall in the IBM Cloud datacenter.



Op vr 19 jul. 2019 om 08:13 schreef Alexander Zozulya <
notifications@github.com>:

**Comment by Omaha2002** [comment]
Hi Alexander,

Reading your links I saw that Firefox seems to be the only browser that
doesn't throw an error when performing this synchronous request and I've
tested https://groningen.network in Firefox and it works fine!
[image: image.png]


Op vr 19 jul. 2019 om 08:13 schreef Alexander Zozulya <
notifications@github.com>:

**Comment by alexanderonlyoffice** [comment]
@Omaha2002, it seems that the problem might be on Chrome based browsers.

**Comment by Omaha2002** [comment]
Issue seems to be fixed after updating Onlyoffice to 5.4
![image](https://user-images.githubusercontent.com/3179748/64282224-3df2c180-cf55-11e9-82e5-0f46adbc6522.png)

**Comment by Omaha2002** [comment]
And strangely enough after an update of onlyoffice app in Nextcloud language reverts back to English again.

**Comment by Omaha2002** [comment]
And updating Onlyoffice nextcloud app to 3.0.2 seems to solve the problem again.

**Comment by LinneyS** [comment]
Thanks for your feedback

**Comment by Omaha2002** [comment]
After upgrading Enterprise Edition to Version: 7.0.1.37 the language defaults to english, even with the locale of the user set to home language.

onloffice app is version: 7.3.2
