### ISSUE TITLE
Getting error after updating to 2.0.4

### ISSUE THREAD

**Issue by bugnetz** [ONLYOFFICE/onlyoffice-nextcloud#11]
Hello,

since yesterday I get following error in two of my cloud instances:

"onlyoffice | Track with empty or not correct hash: Wrong number of segments"

I assume it is related to the last changes.

Best regards

**Comment by alexanderonlyoffice** [comment]
Hello @bugnetz, we added some fixes for security improvement. Unfortunately, if the file was opened for editing during updating ONLYOFFICE integration application, the changes to the file are lost.

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs or we can close the topic.

**Comment by LinneyS** [comment]
This issue was closed due to no response.
