### ISSUE TITLE
Can't access/convert files in group folders if share is not allowed

### ISSUE THREAD

**Issue by jlord87** [ONLYOFFICE/onlyoffice-nextcloud#110]
This is probably related to #27 :

I'm on nextcloud 16.0.2, Ubuntu server 18.04, OnlyOffice document server 5.3.2 on a separate Ubuntu 18.04 vm.

I'm using "Group folders" with "advanced permission" enabled.
If I try to access a file in a folder where I do not have share permission enabled in group folder I get the "Download Failed. Presso "OK" to return to document list." error.

Enabling my group the "share permission" in Group Foilder's permission the document is opened in nextcloud.

Can this be fixed in the plugin or should I open a ticket in Nextcloud git?

thank you

**Comment by alexanderonlyoffice** [comment]
Hello @jlord87, thank you for the provided information. We are managed to reproduce the issue and are working on it at the moment. Unfortunately, I cannot tell you the ETA of the solution release.

**Comment by LinneyS** [comment]
@juliushaertl

**Comment by jlord87** [comment]
> Hello @jlord87, thank you for the provided information. We are managed to reproduce the issue and are working on it at the moment. Unfortunately, I cannot tell you the ETA of the solution release.

Thank you, if you need help in testing patches I'll be glad to help..

**Comment by juliushaertl** [comment]
@LinneyS Most likely a similar issue to the other one where the user session is not setup correctly. The groupfolders ACL adds additional permission checks based on the current user.

**Comment by Thoro** [comment]
Just wanted to confirm this still happens with NC 16.0.5 and GF 4.1.3 and OO 3.0.2

**Comment by LinneyS** [comment]
Hello to all
please check version 4.0.0

**Comment by jlord87** [comment]
Solved for me, that's cool!
[I owe you two](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/156#issuecomment-567378645)!
