### ISSUE TITLE
curl error with NC 16.0.3 and onlyoffice 5.3.4-3

### ISSUE THREAD

**Issue by ClundXIII** [ONLYOFFICE/onlyoffice-nextcloud#117]
Hello,

after an update my onlyoffice stops working. I had to redo a lot of configuration (and fight with the package deleting my web configuration multiple time) and I arrived at the following error when trying to save my secret:
```
Error when trying to connect (cURL error 1: Protocol "https,%20https" not supported or disabled in libcurl (see http://curl.haxx.se/libcurl/c/libcurl-errors.html))
```

The nextcloud log files shows a mixed content error plus the following three times:

```
Request converted file on check error: https, https://<my onlyoffice domain>, <my onlyoffice domain>/cache/files/conv_check_85809239_docx/output.docx/check_85809239.docx?md5=mFj3kLFfILc2pgf_nEKm0Q&expires=1563957541&disposition=attachment&ooname=output.docx cURL error 1: Protocol "https,%20https" not supported or disabled in libcurl (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

I am running onlyoffice and nextcloud on the same virtual machine. The access itself is being done via http behind a proxy vm to the outside (that does the https). The hosts are set up in a way that wgetting either nextcloud or onlyoffice always goes through the web vm and therefore ensures that https is always used.

**Comment by ClundXIII** [comment]
This bug might be a duplicate of #113

when I change the url from https to http the error described in #113 shows up.

**Comment by ClundXIII** [comment]
I think this is just a javascript frontend error. Some small typo in a script. For some reason when using https an http is added infront of the URL. So curl gets something like `https,%20https://` as an argument. If I use http everything is fine.

**Comment by ClundXIII** [comment]
I recently upgraded the Plugin and the documentserver without any success. This Problem still exists.

**Comment by ClundXIII** [comment]
Okay, I managed to debug the issue with adding

`print("Documentservice.Request: $url\n");debug_print_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS, 3);
`

into documentservice.php inside the "Request()" function. I got the following information:
```

Documentservice.Request:
  https://onlyoffice.clundxiii.com/healthcheck #0 OCA\Onlyoffice\DocumentService->Request() called at [/var/www/cloud/apps/onlyoffice/lib/documentservice.php:256] #1 OCA\Onlyoffice\DocumentService->HealthcheckRequest() called at [/var/www/cloud/apps/onlyoffice/controller/settingscontroller.php:283] #2 OCA\Onlyoffice\Controller\SettingsController->checkDocServiceUrl() called at [/var/www/cloud/apps/onlyoffice/controller/settingscontroller.php:168] 
Documentservice.Request:
  https://onlyoffice.clundxiii.com/coauthoring/CommandService.ashx #0 OCA\Onlyoffice\DocumentService->Request() called at [/var/www/cloud/apps/onlyoffice/lib/documentservice.php:301] #1 OCA\Onlyoffice\DocumentService->CommandRequest() called at [/var/www/cloud/apps/onlyoffice/controller/settingscontroller.php:297] #2 OCA\Onlyoffice\Controller\SettingsController->checkDocServiceUrl() called at [/var/www/cloud/apps/onlyoffice/controller/settingscontroller.php:168] 
Documentservice.Request:
  https://onlyoffice.clundxiii.com/ConvertService.ashx #0 OCA\Onlyoffice\DocumentService->Request() called at [/var/www/cloud/apps/onlyoffice/lib/documentservice.php:174] #1 OCA\Onlyoffice\DocumentService->SendRequestToConvertService() called at [/var/www/cloud/apps/onlyoffice/lib/documentservice.php:93] #2 OCA\Onlyoffice\DocumentService->GetConvertedUri() called at [/var/www/cloud/apps/onlyoffice/controller/settingscontroller.php:324] 
Documentservice.Request:
  https, https://onlyoffice.clundxiii.com, onlyoffice.clundxiii.com/cache/files/conv_check_1384897329_docx/output.docx/check_1384897329.docx?md5=OG7m-hHktcUX37tr5yfQyQ&expires=1572265083&disposition=attachment&ooname=output.docx
  #0 OCA\Onlyoffice\DocumentService->Request() called at [/var/www/cloud/apps/onlyoffice/controller/settingscontroller.php:332]
  #1 OCA\Onlyoffice\Controller\SettingsController->checkDocServiceUrl() called at [/var/www/cloud/apps/onlyoffice/controller/settingscontroller.php:168]
  #2 OCA\Onlyoffice\Controller\SettingsController->SaveAddress() called at [/var/www/cloud/lib/private/AppFramework/Http/Dispatcher.php:166] {"documentserver":"https:\/\/onlyoffice.clundxiii.com\/","documentserverInternal":null,"storageUrl":null,"secret":"fhs8z23","error":"cURL error 1: Protocol \"https,%20https\" not supported or disabled in libcurl (see http:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html)"}
```

So something is being replaced in a very, very wrong way.

**Comment by ClundXIII** [comment]
It seems to boil down to the Document Converter messing something up and returning a faulty URL.

**Comment by CarlOnlyoffice** [comment]
Hello @ClundXIII,
Sorry for the delayed reply. Please check if the issue can be reproduced with the Document Server 5.4.2. Also check documentserver/converter/out.log for errors.

**Comment by ClundXIII** [comment]
I have already tried nuking my installation and reinstalling the document server. Unfortunately the debian packages were broken (postprocessing failed) and I had to manually delete files. My System is in quite an undefined state right now :(

You can close this since I don't have the setup any more.

In addition it would also be nice if updating the package did not delete all my config everytime. Maybe use some conf.d/ folder or somehting.

I will try installing onlyoffice again but it might take a while until I find the time to do so.

**Comment by Mer0me** [comment]
If anyone stuck on this like me from this morning, [this post was helpful](https://github.com/ONLYOFFICE/DocumentServer/issues/1020#issuecomment-710990835), it might be a misconfiguration of nginx, having a double proxy_set_header somewhere.
Don't forget to restart nginx after correction since "supervisor restart all" didn't seem to be sufficient.
