### ISSUE TITLE
Spreadsheet table lost content

### ISSUE THREAD

**Issue by janpekar** [ONLYOFFICE/onlyoffice-nextcloud#12]
Today I faced some strange and severe problem with OnlyOffice integrated with nextcloud.

I edited online some spreadsheets and often I returned back to Nextcloud file listing and opened another spreadsheet. After aprox. 10 switches between two xlsx documents I noticed, that there are some cells blank, but before they contained data. Also some cells were shifted etc. So I lost some of the data I entered into that spreadsheets. I recovered some of them downloading previous versions, but not all of them.

I don't know where to submit this issue, so I'm starting here, because I'm sharing the same docker based Onlyoffice server with two nextcloud installations and it happened only at one installation, where I recently upgraded to 2.0.4 onlyoffice-nextcloud plugin version. The other one uses 2.0.2 version and it looks OK, but maybe it has same issue, but it didn't show up.

OnlyOffice document server is 5.1.5. Nextcloud version is 13.0.6. Browser is Firefox 58.0.1-1+b1.

If you will help me where to point my investigation, I will try to do my best.

**Comment by ibnpetr** [comment]
Hello 

> After aprox. 10 switches between two xlsx documents I noticed, that there are some cells blank, but before they contained data. Also some cells were shifted etc. So I lost some of the data I entered into that spreadsheets.

Can the issue be reproduced? We weren't able to reproduce it.
Try downloading the documents from the NC interface and confirm that the information in your spreadsheet is lost.
Check if you have any errors in NC and Document Server log files.

> 10 switches between two xlsx documents

Just switching without closing the tabs?

**Comment by janpekar** [comment]
I was able to reproduce it, but I don't know if it wasn't browser or server or network issue. I can try to reproduce it after client and server reboot.

Yes, even downloaded spreadsheet had empty fields.
I can check server and document server logs.

I was returning back to documents inside the same tab (not closing, not opening another tab).

**Comment by ibnpetr** [comment]
> I can try to reproduce it after client and server reboot.

Ok, please describe your actions step by step. We will try again to reproduce the issue

**Comment by janpekar** [comment]
I didn't have time to reproduce issue, sorry.
I will close issue and when it repeats, I will eventually reopen it.
