### ISSUE TITLE
Problems open odt and docx files  

### ISSUE THREAD

**Issue by c0r3dump3d** [ONLYOFFICE/onlyoffice-nextcloud#120]
Hi, I have NC 14 installation with Onlyoffice App 2.4.0. When I have edited odt files and docx files with Onlyoffice and then I try to open with Libreoffice 6.2 I have and error and the content add with Onlyoffice the content is not displayed.

For odt files error:

![Captura de pantalla de 2019-08-08 10-30-42](https://user-images.githubusercontent.com/5602401/62688044-4d1f3780-b9c8-11e9-9708-5c77dabee839.png)

For docx files error:

![Captura de pantalla de 2019-08-08 10-36-36](https://user-images.githubusercontent.com/5602401/62688101-7f309980-b9c8-11e9-95bd-9c6fe7587c0d.png)

**Comment by HelenBelova17** [comment]
Hello, @**c0r3dump3d**, I can not reproduce your issue, send us files which was created with Onlyoffice and can not be opened in Libreoffice.
