### ISSUE TITLE
File activity not updated reliably

### ISSUE THREAD

**Issue by msumm** [ONLYOFFICE/onlyoffice-nextcloud#122]
I observe the following problem using Nextcloud 16.0.3 + OnlyOffice App 2.4.0:

Collaborative editing is not reported reliably by the Activity App. Consecutive editing by different users is not tracked by the Activity App, at least not within a certain time interval (several hours). 

**Performed action:**
I consecutively edit a shared docx-file using several user accounts and the OnlyOffice App.
(The file is located on an external WebDAV storage.)

What happens (as long as the Versions App is disabled, see #118):
- File is edited
- File editing time is updated
- File is synchronized with external storage & clients
- **The Activity App may or may not track the edits performed by different users. In particular edits made within some hours are not recorded.**

**Expected behaviour:**
Every file edit is recorded within the Activity App, at least if the last editing user changes. Consequently notifications about theses changes are sent to all users having the share.

This problem has already been described in other threads, e. g. [here](https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/57) & [here](https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/27).

Is there any work in progress?

**Comment by Bschalck** [comment]
Hy,

I have the same issue since my first day with OnlyOffice ( 3 years ) .
I'm interesting if the is something to force the Activity App refresh

**Comment by alexanderonlyoffice** [comment]
Hello @msumm and @Bschalck, please note that these application are not related to ONLYOFFICE. If they are malfunctioning, please contact the developers of those applications. 

We implemented the standard way of saving files using integration app, those apps should track changes as by standard means.

**Comment by msumm** [comment]
@alexanderonlyoffice Ok, thanks.

I opened a [corresponding issue](https://github.com/nextcloud/activity/issues/391) in the scope of the Nextcloud Activity App.

**Comment by Bschalck** [comment]
Hy, 
Juste to be clear : when I close the onlyoffice document, the date of change is not up to date.

What happens : 

- I open a file with onlyoffice ( e.g : date of last change is 05/06/2019 )
- I change the file , which is correctly saved
- I return to nextcloud with this button "Open file manager" ( not sure this is in English :) ) 
- The last update of the file **is still**  05/06/2019
- When I reopen the file, it is not the last version, but **the  05/06/2019 version !**
- If I refresh the page, or I browse my nextclou doc, and come back to my OnlyOffice directory, the change is up to date

Regards,

**Comment by LinneyS** [comment]
@juliushaertl
If you have time, look please.

**Comment by c0r3dump3d** [comment]
Hi, I have more or less the same issue, with AppClient version 3.0.2, Nextcloud 16.0.4 and document server 5.3.0:

- Open a file with onlyoffice

- Save the changes in onlyoffice

- Open the file from nextcloud or from "Open file manager", the changes are not present

- Close the tab of onlyoffice and the changes are present in the file.

**Comment by juliushaertl** [comment]
@LinneyS As described here https://github.com/nextcloud/activity/issues/391#issuecomment-526089265 this is mainly an issue because OnlyOffice only persists the changes to the Nextcloud storage once the browser window is closed. So this would work once https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/95 is implemented.

**Comment by msumm** [comment]
@juliushaertl The problem I described initially is in my opinion independent from the issues dealing with closing the browser window. The behaviour I described also occurs when the browser window is closed. In my case (also described [here](https://github.com/nextcloud/activity/issues/391#issuecomment-526137032)) the changes are written back to the Nextcloud storage but the Activity App does not reflect this change.

**Comment by juliushaertl** [comment]
Oh sorry, I was confusing that. I just checked and individual activities are actually created but it seems when merging them for displaying the timestamp is not set correctly. Fix is proposed in https://github.com/nextcloud/server/pull/17484

**Comment by msumm** [comment]
@juliushaertl Thanks!

**Comment by LinneyS** [comment]
Looks like fixed.
