### ISSUE TITLE
Synchronization issues for ods/odt files edits in onlyoffice editor

### ISSUE THREAD

**Issue by pmarini** [ONLYOFFICE/onlyoffice-nextcloud#124]
1. Open a ODS file in Nextcloud using Onlyoffice editor
2. Edit it, for example add a number in a cell
3. Close it and reopen it: the modification is still there. However the Last Modification Time is not modified and the modification is not pushed to other Nextcloud clients.
4. A modification to the file from another client would simply erase the edit 

Everything works well with xlsx and docx files. As far as I understand, editing of ods files should work in exactly the same way.

Versions: 5.3.4-3
Nextcloud 16.0.4

**Comment by HelenBelova17** [comment]
Hello,@**pmarini**, could you attach nextcloud log to make sure everything seems to be fine in logs?

**Comment by pmarini** [comment]
Which log do you need specifically? I have raised the Nextcloud logging level to debug as explained [here](https://docs.nextcloud.com/server/stable/developer_manual/general/debugging.html?highlight=debug), i.e. setting the debug => true flag in config.php but there is no trace of an error or a warning (while the behavior described above is replicated).

**Comment by alexanderonlyoffice** [comment]
Hello @pmarini, please reproduce the issue once again to let the error entries be recorded into the logs and send us the log of NC and archive of the folder with logs of the Document Server. Paths for the logs of DS for different installation types are below: 

Windows: C:\Program Files\ONLYOFFICE\DocumentServer\Logs
Docker: /app/onlyoffice/DocumentServer/logs/documentserver/
DEB/RPM: /var/log/onlyoffice/documentserver/logs

Please send the logs to support@onlyoffice.com with a note 'For technical support'.

**Comment by alexanderonlyoffice** [comment]
Hello @pmarini, thank you for the provided access to your Nextcloud instance. I have checked the case: created a .xlsx file in the test account in web interface -> connected nextcloud desktop application to this account -> edited the file locally on the PC using ONLYOFFICE Desktop Editors and MS Office Excel -> saved and closed the file -> it was successfully synchronized with the file in Nextcloud account in web interface. The main thing is that the changes are not shown in web editor as the file is being edited locally at this same moment and Document Server knows nothing about the changes made to the file. Please note that simultaneous synchronization between the Document Server and desktop applications are impossible.

**Comment by pmarini** [comment]
Dear @alexanderonlyoffice ,

Thanks for your support. 

OK, of course I understand that 'simultaneous synchronization between the Document Server and desktop applications are impossible'

It seems that I have problems when connecting Nextcloud => OO from the same local network where the two machines are installed. Probably I miss some configuration for the network and proxy.

Best regards,

Pietro
