### ISSUE TITLE
Healthcheck Request: 400 Bad Request

### ISSUE THREAD

**Issue by joekerna** [ONLYOFFICE/onlyoffice-nextcloud#125]
I've set up Onlyoffice Docker successfully. The welcome-page appears and says "The documentserver is running."
When I access https://my.server.com/healthcheck I receive a simple "true".

However, when trying to connect to Onlyoffice in Nextcloud I get the following error message

> HealthcheckRequest on check error: Client error: `GET https://my.server.com/healthcheck` resulted in a `400 Bad Request` response: <!DOCTYPE html> <html class="ng-csp" data-placeholder-focus="false" lang="en" data-locale="en" > <head data-requesttok (truncated...)

**Comment by CarlOnlyoffice** [comment]
Hello @joekerna,
sorry for the late reply. Is the issue still relevant?
If yes, specify the versions of DS, NC, connector app; OS of the server where DS is installed; type of installation of DS (docker, deb/rpm).

**Comment by joekerna** [comment]
No the issue is no longer relevant. I think the issue was that I was missing the final / in the URL in the app settings. After adding the / the app works as expected.
Thanks

**Comment by LinneyS** [comment]
Hi @joekerna 
This is strange
This should work since version 1.0.4
https://github.com/ONLYOFFICE/onlyoffice-owncloud/commit/2d558e9129c3c61a01661df94e3ce5c8d591d2c2#diff-b9da532ee3f149e5390718d827c79fc4R143

But I am glad that the problem does not recur
