### ISSUE TITLE
Login prompt recursively appears when opening document through NextCloud with version 2.4.0

### ISSUE THREAD

**Issue by ReSummit** [ONLYOFFICE/onlyoffice-nextcloud#129]
In version 2.4.0, the document page repeatedly shows a login prompt with the domain name only as the text. The document is still editable when the prompt is closed, but is unusable due to the frequency of the popups opening.

Example 1:
![vivaldi_1asCaywTrP](https://user-images.githubusercontent.com/23018622/64472381-3af10000-d112-11e9-9d8d-31c4f912decf.png)

**Comment by alexanderonlyoffice** [comment]
Hello @ReSummit, please specify some additional information: 

1. Version of the Document Server;
2. Version of Nextcloud;
3. How did you integrate the Document Server with your Nextcloud (which instruction did you use)? Send us also the screenshot of ONLYOFFICE integration app settings from Nextcloud;
4. Do you use any proxy server in front of your Document Server? It might be that you use some proxy server with basic authentication.

**Comment by ReSummit** [comment]
> Hello @ReSummit, please specify some additional information:
> 
> 1. Version of the Document Server;
> 2. Version of Nextcloud;
> 3. How did you integrate the Document Server with your Nextcloud (which instruction did you use)? Send us also the screenshot of ONLYOFFICE integration app settings from Nextcloud;
> 4. Do you use any proxy server in front of your Document Server? It might be that you use some proxy server with basic authentication.

1. My version of the Document Server is 5.4.0-21.
2. My Nextcloud instance is version 16.0.4.
3. Both Nextcloud and the Document Server are running on the same computer with different domain paths through Nginx. I installed the Document Server on Linux Mint without Docker following the "Installing Document Server for Linux on Debian, Ubuntu and derivatives." I did deviate from the instructions given and used NodeJS 10 instead of NodeJS 8 due to NodeJS 8 failing to shutdown when updating or recovering (a separate issue, but something to note).

Screenshot of ONLYOFFICE integration app settings:
![FC7lxYdGUX](https://user-images.githubusercontent.com/23018622/64509229-22105800-d294-11e9-8646-3b2f0a4e4dae.png)

The Document Editing Service address is my domain name with the file path "/onlyoffice".

4. I don't use a proxy server in front of the Document Server. Unless Nginx counts because it is a reverse proxy server?

**Comment by alexanderonlyoffice** [comment]
@ReSummit, please show us the config of your nginx. I would also recommend you to open browser console -> Network tab when you get this login window and check the requests for basic authentication header (you can find it in headers, please see this [screenshot](https://monosnap.com/file/c2FmKK0m6Ro7vtnoOe0sWPC1Et1XIh)).

**Comment by ReSummit** [comment]
Erm... I ended up reinstalling the Nextcloud OnlyOffice integration app and I'm no longer seeing the repetitive login prompts. I'm thinking that I might have had corrupted files when I updated to 2.4, though I looked through my nextcloud.log file and didn't find anything that referred to the repetitive login requests I found earlier.
