### ISSUE TITLE
GetConvertedUri on check error: Une erreur s'est produite dans le service de document: Conversion error

### ISSUE THREAD

**Issue by Maxence1502** [ONLYOFFICE/onlyoffice-nextcloud#130]
Hello !
I installed OnlyOffice on https://office.my-domain.fr/ : Document Server is running
But when I try to add on nextcloud (https://cloud.my-domain.fr) the url of onlyOffice, I got this error : http://prntscr.com/p3dzrj

Nextcloud and Onlyoffice are on the same servers, I tried to put rejectUnauthorized on false and verify_peer_off on true but nothing works. Https is provided by cloudfare

Thanks for your help,
Maxence

**Comment by CarlOnlyoffice** [comment]
Hello @MaxenceTP,
Please check Document Server logs for errors:
/var/log/onlyoffice/documentserver/converter & docservice

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs or we can close the topic?
