### ISSUE TITLE
Continuously print error logs after updating to 3.0.0

### ISSUE THREAD

**Issue by zdz2019** [ONLYOFFICE/onlyoffice-nextcloud#135]
I used nextcloud 16.04.1 and PHP7.3.9
I saw the prompt ONLYOFFICE has an update, and then updated online to version 3.0.0, but found that the error log keeps appearing. If ONLYOFFICE is disabled, the error log is no longer displayed. The following is the error log:

Error | jsresourceloader | Could not find resource core/js/oc-backbone-webdav.js to load |   | 2019-09-12T11:47:06+0800
-- | -- | -- | -- | --
Error | PHP | implode(): Invalid arguments passed at /home/www/nextcloud/apps/onlyoffice/templates/settings.php#261 |   | 2019-09-12T11:47:06+0800
Error | PHP | implode(): Invalid arguments passed at /home/www/nextcloud/apps/onlyoffice/templates/settings.php#220 |   | 2019-09-12T11:47:06+0800
Error | PHP | implode(): Invalid arguments passed at /home/www/nextcloud/apps/onlyoffice/templates/settings.php#212 |   | 2019-09-12T11:47:06+0800
Error | PHP | explode() expects parameter 2 to be string, array given at /home/www/nextcloud/apps/onlyoffice/lib/appconfig.php#776 |   | 2019-09-12T11:47:06+0800
Error | PHP | explode() expects parameter 2 to be string, array given at /home/www/nextcloud/apps/onlyoffice/lib/appconfig.php#776 |   | 2019-09-12T11:47:06+0800
Error | PHP | explode() expects parameter 2 to be string, array given at /home/www/nextcloud/apps/onlyoffice/lib/appconfig.php#776

**Comment by acs-ferreira** [comment]
I also add:

`Undefined index: download at /var/www/nextcloud/apps/onlyoffice/controller/editorcontroller.php#959`

to this list

**Comment by winvan** [comment]
Can cofirm. I got same errors when documents opened. Ubuntu 18.04+php 7.3+postrges10+nginx1.14.0

**Comment by Stelorio** [comment]
I have the same issue after updating to Nextcloud 17.0.0 RC1

Error | PHP | Undefined index: download at /var/www/nextcloud/apps/onlyoffice/controller/editorcontroller.php#959 |  
-- | -- | -- | --

Error | PHP | explode() expects parameter 2 to be string, array given at /var/www/nextcloud/apps/onlyoffice/lib/appconfig.php#776 |  
-- | -- | -- | --

**Comment by Stelorio** [comment]
Fixed it (for me) by changing 
/onlyoffice/lib/appconfig.php#776
from
`$result[$key] = $value !== "" ? explode(",", $value) : [];`
to
`$result[$key] = $value`

and 
/onlyoffice/controller/editorcontroller.php#959
from 
`            $params["document"]["permissions"]["download"] !== false);`
to
`!isset($params["document"]["permissions"]["download"]) or $params["document"]["permissions"]["download"] !== false); `

**Comment by LinneyS** [comment]
Released
v3.0.2
