### ISSUE TITLE
Specify spellchecker port ?

### ISSUE THREAD

**Issue by Bschalck** [ONLYOFFICE/onlyoffice-nextcloud#136]
Hy,

I use onlyoffice-documentserver since few years. That works very well .... but I want to clear all mistakes on my servers.

One of them is the spellchecker service, which use 8080port  by default.
But my nginx server is listening to this port too .

Is it possible to change the default spellchecker port ? 
I change it in the  /etc/nginx/includes/http-common.conf file, but it does not change anymore ( still listening at 8080 ) .

Thanks !

**Comment by agolybev** [comment]
Hi @Bschalck.
To change spellchecker listening port you have to change the port number in file `/etc/onlyoffice/documentserver/default.json`  section "SpellChecker"->"server"->"port" and in file `/etc/onlyoffice/documentserver/nginx/includes/http-common.conf` section
```
upstream spellchecker {  
  server localhost:8080;
}
```
After those remember to restart services:
```
$ sudo supervisorctl restart ds:spellchecker
$ sudo service nginx reload
```

**Comment by Bschalck** [comment]
YOU save me ! 

Thanks !
