### ISSUE TITLE
OnlyOffice Editor frontend is trying to access 127.0.0.1 instead of configured domain

### ISSUE THREAD

**Issue by KarimGeiger** [ONLYOFFICE/onlyoffice-nextcloud#137]
I am trying to integrate OnlyOffice into my Nextcloud instance. For examples sake, let's assume I run Nextcloud at example.com. I configured the onlyoffice/documentserver docker to listen to onlyoffice.example.com via 443 through an nginx proxy with a valid Let's Encrypt certificate.

The application seems to be configured and working properly, however, when I try to edit a document through the NextCloud webinterface, it fails with an `"Unknown error"`. The reason being is, it's trying to access the following URL through the JS frontend:

`https://127.0.0.1:4433/cache/files/3426957769/Editor.bin/Editor.bin?md5=xxxxx&expires=1567759383&disposition=attachment&ooname=output.bin`
 
### Steps to reproduce

1. Install onlyoffice with docker
```
docker run --name=ONLYOFFICEDOCKER -i -t -d -p 4433:443 -e JWT_ENABLED='true' -e JWT_SECRET='xxxxxx' --restart=always -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data onlyoffice/documentserver:latest
```
2. nginx:
```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name onlyoffice.example.com;
    [ssl-foo]
    ssl_prefer_server_ciphers on;
    add_header Strict-Transport-Security max-age=31536000;
    proxy_set_header X-Forwarded-For $remote_addr;
    server_tokens off;

    location / {
        proxy_pass    https://127.0.0.1:4433;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_ssl_session_reuse off;
        proxy_ssl_verify off;

        access_log      /var/log/nginx/onlyoffice.access.log;
        error_log       /var/log/nginx/onlyoffice.error.log;
    }
}
```
3. Install OnlyOffice extension in NextCloud.
4. Configure it to access OnlyOffice at: `https://onlyoffice.example.com/` with the secret key properly set.

### Expected behaviour
When opening a word document through the NextCloud interface, it should load the OnlyOffice editor.

### Actual behaviour
Loading the editor fails with an `Unknown error`. The network monitor reveals a failed request to:
```https://127.0.0.1:4433/cache/files/xxxx/Editor.bin/Editor.bin?md5=xxxx&expires=1571047766&disposition=attachment&ooname=output.bin```

I am expecting the editor to request the file at `https://onlyoffice.example.com/cache/files/...`.

#### OnyOffice Access Log
<details>
<summary>OnlyOffice Access Log</summary>

```
185.230.127.233 - - [14/Sep/2019:12:18:41 +0200] "GET /web-apps/apps/api/documents/api.js HTTP/2.0" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15"
185.230.127.233 - - [14/Sep/2019:12:18:42 +0200] "GET /web-apps/apps/documenteditor/main/index.html?_dc=5.4.0-21&lang=en&customer=ONLYOFFICE&frameEditorId=iframeEditor HTTP/2.0" 302 154 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15"
185.230.127.233 - - [14/Sep/2019:12:18:42 +0200] "GET /5.4.0-21//web-apps/apps/api/documents/api.js HTTP/2.0" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15"
185.230.127.233 - - [14/Sep/2019:12:18:42 +0200] "GET /5.4.0-21//web-apps/apps/documenteditor/main/index.html?_dc=5.4.0-21&lang=en&customer=ONLYOFFICE&frameEditorId=iframeEditor HTTP/2.0" 200 29118 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15"
185.230.127.233 - - [14/Sep/2019:12:18:42 +0200] "GET /5.4.0-21//web-apps/apps/api/documents/api.js HTTP/2.0" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15"
185.230.127.233 - - [14/Sep/2019:12:18:43 +0200] "GET /5.4.0-21//doc/3723508311/c/info?t=1568456323463 HTTP/2.0" 200 96 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15"
185.230.127.233 - - [14/Sep/2019:12:18:44 +0200] "GET /5.4.0-21//spellchecker/doc/3723508311/c/info?t=1568456324407 HTTP/2.0" 200 97 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15"
```
</details>

**Comment by CarlOnlyoffice** [comment]
Hello @KarimGeiger,

You need to add the X-Forwarded-Host header to nginx proxy config. Take a look at our example:
https://github.com/ONLYOFFICE/document-server-proxy/blob/master/nginx/proxy-https-to-http.conf

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs?

**Comment by KarimGeiger** [comment]
Thanks for replying! That indeed did solve the problem. Added the following lines to the configuration:
```
proxy_set_header        X-Forwarded-Host   $host:443;
proxy_set_header        X-Forwarded-Server $host;
proxy_set_header        X-Forwarded-Port   443;
proxy_set_header        X-Forwarded-Proto  https;
```
