### ISSUE TITLE
The application interface does not support the Chinese language after updating to 3.0.0

### ISSUE THREAD

**Issue by kongbo521** [ONLYOFFICE/onlyoffice-nextcloud#139]
The application interface does not support the Chinese language after updating to 3.0.0,But before is OK.

**Comment by jlord87** [comment]
I'm facing some interface language problems too; it used to work well in our environment in Italian, now it's in English (on some pc in German).

Where does the document server get the information about the language to be used in the user interface?
Is there a way to force a default language?
Does modifying DocsAPI.DocEditor.defaultConfig "lang" in "/var/www/onlyoffice/documentserver/web-apps/apps/api/documents/api.js " works?

**Comment by Desdemo** [comment]
me too,

**Comment by LinneyS** [comment]
Which interface do you mean?
Editor interface or Nextcloud applications (for example, the connection settings page)?

**Comment by jlord87** [comment]
I'm facing the problem in the editors interfaces

**Comment by Desdemo** [comment]
![image](https://user-images.githubusercontent.com/31582776/65679847-7edb8300-e088-11e9-802b-f16318653ae1.png)
Just like a screenshot。

**Comment by Omaha2002** [comment]
Same issue as I had a few months back? No solution btw

https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/108

**Comment by jlord87** [comment]
Updated to the latest 5.4.1 on my Ubuntu box and 3.0.2 nextcloud app.
It's now working again, good job!
