### ISSUE TITLE
Onlyoffice Mobile App 5.0 (iOS) clears files on nextcloud

### ISSUE THREAD

**Issue by SSpecken** [ONLYOFFICE/onlyoffice-nextcloud#141]
Connected our Nextcloud to the new OnlyOffice iOS App and navigating, reading and creating docs is working very well. But saving an edited docx or xlsx file back to nextcloud is leading to a unusable file with a size of 0 bytes.  

Installed versions:
- OnlyOffice Docments iOS App 5.0
- Nextcloud 16.0.4.1
- Nextcloud App OnlyOffice 3.0.0

I don't find any issues in  the logs. Where could I find more information?

**Comment by nav-fess** [comment]
Неllo @SSpecken. Thank you. I can confirm - this is a bug, issue 42837  in our internal issue tracker.

**Comment by SSpecken** [comment]
Issue was solved with OnlyOffice Documents iOS App 5.0.1
