### ISSUE TITLE
live editing is not reflected for a read-only shared doc

### ISSUE THREAD

**Issue by mclegrand** [ONLYOFFICE/onlyoffice-nextcloud#143]
(same issue as #https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/252 for owncloud)

Hi, 
would it be possible to enable real-time update for read-only shared files ?

Thanks

**Comment by alexanderonlyoffice** [comment]
Hello @mclegrand, we are considering the possibility to add new sharing options to Nextcloud. Unfortunately, I cannot tell you exact time frames at the moment. Support of the new permissions should be implemented on the side of Nextcloud too.

**Comment by mario-zelger** [comment]
Has there been any progress regarding this feature?

**Comment by SergeyKorneyev** [comment]
The live viewer feature is available starting from version 7.2 of the Document Server. It's enabled by default and allows users that open a document in viewing mode to see changes made by other users in real time. The feature can be disabled using the **Advanced Settings -> Collaboration -> Show changes from other users** option in the editor's interface.

Live viewer has a connections limit separate from editing connections. For example, the open source version of the Document Server has the limit of 20 editing connections and 20 live viewer connections.
