### ISSUE TITLE
Can't connect to nextcloud with secret key enabled

### ISSUE THREAD

**Issue by vasyugan** [ONLYOFFICE/onlyoffice-nextcloud#144]
This is a bug report

**What is the current behavior?**

When the secret key is enabled on both the documentserver and Nextcloud 16, enabling OnlyOffice in nextcloud fails and I get the above error message in the onlyoffice log

* set up nextcloud

* set up OnlyOffice as a docker image, as per https://helpcenter.onlyoffice.com/de/server/docker/document/docker-installation.aspx

* Proxy the document server through NGINX in order to have a valid certificate.

* run the document server docker container with secret key enabled (Docker arguments -e JWT_ENABLED=true  -e JWT_SECRET=[secret]
*Set the same secret in Nextcloud and click save

**What is the expected behavior?**
OnlyOffice should conntect to Nextcloud

**Did this work in previous versions of DocumentServer?**
It works when secret key is disabled

**DocumentServer version:**

(latest docker image)

**Operating System:**
Ubuntu 18.04 LTS

**Browser version:**
Firefox 68 (but the issue is not browser related)

**Comment by alexanderonlyoffice** [comment]
Hello @vasyugan, please try to indicate also JWT header in config.php of Nextcloud. It can be found in local.json in /etc/onlyoffice/documentserver/ inside the container.

The section to be added in config.php should look like this:
```
'onlyoffice' =>
  array (
    "jwt_secret" => "secret",
    "jwt_header" => "header"
	)
```
Please make sure the secret indicated in Nextcloud matches the one you indicated in docker run command. 

Please send us also the screenshot of ONLYOFFICE integration app address settings from Nextcloud.

**Comment by vasyugan** [comment]
I have added the sections per your instructions. What is the required value for jwt_header? 
Right now, I get the same error, see the screenshow. Dowloading the doc fails.

![Bildschirmfoto von 2019-09-27 17-07-56](https://user-images.githubusercontent.com/3313208/65780226-9595de80-e149-11e9-907a-1a794aac7c07.png)

**Comment by alexanderonlyoffice** [comment]
Hello @vasyugan, you can set any JWT header, the main thing is that the JWT header in local.json of the Document Server and JWT header you add with the section (specified in my previous message) in config.php match each other (they should be identical). Default header is 'Authorization'. 

Please try to change JWT header in local.json and add the same header in config.php. Please do not forget to restart all services of the Document Server after you make changes to local.json. Use `supervisorctl restart all` command inside the container with the Document Server to restart the services.

**Comment by vasyugan** [comment]
> Hello @vasyugan, you can set any JWT header, the main thing is that the JWT header in local.json of the Document Server and JWT header you add with the section (specified in my previous message) in config.php match each other (they should be identical). Default header is 'Authorization'.
> 
> Please try to change JWT header in local.json and add the same header in config.php. Please do not forget to restart all services of the Document Server after you make changes to local.json. Use `supervisorctl restart all` command inside the container with the Document Server to restart the services.

Thank you @alexanderonlyoffice Instead of manually editing the local.json, shouldn't it be possible to pass the secret and the JWT header on the command line as an environment parameter to the docker container? Because if you have to hand-edit the local.json, all your changes will be lost if you remove the container, won't they?

**Comment by vasyugan** [comment]
Thank you so much for your help! Seems to be working now! I guess it would be great if the steps could be documented in an easy-to-find place and also if one could simply pass the secret and header to the docker container as an environment variable!

**Comment by LinneyS** [comment]
Hi @vasyugan 
You can find in list of environment variables [JWT_HEADER](https://helpcenter.onlyoffice.com/server/docker/document/docker-installation.aspx)

**Comment by vasyugan** [comment]
> Hi @vasyugan
> You can find in list of environment variables [JWT_HEADER](https://helpcenter.onlyoffice.com/server/docker/document/docker-installation.aspx)

They don't seem to have an effect: I launch the docker container as follows:

j 
docker container run --name onlyoffice -i -t -d -p 127.0.0.1:8910:80 --rm \
    -v $PWD/app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice  \
    -v $PWD/app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data  \
    -v $PWD/app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice \
    -v $PWD/app/onlyoffice/DocumentServer/db:/var/lib/postgresql  onlyoffice/documentserver \
    -e JWT_ENABLED=true \
    -e JWT_SECRET=mysecret \
    -e JWT_HEADER=mycustomheader

Yet, /etc/onlyoffice/documentserver/local.json still has the default values.

**Comment by jogehl** [comment]
I have the same problem but setting the jwt_secret and the jwt_header in the nextcloud config not fix the problem. @alexanderonlyoffice is there any other possibility to get it working?

**Comment by vasyugan** [comment]
Why can't jr_header be set through the Nextcloud web interface or occ, given that without it, things don't work?

It is confusing that you can set jr_secret in two different places, the config file and the app settings, (presumably stored in the database) but changing the the config file is not reflected in the nextcloud settings interface.

**Comment by vasyugan** [comment]
btw, the only workaround, I have found for myself is to have docker mount local.json from the native file system as a bind mount.
