### ISSUE TITLE
Error when configuring Only Office on NextcloudVm Preinstalled 500 Gb Get converted Uri

### ISSUE THREAD

**Issue by BetaLeaf** [ONLYOFFICE/onlyoffice-nextcloud#145]
From: https://github.com/nextcloud/vm/issues/954

**Comment by alexanderonlyoffice** [comment]
Hello @Laurent-grain, please specify some additional information on the problem:

1. Please make sure the Nextcloud is accessible for the Document Server. You can check it with wget command. 
2. Please send us the archive of the folder with logs of the Document Server to support@onlyoffice.com with a note 'For technical support'.
3. Please enable Debug logging level in Nextcloud logs. You can find more information [here](https://docs.nextcloud.com/server/10/admin_manual/configuration_server/logging_configuration.html).

**Comment by Laurent-grain** [comment]
Hello 
I've send the logs by email to support

**Comment by alexanderonlyoffice** [comment]
Hello @Laurent-grain, please specify if you checked the accessibility of the Document Server and Nextcloud to each other. 

Do you see any errors in extended Nextcloud log? Please send it to us.

**Comment by Laurent-grain** [comment]
Hello
I think that I've found the problem
When I 've tested the connexion with wget, I've tried from the VM nextcloud, but not from the docker onlyoffice. So I saw that the certificat which is show when I connect from the docker onlyoffice to the "vm" nextcloud was not the real certificate. The problem  is that my docker onlyoffice in resolv.conf have 9.9.9.9 as the first DNS server. I'm looking for changing this and to put my own dns server in local network and I'm sure that the problem wil be resolve.

**Comment by Laurent-grain** [comment]
Hello
The problem is resolve. I change the dns of the docker only office by my own internal  dns server , and I can configure Only / nextcloud correctly. For information, in my case, if the DNS server of the docker only office is an external DNS , the certificat shown is the certifcat of the firewall not  teh certificat of onlyoffice. By Using the Internal dns server, the problem is resovle.

Thanks for your Help
