### ISSUE TITLE
Updating onlyoffice-documentserver broke functionality

### ISSUE THREAD

**Issue by stimpy-ch** [ONLYOFFICE/onlyoffice-nextcloud#148]
Hi,

After updating onlyoffice-documentserver on my machine the functionality seems to be broken.

**What I did:** 
Basically `apt install onlyoffice-documentserver` .

**What I expected to happen:**
Being able to edit documents in nextcloud by clicking on an office document.

**What actually happened:**
Clicking on a file opened a new window where it kept saying "loading document".
![2019-10-03 08_22_18-How to Linux docx - Nextcloud - Vivaldi](https://user-images.githubusercontent.com/1462036/66103923-6b17ab80-e5b7-11e9-8df5-bba09039d5f3.png)

After this I checked configuration:
In webinterface https://../nextcloud/settings/admin/onlyoffice I am having:
![2019-10-03 08_30_06-Settings - Nextcloud - Vivaldi](https://user-images.githubusercontent.com/1462036/66104198-1c1e4600-e5b8-11e9-8b6a-7ea5bbc8480d.png) . 
Secret is empty.
When saving the configuration I got the message:
`Error when trying to connect (Error occurred in the document service: Unknown error)`
Checking the logs it says:
`{"reqId":"oUxsoRCZA7y2JSdSLwqB","level":3,"time":"October 03, 2019 06:31:23","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxxx","app":"onlyoffice","method":"PUT","url":"\/nextcloud\/apps\/onlyoffice\/ajax\/settings\/address","message":"GetConvertedUri on check error: Error occurred in the document service: Unknown error","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64)","version":"16.0.4.1"}`

Checking some other post about similar issue I also did following:
- verified nextclouds config.php contains
```
  'onlyoffice' => 
  array (
          'verify_peer_off' => true,
  ),
```
- in /etc/onlyoffice/documentserver/log4js/production.json set  level from WARN to ALL . However  /var/log/onlyoffice/documentserver/nginx.error.log stays empty, however it is writable by www-data.
- I opened the website https://cloud.domain.org:1543/healthcheck and the whole response I got is: `true`
- In `/etc/onlyoffice/documentserver/default.json` it literally says without no replacements:
```
                        "secret": {
                                "browser": {"string": "secret", "file": "", "tenants": {}},
                                "inbox": {"string": "secret", "file": "", "tenants": {}},
                                "outbox": {"string": "secret", "file": ""},
                                "session": {"string": "secret", "file": ""}
```

**Some background information:**
CPU: i5-core
OS: Ubuntu 18.04.3 LTS
Nextcloud: 16.0.4
onlyoffice-documentserver: 5.4.1-39
I am using a self-signed certificate.
No docker version. Installation according to https://api.onlyoffice.com/editors/nextcloud and https://helpcenter.onlyoffice.com/server/linux/document/linux-installation.aspx .

I really wonder what I missed. Many thanks for any help!

**Comment by CarlOnlyoffice** [comment]
Hello @stimpy-ch 
Please click on Save button in the connector settings and after you see the error please check /var/log/onlyoffice/documentserver/**converter** and **docservice** logs for errors. Also check the availability of Nextcloud and Document Server to each other using wget command:
`wget https://document_server` from Nextcloud machine
`wget https://nextcloud` from DS machine

**Comment by stimpy-ch** [comment]
Hi @CarlOnlyoffice 
Many thanks for your reply. I followed this procedure:
1. I delete all logs 
2. run command `supervisorctl restart all`.
3. Went to onlyoffice setting's page and clicked on save.

As a result I got:
- converter/err.log -> empty
- converter/out.log 
```
[2019-10-08T06:35:52.031] [WARN] nodeJS - update cluster with 1 workers
[2019-10-08T06:35:52.036] [WARN] nodeJS - worker 26033 started.
[2019-10-08T06:35:52.036] [WARN] nodeJS - update cluster with 1 workers
```
- docservice/err.log -> empty
- docservice/out.log (full log here: https://pastebin.com/zp3FTaSC). A similar error like at the end repeats 4 times.
```
[2019-10-08T06:35:52.001] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2019-10-08T06:35:52.007] [WARN] nodeJS - update cluster with 1 workers
[2019-10-08T06:35:52.012] [WARN] nodeJS - worker 26024 started.
[2019-10-08T06:35:52.012] [WARN] nodeJS - update cluster with 1 workers
[2019-10-08T06:35:52.452] [WARN] nodeJS - Express server starting...
[2019-10-08T06:35:52.800] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode
[2019-10-08T06:35:55.599] [ERROR] nodeJS - sqlQuery error sqlCommand: INSERT INTO task_result (id, status, status_info, :
error: relation "task_result" does not exist
    at Connection.parseE (/var/www/onlyoffice/documentserver/server/DocService/node_modules/pg/lib/connection.js:604:11)
    at Connection.parseMessage (/var/www/onlyoffice/documentserver/server/DocService/node_modules/pg/lib/connection.js:401:19)
    at Socket.<anonymous> (/var/www/onlyoffice/documentserver/server/DocService/node_modules/pg/lib/connection.js:121:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)
...
```

Nextcloud and documentserver machines are the same. The are reachable:
```
$ wget http://10.8.0.26/nextcloud/
--2019-10-08 06:52:21--  http://10.8.0.26/nextcloud/
Connecting to 10.8.0.26:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://10.8.0.26/nextcloud/login [following]
--2019-10-08 06:52:21--  http://10.8.0.26/nextcloud/login
Reusing existing connection to 10.8.0.26:80.
HTTP request sent, awaiting response... 200 OK
Length: 6793 (6.6K) [text/html]
Saving to: ‘index.html’

index.html                                       100%[=======================================================================================================>]   6.63K  --.-KB/s    in 0s      

2019-10-08 06:52:21 (1.43 GB/s) - ‘index.html’ saved [6793/6793]
```
and 
```
$ wget http://127.0.0.1:8130/
--2019-10-08 06:53:10--  http://127.0.0.1:8130/
Connecting to 127.0.0.1:8130... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://127.0.0.1:8130/welcome/ [following]
--2019-10-08 06:53:10--  http://127.0.0.1:8130/welcome/
Reusing existing connection to 127.0.0.1:8130.
HTTP request sent, awaiting response... 200 OK
Length: 4592 (4.5K) [text/html]
Saving to: ‘index.html.1’

index.html.1                                     100%[=======================================================================================================>]   4.48K  --.-KB/s    in 0s      

2019-10-08 06:53:10 (654 MB/s) - ‘index.html.1’ saved [4592/4592]
```

So it looks like that something with the database is wrong?

Many thanks

**Comment by stimpy-ch** [comment]
In the meantime I just recreated onlyoffice user and table and then removed and re-installed onlyoffice-documentserver and it works now.
Many thanks!
