### ISSUE TITLE
Problem with versionning files in Onlyoffice/Nextcloud

### ISSUE THREAD

**Issue by xinux4d** [ONLYOFFICE/onlyoffice-nextcloud#157]
Hello,
Our environment:
Onlyoffice Document Server is 5.3.4.3
Nextcloud/Onlyoffice connector: 3.0.2
production server: Nextcloud 16.0.4.4 ( Apache 2.4.38, php 7.3.9)
test server: Nextcloud 16.0.5 ( Apache 2.4.38, php 7.3.10)

The problem:
When a user edits a document, the file is saved, if he edits the document again, the changes are saved.
But if in Nextcloud, the user uses versioning to restore a file.
If he downloads it -> the file is the restored version (good)
If it edits the restored file in Onlyoffice -> it's not good, it's not up to date

We have this problem on both our servers (production and testing), and with Onlyoffice 5.3.4.3.3 or your Onlyoffice test server (30-day demo).

Thank you for your clarification.
Best Regards,

**Comment by zealic** [comment]
Same issue in Nextcloud 17.0.0

**Comment by LinneyS** [comment]
Hello to all
please check version 4.0.0

**Comment by xinux4d** [comment]
It's ok for me !
(tests in 17.0.1 and 16.0.4)

Thank's !
