### ISSUE TITLE
Watermarking ("Secure view") on PDFs not working

### ISSUE THREAD

**Issue by wiswedel** [ONLYOFFICE/onlyoffice-nextcloud#158]
I've configured some simple secure view settings:

![image](https://user-images.githubusercontent.com/1804221/67952605-d91eb500-fbed-11e9-966b-2aba074bbfec.png)

On opening any kind of office file, watermarks are shown just fine.

Opening a PDF however results in the following error:
![image](https://user-images.githubusercontent.com/1804221/67952452-9e1c8180-fbed-11e9-9877-c0ecf99b279a.png)

PDFs without _watermark_ tag also open just fine in ONLYOFFICE.

## Test environment

- Nextcloud 17.0.0
- ONLYOFFICE connector 3.0.2
- ONLYOFFICE Integration Edition 5.4.1, linux-installed

## Logs

Nothing related to be found in any logs :-(

**Comment by LinneyS** [comment]
@K0R0L
@DenisDeeSign

**Comment by K0R0L** [comment]
Fixed in 5.4.2

**Comment by LinneyS** [comment]
v5.5.0
https://github.com/ONLYOFFICE/sdkjs/commit/2c40d4d02a03cbb0d5b6e4d672ee4f9061db810f

**Comment by LinneyS** [comment]
v5.5 is released

**Comment by jpbraun** [comment]
Nextcloud 18 & pdf (OnlyOffice): I still have the same problem. I need to watermark a pdf document. Is there a workaround?

**Comment by LinneyS** [comment]
@jpbraun 
ONLYOFFICE Document Server v5.5.3 open pdf with watermark well
