### ISSUE TITLE
Receive an email when a doc is commented

### ISSUE THREAD

**Issue by danicotillas** [ONLYOFFICE/onlyoffice-nextcloud#16]
Hi,
It´s a while I´m using OnlyOffice on a Nextcloud install and it´s great. There is a functionality I missed a lot, is there any way to mention people from the same network or that we have shared the doc with them so that they receive an email saying "You have a message on this doc" or something similar?

Thanks a lot!

**Comment by alexanderonlyoffice** [comment]
@danicotillas, could you please contact Nextcloud support team, so they consider adding such enhancement to Nextcloud, as this feature is not related to ONLYOFFICE.
