### ISSUE TITLE
Error when trying to connect (cURL error 28 [Ubuntu 18.04 - OnlyOffice on docker lastest

### ISSUE THREAD

**Issue by uSyzex** [ONLYOFFICE/onlyoffice-nextcloud#160]
Hi, 

So I followed up this tutorial : https://www.c-rieger.de/nextcloud-and-only-office-nginx/#one
(First part, same server + docker)

And I get this error when trying to connect on Nextcloud:

Error when trying to connect (cURL error 28: Operation timed out after 60001 milliseconds with 0 out of 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html))

I tried with wget to reach the link, but same problem : Unable to establish SSL connection after 60 seconds. 

Thank you kind stranger.

**Comment by ibnpetr** [comment]
> I tried with wget to reach the link, but same problem : Unable to establish SSL connection after 60 seconds.

Please check if the Document Server is reachable in your browser. 
If yes, please check if you have any errors in nginx logs.

**Comment by uSyzex** [comment]
> 
> 
> > I tried with wget to reach the link, but same problem : Unable to establish SSL connection after 60 seconds.
> 
> Please check if the Document Server is reachable in your browser.
> If yes, please check if you have any errors in nginx logs.

Yes it is, sorry I didn't mentionned it. 
Will check this, thank you !

**Comment by uSyzex** [comment]
> If yes, please check if you have any errors in nginx logs.

I dont see anything related to my office in the file /var/log/nginx/error.log or error.log.1
I can only see my failed attempt to set up GeoIP.

**Comment by alexanderonlyoffice** [comment]
@uSyzex, please specify if you are using CA-signed SSL certificates or self-signed ones?

Please send us the output of the wget commands.

**Comment by uSyzex** [comment]
@alexanderonlyoffice I'm using self-signed SSL certificates created with Let'sEncrypt. 

Here is the output : 
`
root@hkzserv:~# wget https://myserv.dyn.net:8443
--2019-11-02 10:48:01--  https://myserv.dyn.net:8443/
Resolving https://myserv.dyn.nett (https://myserv.dyn.net)... MyIP
Connecting to myserv.dyn.net (myserv.dyn.net)|8MyIP|:8443... connected.
Unable to establish SSL connection.
`

**Comment by uSyzex** [comment]
I tried to connect with UFW disabled and Fail2ban disabled, exact same error. For me it's a DNS problem or certificates problem

**Comment by alexanderonlyoffice** [comment]
@uSyzex, please check you SSL certificate with SSL Checker under this [link](https://www.sslshopper.com/ssl-checker.html).

**Comment by uSyzex** [comment]
Everything seems to be fine with the SSL certificate, all is checked.

If I try to connect using http, I get a bad request error, so there's maybe
something with the SSL certificate but I can't figure out.

**Comment by uSyzex** [comment]
If the problem is a DNS problem, do you have any idea on what can it be ?
I'm trying to troubleshooting this because I think that the resolution
between the docker document server and the main server isnt done properly.

**Comment by DrRSatzteil** [comment]
If you followed the tutorial mentioned then you are using the default docker network. For some reason the container looses its abilities to perform DNS lookups in that case. I have no idea why this happens but you may want to try to use a custom network (use e.g. "--network onlyoffice" in docker run command). This fixed the issue for me.

**Comment by uSyzex** [comment]
> 
> 
> If you followed the tutorial mentioned then you are using the default docker network. For some reason the container looses its abilities to perform DNS lookups in that case. I have no idea why this happens but you may want to try to use a custom network (use e.g. "--network onlyoffice" in docker run command). This fixed the issue for me.

I will try this ASAP, thank you very much !

**Comment by DrRSatzteil** [comment]
Actually I think you don't have to configure anything for the new network. However I'm not really familiar with docker networks. I just reused an existing custom network which does the trick for my private home installation. You may want to be a bit more professional in other environments I guess ;)

**Comment by DrRSatzteil** [comment]
Oh and in case I got your question wrong: there are no configuration changes for onlyoffice needed.

**Comment by uSyzex** [comment]
> 
> 
> Actually I think you don't have to configure anything for the new network. However I'm not really familiar with docker networks. I just reused an existing custom network which does the trick for my private home installation. You may want to be a bit more professional in other environments I guess ;)

Okay thank you, I read that network in docker will use by default the hosts file on the machine it's running. Can't wait to try that, thank you very much !

> 
> 
> Oh and in case I got your question wrong: there are no configuration changes for onlyoffice needed.

You got it right, no worries

**Comment by uSyzex** [comment]
Fixed it by adding a local DNS Resolution in /etc/hosts.
<local IP>  <myserv.dyn.net> <name>
I feel dumb, but hope it will help someone else meh.
