### ISSUE TITLE
Watermark does not work

### ISSUE THREAD

**Issue by 4y55** [ONLYOFFICE/onlyoffice-nextcloud#165]
Configuration
![config](https://user-images.githubusercontent.com/50604378/69007536-a0851800-091d-11ea-8f77-3cc64163f64e.png)

```
[PHP] Error: Undefined index: allGroupsList at /var/www/html/apps/onlyoffice/lib/appconfig.php#733

PUT /index.php/apps/onlyoffice/ajax/settings/watermark
from 10.0.0.1 by admin at 2019-11-17T12:32:41+00:00
```
```
[PHP] Error: trim() expects at least 1 parameter, 0 given at /var/www/html/apps/onlyoffice/controller/settingscontroller.php#232

PUT /index.php/apps/onlyoffice/ajax/settings/watermark
from 10.0.0.1 by admin at 2019-11-17T12:32:41+00:00
```

- Nextcloud 17.0.1
-  ONLYOFFICE 3.0.2
- Version 5.2.8 CE

**Comment by LinneyS** [comment]
fixed
97b07920eaa70b6406e7495fe543f6ebeaa7f310
6c403665b3a227d8907030d38d831429273f7470

It will be released in the next version

**Comment by 4y55** [comment]
Thanks for the quick support / help.
I made the necessary corrections, and no more errors in the console, but the watermark does not appear yet.

Are there any more fixes yet to be released?

**Comment by LinneyS** [comment]
Hello @4y55 
please check version 4.0.0
