### ISSUE TITLE
Onlyoffice versions not saved in Nextcloud

### ISSUE THREAD

**Issue by curiousmitchell** [ONLYOFFICE/onlyoffice-nextcloud#168]
Hi folks, I'm running Nextcloud 16.05 with docker on Apache with an Archlinux server. The docker image was created 3 days ago, so is current. Issue I'm having is that while I can edit files within Nextcloud in Onlyoffice, the timestamp is not updated in Nextcloud. I.e. - edited files show when they were last modified and uploaded to Nextcloud from my desktop. 

If I open the file in Onlyoffice in Nextcloud I can see the changes. The only way to have this sync with my desktop computer is to download the file, and save it in Nextcloud - i.e., working-file(2).doc
Then I can delete the original file, and rename the one I've just created - tedious.

Is there a way to troubleshoot this, and work out why the Nextcloud timestamp isn't being updated when I modify files within Nextcloud with Onlyoffice? This happens regardless of file type.

Thanks.

**Comment by LinneyS** [comment]
Hi @curiousmitchell 
Are you sure that the file is changed after editing? When you download a file from Nextcloud (not from ONLYOFFICE editor), it does have your changes? file size changed?
Just want to make sure that you see the changes that are not in the cache.

**Comment by curiousmitchell** [comment]
Weirdly, no changes at all in Nextcloud, however when I open the file again in Onlyoffice I see my changes. 
I.e.:
Open finances.xlsx by clicking on it in Nextcloud, and the file opens in Onlyoffice. Make my edits. Save file. Close browser window and log into Nextcloud again. Downloading finances.xlsx and opening from my computer dow not show my changes, however opening the file on Nextcloud in Onlyoffice shows my changes. 

Any idea what's going on here?

**Comment by alexanderonlyoffice** [comment]
@curiousmitchell, please click on the 'Save' button on ONLYOFFICE integration app settings page once again, we suppose there should be an error message if you do this.

**Comment by curiousmitchell** [comment]
Just tried it - the only message I see is "Settings have been updated succesfully."Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Alexander Zozulya <notifications@github.com> Date: 19/11/19  6:22 pm  (GMT+10:00) To: ONLYOFFICE/onlyoffice-nextcloud <onlyoffice-nextcloud@noreply.github.com> Cc: curiousmitchell <mitchell@curiouslegends.com.au>, Mention <mention@noreply.github.com> Subject: Re: [ONLYOFFICE/onlyoffice-nextcloud] Onlyoffice versions not saved in Nextcloud (#168) @curiousmitchell, please click on the 'Save' button on ONLYOFFICE integration app settings page once again, we suppose there should be an error message if you do this.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/168?email_source=notifications\u0026email_token=ANZSKPVABF4RGBXI3JZXDMTQUOH2NA5CNFSM4JOMEIK2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEENEK2A#issuecomment-555369832",
"url": "https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/168?email_source=notifications\u0026email_token=ANZSKPVABF4RGBXI3JZXDMTQUOH2NA5CNFSM4JOMEIK2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEENEK2A#issuecomment-555369832",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Zelphy** [comment]
Hi,

It seems that we also have this behaviour!

Nextcloud client is installed on my computer.
- If I save my file via Excel / LibreOffice, a sync is triggered and I can see the changes if I open the document in ONLYOFFICE;
- If I open the document in ONLYOFFICE, I can do some changes and save the document (or auto-save) but sync is NOT triggered, NO revision is created and if I download this file, my changes are not present. If I open this file via ONLYOFFICE, changes are there.

Nextcloud version: 17.0.0

**Comment by alexanderonlyoffice** [comment]
@curiousmitchell, is there a possibility to create a test account in your Nextcloud for us? You can use our email address 4test@onlyoffice.com to register it. If it is possible, please send us the login data to support@onlyoffice.com with a note for technical support. 

@Zelphy, it seems that you have another issue, please specify if you are talking about the sync problem in Nextcloud desktop client. If not, please provide more information about the problem: 

1. OS of the server where ONLYOFFICE Document Server is deployed;
2. Its installation type (docker or deb/rpm);
3. Click on the 'Save' button on ONLYOFFICE integration app settings page and send us a screenshot of the message you get.

**Comment by curiousmitchell** [comment]
@alexanderonlyoffice Thanks for that, I have created a test user and sent the email through. Fingers crossed. M

**Comment by alexanderonlyoffice** [comment]
@curiousmitchell, thank you for the provided access. I wasn't able to open any file, as the Document Server seems inaccessible, but, I have noticed that the Document Server uses self-signed SSL certificate. If you are using self-signed certificates on the Document Server's side, you need to disable verification of not-trusted SSL certificates by Nextcloud by adding the following section to config.php: 
```
'onlyoffice' =>
  array (
    'verify_peer_off' => TRUE,
  )
```
The most right solution will be to use CA-signed certificates.

**Comment by curiousmitchell** [comment]
Thanks for that. I'm not sure why you are unable to edit documents,  I just signed into that account, clicked on test.docx and it opened in Onlyoffice fine. Are you able to retest? I can look into sorting another certificate, however does this mean that Onlyoffice doesn't suppory self signed certificates? I have already edited the config files as you suggested.

**Comment by alexanderonlyoffice** [comment]
@curiousmitchell, I just checked once again and I do not see any problems with files saving. I have added some changes to the test.docx file, closed it, waited about 10 seconds to make sure the file version is saved in Nextcloud (timestamp changed), downloaded the file and opened it locally on PC, all changes are in file.

**Comment by curiousmitchell** [comment]
> @curiousmitchell, I just checked once again and I do not see any problems with files saving. I have added some changes to the test.docx file, closed it, waited about 10 seconds to make sure the file version is saved in Nextcloud (timestamp changed), downloaded the file and opened it locally on PC, all changes are in file.

 Bizarre... just tried again from my end and same issue as before. I opened the docx file with Onlyoffice, made changes, saved it, then checked the timestamp - no change in my Nextcloud server. What else can I try?

**Comment by alexanderonlyoffice** [comment]
@curiousmitchell, please see this [screenshot](https://take.ms/w0jI6). Try to clear browser cache, use another browser or open Nextcloud in incognito window.

If possible, please make a video showing the problem on your side.

**Comment by curiousmitchell** [comment]
Thanks for that, will test extensively. What browser are you using?

**Comment by alexanderonlyoffice** [comment]
@curiousmitchell, checked on the latest versions of Mozilla Firefox (71.0) and Chrome (78.0.3904.108) browsers.

**Comment by curiousmitchell** [comment]
Ok - have checked now on firefox, both 70 (linux) & 68.3 on android. Seems to be working fine. Not sure what's changed, except I notice that unless I close the browser tab the document is open in, it doesn't save to Nextcloud. I.e. - Open document in Onlyoffice, click right hand icon to open file location, and nothing is saved to Nextcloud. Can wait as long as I like and it doesn't happen. But if I close the browser tab with Onlyoffice running, then the file writes to Nextcloud, etc.

Not sure if this is intended behavior, but now I'm aware of it there is a perfectly easy work around - close the office tab first. Thanks again! Please let me know if you would like me to test anything else. I'll wait for your reply, then am happy to makr this as solved.

**Comment by alexanderonlyoffice** [comment]
@curiousmitchell, while you are editing the file all the changes added to the file are stored in the Document Server's cache, then after all editing sessions are over (all browser tabs with this file are closed) the final version of the file is built and then saved in the storage. This is how saving of the file works in editors at the moment.

I am glad the issue has been resolved.

**Comment by fcayre** [comment]
Hello @alexanderonlyoffice does that mean that if, in a collaborative work situation, a person does never close its onlyoffice editing browser tab the document is never saved? Is there at least a timeout for the Document Server's cache to flush to the Nextcloud file? If not, this looks very dangerous to me. Any thoughts?

**Comment by alexanderonlyoffice** [comment]
Hello @fcayre,  you can set "sessionidle" parameter in default.json of Document Server, which is responsible for ending sessions due to user's inactivity. It can be set by a text, for example: `"sessionidle": "1d",` or `"sessionidle": "1h",`. Default.json config can be found in /etc/onlyoffice/documentserver/ for DEB/RPM (or C:\Program Files\Onlyoffice\DocumentServer\config for Windows OS). Please do not forget to restart all Document Server services with `supervisorctl restart all` for the changes to default.json to be applied.

You can also use `documentserver-prepare4shutdown.sh` script that was developed for the update process of the Document Server to avoid data loses. After its execution `bash documentserver-prepare4shutdown.sh` it ends all active editing sessions to let the files be saved in DMS. Please note that it also prevents the new sessions from opening, so you need to restart Document Server services with the command mentioned above to allow document editing again.

**Comment by fcayre** [comment]
Thanks for the tip @alexanderonlyoffice ! The default value for sessionidle (="0", meaning "never consider sessions idle I suppose), is a bit strange, especially in a nextcloud context, and may require a change ("1h" looks like a good default value).

**Comment by jayfinley** [comment]
Hi

How are these changes implemented using the Community Document Server? (For those using cPanel for example)

I edit the document in OnlyOffice and when I open the same document using Excel via Web drive the files is corrupt.

Only solution I have is to open the file again in OnlyOffice and then save a copy.

:-)

**Comment by PacNiKK** [comment]
Hi @alexanderonlyoffice I have the exact same Issue (changes are only seen by onlyoffice, not by nextcloud), but changing my browser or even device does not solve the issue. Onlyoffice on my mobile phone sees the changes I make on my computer, but my nextcloud does not. Seems like the session is never closed somehow, so changes stay in the server, but the actual file is never built.
Nextcloud version is 22.0.0 and community server version is: 0.1.11
Thanks for your help

**Comment by ShockwaveNN** [comment]
@PacNiKK 
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate [GitHub repository](https://github.com/nextcloud/documentserver_community). 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).

**Comment by PacNiKK** [comment]
> @PacNiKK
> Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate [GitHub repository](https://github.com/nextcloud/documentserver_community).
> 
> If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).

Thanks for your reply, i was not aware that the Community Document Server was not developed by you. I think I figured out that my problem has something to do with cron.php not being executed properly.

**Comment by CarlosAPCunha** [comment]
> > @PacNiKK
> > Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate [GitHub repository](https://github.com/nextcloud/documentserver_community).
> > If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).
> 
> Thanks for your reply, i was not aware that the Community Document Server was not developed by you. I think I figured out that my problem has something to do with cron.php not being executed properly.

Hi!

I have believe the same problem, nextclound in SNAP, and Onlyoffice via Docker, changes to files are only seen if they are seen by onlyoffice, if you download the file it doesn't see with the changes.

What was your solution?

Regards;
