### ISSUE TITLE
Onlyoffice does not work after update of NC

### ISSUE THREAD

**Issue by rollanders** [ONLYOFFICE/onlyoffice-nextcloud#17]
I have two NS installations - one NC13.0.6 on an externally hosted VPS and one NC 14.0.3 on a local NAS. In both installations Only office stopped functioning after an update.
If I try to access the OnlyOffice directly at https://mydomain.com:8443 I get an https error (unsafe)
If i try the same on my NAS I just get a message unable to connect the adress.  docker and nginx are running. 
Originally I got an error "Onlyoffice cannot be reached" when I tried open a document, but now I are given the alternative to download the file on the VPS, and on the NAS the document is opened in Collabora (I have both on the NAS). 
Help

**Comment by dmitrydrynov** [comment]
Onlyoffice not working after update to 14.0.3 (in old version 14.0.1 was ok)

Error
"Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.)"

Config file same as before.
Nginx same as before.
Onlyoffice server config same as before.

**Comment by BVEsun** [comment]
Same happen
Onlyoffice not working after update to 14.0.3 (in old version 13.0.5 was ok)

Error
"Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.)"

Config file same as before.
Nginx same as before.
Onlyoffice server config same as before.

**Comment by alexanderonlyoffice** [comment]
@rollanders, @dmitrydrynov, @BVEsun could you please specify some additional information:

1. OS of the server where ONLYOFFICE Document Server is installed;
2. Its installation type (docker, deb/rpm or Windows installation).

We are going to reproduce the mentioned issue.

**Comment by rollanders** [comment]
The OS is Ubuntu 18.04 and the OpenOffice is a docker (on the same server). The installations were similar on one hosted VPS (Contabo) and a QNAP NAS. Worked well up to the update. Same problem in both installations. 

I have used these instructions/scripts for the installation
https://www.c-rieger.de/nextcloud-14-nginx-installation-guide-for-ubuntu-18-04-lts/
https://www.c-rieger.de/nextcloud-and-only-office-nginx/ the second alternativ on same server.

**Comment by BVEsun** [comment]
OS: CentOS Linux release 7.5.1804
Nextcloud is installed version: 14.0.3
OpenOffice is a docker (On the same server)
nginx version: nginx/1.12.2
PHP 7.2.10 (cli) (built: Sep 15 2018 07:10:58) ( NTS )
mysql  Ver 15.1 Distrib 5.5.60-MariaDB

**Comment by alexanderonlyoffice** [comment]
Hello @rollanders, @BVEsun, it seems that the address settings of the integration app are incorrect. Please make sure that the Document Server can be accessed via the address specified for ONLYOFFICE integration app settings. Check also if NC is accessible for the Document Server.

**Comment by kickitt** [comment]
Same problem. I have Ubuntu 16.04 after update to 2.1.0 version of app in nextcloud 13.0.5 i faced with this error.

**Comment by rollanders** [comment]
I solved it by a reinstallation

**Comment by kickitt** [comment]
> I solved it by a reinstallation

By reinstallation of what?

**Comment by derwolfk** [comment]
I could solve it by:
/etc/onlyoffice/documentserver/default.json
Please change the value of the parameter "rejectUnauthorized": from true to false

**Comment by kickitt** [comment]
Solved it using correct SSL certs and correct version of node js on the onlyoffice server side. After making correct settings use next command sudo supervisorctl restart all .

**Comment by barrydegraaff** [comment]
I am having the same issue.

I have an OnlyOffice server running, and it works fine when I use it using the integration in Zimbra (that I wrote https://github.com/Zimbra-Community/owncloud-zimlet),  but it does not work when using the Nextcloud OnlyOffice app.

In the running docker container I did as suggested above:
/etc/onlyoffice/documentserver/default.json
Please change the value of the parameter "rejectUnauthorized": from true to false

And a `supervisorctl restart all`

That did make it work again. The weird part is, that this instance does not use jwt, so why does this work? Also it will break the next time I redeploy docker, as that is what I am using, and I redeploy often.

**Comment by barrydegraaff** [comment]
Can it be it requires some specific user agent string?

**Comment by alexanderonlyoffice** [comment]
@rollanders, please confirm that the issue has been resolved. 

@barrydegraaff, @kickitt I would ask you to create new separate issues with detailed description of your servers and information about the problem.
