### ISSUE TITLE
Support for document history API

### ISSUE THREAD

**Issue by awesome-manuel** [ONLYOFFICE/onlyoffice-nextcloud#175]
This is a request to support the document history API of OnlyOffice: https://api.onlyoffice.com/editors/history

This is actually one of the main drawbacks compared to Collabora in my opinion.

**Comment by alexanderonlyoffice** [comment]
@awesome-manuel, thank you for your feedback. We will take it into consideration.

**Comment by LinneyS** [comment]
#194
