### ISSUE TITLE
User agent clarification

### ISSUE THREAD

**Issue by tobiasKaminsky** [ONLYOFFICE/onlyoffice-nextcloud#179]
Hi @LinneyS 

we discussed the user agent part in our chat.
can you some this up, for our other engineers here? 
If I remember correctly, there are 4 cases: Android/ios and mobile/tablet.
Can you provide also an example for each?

**Comment by LinneyS** [comment]
Hi @tobiasKaminsky 

Current UserAgent
Android: `Mozilla/5.0 (Android) Nextcloud-android/3.9.2`
iOS: `Mozilla/5.0 (iOS) Nextcloud-iOS/2.24.0`

We ask you to change this.
Android: add the space with the number after `Android` and add the word `Mobile`.
Example for android: `Mozilla/5.0 (Android 5) Mobile Nextcloud-android/3.9.2`

iOS: add the word `Mobile` for mobile phones only. For tablets, leave unchanged.
Example for iOS phone: `Mozilla/5.0 (iOS) Mobile Nextcloud-iOS/2.24.0`
Example for iOS tablet: `Mozilla/5.0 (iOS) Nextcloud-iOS/2.24.0`

@ayuzhin @michael-efremov

feature: direct editor
https://github.com/ONLYOFFICE/onlyoffice-nextcloud/tree/feature/direct-editor

**Comment by tobiasKaminsky** [comment]
@marinofaggiana

**Comment by marinofaggiana** [comment]
mmm I think about it with Ivan

**Comment by tobiasKaminsky** [comment]
It is only when you open the url you get for OO (from direct editing).
Is not about changing the user agent globally.

**Comment by Ivansss** [comment]
> It is only when you open the url you get for OO (from direct editing).
> Is not about changing the user agent globally.

In this case, it should be fine @marinofaggiana.
We also modify the user agent when subscribing for push notifications.

**Comment by marinofaggiana** [comment]
Yes, possible .... but is not a good thing only for OO

**Comment by tobiasKaminsky** [comment]
Why? They need it for their special internal handling.

**Comment by marinofaggiana** [comment]
Because I use only a function for passing the useragent to driver(s) and the useragent is used for all endpoint call, modify only for this func is hardcode

**Comment by tobiasKaminsky** [comment]
True, but on Android I also have to send a custom user agent for push, authentication.
Therefore I already have a more flexible way…

But if OO needs it, I fear there is no other choice…

**Comment by marinofaggiana** [comment]
We can't pass a parameter ?

**Comment by LinneyS** [comment]
Why can't you use a more informative userAgent globally on your mobile device? With operating system version and device type
It seems to me the current value is hardcode.

**Comment by marinofaggiana** [comment]
@LinneyS yes for me is better a globally modify for a better user agent and yes now is already hardcoded originally

**Comment by marinofaggiana** [comment]
@Ivansss which user agent use you ?

**Comment by Ivansss** [comment]
The problem if we change the userAgent globally is that we should also change the regexs that Nextcloud use to detect the clients (and create backports for older NC versions).
I still think the simplest solution here is to use this new userAgent only when opening OO files.
We already use a custom userAgent for push notifications, so I would also use a custom one (the one described [above](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/179#issuecomment-566531625)) for this case.
What do you think @marinofaggiana @tobiasKaminsky @LinneyS ?

**Comment by tobiasKaminsky** [comment]
We cannot change this globally and it is not needed/meaningful.
It should just be another user agent, if and only if we connect to OnlyOffice.

**Comment by LinneyS** [comment]
Android:
https://github.com/nextcloud/android/pull/4890
at https://github.com/nextcloud/android/commit/ddffaf7b496c44a3eeb1252a44ccd8ee845a746d

**Comment by marinofaggiana** [comment]
@LinneyS why is not possible open a file from Nextcloud iOS "open in ..." and OnlyOffice App "Documents" on iOS ?

**Comment by LinneyS** [comment]
@marinofaggiana 
Can you check with v4.1.1
On v4.1.2 I made a mistake https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/228

**Comment by marinofaggiana** [comment]
Thanks, @LinneyS now I add the UserAgent on webview, can you use TestFlight for test when ready ?

https://testflight.apple.com/join/GjNbfo2a

**Comment by marinofaggiana** [comment]
https://github.com/nextcloud/ios/commit/479e57cb35a126bd2ed2353cefecf71107e380ee

**Comment by nav-fess** [comment]
Hi. Please tell me when I can install a new build from Test Flight? Update has not yet arrived.

**Comment by marinofaggiana** [comment]
yes @nav-fess , I think Wednesday  or Thursday.

**Comment by nav-fess** [comment]
Thanks for the answer

**Comment by marinofaggiana** [comment]
Version 2.25.6 (2) available :-) please test it

**Comment by LinneyS** [comment]
Hi @marinofaggiana 
Sorry
We made a mistake with the parameter.

Example for iOS phone: `Mozilla/5.0 (iPhone) Mobile Nextcloud-iOS/2.24.0`
Example for iOS tablet: `Mozilla/5.0 (iPad) Nextcloud-iOS/2.24.0`

**Comment by marinofaggiana** [comment]
@LinneyS news here ?

**Comment by LinneyS** [comment]
Hi @marinofaggiana 
When the file is opened then the correct useragent `Mozilla/5.0 (iPhone) Mobile Nextcloud-iOS/2.25.6`
But when creating, the previous version is still `Mozilla/5.0 (iOS) Nextcloud-iOS/2.25.6`

**Comment by marinofaggiana** [comment]
@LinneyS I thought it was only for viewing, ok, I add for create as well.

**Comment by LinneyS** [comment]
We also detected a problem with the iOS application.
Editors zoom when starting editing.
Can you add the value `user-scalable=no`:
https://github.com/nextcloud/server/blob/062d9dadcb696f3b508d857686ade6db0ff29752/core/templates/layout.base.php#L9
```
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=no">
```

Should I create issue on core?

**Comment by juliushaertl** [comment]
Yes, please open an issues in the server repo so we can discuss with we can possibly make this a default.

In the meantime you can set the viewport dynamically like this:
https://github.com/nextcloud/text/blob/252296e15e583d0ec8dca957d5532bbb87d61579/src/views/DirectEditing.vue#L108

**Comment by marinofaggiana** [comment]
@LinneyS V. 2.25.6 build 8
