### ISSUE TITLE
Presented with a blank screen

### ISSUE THREAD

**Issue by DotOnedotNL** [ONLYOFFICE/onlyoffice-nextcloud#182]
<img width="1724" alt="Screenshot 2019-12-23 at 19 29 10" src="https://user-images.githubusercontent.com/19171666/71374746-1c791c80-25bc-11ea-9716-97b6610f3a27.png">
I have nextcloud and onlyoffice running in docker containers.
Both are behind a Traefik 2.0 proxy.

nextcloud works fine and when I go to the onlyoffice url I'm presented with the message that the onlyoffice server is running.
In the integration tool I entered the onlyoffice URL and for security I changed the secret.
When I press the apply button the URL is accepted and the additional 'Common Settings' are shown.

So far so good. However, If I try to edit a document or open a new document I'm presented with an blank page only showing the nextcloud header. It does not start onlyoffice.

I changed the loglevel to debug in the onlyoffice 'production.json' file.
Pressing the apply button on the configuration page shows the document conversion in the logging:

> onlyoffice       | [2019-12-23T18:10:56.666] [DEBUG] nodeJS - output (data={"cmd":{"c":"conv","id":"conv_check_1219178434_docx","format":"docx","url":"https://cloudstore.XXXXX.YY/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.nLPhy2-rN_sdIQVhzZ5KTe5qG3NisGYSjILfTDuDCt0","title":"check_1219178434.docx","outputformat":65,"outputpath":"output.docx","codepage":46,"delimiter":4,"embeddedfonts":false,"status_info":0,"nobase64":true}};id=conv_check_1219178434_docx)
onlyoffice       | [2019-12-23T18:10:56.667] [DEBUG] nodeJS - postProcess (id=conv_check_1219178434_docx)
onlyoffice       | [2019-12-23T18:10:56.667] [DEBUG] nodeJS - deleteFolderRecursive (id=conv_check_1219178434_docx)
onlyoffice       |
onlyoffice       | ==> /var/log/onlyoffice/documentserver/docservice/out.log <==
onlyoffice       | [2019-12-23T18:10:56.670] [DEBUG] nodeJS - Start receiveTask: docId = conv_check_1219178434_docx {"cmd":{"c":"conv","id":"conv_check_1219178434_docx","format":"docx","url":"https://cloudstore.XXXXX.YY/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.nLPhy2-rN_sdIQVhzZ5KTe5qG3NisGYSjILfTDuDCt0","title":"check_1219178434.docx","outputformat":65,"outputpath":"output.docx","codepage":46,"delimiter":4,"embeddedfonts":false,"status_info":0,"nobase64":true}}
onlyoffice       | [2019-12-23T18:10:56.675] [DEBUG] nodeJS - End receiveTask: docId = conv_check_1219178434_docx
onlyoffice       | [2019-12-23T18:10:57.529] [DEBUG] nodeJS - End convert request end true url http://onlyoffice/cache/files/conv_check_1219178434_docx/output.docx/check_1219178434.docx?md5=e2ih-BSZAEXf7Kwqs7GqEw&expires=1577125558&disposition=attachment&ooname=output.docx status 0 docId = conv_check_1219178434_docx

I don't seen any strange things in the traefik configuration

> onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    hostname: onlyoffice
    environment:
      - HTTP_CHECK=GET /healthcheck
      - EXTRA_SETTINGS=http-check expect string true
    stdin_open: true
    tty: true
    restart: always
    networks:
      - traefik_proxy
    volumes:
      - ${DATADIR}/onlyoffice/data:/var/www/onlyoffice/Data
      - ${DATADIR}/onlyoffice/log:/var/log/onlyoffice
      - ${CONFIGDIR}/onlyoffice/production.json:/etc/onlyoffice/documentserver/log4js/production.json:ro
      - ${CONFIGDIR}/onlyoffice/local.json:/etc/onlyoffice/documentserver/local.json:ro
    env_file: cloudstore.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.document-secure.entrypoints=https"
      - "traefik.http.routers.document-secure.rule=Host(`document.${DOMAINNAME}`)"
      - "traefik.http.routers.document-secure.tls=true"
      - "traefik.http.routers.document-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.document-secure.service=document"
      - "traefik.http.routers.document-secure.middlewares=secured@file"
      - "traefik.http.services.document.loadbalancer.server.port=80"
      - "traefik.http.services.document.loadbalancer.passHostHeader=true"
      - "traefik.docker.network=traefik_proxy"

Anyone an idea?

**Comment by DotOnedotNL** [comment]
Anyone an idea?

It looks like onlyoffice does not even get called when trying to edit a document

**Comment by alexanderonlyoffice** [comment]
@DotOnedotNL, please specify if Document Server and ONLYOFFICE Document Server are installed on the same machine or on different ones. 

Do you get any errors when clicking on the 'Save' button on ONLYOFFICE integration app settings page?

Try to check the accessibility of the Document Server and Nextcloud to each other with wget command from inside the containers. `wget https://documentserver_address/ `from inside the container with Nextcloud and `wget https://nextcloud_address/` from the container with Document Server. 

Open browser console and choose Network tab when opening the file. If there are any error entries, please send us the screenshot. Do the same with Console tab of browser console opened. 

Specify how you enabled HTTPS on the Document Server's side and specify if you are using self-signed certificates.

**Comment by DotOnedotNL** [comment]
Sorry for the late reply, I'm off on holiday for a couple of days.
But yes, both nextcloud and onlyoffice are running on the same server.
When I press the save button I don't get any errors.

Both servers are proxied by Traefik which also takes care of the ACME certs.
So both the nextcloud server and the openoffice server do not use certificates. the Traefik proxy is taking care of that.

Let me try to open a VPN and do some tests remotely.

**Comment by DotOnedotNL** [comment]
I did a _wget https://documentserver_address/_ from inside the container with Nextcloud and _wget https://nextcloud_address/_ from the container with Document Server. 
Both resolve and download ok.

On the onlyoffice container:
```
root@onlyoffice:/# wget https://cloudstore.familievink.nl
--2019-12-30 21:17:06--  https://cloudstore.familievink.nl/
Resolving cloudstore.familievink.nl (cloudstore.familievink.nl)... 2001:980:XXXX:YYYY:192:168:1:9, 192.168.1.9
Connecting to cloudstore.familievink.nl (cloudstore.familievink.nl)|2001:980:XXXX:YYYY:192:168:1:9|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cloudstore.familievink.nl/login [following]
--2019-12-30 21:17:06--  https://cloudstore.familievink.nl/login
Reusing existing connection to [cloudstore.familievink.nl]:443.
HTTP request sent, awaiting response... 200 OK
Length: 5718 (5.6K) [text/html]
Saving to: ‘index.html’

index.html                    100%[=================================================>]   5.58K  --.-KB/s    in 0s

2019-12-30 21:17:06 (58.0 MB/s) - ‘index.html’ saved [5718/5718]

```


And on the nextcloud container:
```
root@7c3aba19a6a9:/# wget https://document.familievink.nl
--2019-12-30 21:23:17--  https://document.familievink.nl/
Resolving document.familievink.nl (document.familievink.nl)... 2001:980:XXXX:YYYY:192:168:1:9, 192.168.1.9
Connecting to document.familievink.nl (document.familievink.nl)|2001:980:XXXX:YYYY:192:168:1:9|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://document.familievink.nl/welcome/ [following]
--2019-12-30 21:23:17--  https://document.familievink.nl/welcome/
Reusing existing connection to [document.familievink.nl]:443.
HTTP request sent, awaiting response... 200 OK
Length: 4592 (4.5K) [text/html]
Saving to: 'index.html'

index.html                    100%[=================================================>]   4.48K  --.-KB/s    in 0s
```

**Comment by DotOnedotNL** [comment]
She screenshot from the network tab of the browser console.
All is loading fine except for script files on the top.
If I scroll down I still see success messages for these files


<img width="1561" alt="Screenshot 2020-01-01 at 11 57 54" src="https://user-images.githubusercontent.com/19171666/71641116-81083b80-2c8e-11ea-8e94-facb8a48b21d.png">

<img width="1723" alt="Screenshot 2020-01-01 at 12 01 09" src="https://user-images.githubusercontent.com/19171666/71641117-88c7e000-2c8e-11ea-8390-0365e052e95a.png">

**Comment by CarlOnlyoffice** [comment]
Hello @DotOnedotNL,
Are there any errors in the 'Console' tab of the browser console? 
Please try to comment out the x-frame-options header on the side of Nextcloud and check the results.

**Comment by DotOnedotNL** [comment]
We're a bit closer to the solution.
Traefik, being the proxy for both containers used the same header setting for the nextcloud and onlyoffice.
Nextcloud requires the x-frame-options: SAMEORIGIN but it should not be set for onlyoffice.
I removed the x-frame-options for the onlyoffice container and now it does open.
It still shows an error that it cannot connect to the spell checker.

`Firefox can’t establish a connection to the server at wss://document.familievink.nl/5.4.2-46//spellchecker/doc/3516194505/c/897/dicelr2v/websocket. `

Another thing we have to tackle, but we're close

**Comment by defilor** [comment]
Any solution to this problem? I have the exact same problem, it seems, running behind an Apache reverse proxy. Finally got to the point where Nextcloud connects to Onlyoffice without an error message, but when I open or create a new document I get exactly the same. On chrome/firefox an empty page, on iOS Safari the "unknown error", returning to document list. 

Thanks!

**Comment by DotOnedotNL** [comment]
It is a proxy issue indeed.
After some searching, trial and error I found that removing the Connection header line from /etc/nginx/includes/http-common.conf fixed the issue.

`

proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
\#  proxy_set_header Connection $proxy_connection;
proxy_set_header X-Forwarded-Host $the_host;
proxy_set_header X-Forwarded-Proto $the_scheme;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
`

**Comment by bloomvdomino** [comment]
@DotOnedotNL There is no need to operate inside the container.

Simply add the following line to your labels (or add it to a separate tls settings file):

traefik.http.middlewares.oo-header.headers.customRequestHeaders.X-Forwarded-Proto=https

That should solve the problem.

**Comment by defilor** [comment]
Unfortunately, I run the reverse proxy in Apache 2.4 and can not figure out how this is achieved. Anyone able to help how the commented-out "proxy_set_header"-directive translates into "Apachian"? None of my searches have produced any results and I can't find any configuration examples. Thanks!

**Comment by DotOnedotNL** [comment]
@bloomvdomino thnx, verified and works
