### ISSUE TITLE
Error on save configuration

### ISSUE THREAD

**Issue by mishka88ru** [ONLYOFFICE/onlyoffice-nextcloud#184]
Hello!

I am trying to install OnlyOffice docker to use it with existing Nextcloud instance (on the same machine).  
In Nextcloud Settings/OnlyOffice panel configuration is
```
Document Editing Service address = https://office.xxx.local
secret = ""
Document Editing Service address for internal = https://office.xxx.local
Server address for internal = https://cloud.xxx.local
```
After I press the Save button, error appears:
```
{
"reqId":"qweasdzxc","level":3,"time":"2019-12-25T13:16:18+03:00",
"remoteAddr":"192.168.x.y","user":"root","app":"onlyoffice",
"method":"PUT","url":"\/apps\/onlyoffice\/ajax\/settings\/address",
"message":"HealthcheckRequest on check error: cURL error 56: Received HTTP code 503 from proxy after CONNECT (see http:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html)",
"userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.88 Safari\/537.36","version":"17.0.2.1"
}
```

With https://office.xxx.local replaced to https://ya.ru it is reporting that /healthcheck is not found.  

So I assume that my server configuration is not correct. But I cannot understand what exactly is wrong, because I can successfully curl https://office.xxx.local from everywhere I have tried:
* from the server with nextcloud (as root and web-server user)
* from inside docker with onlyoffice (as root and www-data) (`docker exec -it ID /bin/bash`)
* I can also access https://office.xxx.local /healthcheck from browser on my desktop PC (returns "true")

OS is CentOS 7.7.1908 (Core), packages updated today, Nextcloud version is 17.0.2, onlyoffice docker was pulled yestarday.

Both onlyoffice docker and nextcloud are on the same machine (I am using nginx), with self-signed certs for office/cloud. And behind corporate proxy.  
I am starting docker like this to insert my certificates (I am also passing http(s)/no_proxy (+uppercase variants) to docker:
```
docker run \
    -i -t -d -p 9981:80  \
    -v /root/unsecure-onlyoffice-default.json:/etc/onlyoffice/documentserver/default.json  \
    -v /root/wgetrc-onlyoffice:/etc/wgetrc  \
    -e CURL_CA_BUNDLE=/var/shared-dir/certs.crt 
    -v /var/shared-dir/certs.crt:/var/shared-dir/certs.crt  \
    --restart=always onlyoffice/documentserver
```
unsecure-onlyoffice-default.json was copied from docker and "rejectUnauthorized" set to *false*  
certs.crt is just an official curl certs bundle with my self-signed certs appended  
wgetrc I believe is not required... it also just points to custom certs.crt

So, when nextcloud is reporting error, who is running that curl request? Nextcloud or docker and from what username?

**Comment by CarlOnlyoffice** [comment]
Hello @mishka88ru,
Please try disabling Advanced Server Settings in the ONLYOFFICE connector settings in Nextcloud. Check if the issue persists.

**Comment by mishka88ru** [comment]
Hi @CarlOnlyoffice, it didn't work.

I also tried adding /ds-vpath/ (found such advice somewhere) to the links with no luck.  
Disabling SELinux & firewall also didn't help.

Using tcpdump I see that request to proxy was sent with
`user-agent = Nextcloud Server Crawler`

Because it is a request to internal resouce (*.local) proxy returns error. But I have `no_proxy` in /etc/environment and many other places like .bashrc, docker config...

**Comment by mishka88ru** [comment]
Finally I fix this issue using https://github.com/nextcloud/server/issues/12402  
It seems that Nextcloud is not using `no_proxy` environment variable, so I removed proxy settings from *config.php* and now *Save* button works.  
But now Nextcloud instance does not have access to Internet.

**Comment by CarlOnlyoffice** [comment]
Hello @mishka88ru 
I'm afraid we cannot give any recommendation on why your Nextcloud has no access to the Internet. Please try to look for issues in your network configuration.

**Comment by mishka88ru** [comment]
It is not related to OnlyOffice. No Internet because I must remove proxy config from Nextcloud configuration.

I can temporary enable it to update Nextcloud, then disable again so Nextcloud can access local resources.

When that issue I mentioned earlier will be resolved (use NO_PROXY or new parameter noproxy in nextcloud config.php), everything will work again.
