### ISSUE TITLE
[NextCloud+OnlyOffice]  Shared editing does not show changes from other users

### ISSUE THREAD

**Issue by sonaro** [ONLYOFFICE/onlyoffice-nextcloud#193]
Hello,

Firstly, I have just started testing OO, and I am very excited and impressed with the features.

I have a new installation of OO by following the [Linux installation guide](http://helpcenter.onlyoffice.com/server/linux/document/linux-installation.aspx).  I created a document and shared it inside NextCloud between two users.  Chrome crashed while in the middle of the users collaboratively editing the file, and now users attempting to edit that specific file cannot see realtime edits from other users.  If I create a new file, the system works normally.  If either user edits the broken file, the file will be modified and saved properly.  The only functionality that is broken is the collaborative editing.

I have saved the state of the system since I think debugging this specific issue will be helpful.  This issue is very important because multiple people can be happily editing files and overwrite other changes (since the users think no one else is editing the files).  I can dive into the code, although I think this is a fairly trivial issue to diagnose by someone experienced with the codebase.

Restarting nginx, rabbitmq, and redis did not affect the state (the issue persisted).  The respective logfiles do not contain any errors pointing to a simple cause.  What debug info is needed to determine the root cause?

Steps to reproduce (~~I have not fully reproduced the error on a clean system yet~~):
1.  Clean installation following OO linux install guide
2.  Link to Nextcloud
3.  USER1@Nextcloud web:  Create document DOC1 in a shared folder
4.  USER2@Nextcloud web:  Open document DOC1 shared from USER1
5.  Edit the document from USER1 and USER2.  Verify edits are shared in both directions
6.  ~~Force quit / Uncleanly exit Chrome on USER1 + USER2~~
7.  ~~Restart Chrome~~
8.  USER1@Nextcloud web:  Open DOC1 for editing, make changes, and exit
9.  USER2@Nextcloud web:  Open DOC1 for editing, make changes, and exit
10.  At some point, changes to either file will not sync and the Chat panel will only contain USER1 or USER2.  The realtime changes do not appear in the opposite user session
11.  **Quickly repeat** steps 8-10 until users become unsynchronized.  The users should remain unsync'd for a at least a few closes and opens

Minor debug note:  While on the same workstation, I used Google Chrome in normal mode for USER1 and incognito mode for USER2 (to maintain separate sessions for USER1 and USER2).

NextCloud 13.0.0
OnlyOffice 5.0.7 CE
nginx 1.10.3 (SSL enabled)
Google Chrome 64.0.3282.167
Client OS:  OSX 10.13.3
Server OS:  Ubuntu 16.04.3

**Comment by LinneyS** [comment]
Versioning issue mentioned in #157 
please check version 4.0.0
