### ISSUE TITLE
Document history 

### ISSUE THREAD

**Issue by ghost** [ONLYOFFICE/onlyoffice-nextcloud#194]
Hi. We have integrated NextCloud 12 with ONLYOFFICE Document server 5.0.6 and at **https://api.onlyoffice.com/editors/history** we can see that ONLYOFFICE says:

> If the document has been previously edited using Document Editor, you can view the document history.

 But I can't find how to view history via the onlyoffice-owncloud app. Can you please give us some advice. How to view Document history with NC+OO?

> This way the following events must be added to the config file to enable the document changes history display:

> onRequestHistory with refreshHistory which contains document history for each document version if the history parameter has been present for each version.
> onRequestHistoryData with setHistoryData which contains the link to the file of the corresponding version, the link to the previous version and the link to the file received using the changesUrl.

**Comment by gillesdubois** [comment]
Hi,

Do you have any news on this feature ? 
Thanks for providing us this amazing product.

Regards,
Gilles Dubois.

**Comment by LinneyS** [comment]
Released in v5.0.0
