### ISSUE TITLE
Collaboration Not Working in NextCloud and External Drive

### ISSUE THREAD

**Issue by BrianEnders** [ONLYOFFICE/onlyoffice-nextcloud#196]
I am running a NextCloud 12.0.3 server on Ubuntu. I have an OnlyOffice document server on Windows 10 that is also hosting a shared folder. In NextCloud I added that shared folder using the external drive plugin. Credentials are stored in the database.

I can get collaboration working with a file not on the external drive, but it's not available when a file is on the drive. Any ideas?

**Comment by LinneyS** [comment]
This issue was closed due to no response.
