### ISSUE TITLE
onlyoffice plugin in nextcloud

### ISSUE THREAD

**Issue by gilluc** [ONLYOFFICE/onlyoffice-nextcloud#198]
dear all,
i cannot link nextcloud and onlyoffice using https...on my local computer.
i cannot find any solution.
see my 2 screenshots

![plugin1](https://user-images.githubusercontent.com/45982037/71784455-f60fa400-2ff3-11ea-87ed-e959a6140b42.png)
![plugin2](https://user-images.githubusercontent.com/45982037/71784458-0031a280-2ff4-11ea-80cc-47b4fe260d49.png)

**Comment by SuperSandro2000** [comment]
You have a self signed certificate which is not valid for Nextcloud.

**Comment by CarlOnlyoffice** [comment]
Hello @gilluc,
Please try to disable certificate verification on Document Server side. Go to /etc/onlyoffice/documentserver/default.json => set rejectUnauthorized value to **false** => restart Document Server services `supervisorctl restart all` => try to save ONLYOFFICE connector app settings again. Let us know the results.

**Comment by gilluc** [comment]
Sandro, 
@Jassonmc sent me the solution, it is possible.... 

⁣.................
Gilles Lucato
gilles@lucato.com
................ 

Télécharger BlueMail pour Android ​

Le 5 janv. 2020 à 22:23, à 22:23, Sandro <notifications@github.com> a écrit:

**Comment by gilluc** [comment]
Great, it works.... 

⁣.................
Gilles Lucato
gilles@lucato.com
................ 

Télécharger BlueMail pour Android ​

Le 6 janv. 2020 à 08:18, à 08:18, Carl <notifications@github.com> a écrit:

**Comment by gilluc** [comment]
it works thanks to @jassonmc
