### ISSUE TITLE
Image in docx is displayed partially incorrect

### ISSUE THREAD

**Issue by mishka88ru** [ONLYOFFICE/onlyoffice-nextcloud#20]
Hi :)

Here is the screenshot from OnlyOffice Docker on Nextcloud (left) and MS Word 2010 (right):

![1](https://user-images.githubusercontent.com/44462629/47631481-4a4d0780-db57-11e8-92a9-dbe8eb766da1.png)

And the document:
[1.docx](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/files/2524019/1.docx)

**Comment by ShockwaveNN** [comment]
@mishka88ru Hi, please duplicate your issue in https://github.com/ONLYOFFICE/DocumentServer/issues, since it's not nextcloud related problem
