### ISSUE TITLE
The file is not exported in other formats in Nextcloud Adnroid app

### ISSUE THREAD

**Issue by nav-fess** [ONLYOFFICE/onlyoffice-nextcloud#207]
1. In the document settings tap on Download. 
2. Choose the file format for export and tap on it.

Connector: [https://github.com/ONLYOFFICE/onlyoffice-nextcloud/commit/4f788e907079812f45225cf239908e0489287b43](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/commit/4f788e907079812f45225cf239908e0489287b43)
app: v 12277
Android 7, 9

**Comment by LinneyS** [comment]
Download implemented https://github.com/nextcloud/android/pull/5209
