### ISSUE TITLE
creating, editing and co-authoring files in Nextcloud Android mobile application

### ISSUE THREAD

**Issue by markuman** [ONLYOFFICE/onlyoffice-nextcloud#212]
I read the release note about 4.1.0

> creating, editing and co-authoring files in Nextcloud Android mobile application

what does this mean? I can edit documents in the nextcloud android app?
or does this need an android onlyoffice android app too?

**Comment by SimJoSt** [comment]
I had the same question and emailed the developer who published the release. You're approach is much more sensible 👍

**Comment by LinneyS** [comment]
Hi @markuman 
As stated in the description, only Nextcloud mobile application is required (version 3.10.0)
If the onlyoffice application is configured on the Nextcloud server, then editing for docx, xlsx, pptx will also be available in the Nextcloud Android mobile application.
Unfortunately, in the version description [3.10.0](https://github.com/nextcloud/android/releases/tag/stable-3.10.0) only a text editor is specified, but onlyoffice is also available.

@SimJoSt 
I have received your email. I think there is enough answer
Thank you for your interest

**Comment by drikqlis** [comment]
I have Nextcloud 17.02, Onlyoffice-Nextcloud 4.1.2 and Nextcloud Android 3.10.0 and when I try to open docx, xlsx files from Nextcloud Android it opens in Word/Excel/Google Docs/Google Sheets. How can I coedit files?

**Comment by LinneyS** [comment]
Hi @drikqlis 
Nextcloud 18 required
