### ISSUE TITLE
Doesnt work in Safari browser

### ISSUE THREAD

**Issue by NiTRoeSE** [ONLYOFFICE/onlyoffice-nextcloud#213]
Hi, i recognized that documentserver dont work in safari browser, but in firefox and chrome.
Safari just doesnt display the "editor".
Error message from browser console :

"Unrecognized Content-Security-Policy directive 'worker-src'."

<img width="1760" alt="Bildschirmfoto 2020-01-18 um 12 49 43" src="https://user-images.githubusercontent.com/24574743/72663354-06f7e680-39f2-11ea-90a7-eb680a3f4041.png">

Hope its possible to fix it.

Thanks for your work!

**EDIT:**

I researched a bit and it seems that this error / problem only occurs if option "open in same tab " is set in onlyoffice app. If i unset this option the editor loads in new tab correctly.

**Comment by jbrrrr** [comment]
I second that -> I see same behavior under Safari Browser - Reload necessary to open document.
Thanks for a fix in 4.1.2

**Comment by jakeh999** [comment]
Same issue here. No longer works with Safari since version 4.1.1

**Comment by Yomark1** [comment]
Same issue in Internet Explorer(yes, still used a lot because of otherwise non-working corporate websites).   And as a workaround disabling "open in same tab"(tnx NiTRoeSE ) does also fix it..
