### ISSUE TITLE
"back to files" button missing since 4.1.1

### ISSUE THREAD

**Issue by SimJoSt** [ONLYOFFICE/onlyoffice-nextcloud#214]
Since updating to version 4.1.1 the "back to files" button in the top right corner, left of the burger menu icon is missing. Users have no way of going back through the file view through the interface of the OnlyOffice editor.

Am I missing a UX change?

**Comment by jeyca** [comment]
I am using version 4.1.4 but the button is still missing, do I have to activate it somehow?
