### ISSUE TITLE
Creating and editing documents not possible

### ISSUE THREAD

**Issue by LukasK13** [ONLYOFFICE/onlyoffice-nextcloud#216]
Hello everybody,

I installed the onlyoffice app in nextcloud hub (nc 18.0.0) but can't create or edit a document.
For backend I tried using the community server app, the community server as docker container as well as the demo server. I don't get any error message, the configuration of the onlyoffice app works perfectly but clicking on a document file just downloads it and adding a new file via "+" doesn't show an option for creating a new document.

Thank you very much.

**Comment by oakbrad** [comment]
I am also having this problem. I am running NC18 in a Docker environment.

I have installed the onlyoffice/document-server container alongside my NC. It is working fine and I can access it via the web interface and see the success message.

I have enabled the OnlyOffice connector Nextcloud app, and given it the URL of the OnlyOffice server. Saving the settings works and it all appears like it's connecting to OO (no error message).

However in the NextCloud UI I do not see the OnlyOffice options under the "+" menu, I do not see the icons for the apps in the App menu, etc. Trying to open the files it should be associated with does not attempt to open them in OO, it just downloads it like a regular file.

I'm not seeing anything in my logs that shows an error but am happy to look into it further if anyone can point me in right direction.

**Comment by ongchi** [comment]
Same problem here. I'm also go with a docker container environment.

Before upgrade to NC18, everything works fine with NC 17 and external OnlyOffice document server. I don't see any error in my logs either, the connection test performed by the OnlyOffice setting in NC18 seems works.

**Comment by alexanderonlyoffice** [comment]
@LukasK13, @oakbrad , regarding the questions about Community Document Server provided by Nextcloud please refer to the post on our official forum under this [link](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).   

@ongchi, if you have enabled Community Document Server, please note that we strongly recommend you to disable it if you are using external ONLYOFFICE Document Server.

**Comment by LukasK13** [comment]
I was able to fix the problem by disabling the App _Full Text Search - Files_ according to this [thread](https://help.nextcloud.com/t/full-text-search-files-breaks-onlyoffice/68554).

See also this [bug report](https://github.com/nextcloud/files_fulltextsearch/issues/83)
