### ISSUE TITLE
Undefined variable: error at settingscontroller.php#178

### ISSUE THREAD

**Issue by himpierre** [ONLYOFFICE/onlyoffice-nextcloud#218]
Hello Devs.

Just tried the new integrated document_server in nextcloud 18 but to no avail. Installatii went well but when i try to open a doc I get: ONLYOFFICE cannot be reached. Please contact admin.

Log:
`
{"reqId":"59xHcdAEfkoJWIK5WfA5","level":3,"time":"2020-01-20T12:54:04+00:00","remoteAddr":"xx.xx.xx.x","user":"admin","app":"PHP","method":"PUT","url":"/apps/onlyoffice/ajax/settings/address","message":"Undefined variable: error at /var/www/html/custom_apps/onlyoffice/controller/settingscontroller.php#178","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0","version":"18.0.0.10"}
`

**Comment by LinneyS** [comment]
The message in the logs is not critical and does not affect the opening of the file.
The editor does not open due to incorrect settings for the connection address to the Document Server. Check the availability of the address in the browser.

**Comment by himpierre** [comment]
Thanks for the answer @LinneyS. Going to the configured connection address redirects me to the files app. So I guess the document_server app ist not installed correctly although it seemed to be.

**Comment by himpierre** [comment]
Turns out it is a HSTS Problem.
![Screenshot from 2020-01-30 15-24-30](https://user-images.githubusercontent.com/40269193/73457875-a44d0600-4374-11ea-9bef-3ae1936c2ce6.png)

**Comment by himpierre** [comment]
Don't know how to deal with it right now. The Nextcloud OnlyOffice Settings Page shows only https://. There is no http:// configured as far as i can see.

**Comment by LinneyS** [comment]
`Undefined variable` fixed at v4.1.2

with https question create new issue
