### ISSUE TITLE
Error while downloading the document file to be converted - Onlyoffice with Nextxloud

### ISSUE THREAD

**Issue by jcaplu** [ONLYOFFICE/onlyoffice-nextcloud#219]
Hi Everyone

I installed Onlyoffice with docker on a Linux 4.19.0-6-amd64 system running with Apache2 with a Nextcloud installed on it.

All the SSL-certifiactes are made and valid. The vhosts file are correct as well. The document server is running and seems to be good! So far all good :-) 

I installed the docker with the following command:
`docker run -i -t -d -p 127.0.0.1:9981:80 -e JWT_ENABLED='true' -e JWT_SECRET='mysecretkey' -e JWT_HEADER="Authorization" --restart=always --name CAP-Office onlyoffice/documentserver`

In the default.json file I changed `rejectUnauthorized` to `false`

In the Nextcloud config.php file i added:
` 'onlyoffice' =>
  array (
    'verify_peer_off' => true,
    'jwt_header' => 'Authorization',
    'jwt_secret' => 'mysecretkey',
  ),`

But still if I configure the Onlyoffice App on my Nextcloud I get the following error:

> Fehler beim Anschließen (Im Dokumentenservice ist ein Fehler aufgetreten: Error while downloading the document file to be converted.)

which means as much as...

> Error during connection (An error has occurred in the document service: Error while downloading the document file to be converted)

I checked also the log file and there I get the following msg as far I try to save the settings in my nextcloud (/var/log/onlyoffice/documentserver/converter/out.log): 

> [ERROR] nodeJS - error downloadFile:url=https://cloud.DOMAIN.ch/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.j7mrSSx3GdHTMhAFwRCkko9v60vmffHX3EeZ6eee1g4;attempt=1;code:ETIMEDOUT;connect:true;(id=conv_check_876118450_docx)
> Error: ETIMEDOUT
>     at Timeout._onTimeout (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:849:19)
>     at ontimeout (timers.js:498:11)
>     at tryOnTimeout (timers.js:323:5)
>     at Timer.listOnTimeout (timers.js:290:5)

If I check the link in the error msg i get the following output on the page:

> {"message":"Access denied"}

Any Inputs/Ideas/Solutions?

Thank you for your help already now!

**Comment by jcaplu** [comment]
@CarlOnlyoffice 
Thank you so much! I tried this but on the wrong server. I edited the host file on the nextcloud server instead of on the documentserver. As soon I did that It worked perfectly!

I'am so happy for your help!

**Comment by qawsedrftgzh** [comment]
> Hello @jcaplu,
> please try to add the IP address + the domain name of your Nextcloud to /etc/hosts inside the Document Server container.
If i Use the IP Address as domain I just would have to add "192.168.2.42 192.168.2.42" to the /etc/hosts of the Document server Container?
