### ISSUE TITLE
"Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.)"

### ISSUE THREAD

**Issue by BP-Santo** [ONLYOFFICE/onlyoffice-nextcloud#220]
When attempting to save settings to connect onlyoffice document server with nextcloud using the connector app I get the following error:

![Screen Shot 2020-01-21 at 04 29 04](https://user-images.githubusercontent.com/50782109/72773183-9bd32d80-3c06-11ea-9768-84860b1762c7.png)

This issue is similar to another one currently opened however I thought it would be better to open a new one given the other has stalled.
No other things are displayed on the nextcloud page, the connector is never enabled due to this error.

**Configuration**
Nextcloud is running inside its own VM, on stock Debian 10 stable, everything seems to be nominal including https.
(please let me know if you would like to see any apache config files or similar).

Document server is running inside its own VM, on stock debian 10 stable, the welcome page displays correctly, all the installation steps (from the onlyoffice help center instructions for linux installation) completed successfully - all the relevant packages are managed by apt and documenserver itself was installed using apt after dependencies where already installed (postgre etc.).

Both servers have their local domain names resolved inside the lan, can ping each other, can ssh into each other. Both use ssl and have self signed certificates of their own.

**Additional information**
First problem was that Nextcloud could not use curl on the documentserver due to a self signed certificate missing a Common Name field. I have solved this problem by created a new self signed certificate for documentserver with SAN and CN properly present and adding this certificate on the nextcloud server to the openssl trusted certificates which solved the problem.
I am able to curl from the nextcloud server to the documentserver without any errors and without turning off validation with -k or similar flags.

**Troubleshooting steps already attempt**
I have tried adding the document server to trusted domains in nextcloud config.php in multiple ways, using ip's, domain names with and without https mentioned. 
I have also tried connecting with certificate validation disabled completely.
I have added for nextcloud to listen on ports 8080 for https connections.
I have confirmed that both hosts get their DNS servers properly set from dhcp, all dig (dnsutils) queries return my local dns server correctly.
I have tried to find settings for documentserver inside its jason files that would be relevant however they all seem to relate to helper services running on the same host and connecting via localhost.

Please let me know in case any logs or config files would be helpful.

**Comment by CarlOnlyoffice** [comment]
Hello @BP-Santo,
Please try to save the settings in the connector app anew and check this log for errors:
/var/log/onlyoffice/documentserver/converter/out.log

**Comment by BP-Santo** [comment]
I checked the log and it seems nodeJS on the document server is not liking that its a self signed certificate? I can recreate the onlyoffice certificate with proper CN and SAN fields however I am not sure how to add that certificate to the trusted certificates for the document server.

As I mentioned before, on my nextcloud host I added the documentserver self signed certificate to the openssl ones which was enough to make curl work properly - I am however not sure about nodeJS or document server in general.

out.log:
```
[2020-01-21T11:24:40.622] [ERROR] nodeJS - error downloadFile:url=https://nextcloud-kancelaria.liquid/index.php/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.LJQf8gxWIaE3oIUKAkmrFjicYzktFoDA7SGfKrni1t8;attempt=1;code:DEPTH_ZERO_SELF_SIGNED_CERT;connect:null;(id=conv_check_354815335_docx)
Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1055:34)
    at TLSSocket.emit (events.js:189:13)
    at TLSSocket._finishInit (_tls_wrap.js:633:8)
[2020-01-21T11:24:41.628] [ERROR] nodeJS - error downloadFile:url=https://nextcloud-kancelaria.liquid/index.php/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.LJQf8gxWIaE3oIUKAkmrFjicYzktFoDA7SGfKrni1t8;attempt=2;code:DEPTH_ZERO_SELF_SIGNED_CERT;connect:null;(id=conv_check_354815335_docx)
Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1055:34)
    at TLSSocket.emit (events.js:189:13)
    at TLSSocket._finishInit (_tls_wrap.js:633:8)
[2020-01-21T11:24:42.635] [ERROR] nodeJS - error downloadFile:url=https://nextcloud-kancelaria.liquid/index.php/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.LJQf8gxWIaE3oIUKAkmrFjicYzktFoDA7SGfKrni1t8;attempt=3;code:DEPTH_ZERO_SELF_SIGNED_CERT;connect:null;(id=conv_check_354815335_docx)
Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1055:34)
    at TLSSocket.emit (events.js:189:13)
    at TLSSocket._finishInit (_tls_wrap.js:633:8)
```

**Comment by CarlOnlyoffice** [comment]
@BP-Santo,

You need to disable certificate verification by setting **rejectUnauthorized** to **false** in /etc/onlyoffice/documentserver/default.json

After that restart Document Server services `supervisorctl restart all`

**Comment by BP-Santo** [comment]
After changing default.json it was possible to save the settings in nextcloud however upon trying to edit the example .odt document in nextcloud it opens a new tab with a blank page below the nextcloud header and an error
`ONLYOFFICE cannot be reached. Please contact admin`
![Screen Shot 2020-01-21 at 12 56 22](https://user-images.githubusercontent.com/50782109/72803187-ba104c00-3c4d-11ea-9e12-b3affc4521f1.png)

There are no new log entries in out.log

**Comment by CarlOnlyoffice** [comment]
@BP-Santo,

Please reproduce the issue with open browser console and check if there are any errors in Network and Console tabs.

**Comment by BP-Santo** [comment]
![Screen Shot 2020-01-21 at 13 32 20](https://user-images.githubusercontent.com/50782109/72805144-7f5ce280-3c52-11ea-844c-1277fec1b7a9.png)

**Comment by CarlOnlyoffice** [comment]
@BP-Santo,

Open the config file /nextcloud/config/config.php 
 And add a section: 
```
'onlyoffice' =>
  array (
    'verify_peer_off' => TRUE,
  )
```
After that try to reproduce the issue.

**Comment by BP-Santo** [comment]
The error still seems to show up (I restarted apache and then also tried again after rebooting the host just in case), output from js console seems to be the same too.

**Comment by CarlOnlyoffice** [comment]
@BP-Santo,

Try to run `wget https://document-server-address` from Nextcloud machine. Let me know if there is any SSL error.

**Comment by BP-Santo** [comment]
Seems to look fine?
```
wget https://onlyoffice-document.liquid
--2020-01-21 13:49:25--  https://onlyoffice-document.liquid/
Resolving onlyoffice-document.liquid (onlyoffice-document.liquid)... 192.168.88.228
Connecting to onlyoffice-document.liquid (onlyoffice-document.liquid)|192.168.88.228|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://onlyoffice-document.liquid/welcome/ [following]
--2020-01-21 13:49:25--  https://onlyoffice-document.liquid/welcome/
Reusing existing connection to onlyoffice-document.liquid:443.
HTTP request sent, awaiting response... 200 OK
Length: 4592 (4.5K) [text/html]
Saving to: ‘index.html’

index.html                                                          100%[=================================================================================================================================================================>]   4.48K  --.-KB/s    in 0s      

2020-01-21 13:49:25 (151 MB/s) - ‘index.html’ saved [4592/4592]

```

**Comment by CarlOnlyoffice** [comment]
@BP-Santo,
The certificate of your Document Server seems to be blocked by your browser. Please add it to the trusted list of your browser or use CA-signed certs.

**Comment by BP-Santo** [comment]
Thank you very much, It finally works :) !

Is there an accepted way to add a specific certificate (to auth nextcloud) to be trusted by the document server without turning off peer verification with rejectUnauthorized False?

We will most likely run the stack only on a lan and access it via an ipsec tunnel to the router or a wireguard tunnel to one of the hosts so I don't think it would be possible to use letsencrypt/certbot - it would be great to be able to maintain peer verification inside the lan for specific certificates.

**Comment by CarlOnlyoffice** [comment]
@BP-Santo,

You can add the Nextcloud certificate to the CA-bundle of the server where your Document Server is installed (copy it to /usr/local/share/ca-certificates/ with .crt extension and run `update-ca-certificates`).

After that add a flag `--use-openssl-ca` to /etc/onlyoffice/documentserver/supervisor/ds-converter.conf and /etc/onlyoffice/documentserver/supervisor/ds-docservice.conf and switch rejectUnauthorized back to true => `service supervisor restart` => `supervisorctl restart all` => check the result.

**Comment by BP-Santo** [comment]
Thank you very much for all the help - I will try the above steps in the next couple of days and report back.
