### ISSUE TITLE
"Error updating the share" fails when trying to set "Allow editing"

### ISSUE THREAD

**Issue by Wikinaut** [ONLYOFFICE/onlyoffice-nextcloud#223]
![grafik](https://user-images.githubusercontent.com/1151915/72962598-13df5600-3db5-11ea-83d0-17fa57b5f9a9.png)

* I just upgraded Nextcloud to NC 18, installed ONLYOFFICE and Community Document App.
* I created a file test.docs and wanted to send a link to friends to test editing it.

This fails, see screenshot.

The moment when I enable "allow editing" (1), the message (2) is shown: "Error updating the share".

### on one server
* The problem is present on one instance on server 1.
* The problem is **not** present on a different instance on a second server.

Please assist; I don' thave any idea why I can't set up an "edit"share for a document on server 1.

**Comment by Wikinaut** [comment]
(updated screenshot and title). Problem persists.

**Comment by HelenBelova17** [comment]
@**Wikinaut**, please try to delete the application Community Document Server and re-save the settings on ONLYOFFICE integration app settings page.

**Comment by Wikinaut** [comment]
Shall I 

* uninstall the Community Document Server and
* then re-install this?
* And what settings do you mean? I did not change anything after installation.

**Comment by Wikinaut** [comment]
Same problem after de- and re-installation of Community Document Server.

**Comment by LinneyS** [comment]
This does not apply to ONLYOFFICE
Please report it here https://github.com/nextcloud/server

**Comment by Wikinaut** [comment]
Solution:

It appears, that this setting (1) **must** be active:
![grafik](https://user-images.githubusercontent.com/1151915/72977063-fb326880-3dd3-11ea-9eb6-fd439e7b330e.png)
