### ISSUE TITLE
Documents do not open with Nextcloud 18

### ISSUE THREAD

**Issue by olliware** [ONLYOFFICE/onlyoffice-nextcloud#227]
Hey everyone,

I had a working ONLYOFFICE-integration with docker and an Apache reverse proxy before upgrading to Nextcloud 18. After upgrading, documents do not open automatically anymore - for example, once I create a new document I see the message that it is being created and an empty screen simultaneously. The document is created and once I reload the page, the document opens and I am able to edit it.

Everything is running on Debian 10 with Apache, PHP 7.3 without any problems so far. I tried to delete the ONLYOFFICE-integration app and fetched it manually via the "git clone" - same effect. The only error message in the Nextcloud-log shows

> [onlyoffice] Error: GetConvertedUri on check error: Im Dokumentenservice ist ein Fehler aufgetreten: Error while downloading the document file to be converted.
> 
> PUT /index.php/apps/onlyoffice/ajax/settings/address
> from 162.158.92.45 by NC-Admin at 2020-01-24T18:13:22+00:00

Any ideas on that? The docker container as well as the reverse proxy work without problems.

<img width="279" alt="Bildschirmfoto 2020-01-24 um 19 07 55" src="https://user-images.githubusercontent.com/42076599/73095591-438c7c00-3ee3-11ea-9190-49d914444832.png">
<img width="341" alt="Bildschirmfoto 2020-01-24 um 19 08 01" src="https://user-images.githubusercontent.com/42076599/73095592-438c7c00-3ee3-11ea-96b5-1bdf1573bc4c.png">
<img width="646" alt="Bildschirmfoto 2020-01-24 um 19 10 49" src="https://user-images.githubusercontent.com/42076599/73095594-44251280-3ee3-11ea-88d6-40e0b82455eb.png">

Thanks in advance for any hint and best regards,

Oliver

**Comment by HelenBelova17** [comment]
Hello @**olliware**, are there any errors in the 'Console' tab of the browser console?

**Comment by CarlOnlyoffice** [comment]
@olliware,

Please try to re-save the connector settings. If there is an error, go to /app/onlyoffice/DocumentServer/logs/documentserver/converter/out.log and look for the error entries there.

**Comment by olliware** [comment]
Hey folks,

thanks for the answers. In the meantime, completing wiping the app and the docker container helped. Installed both again afterwards and now everything's behaving in the ways it should.

Thanks for your thoughts on that one!

Best regards,

Oliver
