### ISSUE TITLE
Onlyoffice on Android won’t load after onlyoffice 4.1.2 update

### ISSUE THREAD

**Issue by jakobroehrl** [ONLYOFFICE/onlyoffice-nextcloud#228]
after installing the update to 4.1.2 onlyoffice is still working in the browser but don’t load in the Android App:
![grafik](https://user-images.githubusercontent.com/24530680/73132075-7aaf7a00-4016-11ea-8723-fb5f5ba1b284.png)
If I downgrade to 4.1.1 it's working again.

https://help.nextcloud.com/t/onlyoffice-on-android-wont-load-after-onlyoffice-and-documentserver-update/69231

**Comment by BastiG** [comment]
Hi, same behavior here.
Not sure if it's relevant but my OnlyOffice reverse proxy access logs contain the following:
```
217.235.x.x - myuser [26/Jan/2020:11:01:37 +0000] "GET /ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 601 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.10.0" "-"
217.235.x.x - myuser [26/Jan/2020:11:01:37 +0000] "POST /ocs/v2.php/apps/files/api/v1/directEditing/open?format=json HTTP/1.1" 200 202 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.10.0" "-"
2003:c3::y:y - - [26/Jan/2020:11:01:38 +0000] "GET /apps/files/directEditing/XMpptCNqQEQ3AHSWpAXFGWDmLMMmkmsSnSEMamdNTFSGoMw94KscsbBGcnKkngze HTTP/2.0" 404 153 "-" "Mozilla/5.0 (Android 10) Mobile Nextcloud-android/3.10.0" "-"
```

First two entries show authenticated IPv4 session ('myuser') and generate 200 OK responses, the last entry switches to non-authenticated IPv6 and the response code is 404 Not Found. No more log entries from my devices after that line so it seemed important. (Ok, I'm omitting the /favicon.ico request which has the 404 URL as referrer)

**Comment by BastiG** [comment]
The log looks the same in version 4.1.1 but there it works.
Some more digging revealed that isUserAllowedToUse() fails. The call is new in 4.1.2 (see https://github.com/ONLYOFFICE/onlyoffice-nextcloud/pull/226/files#diff-98f41e4acfeac80f65d6397314947e94R137) -- commenting it out fixes the issue for me.

I'm removing IPv6 for my domain to see if it works in a single stack environment but I'll have to wait for DNS TTL expiration ...

**Comment by BastiG** [comment]
Removed IPv6, and even HTTP/2 from my systems, no change unfortunately.
```
87.148.x.x - - [26/Jan/2020:12:51:45 +0000] "GET /apps/files/directEditing/CY6nq4a8otB2GDF8iiDbJ2mTg74wpMzT58gkiKoNYzjniRL6PMNXGo3RzR2Ri52s HTTP/1.1" 404 153 "-" "Mozilla/5.0 (Android 10) Mobile Nextcloud-android/3.10.0" "-"
```

Another finding `$userSession->getSession()->get('user_id')` is null, so it seems the session is lost in the last call...

**Comment by BastiG** [comment]
Quick check shows documents are loading fine in web browser and on Android devices. No issues observed so far.
Thanks for the fast fix @LinneyS
