### ISSUE TITLE
[Bug] Status of track changes mode is not saved with document

### ISSUE THREAD

**Issue by philipreimer** [ONLYOFFICE/onlyoffice-nextcloud#232]
## Steps to reproduce

1. Install nextcloud with onlyoffice app and onlyoffice document server - I used docker images from here: https://github.com/ONLYOFFICE/docker-onlyoffice-nextcloud
2. Login to nextcloud
3. Create a document
4. Enable "Track Changes" mode in "Collaboration" menu
5. Write some text
6. Save and close doc.
7. Logout of Nextcloud
8. Login again to Nextcloud
9. Open the document
10. Write some text
11. Check status of "Track Changes" mode in "Collaboration" menu

## Result
Text entered in step 10 above is not marked as new change
"Track Changes" mode is **not** enabled anymore

## Expected Result
Text entered in step 10 above should be marked as new change
"Track Changes" should be enabled

**Comment by LinneyS** [comment]
https://github.com/ONLYOFFICE/DocumentServer/issues/768
