### ISSUE TITLE
Paste image: Infinite loading

### ISSUE THREAD

**Issue by jakobroehrl** [ONLYOFFICE/onlyoffice-nextcloud#233]
If I paste a Image (eg a screenshot I made) into an Document the message "image is loading" never disappears. 

Same problem occurs If I add a picture from an URL.

**Comment by alexanderonlyoffice** [comment]
@jakobroehrl, please specify the exact ONLYOFFICE product you are using and its current version. Specify also the installation type of the Document Server (docker or deb/rpm).

Send us also screenshots with browser console opened (choose Console tab -> reproduce the issue and send us the screenshot, if there are any errors; do the same with chosen Network tab).

**Comment by HelenBelova17** [comment]
Are you able to create documents in main menu by clicking '+'?

**Comment by jakobroehrl** [comment]
Document Editor 5.4.2 with https://github.com/nextcloud/documentserver_community
No error, sorry:
![grafik](https://user-images.githubusercontent.com/24530680/74243506-2d9ef980-4ce0-11ea-898d-1c3e72e55697.png)

**Comment by alexanderonlyoffice** [comment]
@jakobroehrl, if you are using the Community Document Server app developed by Nextcloud, we cannot assist with its issues. Please refer to this [post](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444) on our Forum. 

There is a similar problem in Nextcloud branch, please follow this [link](https://github.com/nextcloud/documentserver_community/issues/64).

**Comment by jakobroehrl** [comment]
Thanks for the info and looking over the problem.
I didn't know where to post to Issue.
