### ISSUE TITLE
Copying XLSX Files leads to data loss

### ISSUE THREAD

**Issue by tk7936** [ONLYOFFICE/onlyoffice-nextcloud#235]
Hi
Nextcloud 18.01
Community Doument Server 0.15
Onlyoffice 4.1.4

Problem:
When i copy a Excel Spreadsheet with the Nextcloud copy feature (within the directory listing not from within Onlyoffice) the File gets copied but is either
EMPTY
ONLY PARTIALLY COMPLETE (ROWS missing)
OR EVEN WIERDER CONTAINS ROWS FROM OTHER FILES THAT WERENT COPIED

When using the internal copy file feature within Onlyoffice it works fine. 

Protocol logs no Errors

Something seems very wrong. Any help appreciated.

**Comment by HelenBelova17** [comment]
Hello @**tk7936**

Can't reproduce your issue. 
Please provide a more detailed description of the issue:
1. Version of DS.
2. Provide some steps to reproduce the issue. You can also record a video/gif.

**Comment by tk7936** [comment]
Hi,

What is DS ?

What i do as follows.
I go into directory with my xlsx files.
I click the 3 dotted symbol on the file i want to copy.
I chose copy / move.
I want a copy within the same directory so i just click the copy button.
The copied file now apears in the directory as name filename (copy):
So far so good.
Now i open the xlsx file. 
Onlyoffice opens displaying the copied file but lacks most data of the original.
As said this does not happen when i use the internal save as function within Onlyoffice.

**Comment by tjareson** [comment]
Did you edit the document with onlyoffice (means "inside" of nextcloud) before you tried to copy it?

**Comment by tk7936** [comment]
No, it was a couple days old when i copied it.

**Comment by tk7936** [comment]
I can edit it though before and its doesnt change the behavior.

**Comment by tjareson** [comment]
Understood, still: did you edit/created it with onlyoffice before (even a couple of days ago) or did you upload it into nextcloud?
The reason why I'm asking: There is another issue #187 and #21 which leads exactly to what you describe. In that case Onlyoffice is not copying back what was changed in the document to nextcloud. So if you create an xls file with Onlyoffice the empty file gets created in nextcloud and then handed over to onlyoffice. You can change and edit it there and see everything. But in nextcloud you still have only the empty file. When you copy it, you just get a copy of that empty file. 
If you click on the original file, you still see what temporary file onlyoffice created for that file id.

**Comment by tk7936** [comment]
Yes all the files were created  and edited with Onlyoffice. Interesting (maybe related) is that there is a sync client running and it only syncs if the onlyoffice file is create new or deleted. If it is changed the file (the changes) arent synced locally anymore. The Nextcloud file list also doesnt update the change date, its stays as the creation date. Probally a different problem though and not related to this.

**Comment by tjareson** [comment]
Actually the issue with the sync client is the same reason:
The empty file is created in nextcloud, which gets noticed by the sync client, hence it is syncing the new/empty file.
Then the empty new file gets handed over to onlyoffice and edited there. But all changes remain in the temporary file which is created by onlyoffice and are never copied back into the filespace of nextcloud. Subsequently also the change date/time is stuck with creation time. 
The standard answer to that is that onlyoffice is generating the updated file only into nextcloud after all edit sessions are definitely closed + 10 seconds or so. 
Unfortunately excatly that doesn't seem to work. 
So, what you see as result is: copied files which are empty, no updated date/time and also empty files if you try to download out of nextcloud (not onlyoffice, where this is also possible)

What worries me: the first time that issue was mentioned in Oct 2018 #21 and I didn't see any answer yet which would really address the issue...

**Comment by tk7936** [comment]
Oh dear yes that is worrisome. I also just noticed that Versioning doesnt work either, i suppose for the same reason. Given that this can lead to dataloss im surprised its hard to find people with related posts.

**Comment by tjareson** [comment]
Probably it is also based on a certain way of installation. I'm using nextcloud as fully integrated docker version, so including onlyoffice, but with MariaDB as database on the host system and nginx as proxy for https connections. Not sure if other setups don't have that issue.

**Comment by tk7936** [comment]
Im using NC HUb with integrated Document Server app on Debian 9, Apache 2.4, MariaDb, PHP 7.2
No Docker, no Proxy.

**Comment by alexanderonlyoffice** [comment]
@tk7936, if you are using Community Document Server integrated in Nextcloud Hub, I would recommend you to contact Nextcloud Team, as this app was developed by them. Please refer to this post on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).

**Comment by tk7936** [comment]
>Ok, thankyou.
> 
> @tk7936, if you are using Community Document Server integrated in Nextcloud Hub, I would recommend you to contact Nextcloud Team, as this app was developed by them. Please refer to this post on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).
