### ISSUE TITLE
how to save the settings over occ and trigger connection test?

### ISSUE THREAD

**Issue by szaimen** [ONLYOFFICE/onlyoffice-nextcloud#237]
When I change e.g. the documentserverurl over occ, the changes aren't automatically saved (or at least it doesn't try to connect to the new documentserverurl, if changes via occ). I have to navigate to the settings page and manually save them to trigger the connection test.
Is there a way to force saving the settings and trigger the connection test?

**Comment by enoch85** [comment]
Should be implemented if not already in core IMHO.

After testing it myself, I think it's pretty unstable, not even the address got right, and if we implement this in the VM, it has to work, every time.

Thanks! :)

**Comment by acsfer** [comment]
At least URL and SECRET should be possible to be changed trough the `occ` command.
In environments where administration is done 99,9% trough CLI, this is a must have.

**Comment by szaimen** [comment]
At least the url is definitely already possible to set via cli.
@acsfer please look here: https://github.com/nextcloud/vm/blob/aeab72a3b707977a73323189fdab6cbeef148e7f/apps/onlyoffice_docker.sh#L335

**Comment by acsfer** [comment]
@szaimen yep, i know it, but what about Secret?
This is why I've specified URL **and** SECRET ;-)

**Comment by acsfer** [comment]
Ok I've found it.

```
occ app:install onlyoffice
occ config:app:set onlyoffice DocumentServerUrl --value="https://domain"
occ config:app:set onlyoffice jwt_secret --value="secret"
```
