### ISSUE TITLE
Fail to add new fonts

### ISSUE THREAD

**Issue by flymin** [ONLYOFFICE/onlyoffice-nextcloud#238]
Hi,
I am using docker image for onlyoffice document server 5.4.2.46. I installed the Community Edition follow this [page](https://helpcenter.onlyoffice.com/server/docker/opensource/opensource-script-installation.aspx?_ga=2.136455602.300593906.1582088840-1946479620.1582088840). I have noticed that it is possible to add new fonts by copying them into `/app/onlyoffice/DocumentServer/fonts` and restart the container.

Here's the thing. I have successfully installed new fonts for my document server and they have shown up on pages for community server, see those in red box.
![image](https://user-images.githubusercontent.com/28671430/74816380-01b1f280-5336-11ea-93c4-9e53f0f37f06.png)
However, for nextcloud side, which is using the same backend as community server, all fonts remain unchanged and my new fonts did not show up.
![image](https://user-images.githubusercontent.com/28671430/74816503-4178da00-5336-11ea-830e-577757c7875f.png)

Could you please tell me how to figure this out?

**Comment by CarlOnlyoffice** [comment]
Hello @flymin,

Please specify what you mean by 
> for nextcloud side, which is using the same backend as community server

Please explain step-by-step how you integrated the Document Server with Nextcloud.

**Comment by flymin** [comment]
I am using nextcloud version 18.0.1, set up based on the release version, not docker version. Since the network of my server is not so well, I installed onlyoffice app by copy release code from [App Store](https://apps.nextcloud.com/apps/onlyoffice) to `nextcloud/apps` folder and enable in app panel for nextcloud. Here are my settings for document server connection:
![image](https://user-images.githubusercontent.com/28671430/74820297-bea74d80-533c-11ea-822d-5b7cfb4d338b.png)

**Comment by HelenBelova17** [comment]
@flymin, which version of ONLYOFFICE Document Server are you using?

Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).

**Comment by flymin** [comment]
I use onlyoffice with docker, and both community server and nextcloud server are using the same document server backend.
I updated to the latest docker image, version 5.5.0.165. New fonts can show up in my nextcloud app.
Thank you. I will close this.
