### ISSUE TITLE
Onlyoffice mobile isn't loading .doc Documents (docx is working)

### ISSUE THREAD

**Issue by jakobroehrl** [ONLYOFFICE/onlyoffice-nextcloud#239]
Steps to reproduce
Create a .doc Word document (docx is working)
It is loading in the Browser
It isn't loading in the Android App, a download starts

Expected behaviour
doc should be open the onlyoffice build-in editor

it seems that onlyoffice is not exposing the mimetype for doc files:
![grafik](https://user-images.githubusercontent.com/24530680/74827417-b4ba2600-530d-11ea-9748-15759759fb37.png)

More infos: https://github.com/nextcloud/android/issues/5489

**Comment by alexanderonlyoffice** [comment]
@jakobroehrl, please note that .doc format is not planned to be supported for editing in mobile apps.

**Comment by jakobroehrl** [comment]
OK, thanks. Maybe there is a hint for the user possible?

**Comment by alexanderonlyoffice** [comment]
@jakobroehrl, basically ONLYOFFICE editors don't allow editing of .doc files in original format, so the files are converted at first. We are planning to add the possibility to convert the files in .docx format. By the way, Nextcloud mobile app allows to open the file only for editing.
