### ISSUE TITLE
OnlyOffice no open doc on nextcloud

### ISSUE THREAD

**Issue by liberodark** [ONLYOFFICE/onlyoffice-nextcloud#24]
**Do you want to request a *feature* or report a *bug*?**
Report a Bug !
OnlyOffice failed for open document on nexcloud 13.0.6 !

**What is the current behavior?**
OnlyOffice is connected has nextcloud but no open file !

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Is Nexcloud installed on debian 9 and onlyoffice installed on debian 9
With official step no more informations :(

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**
No is clean install

**DocumentServer version:**
5.2.3

**Operating System:**
Manjaro and Windows 10 Pro

**Browser version:**
Firefox 63

**Comment by ShockwaveNN** [comment]
@liberodark seems this issue is not related to DocumentServer itself, so moved to `nexcloud` issue repo

**Comment by LinneyS** [comment]
What is the DocumentServer address you specified? It should not contain `/welcome`

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs or we can close the topic?

**Comment by johnwry** [comment]
this is not resolved. 

<img width="635" alt="Screen Shot 2022-11-14 at 4 10 14 AM" src="https://user-images.githubusercontent.com/66494821/201722854-b3a97f0e-97fe-4bff-ad85-e9dac5fb53e1.png">

click OK and it sits there loading... sometimes it tells you to download the file...

**Comment by LinneyS** [comment]
This issue was closed due to no response.

@johnwry You have another problem unrelated to this issue. Please open a separate issue
