### ISSUE TITLE
ONLYOFFICE cannot be reached

### ISSUE THREAD

**Issue by domchrgit** [ONLYOFFICE/onlyoffice-nextcloud#240]
I have fresh installation of Nexcloud 18.0.1 on a webserver (Debian 8 Jessie on x86-64 architecture)
I activated ONLYOFFICE version 4.1.4
I installed and activated the available "Community Document Server" app version 0.1.5
When I try to open a document (docx for example) I obtain the following error
"ONLYOFFICE cannot be reached. Please contact admin"

How to solve this issue ?

**Comment by alexanderonlyoffice** [comment]
@domchrgit, please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository.
