### ISSUE TITLE
Application Setting Formula and Regional Settings Default not changeable

### ISSUE THREAD

**Issue by mr-bolle** [ONLYOFFICE/onlyoffice-nextcloud#246]
### Steps to reproduce
1. I force into my Nextcloud config.php the Language and locale.
>  'force_language' => 'de',
>  'force_locale' => 'de_DE',

2. Create a new Spreadsheet and change the Formula and Regional Settings to o other Language (ex. deutsch/german)
3. Login into your Nextcloud with a other User, and repeate Point 2 - you can see that the default Language are again English

https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/64 https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/108 

<img src="https://user-images.githubusercontent.com/22414212/76145861-0c86ba00-608e-11ea-9c37-a744789f2a26.jpg" alt="Screenshot_20200307-160350_Chrome" width="450"/>

### Expected behaviour
I would be able to use the default Language from the Nextcloud Server, or have any other posibillity to change the default Language.

### Actual behaviour
If i edit a Spreadsheet the Formular Language are still English, i have to change this for every Nextcloud Account.

## Server configuration detail

**Operating system:** Linux 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** mysql 10.4.12

**PHP version:** 

7.3.15
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 18.0.1 - 18.0.1.3

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** nextcloud/docker

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - calendar: 2.0.2
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.2.0
 - dav: 1.14.0
 - documentserver_community: 0.1.5
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - mail: 1.1.3
 - nextcloud_announcements: 1.7.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - onlyoffice: 4.1.4
 - password_policy: 1.8.0
 - photos: 1.0.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - spreed: 8.0.5
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - tasks: 0.11.3
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nextcloud.domain.com"
    ],
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.1.3",
    "overwrite.cli.url": "http:\/\/nextcloud.domain.com",
    "overwriteprotocol": "https",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpsecure": "ssl",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_sendmailmode": "smtp",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "force_language": "de",
    "force_locale": "de_DE"
}
```
</details>

**Are you using external storage, if yes which one:** none

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0  / Google Chrome

**Operating system:** MX Linux (Debian based) / Android 10

**Comment by LinneyS** [comment]
Hi @mr-bolle 

In the desktop browser, the editors open with the correct language. In the mobile browser too.
But I repeated the problem on Nextcloud Android mobile app (3.12.1).

https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/4b4722ab19db39c736c514766d2e606843c4962b/controller/editorcontroller.php#L631-L632

in browser: `"lang":"de-DE","region":"de-DE"`
but for directediting: `"lang":"en","region":"en-US"` for mobile with English regional settings

@tobiasKaminsky Can you answer why you change the language?
@juliushaertl How can I get a custom language?

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky Can you answer why you change the language?

I do not do anything with language.
Android just opens up OO via NC app.
@juliushaertl do you change something there?

**Comment by juliushaertl** [comment]
Yes, since we don't have the user session available in direct editing, we do not load the actual locale and fallback to the default one in the browser then. Should be fixable in the server, I'll have a look.

**Comment by juliushaertl** [comment]
Moved it to https://github.com/nextcloud/server/issues/22429 so it doesn't get lost. @LinneyS Feel free to close it here since it is a Nextcloud issue.
