### ISSUE TITLE
Header buttons use wrong color

### ISSUE THREAD

**Issue by nickvergessen** [ONLYOFFICE/onlyoffice-nextcloud#247]
It's okay for normal mode:
![Bildschirmfoto von 2020-03-09 09-46-08](https://user-images.githubusercontent.com/213943/76196916-69e44d80-61eb-11ea-94b2-9830d166461d.png)

But on dark mode the buttons should still be white:
![Bildschirmfoto von 2020-03-09 09-48-08](https://user-images.githubusercontent.com/213943/76196948-79fc2d00-61eb-11ea-83a0-8a24e386ea51.png)

**Comment by nickvergessen** [comment]
Ah hmmm, in the end this might be the same problem as https://github.com/nextcloud/server/issues/19565

**Comment by LinneyS** [comment]
These buttons were added as temporary only to work with ONLYOFFICE Document Server version 5.4 and below.
Styles are used standard from Nextcloud.

With the release of version 5.6, these buttons will be removed.
We are not planning to fix it.
