### ISSUE TITLE
OnlyOffice Work on Chrome but not Firefox

### ISSUE THREAD

**Issue by liberodark** [ONLYOFFICE/onlyoffice-nextcloud#25]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Just no open documents with firefox have blank page.
Have fixe chrome with add_header X-Frame-Options "ALLOW-FROM https://__DOMAIN__/";

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
OnlyOffice installed on Debian 9 with nextcloud 13

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**
NO is clean install

**DocumentServer version:**
5.2.3

**Operating System:**
MacOS Mojave / Linux : Manjaro / Windows 10

**Browser version:**
FF 63

**Comment by ShockwaveNN** [comment]
seems this is nextcloud connector problem, moved to nextcloud repo

**Comment by liberodark** [comment]
Ok

**Comment by liberodark** [comment]
Is my F12 console from FF

```Échec du chargement pour l’élément <script> dont la source est « https://cloud.copysud.fr/ynhpanel.js ». 37496:47:1
JQMIGRATE: Migrate is installed, version 1.4.0 core.js:7:542
Load denied by X-Frame-Options: https://yuno.probetech.be/v5.2.3-64//web-apps/apps/documenteditor/main/index.html?_dc=5.2.3-64&lang=fr&customer=ONLYOFFICE&frameEditorId=iframeEditor does not permit cross-origin framing.
Content Security Policy: Ce site (https://yuno.probetech.be) possède une politique Report-Only sans URI de rapport. CSP ne bloquera pas cette politique et ne pourra pas rapporter ses violations.
Erreur dans les liens source : TypeError: NetworkError when attempting to fetch resource.
URL de la ressource : https://cloud.copysud.fr/core/vendor/core.js?v=da08f6c8-1
URL du lien source : purify.min.js.map[En savoir plus]```

**Comment by alexanderonlyoffice** [comment]
@liberodark, there is a similar issue #31.

**Comment by LinneyS** [comment]
We set the `X-Frame-Options` header to the Community Server only. And it applies to Document Server in Enterprise Edition on Windows.

**Comment by adietz00** [comment]
I'm having this same exact problem. X-Frame-Options is not set in either OODS or proxy. Issue #31 linked above is closed, but offers no clue as to how to fix it.... Any help would be greatly appreciated.

**Comment by alexanderonlyoffice** [comment]
Hello @adietz00, please specify some additional information: 

1. As far as I understand, the issue appears only in Firefox browser? 
2. Open browser's console (choose Network tab) -> Reproduce the issue -> Send us a screenshot of the page with browser's console opened, if there are any errors; 
3. Open browser's console (choose Console tab) -> Reproduce the issue -> Send us a screenshot of the page with browser's console opened, if there are any errors.

**Comment by liberodark** [comment]
For me need to test have dev new version of project and no test but i think work on firefox

**Comment by peacepenguin** [comment]
Latest version of Nextcloud (Linux) and Document Server (Linux, binary install) and latest Firefox (on windows), everything is working great for me.

All default settings, no encryption or add-on nextcloud apps just the onlyoffice connector app.

I notice the original issue report is using two different Top level domains. In my case the two working urls are in the same top level domain:

nextcloud.mydomain.net
onlyoffice.mydomain.net

The cross-origin warning is related to the TLD of the two sites. So perhaps there's an issue hosting the onlyoffice instance at a different top level domain than nextcloud? iframes in general have this issue, so there may not be a fix except to override default browser behavior to allow cross-origin iframes, sounds like firefox might not support an option like that that reduces your browser security. 

Either way its an edge case and if different TLD is the cause; the bug report needs to be clarified. The statement as reported "onlyoffice works on chrome but not firefox" is not true in any of my up to date nextcloud with onlyoffice installed sites.

**Comment by LinneyS** [comment]
@adietz00 
Open new issue in [DocumentServer ](https://github.com/ONLYOFFICE/DocumentServer)repository if the problem in the word processor recurs.
@peacepenguin 
With the default settings ONLYOFFICE there should be no CORS problem.
With normal ONLYOFFICE connection settings, there should be no CSP problem.

**Comment by LinneyS** [comment]
@liberodark 
Could you please specify if the problem recurs or we can close the topic?

**Comment by peacepenguin** [comment]
@LinneyS I use firefox with onlyoffice via nextcloud integration regularly. This no longer seems to be an issue in a default/normal install.

Tested, working well with: 
Nextcloud server: Ubuntu 20.04, nextcloud 21.0.2
With onlyoffice server: Ubuntu 20.04, onlyoffice 6.3.0
Via: Win 10, 20h2, with firefox 88.0.1
