### ISSUE TITLE
Nextcloud ONLYOFFICE Integration

### ISSUE THREAD

**Issue by Sys-Admin889** [ONLYOFFICE/onlyoffice-nextcloud#250]
Hello everyone,

- I have an ONLYOFFICE Document Server v.5.5.0 installed on Ubuntu 18.04 TLS as the following 
   [instructions](https://helpcenter.onlyoffice.com/server/linux/document/linux-installation.aspx)

- After that Nginx configured to use Self-Signed SSL/TLS Certificate as the following [instructions](https://hostadvice.com/how-to/how-to-configure-nginx-to-use-self-signed-ssl-tls-certificate-on-ubuntu-18-04-vps-or-dedicated-server/)

- Finally Document Server switched to HTTPS protocol as the following [intructions](https://helpcenter.onlyoffice.com/server/linux/document/switch-to-https.aspx)
  
 - There is another Nextcloud server v17.0.3.1 installed on Ubuntu 18.04 TLS as the following 
    instructions:
    1- sudo snap install nextcloud
    2- sudo ufw allow 443/tcp
    3- sudo nextcloud.enable-https self-signed

- I want to integrate the two servers to be able to create Docs, Sheets & Slides from Nextcloud side.
  
- The next step is enabling ownCloud/Nextcloud ONLYOFFICE integration app as the following 
   instructions:
  1- Download the ownCloud/Nextcloud ONLYOFFICE integration app from [GitHub]() and place it to 
      my Nextcloud server into the /apps directory.
  2- Open Nextcloud. Go to Apps >> Not Enabled >> ONLYOFFICE and click the Enable button.
  3- Go to the Nextcloud Admin settings, find the ONLYOFFICE section and enter the address of the 
      server with ONLYOFFICE Document Server installed. Do not forget to save the changes.

- I can't find /apps directory in Nextcloud server.
- Are there any other steps that must be taken to complete the integration process?

**Comment by HelenBelova17** [comment]
Hello @**Sys-Admin889**

When working with nextcloud-snap add ONLYOFFICE app from Nextcloud’s store, then follow step 3- Go to the Nextcloud Admin settings...

**Comment by Sys-Admin889** [comment]
@HelenBelova17 Thanks for clarifying this, can you tell me all needed steps (How to install app after downloading from Nextcloud’s store, etc).

**Comment by HelenBelova17** [comment]
Go to Nextcloud’s apps page/Files/find ONLYOFFICE/Download and enable

**Comment by Sys-Admin889** [comment]
It has already been enabled after that, once trying to apply step3 this error occured.
![Capture](https://user-images.githubusercontent.com/59320357/76758056-8e16d000-6791-11ea-85aa-9f9d6011e6f5.JPG)

**Comment by HelenBelova17** [comment]
@**Sys-Admin889**, if you are using a self-signed certificate for your Document Server, Nextcloud will not validate such a certificate and will not allow connection to/from Document Server. This issue can be solved the following way: locate the Nextcloud config file (/nextcloud/config/config.php) and open it. Insert the following section to it:
```
'onlyoffice' =>
  array (
    'verify_peer_off' => TRUE,
  )
```

**Comment by Sys-Admin889** [comment]
![Capture](https://user-images.githubusercontent.com/59320357/76775906-ba8d1500-67ae-11ea-8a9f-c078b990f99b.JPG)

**Comment by Sys-Admin889** [comment]
@HelenBelova17 After adding there is another error occured
![Capture](https://user-images.githubusercontent.com/59320357/76783809-3c833b00-67bb-11ea-9011-67e55f96d075.JPG)

**Comment by Sys-Admin889** [comment]
I think the error occurs because I'm trying to add server ip address only without secret, so I need to anable jwt for document server to add jwt-secret and jwt-header, also adding to config.php file in nextcloud server as following:
![Capture](https://user-images.githubusercontent.com/59320357/76798858-11a7df80-67d9-11ea-826b-4a362fa203ba.JPG)
So, how to enable jwt?

**Comment by Sys-Admin889** [comment]
@alexanderonlyoffice Can you help me in my case ?

**Comment by Sys-Admin889** [comment]
@HelenBelova17  In my ONLYOFFICE document server, I don't have this directory. 

/snap/nextcloud/19299/htdocs/apps/files_external/lib/config.php
/snap/nextcloud/19299/htdocs/config/config.php
/var/snap/nextcloud/19299/nextcloud/config/config.php
/var/tmp/config.php.swp

**Comment by Sys-Admin889** [comment]
@HelenBelova17 It is already added before, could you check config.php file for any syntax error please?
[config.php.txt](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/files/4346073/config.php.txt)

**Comment by Sys-Admin889** [comment]
This error still appears, anybody can help me please?

**Comment by Sys-Admin889** [comment]
- The last section added as the bellow steps but the error still appears.
   1- cd /var/snap/nextcloud/19299/nextcloud/config/
   2- sudo nano /var/snap/nextcloud/19299/nextcloud/config/config.php
   3- Adding the bellow section on config.php file before the last );
   ‘onlyoffice’ => array ( ‘verify_peer_off’ => TRUE, ),
 
 - After that checked the connection between Document server and Nextcloud
   servers from Nextcloud side and the result here:
   administrator@ubuntu:~$ wget 192.168.1.8
   –2020-03-18 14:09:29-- http://192.168.1.8/
   Connecting to 192.168.1.8:80… connected.
   HTTP request sent, awaiting response… 301 Moved Permanently
   Location: https://192.168.1.8/ [following]
   –2020-03-18 14:09:29-- https://192.168.1.8/
   Connecting to 192.168.1.8:443… connected.
   ERROR: cannot verify 192.168.1.8’s certificate, issued by
   ‘emailAddress=admin@onlyoffice-tadweer.com,CN=onlyoffice-
   tadweer.com,OU=Textiles,O=Tadweer,L=Sadat City,ST=Monofia,C=EG’:
   Self-signed certificate encountered.
   ERROR: certificate common name ‘onlyoffice-tadweer.com’ doesn’t match
   requested host name ‘192.168.1.8’.
   To connect to 192.168.1.8 insecurely, use `–no-check-certificate’.

   What should I do for now?

**Comment by CarlOnlyoffice** [comment]
Hello @Sys-Admin889,

Is your Nextcloud also using a self-signed certificate? In this case go to Document Server's config /etc/onlyoffice/documentserver/default.json, switch `rejectUnauthorized` to `false` and run `supervisorctl restart all`. After that try to save the connector settings anew.

**Comment by Sys-Admin889** [comment]
@CarlOnlyoffice Thanks for your reply,
Yes Nextcloud also using a self-signed certificate.
After changing rejectUnauthorized value to false, error writing occured when trying to save (ctr+o).

**Comment by CarlOnlyoffice** [comment]
> error writing occured when trying to save
Is there an error when saving the connector settings? Have you restarted the Document Server's services?

**Comment by Sys-Admin889** [comment]
No, I mean that default.json reject to be modified.

**Comment by Sys-Admin889** [comment]
@CarlOnlyoffice Thank you connection have succeeded. I was trying to modify default.json on another document server installed by snap.

**Comment by Sys-Admin889** [comment]
@CarlOnlyoffice after creating first docs file, it openned one time then it can't be openned and this error appears 
![Capture](https://user-images.githubusercontent.com/59320357/77069125-87d25f00-69f0-11ea-8349-0f28f02f7379.JPG)

**Comment by caqcchuteauxoutardes** [comment]
i have the same error saying

**Comment by Sys-Admin889** [comment]
@caqcchuteauxoutardes All needed steps documented here in this issue, follow these steps to solve error occurred.
