### ISSUE TITLE
Blank files if edited offline

### ISSUE THREAD

**Issue by Jolopu** [ONLYOFFICE/onlyoffice-nextcloud#251]
I can create and edit documents online in OnlyOffice. Then they get saved locally by the Nextcloud Client. When I open the local version the document is blank. The version date always stays at the creation date even if the document is edited online.
I use:
Nextcloud 18.0.2 on a shared hosting - fresh install
Community Document Server 0.1.5
ONLYOFFICE 4.1.4

The log throws this error:

[index] Error: OCP\Files\NotFoundException: /appdata_oc4yx4ilf7lb/documentserver_community/doc_2395508721/Editor.bin at <<closure>>

 0. /home/www/cloud.myserver.com/lib/private/Files/Node/Folder.php line 137
    OC\Files\Node\Root->get("/appdata_oc4yx4 ... n")
 1. /home/www/cloud.myserver.com/lib/private/Files/SimpleFS/SimpleFolder.php line 74
    OC\Files\Node\Folder->get("Editor.bin")
 2. /home/www/cloud.myserver.com/apps/documentserver_community/lib/Document/DocumentStore.php line 99
    OC\Files\SimpleFS\SimpleFolder->getFile("Editor.bin")
 3. /home/www/cloud.myserver.com/apps/documentserver_community/lib/XHRCommand/OpenDocument.php line 99
    OCA\DocumentServer\Document\DocumentStore->getDocumentForEditor(2395508721, OC\Files\Node\File {}, "txt", null)
 4. /home/www/cloud.myserver.com/apps/documentserver_community/lib/XHRCommand/AuthCommand.php line 133
    OCA\DocumentServer\XHRCommand\OpenDocument->openDocument({c: "open",id: " ... e}, OCA\DocumentServer\IPC\IPCChannel {})
 5. /home/www/cloud.myserver.com/apps/documentserver_community/lib/XHRCommand/CommandDispatcher.php line 45
    OCA\DocumentServer\XHRCommand\AuthCommand->handle({type: "auth",do ... }}, OCA\DocumentServer\Channel\Session {}, OCA\DocumentServer\IPC\IPCChannel {}, OCA\DocumentServ ... {}, OCA\DocumentServ ... {})
 6. /home/www/cloud.myserver.com/apps/documentserver_community/lib/Channel/Channel.php line 106
    OCA\DocumentServer\XHRCommand\CommandDispatcher->handle({type: "auth",do ... }}, OCA\DocumentServer\Channel\Session {}, OCA\DocumentServer\IPC\IPCChannel {}, OCA\DocumentServ ... {})
 7. /home/www/cloud.myserver.com/apps/documentserver_community/lib/Controller/SessionController.php line 114
    OCA\DocumentServer\Channel\Channel->handleCommand({type: "auth",do ... }})
 8. /home/www/cloud.myserver.com/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\DocumentServer\Controller\SessionController->xhrSend(null, "2395508721", "960", "vfe0ttks")
 9. /home/www/cloud.myserver.com/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\DocumentServ ... {}, "xhrSend")
10. /home/www/cloud.myserver.com/lib/private/AppFramework/App.php line 125
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\DocumentServ ... {}, "xhrSend")
11. /home/www/cloud.myserver.com/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\DocumentSe ... r", "xhrSend", OC\AppFramework\ ... {}, {documentId: "23 ... "})
12. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({documentId: "23 ... "})
13. /home/www/cloud.myserver.com/lib/private/Route/Router.php line 299
    call_user_func(OC\AppFramework\ ... {}, {documentId: "23 ... "})
14. /home/www/cloud.myserver.com/lib/base.php line 1008
    OC\Route\Router->match("/apps/documents ... d")
15. /home/www/cloud.myserver.com/index.php line 38
    OC::handleRequest()

POST /index.php/apps/documentserver_community/3rdparty/onlyoffice/documentserver/doc/2395508721/c/960/vfe0ttks/xhr_send?t=1584399275870
from 89.187.189.198 by frank at 2020-03-16T22:54:36+00:00

**Comment by KevID** [comment]
I have the similar problem with a fresh install with Nextcloud VM (https://github.com/nextcloud/vm), 2 days ago.

I use:
Nextcloud 18.0.2 on a shared hosting - fresh install with Nextcloud VM
Community Document Server 0.1.5
ONLYOFFICE 4.1.4

**Comment by HelenBelova17** [comment]
@**Jolopu**, @**KevID**, please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).

**Comment by Jolopu** [comment]
@HelenBelova17 Thank you. For us as end users it's hard to tell if it's a OnlyOffice-Nextcloud or a Nextcloud-Document Server issue. I posted the issue over on: https://github.com/nextcloud/documentserver_community/
