### ISSUE TITLE
Sidebar no longer showing (4.1.4)

### ISSUE THREAD

**Issue by wiswedel** [ONLYOFFICE/onlyoffice-nextcloud#252]
As of 4.1.4, the sidebar controls are no longer visible.

### 4.1.2

![photo5440684478755351935](https://user-images.githubusercontent.com/1804221/76865748-760f8100-6863-11ea-9293-2bf33f886e18.jpg)

### 4.1.4

![4 1 4](https://user-images.githubusercontent.com/1804221/76865764-7b6ccb80-6863-11ea-8503-96bcce829b5e.png)

**Comment by HelenBelova17** [comment]
Hello @wiswedel, clicking on this icon opens the sidebar
![Screenshot_41](https://user-images.githubusercontent.com/31805700/76867775-0e633100-6877-11ea-82cf-c929297e401f.png)

**Comment by wiswedel** [comment]
@HelenBelova17 I only have this:

![image](https://user-images.githubusercontent.com/1804221/76868303-fbe0fb80-6866-11ea-8a71-4452bc2052f9.png)

**Comment by HelenBelova17** [comment]
@**wiswedel**, what version Nextcloud and Document Server do you use?

**Comment by wiswedel** [comment]
Ah, my bad I guess. This was from the Community Document Server (the Nextcloud adaption).
Now tested with 5.5 Integration Edition and it works as you described.
I'll open a new post over at Nextcloud's repo.

**Comment by wiswedel** [comment]
rel: https://github.com/nextcloud/documentserver_community/issues/92

**Comment by violoncelloCH** [comment]
I'm not sure if this is related to integration edition vs community document server (nextcloud adaption)
I'm encountering the same behavior with both versions of the document server (docker image onlyoffice/documentserver):
In the default configuration everything works fine (the x and the sharing icon in nextcloud's top bar is shown); however checking the setting "Display toolbar tabs" changes it to the icons embedded into the editor... now when unchecking this setting and applying again, this stays and I couldn't find a way to bring the original behavior back... 

Nextcloud: 18.0.3
Onlyoffice Nextloud App: 4.1.4

@wiswedel and @HelenBelova17 can you reproduce this as well?

**Comment by HelenBelova17** [comment]
Hello @**violoncelloCH**, can't reproduce with Document Server: 5.5.0.165. Specify version of Document Server which you use?

**Comment by violoncelloCH** [comment]
This is with the latet docker image onlyoffice/documentserver... (just tried to pull again to be sure it's the latest)/The version I see in the editor is 5.5.0... Where can I find the exact version number when using the docker image?

**Comment by HelenBelova17** [comment]
In editor 5.5.0, the icons are built into the editor and with the option “Display toolbar tabs” turned on, the interface looks like this 
![Screenshot_70](https://user-images.githubusercontent.com/31805700/78246528-f8e63c00-74f1-11ea-839d-db2e1ec963f2.png)

and with the option “Display toolbar tabs” turned off, the interface looks like this 
![Screenshot_71](https://user-images.githubusercontent.com/31805700/78246592-11565680-74f2-11ea-86a9-07147db00a20.png)

**Comment by collex100** [comment]
I set up 18 nextcloud. By default, Community Document Server 0.1.5 is installed with onlyoffice 5.4.2. How do I upgrade onlyoffice from 5.4.2 to 5.5.0 in a Community Document Server? Or do you use a third-party onlyoffice application (docker)? 
I wonder if the onlyoffice version will be upgraded in the Community Document Server? Thank you!

**Comment by wiswedel** [comment]
> I set up 18 nextcloud. By default, Community Document Server 0.1.5 is installed with onlyoffice 5.4.2. How do I upgrade onlyoffice from 5.4.2 to 5.5.0 in a Community Document Server? Or do you use a third-party onlyoffice application (docker)?
> I wonder if the onlyoffice version will be upgraded in the Community Document Server? Thank you!

@collex100 Please open a new issue for this completely different question.
