### ISSUE TITLE
Onlyoffice changes are not saved in Nextcloud and sync wipes changes

### ISSUE THREAD

**Issue by timo12357** [ONLYOFFICE/onlyoffice-nextcloud#254]
####Issue
Edits and changes made in Onlyoffice are not saved into Nextcloud and sync from Nextcloud to Onlyoffice destroys all changes made in Onlyoffice.

#### Expected Behavior
Edits and changes written in Onlyoffice sync to the local desktop environment and the changes done in the desktop environment sync to OnlyOffice

#### Actual Behavior
Files stored in the local desktop environment are synced flawlessly to Nextcloud. Onlyoffice opens them flawlessly and lets the user edit the document. After saving the document and or logging out from nextcloud changes are kept in OnlyOffice cache and never written to the actual document. When user opens same document from the desktop the changes have disappeared. If user saves the document with a small change, this change is synced to OnlyOffice overwriting the changes in the cache.

#### Possible Fix
Write cache data to file regularly and frequently. Recognize when user leaves Onlyoffice or closes file and write cache to file. In short: Copy the functionality of Google Docs.

#### Steps to Reproduce

1. Use a desktop wordprocessor and create a document in a NextCloud synced folder in your desktop environment 
2. Log onto the Nextcloud web UI and open the file with OnlyOffice.
3. Ask colleague to do the same
4. Make changes in document
5. Exit document 
6. Open document with desktop wordprocessor from local NextCloud synced folder.
7. Notice that the changes never were saved to the file in NextCloud,.
8. Open file in OnlyOffice from the Nextcloud web UI to notice changes are still there
9. Close OnlyOffice
10. Make minimal change in the desktop wordprocessor and save file locally.
11. Let NextCloud sync
12. Open file in OnlyOffice from the Nextcloud web UI to notice all changes made in OnlyOffice have been lost and overwritten with those made in the desktop environment
13. Feel despair.

#### Context
We just lost 2 days worth of expensive work made by our consultant. This is becoming very expensive to us!

#### Your Environment

* Nextcloud 18.0.3
* OnlyOffice Community Server bundled with NextCloud 18
* Nextcloud desktop client 2.6.4 Linux
* Nextcloud desktop client 2.6.4 Mac

**Comment by HelenBelova17** [comment]
@**timo12357** 
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).

**Comment by HelenBelova17** [comment]
@**timo12357** 

Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).

**Comment by timo12357** [comment]
:-I

**Comment by Skywrath-Mage** [comment]
Hello, 
We have the same issue with a dedicated docker instance for the document server.

**Comment by HelenBelova17** [comment]
Hello @**Skywrath-Mage**, please specify some additional information:
1. version of Nextcloud
2. version of Document Server
3. version of the ONLYOFFICE integration app for Nextcloud
4. version of Nextcloud desktop client

**Comment by Skywrath-Mage** [comment]
1. Nextcloud 18.0.2
2. OnlyOffice 5.5.0
3. 4.1.4	
4. Web OnlyOffice client and Mac 5.4.2 OnlyOffice client

**Comment by LinneyS** [comment]
The initial question was about the Community Document Service

@Skywrath-Mage 
you can create a new issue
