### ISSUE TITLE
Missing Functionality: Open "ReadOnly" by default

### ISSUE THREAD

**Issue by rgl1234** [ONLYOFFICE/onlyoffice-nextcloud#256]
Hello
I miss the functionalty to open every file in nextcloud-onlyoffice by default in readonly mode to avoid the corruption of clean MSOffice-Files.
So today it happens, that clean MSOffice files are getting corrupt if saved by onlyoffice. So I would like to activate read-functionality only (maybe in a second step after opening the file....), if the user knows what he is doing....
What do you think about this?
René

**Comment by mmccarn** [comment]
I did this manually a while back.

I put my notes into the enhancement issue: https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/93#issue-456536226

**Comment by rgl1234** [comment]
thanks @mmccarn 
this is rely helpful.....

**Comment by LinneyS** [comment]
#170
