### ISSUE TITLE
Although selected for file type, on public share collabora opens file type

### ISSUE THREAD

**Issue by b90g** [ONLYOFFICE/onlyoffice-nextcloud#259]
When Sharing selected File Types on a Nextcloud installation which has collabora & onlyoffice active, the file gets opened  internally as desired, but the sharing links will be opened by collabora.

Adding `apps/onlyoffice` in between `.tdl/` and `s/` will open shared links in only office but this works only as a work around.

Is the file assignment external differently determined than internally?
...
On a Nextcloud 18,
Php 7.2.24
Mariadb 10.2.31

**Comment by kolAflash** [comment]
I'm in the same organization as @b90g and to me it looks like the internal / external-link behaviour is only a result of a deeper problem.
It actually looks like opening a file directly or from a folder via files app makes the real difference.

When logged into NextCloud you usually open a file via the files app. In that case it always opens with OnlyOffice.
But when you got an external link, it depends on if it's a link to a folder or a file.

If it's an external link to a folder containing an office document, then the link will open the files app first. And when you open the actual file inside the folder, it happens from within the files app. So again OnlyOffice will come up.

But if it's a direct external link to a file, it will open with Collabora/LibreOfficeOnline.
Workaround (as said by @b90g): Put `apps/onlyoffice/` behind the slash at the end of `example.org/` and before `s/`.

**Comment by LinneyS** [comment]
Please report this issue to the Nextcloud team again to resume fixing.

The problem is described here nextcloud/richdocuments#361
@juliushaertl
