### ISSUE TITLE
Address of "Document Editing Service" is converted to lowercase

### ISSUE THREAD

**Issue by krzotr** [ONLYOFFICE/onlyoffice-nextcloud#26]
Hi,

We use a reverse proxy to serve Nextcloud which is located in `/xDrive/`, e.g. `https://cloud.test.pl/xDrive/`. To install onlyoffice we created a new virtual machine and set up docker. Url of the resource is `https://cloud.test.pl/xDrive/onlyoffice/`.

When we put the address to onlyoffice in "Document Editing Service address" field (`https://cloud.test.pl/xDrive/onlyoffice/`), the letter `D` is converted to `d`. We can not setup onlyoffice service address properly, because we use one capital letter `D`. 

Please see my video.

![onlyoffice](https://user-images.githubusercontent.com/655681/48717785-5d18a080-ec1a-11e8-8fb9-d2e234fb0f36.gif)

The same situation in `Document Editing Service address for internal requests from the server` and `Server address for internal requests from the Document Editing Service` fields.

## Solution

`strtolower` function should be removed from URLs to allow addresses which contain capital letters.

I checked source code.  In `lib/appconfig.php` someone put `strtolower` function which converts all URLs to lowercase. When I removed `strtolower` everything is working correctly.
- https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/v2.0.4/lib/appconfig.php#L249
- https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/v2.0.4/lib/appconfig.php#L284
- https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/v2.0.4/lib/appconfig.php#L211

## Workaround

At the moment we have modified URL to onlyoffice document service directly in the database.

## Steps to reproduce
1. Go to "Apps"
2. Find "onlyoffice"
3. Click "Download and enable" button
4. Go to "Settings" -> "ONLYOFFICE"
5. Put `https://cloud.test.pl/xDrive/onlyoffice/` in "Document Editing Service address"
6. The address is converted to `https://cloud.test.pl/xdrive/onlyoffice/` (`D` is replaced to `d`)

## Testing Platform

Nextcloud: 14.0.3 (nextcloud VM image - 14.0.3_1)
Onlyoffice Nextcloud: 2.0.4

**Comment by LinneyS** [comment]
Thank you for your comment.
Instead of a database, you can put the address in the Nextcloud configuration file  `config/config.php`
```
'onlyoffice' => array (
    'DocumentServerUrl' => 'https://cloud.test.pl/xDrive/onlyoffice/'
)
```
