### ISSUE TITLE
OnlyOffice Document Server 5.5.1: undefined error

### ISSUE THREAD

**Issue by dea-75** [ONLYOFFICE/onlyoffice-nextcloud#262]
Hi all !
I use Nextcloud 18.0.3 & OnlyOffice app connect 4.1.4 on a Debian 10 server.
On an external, dedicated, Debian 10 server I've installed OnlyOffice Document server 5.5.0 and works fine.
Now, I've upgraded to OnlyOffice 5.5.1, same configuration... when I try to open a document: "Undefined error"
No error in log.... 

Any idea ?

Thanks

Luca

**Comment by dea-75** [comment]
Same notes:
- OnlyOffice dedicated servers run on Debian 10, PostgreSQL and all over daemon included in Debian 10 pack.
- OnlyOffice installed by deb pack
- Nextcloud and OnlyOffice servers use a formal valid SSL certificate
- OnlyOffice run on alternative tcp port: 1443 (over SSL)
- Nextcloud point to OnlyOffice URL
- OnlyOffice use a secret key to protect connection (specify in Nextcloud connector)

**Comment by acs-ferreira** [comment]
Same here, in french.

![image](https://user-images.githubusercontent.com/12234510/79074044-652f1f80-7cea-11ea-89fe-ba6183583cdd.png)

**Comment by dea-75** [comment]
Yes, exactly the same

**Comment by johnjameswhitman** [comment]
I'm getting something similar with OnlyOffice document server 5.5.1 and and Nextcloud 18.0.2. I can't find much in the logs on the document server. Happy to dive in if there's a quick way to enable debug logging.

![Screenshot](https://user-images.githubusercontent.com/1639083/79241467-1942be80-7e41-11ea-843a-2490267330e4.png)

**Comment by dea-75** [comment]
I think the problem is not in OnlyOffice document server (version 5.5.1), seems works correctly.
Is it possible that the problem is in the connection app with the document server ?
Now in release 4.1.4, maybe not compatible with DC 5.5.1 ......

**Comment by acs-ferreira** [comment]
We have reverted **back to 5.5.0** from https://github.com/ONLYOFFICE/DocumentServer/releases

```
wget https://github.com/ONLYOFFICE/DocumentServer/releases/download/ONLYOFFICE-DocumentServer-5.5.0/onlyoffice-documentserver_amd64.deb
apt install -y ./onlyoffice-documentserver_amd64.deb
```

This version works fine.

**Comment by dea-75** [comment]
Yes, I can confirm. The release 5.5.0 works fine !

**Comment by dea-75** [comment]
Any news ?

**Comment by alexanderonlyoffice** [comment]
@dea-75, @acsfer, please specify some additional information about the problem: 

1. Do you see any errors when clicking on the 'Save' button on ONLYOFFICE integration app settings page in Nextcloud;
2. What logs exactly did you check? Please check out.log of the DocService and Converter in the folders /var/log/onlyoffice/documentserver/docservice and  /var/log/onlyoffice/documentserver/converter;
3. Do you use self-signed or CA-signed certificates? Please try to check the accessibility of the server to each other using egt command. wget https://documentserver_address from the server with Nextcloud and wget https://nextcloud_address from the server with Document Server. Send us the screenshot of these commands outputs;
4. Did you add the same JWT secret on ONLYOFFICE integration app settings page in Nextcloud as the one specified in config.php of Nextcloud?

@johnjameswhitman, how often do you get this error? Does the error occur on all files?

**Comment by dea-75** [comment]
1. No, simply double click on a document... try to open than... "Undefined error"
2. Sorry, I've rollback to 5.5.0 than works fine
3. No, We use a formal valid SSL certificate. Access to the server in https://servername.domain/welcome or /info is correct. 
4. Yes, I've added.

Repeat, OnlyOffice 5.5.0 works perfectly with this configuration, any change during the upgrade to 5.5.1 (except the change in secret)

**Comment by johnjameswhitman** [comment]
I was getting the error on all files, but am no longer seeing the issue. Since I last commented I've upgraded NextCloud to v18.04 w/ the v4.1.4 OnlyOffice app. The OnlyOffice server is still at v5.5.1.

**Comment by loelkes** [comment]
After upgrading to 5.5.1 the secrets in `/etc/onlyoffice/documentserver/local.json` were gone. This was the cause of many _Track without jwt_ and _Download without jwt_ errors in nextcloud. Resetting the tokens fixed it for me.

**Comment by dea-75** [comment]
I've just upgrade to 5.5.3 and the problem persist. Works fine only on 5.5.0.
I use secrets in local.json and Nextcloud, after upgrade verify and adapt local.json, but persist an "undefined error" when try to open every document.
Exactly same configuration works fine on version 5.5.0

**Comment by dea-75** [comment]
OK, I've resolved the problem.
Local.json was update , it wasn't the problem.
When I upgrade on Debian Onlyoffice, I havn't modify ngnix configuration with the new package version. The problem was the ngnix configuration file.
Solved !

**Comment by acsfer** [comment]
@dea-75 What does that mean?

**Comment by dea-75** [comment]
Il 12/06/20 11:24, Carlos Ferreira ha scritto:
> What does that mean?


That the problem was related to the configuration of nginx, during the 
update I answered "no" to the replacement of the configuration file of 
nginx. Now works very well !

**Comment by acsfer** [comment]
May I ask you to please post your new nginx conf here so we can compare with previous versions and find what has changed and why it fails?

In large productions, we can't just say 'yes' without understanding what happens behind.

Many thanks.

**Comment by dea-75** [comment]
Yes I know, tipically I say no, to preserv the original configuration.
Simply the correct configuration is inside the onlyoffice 5.5.3 deb package in the nginx directory.

Luca

Il giorno 12 giu 2020, 20:09, alle ore 20:09, Carlos Ferreira <notifications@github.com> ha scritto:
