### ISSUE TITLE
Will be upgraded in the Community Document Server from 5.4.2 to 5.5.0 Onlyoffice ?

### ISSUE THREAD

**Issue by collex100** [ONLYOFFICE/onlyoffice-nextcloud#263]
I set up 18 nextcloud. By default, Community Document Server 0.1.5 is installed with onlyoffice 5.4.2. How do I upgrade onlyoffice from 5.4.2 to 5.5.0 in a Community Document Server? Or do you use a third-party onlyoffice application (docker)?
I wonder if the onlyoffice version will be upgraded in the Community Document Server? Thank you!

**Comment by HelenBelova17** [comment]
Hello @**collex100**,
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).
