### ISSUE TITLE
Onlyoffice on Android won't load after onlyoffice 4.1.4 update

### ISSUE THREAD

**Issue by SomaliRaven** [ONLYOFFICE/onlyoffice-nextcloud#268]
After installing the update to 4.1.4 onlyoffice is still working in the browser but does not load in the Android app. See picture below:

![issue](https://user-images.githubusercontent.com/32564553/79964760-7109a700-848b-11ea-9f70-2cb4cac2ba69.jpg)

May correlate to #228 but does not seem to be fixed in 4.1.4. 
Nextcloud Android App is Version 3.11.0

**Comment by nav-fess** [comment]
Please upgrade ONLYOFFICE to 5.5.1.
Documents will open correctly.

Nextcloud Android App is Version 3.11.1 RC1
Onlyoffice Document Server is Version 5.5.1

**Comment by SomaliRaven** [comment]
Onlyoffice was already up to date.

The Version 3.11.1 RC1 of Nextcloud Anroid App is still in "pre-release" and could not be downloaded. I tested it by manually installing it via .apk (https://github.com/nextcloud/android/releases/tag/rc-3.11.1-01). It is fixed.

Thank you very much.
