### ISSUE TITLE
No File access when using "File access control" app

### ISSUE THREAD

**Issue by zirkeltraining** [ONLYOFFICE/onlyoffice-nextcloud#27]
i installed the Nextcloud-offical app "File access control" and set up some access restrictions so that there is now a folder "Finance" which is only accessible for users in the user group "Accountants".

Now being in said group, i can create, see and download an xlsx there, but attempting to edit it gives me "Download failed" just after the editor has loaded.

![image](https://user-images.githubusercontent.com/26162293/48919072-0668cc00-ee91-11e8-8552-e4bb73b41057.png)
I suspect it may be because the user that the OO connector app acts under is different from "me". Is there a way i can add that virtual user to the group of users with the right permission?

**Comment by alexanderonlyoffice** [comment]
Hello @zirkeltraining, this error means that the Document Server cannot download the file for editing.

Could you please specify some more information: 

1. OS of the server where ONLYOFFICE Document Server is installed;
2, Its installation type (docker or deb/rpm);
3. Current version of the Document Server; 
4. Specify is the error occurs when "File access control" app is disabled.

**Comment by zirkeltraining** [comment]
OS: Debian Stretch
Installation type: deb
Version: 5.1.3-35
can you clarify #3? the error only occurs on that file when file access control is active. Disabling FAC entirely makes the problem go away.

**Comment by alexanderonlyoffice** [comment]
Hello @zirkeltraining, I apologize for misspelling, you answered my question

> Disabling FAC entirely makes the problem go away.

We will try to reproduce the issue on our side to detect its reason.  Could you please describe also step-by-step scenario on how to reproduce it.

**Comment by zirkeltraining** [comment]
i currently have issues since tagging is broken on my server: Apparently [tagging is unstable in NC 14.0.4 ](https://github.com/nextcloud/server/issues/10774 )and should be back up in 14.0.5. 
But this is how it behaved when tagging still worked for me:

1.  in NC settings->Administration->Workflow, create a tag "secret" of type "invisible"
2.  in NC settings->Administration->file access control, create a rule group "hide secret files": "File system tag/is tagged with/"secret" 
3.  in nextcloud, i create an onlyoffice file "secret-test.docx". 
4. While it's not tagged, i can edit it inline by clicking it in NC, it opens in OO
5. as soon as i tag the file as "secret", oo throws the above error as i try to open it.

(a note: also i just found i have Onlyoffice nextcloud app ver. 2.0.4., not 2.1.0. at the moment)

**Comment by alexanderonlyoffice** [comment]
@zirkeltraining, we have tried to reproduce the issue on the latest version of Nextcloud, which is 14.0.4 and, as you said the tagging is not working on that version. Please specify then which version you had when the problem occurred.

**Comment by zirkeltraining** [comment]
It most likely was the last previous release. However, we can't roll back as we're on a productive system; I'll revisit this issue once Nextcloud has issued an update to fix the tagging.

**Comment by alexanderonlyoffice** [comment]
@zirkeltraining, ok, thank you for this information. We will try to reproduce the issue.

**Comment by alexanderonlyoffice** [comment]
@zirkeltraining, we have checked the issue and found its reason, unfortunately, there is no possibility to solve the issue at the moment.

**Comment by zirkeltraining** [comment]
After having upgraded our nextcloud, so that tagging works again for me, i can confirm the error persists. Any Ideas about a workaround maybe?

**Comment by alexanderonlyoffice** [comment]
@zirkeltraining, we are thinking on how to solve the issue, but at the moment it does not have a solution.

**Comment by martinspaeth** [comment]
Hi there, we facing the same problem as described. Is there any news regarding this issue? Any way to support here?

**Comment by krenn08** [comment]
Greetings... we're suffering this same ailment.  We need both Openoffice and File Access Control to get along nicely, or we're sunk. :/

**Comment by LinneyS** [comment]
@zirkeltraining 
>     1. in NC settings->Administration->Workflow, create a tag "secret" of type "invisible"
>     2. in NC settings->Administration->file access control, create a rule group "hide secret files": "File system tag/is tagged with/"secret"
>     3. in nextcloud, i create an onlyoffice file "secret-test.docx".
>     4. While it's not tagged, i can edit it inline by clicking it in NC, it opens in OO
>     5. as soon as i tag the file as "secret", oo throws the above error as i try to open it.

I am reproducing this scenario and I understand that no application has read access to the file with this tag.
The file can neither be downloaded nor edited by other apps.
Can you give another example of using the File Access Control application when the file remains available?

**Comment by martinspaeth** [comment]
Any news on this topic?

**Comment by krenn08** [comment]
Ok - there may be an issue still in the programming.  But.. our problem was NOT with OnlyOffice - just the way it's set up for us.

Long story short - we have our OO server set up in the DMZ.  The Docker container, where OO lives, has DNS going to Google.  However, we needed the Nextcloud's IP to be the DMZ address, NOT the external address, which is indicated by Google (or our DMZ DNS servers, for that matter).  So, we do:

 sudo docker run -i -t -d -p 443:443 --restart=always     --add-host=nextcloudserver.mypublicdomain.com:192.168.42.36 -v /app/only...

Add the host to the docker image's local host file, and you're good to go.

Hope this helps.

**Comment by LinneyS** [comment]
@juliushaertl
If you have the time, you can see it?

**Comment by juliushaertl** [comment]
My guess would be that the files_accesscontrol app blocks fetching the file in https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/9c5aae53badc3a1770f70c0a9fa92b1eafe168f9/controller/editorcontroller.php#L614 or https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/46320b60f1f906103302aa1b018fc96e9289b080/controller/callbackcontroller.php#L471 since the request from only office doesn't have the current user session. You can work around that by temporarily setting the user session for the requests that need it with https://github.com/nextcloud/server/blob/0a874c51af8dd6652c694f0545489af23d53771a/lib/public/IUserSession.php#L68

**Comment by LinneyS** [comment]
@juliushaertl 
It helped me in #110 

But I decided that this scenario https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/27#issuecomment-445197424 has no solution. No problems at the ONLYOFFICE app. File, in principle, can not be downloaded.

**Comment by juliushaertl** [comment]
> But I decided that this scenario [#27 (comment)](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/27#issuecomment-445197424) has no solution. No problems at the ONLYOFFICE app. File, in principle, can not be downloaded.

The scenario described there is expected behavior, the whole point of the files_accesscontroll app is to block access to a file. So if the only rule is that a tag is present and the file is tagged, the file can never be accessed from anywhere.

**Comment by SureshUppelli** [comment]
can i restrict access to file on local machine when fellow members working on it? is there any option for it? please let me know ?
