### ISSUE TITLE
An Error has occurred while opening the file

### ISSUE THREAD

**Issue by toehold** [ONLYOFFICE/onlyoffice-nextcloud#272]
Hi,

installed on ubuntu 18.04 64bit 
NC 18.04
OnlyOffice: 0.1.5
Community Document Server: 0.1.5

When opening a ods file get this error messge:

An Error has occurred while opening the file

Any ideas?

THanks a lot!

**Comment by HelenBelova17** [comment]
Hello @**toehold**,
please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).

**Comment by toehold** [comment]
Thanks, opened issue with them.
