### ISSUE TITLE
Use ONLYOFFICE application with nextcloud v19beta

### ISSUE THREAD

**Issue by guryanovev** [ONLYOFFICE/onlyoffice-nextcloud#273]
Currently the connector app has a restriction for NextCloud version to be less or equal to 18, is there any way to use the app with beta version (19) of Next Cloud Server?

**Comment by HelenBelova17** [comment]
Hello @**guryanovev**,  change max-version to 19 in this file [https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/f9e427ea53866568271a950c27343ca0ebee8aae/appinfo/info.xml#L32](url)

**Comment by LinneyS** [comment]
Nextcloud 19 is supported since v4.2.0
84c1cb39a8f10b57e6af1a91bd6f93349cbbc084
