### ISSUE TITLE
Mousewheel click doesn't open file

### ISSUE THREAD

**Issue by Irillit** [ONLYOFFICE/onlyoffice-nextcloud#274]
Hello,
My users expect that clicking mousewheel on file in Files view will open their document in a new tab, but instead it downloads the file.
I suppose I can fix it, but do you need this kind of feature as pull request?

**Comment by LinneyS** [comment]
Hi @Irillit 
Clicking on the wheel opens the url of link.
Or handle the click event programmatically and open the link.
Both decisions are on the side of the Nextcloud team

Contact [them](https://github.com/nextcloud/server) with this offer.
@jancborchardt

**Comment by jancborchardt** [comment]
Yes, mousewheel click should have the expected behavior, which is opening whatever would happen on click, but in a new tab.

As @LinneyS said, please open an issue about that at https://github.com/nextcloud/server/issues
cc @juliushaertl
