### ISSUE TITLE
ONLYOFFICE cannot be reached. Please contact admin 

### ISSUE THREAD

**Issue by timoerti** [ONLYOFFICE/onlyoffice-nextcloud#279]
This error comes when I want to open a docs or xls document. I have reinstall Onlyoffice but the error is still there.

**Comment by romankh3** [comment]
I faced the same problem. 
Is it related to the self-signed SSL certificate?

**Comment by timoerti** [comment]
Yes

**Comment by romankh3** [comment]
@timoerti , Will lets-encryped solve this problem?

**Comment by timoerti** [comment]
no it is lets-encrypted

**Comment by timoerti** [comment]
I don´t know

**Comment by romankh3** [comment]
No, it doesn't help with it.

**Comment by timoerti** [comment]
ok you have any ideas to fix that?

**Comment by romankh3** [comment]
Just a workaround: for smartphone, I'm using `onlyoffice` app,
also can be used the previous version. but I don't know-how.

**Comment by paschaef** [comment]
If you are using the `Community Document Server` app as the document server in your nextcloud, make sure it is enabled. Mine was disabled out of nothing and caused the above mentioned error. 
After enabling the app again it worked fine.

**Comment by romankh3** [comment]
@paschaef, Unfortunately it didn't help me. Thanks for your response

**Comment by timoerti** [comment]
@paschaef  I installed the Community Document Server but now I get a 502 Bad Gateway for the Document Server.

**Comment by timoerti** [comment]
I have fixed it. Thank you all for your help.

**Comment by romankh3** [comment]
@timoerti , how did you fix that? Did you install separated onlyoffice Document Server?

**Comment by timoerti** [comment]
Yes @romankh3 I installed the Document server.

**Comment by romankh3** [comment]
@timoerti Can you provide some guidelines?

**Comment by romankh3** [comment]
I found the problem!
there was a wrong settings for ONLYOFFICE. `Document Editing Service address` was wrong. it refers to `http` host without domain name.

When I changed it to my https URL with domain name it was fixed it.

**Comment by vasyugan** [comment]
> If you are using the `Community Document Server` app as the document server in your nextcloud, make sure it is enabled. Mine was disabled out of nothing and caused the above mentioned error.
> After enabling the app again it worked fine.
> See [nextcloud/server#20824](https://github.com/nextcloud/server/issues/20824)

My issue is actually not with the documentserver as an app. I run the dockerized version. My problem is that the OnlyOffice app got repeatedly deactivated for no apparent reason. This sounds like an entirely different problem to me.
