### ISSUE TITLE
access authorized for group members

### ISSUE THREAD

**Issue by Bschalck** [ONLYOFFICE/onlyoffice-nextcloud#28]
Hello,

I have a Nextcloud instance with 60users.
Can we specify which group can access to OnlyOffice ? 

Regards,

**Comment by Bschalck** [comment]
Hello,

Do you know if this feature is in devlopment ? Can you expect to have it a day ?

Cordialement,

**Comment by LinneyS** [comment]
I am working on this task.
Most likely, it will be implemented in one of the next releases.

**Comment by Bschalck** [comment]
Thanks for the answer :) 
Good work !
