### ISSUE TITLE
ONLYOFFICE cannot be reached. Please contact admin

### ISSUE THREAD

**Issue by romankh3** [ONLYOFFICE/onlyoffice-nextcloud#280]
I have this error when I try to open a doc or spreadsheet.
I have reinstalled Onlyoffice bit the error is still there.

Also, I have checked, that `Community Document Server` is installed and enabled.

Versions:
*   `Nextcloud Server` is  `18.0.4`
*   `Community Document Server` is `0.1.5`
*   `ONLYOFFICE` is `4.14`

**Comment by HelenBelova17** [comment]
Hello @**romankh3**,
please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).

**Comment by romankh3** [comment]
thank you, @HelenBelova17
