### ISSUE TITLE
make more than one install domain possible

### ISSUE THREAD

**Issue by mokkin** [ONLYOFFICE/onlyoffice-nextcloud#285]
We have installed Onlyoffice via https://github.com/nextcloud/documentserver_community on `cloud.example.com` Our cloud we are accessing, depending on the usecase, from `cloud.example.com` and `cloud.anotherexample.com`-
Unfortunately Onlyoffice is not accessible when we are opening an office file from inside `cloud.anotherexample.com`.
This should be possible too, as it is configured in

**Comment by HelenBelova17** [comment]
Hello @**mokkin**,
please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).
