### ISSUE TITLE
Drop-downs of unknown errors in Onlyoffice 4.1.4

### ISSUE THREAD

**Issue by olsta34** [ONLYOFFICE/onlyoffice-nextcloud#287]
When I open an xlsx (or another format) file in onlyoffice that has drop-downs, they are not displayed. If I want to change the value manually, then I only get 'Unknown error'. Is there a way to fix this problem?

**Comment by HelenBelova17** [comment]
Hello @**olsta34**,
please specify some additional information:

Version of the Onlyoffice Document Server;
Version of the ONLYOFFICE integration app for Nextcloud;
Version of Nextcloud.

**Comment by olsta34** [comment]
I've had this problem since version 

Nextcloud 18.0.4
Document Server 0.1.5
OnlyOffice 4.1.4

With Nextcloud 18.0.6, Documentserver 0.1.7 and OnlyOffice 4.3.0 the problem is still there.

In OnlyOffice Desktop it was fixed

https://github.com/ONLYOFFICE/DocumentServer/issues/252

**Comment by HelenBelova17** [comment]
Hello @olsta34,
It seems you use Community Document Server by Nextcloud developed, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).
