### ISSUE TITLE
Can't connect do document server after update to NC19

### ISSUE THREAD

**Issue by k-matti** [ONLYOFFICE/onlyoffice-nextcloud#297]
Get errors:

Error onlyoffice OCP\Http\Client\LocalServerException: Host violates local access rules
Warning no app in context Host 192.168.0.50 was not connected to because it violates local access rules

Everything was working before update to NC19.
I have added in my config.php:

‘onlyoffice’ =>
array (
‘verify_peer_off’ => true,
),

My documentserver is docker container

**Comment by HelenBelova17** [comment]
Hello @**k-matti**, 
add this to config.php:

'allow_local_remote_servers' => true,

**Comment by k-matti** [comment]
Thanks it helped

**Comment by Darkha1f** [comment]
Sorry for a dumb question. which config.php should be edited? could you please drop a location
