### ISSUE TITLE
NC Version control / side-by-side show changes

### ISSUE THREAD

**Issue by P3Shaw** [ONLYOFFICE/onlyoffice-nextcloud#302]
Hey,
is there any chance to use nextcloud version control for nextcloud side by side comparison of the document changes? like sharepoint can do? Also would be great who did this changes? Like wiki track all changes.

**Comment by LinneyS** [comment]
Request to support Nextcloud versions: #194 

Comparison of two documents is possible starting from version 5.5 of ONLYOFFICE Document Server. https://api.onlyoffice.com/editors/config/events#onRequestCompareFile
But comparing versions will not be valid
