### ISSUE TITLE
iPadOS/iOS: Items like menu bar are hidden behind Nextcloud menu bar 

### ISSUE THREAD

**Issue by microfx** [ONLYOFFICE/onlyoffice-nextcloud#307]
Hey!

Am I the only one who constantly has problems with hidden / inaccessible menus / buttons on iPadOS/iOS (latest version 13.5.1)? Top menu and bottom icons are not accessible - only visible when swiping down / up.

it seems like the iFrame (or how it‘s called) is a bit too large to fit inside the Nextcloud interface. 

Any ideas if I can fix this in the config?

Thanks for reading / helping!

Nextcloud Version 18.0.6 / OnlyOffice 4.3.0 / Community Document Server 0.1.7 

![3200A82B-1B5C-4563-9B73-CECE63D16A9E](https://user-images.githubusercontent.com/37987212/86211504-cabadb80-bb76-11ea-8428-a4faf16fea7d.jpeg)

**Comment by HelenBelova17** [comment]
Hello @**microfx**,
please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).
