### ISSUE TITLE
Documentserver ConversionException namespace error

### ISSUE THREAD

**Issue by rolandverhaar** [ONLYOFFICE/onlyoffice-nextcloud#309]
I have found some related problems on the web.
Running onlyoffice 4.3.0 on nextcloud 19.0.0 in a docker environment.
Some documents run into the issue:

`OCA\DocumentServer\Document\DocumentConversionException: namespace error : Namespace prefix wp14 on sizeRelH is not defined lding" hidden="false"/><wp:cNvGraphicFramePr/><wp14:sizeRelH relativeFrom="page" ^ namespace error : Namespace prefix wp14 on pctWidth is not defined false"/><wp:cNvGraphicFramePr/><wp14:sizeRelH relativeFrom="page"><wp14:pctWidth ^ namespace error : Namespace prefix wp14 on sizeRelV is not defined p14:pctWidth>0</wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="page" ^ namespace error : Namespace prefix wp14 on pctHeight is not defined wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="page"><wp14:pctHeight ^

    /var/www/html/custom_apps/documentserver_community/lib/DocumentConverter.php - line 123:

    OCA\DocumentServer\Document\ConverterBinary->run("/tmp/oc_tmp_HnIqXs-.xml", null)

    /var/www/html/custom_apps/documentserver_community/lib/DocumentConverter.php - line 78:

    OCA\DocumentServer\DocumentConverter->runCommand(OCA\Document ... {})

    /var/www/html/custom_apps/documentserver_community/lib/Document/DocumentStore.php - line 151:

    OCA\DocumentServer\DocumentConverter->saveChanges("*** sensiti ... *", [ "78;AgAAAD ... "], "/var/www/ht ... x", "docx")

    /var/www/html/custom_apps/documentserver_community/lib/LocalAppData.php - line 100:

    OCA\DocumentServer\Document\DocumentStore->OCA\DocumentServer\Document\{closure}("*** sensiti ... *")

    /var/www/html/custom_apps/documentserver_community/lib/Document/DocumentStore.php - line 164:

    OCA\DocumentServer\LocalAppData->getReadWriteLocalPath(OC\Files\Sim ... {}, Closure {})

    /var/www/html/custom_apps/documentserver_community/lib/Document/SaveHandler.php - line 56:

    OCA\DocumentServer\Document\DocumentStore->saveChanges(714960670, [ OCA\Docume ... }])

    /var/www/html/custom_apps/documentserver_community/lib/BackgroundJob/Cleanup.php - line 69:

    OCA\DocumentServer\Document\SaveHandler->flushChanges(714960670)

    /var/www/html/lib/public/BackgroundJob/Job.php - line 80:

    OCA\DocumentServer\BackgroundJob\Cleanup->run(null)

    /var/www/html/cron.php - line 126:

    OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})`

I can and do understand that this may be a problem with the original document of the user.
Can someone please tell me if this error is generating more problems for other users? (Like, the whole process is stopped) Or this problem is only a problem for this user and this document?

Thanks!

**Comment by HelenBelova17** [comment]
Hello @**rolandverhaar**
it seems you use Community Document Server by Nextcloud developed, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).

**Comment by rolandverhaar** [comment]
Hello @HelenBelova17 
Thanks for your message.
I have built a nextcloud/onlyoffice instance in a docker platform.
The docker-compose.yml file uses:
```
  onlyofficeapp:
    container_name: onlyofficeapp
    image: onlyoffice/documentserver:latest
```
So, I am not sure if this is the nextcloud version or the onlyoffice version.
As far as I know, I have used the documentation of both nextcloud and onlyoffice to integrate it.

Thanks for your help!

**Comment by rolandverhaar** [comment]
Hello @HelenBelova17
Once again. thanks for your message.

Do you have any recommendations for me to find a solution to the errors?

Thanks in advance,
Roland

**Comment by HelenBelova17** [comment]
@**rolandverhaar**, errors in log from documentserver_community, try to disable this app. Report if problem persists.
