### ISSUE TITLE
editing document is unavailable, but editing spreadsheet and presentation works

### ISSUE THREAD

**Issue by Cavesnakes** [ONLYOFFICE/onlyoffice-nextcloud#31]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
I use docker version of OODS to intergrate with Nextcloud 14
Can't edit documents which have extentions like doc,docx,txt etc.
when i attempt to edit these, continuously whitescreen is appeared
I'm curious why Spreadsheet and Presentation works

**Did this work in previous versions of DocumentServer?**
1 years ago, Yes

**DocumentServer version:**
OODS-latest created on 2018-10-26 (Docker-CE 18.03.1-ce)

**Operating System:**
CentOS 7 (Up to date)

**Browser version:**
Firefox 63.0.3

**Comment by alexanderonlyoffice** [comment]
Hello @Cavesnakes, please specify if any actions were performed (like update of the DS or NC) before the issue occurred.

Please also make several screenshots with browser console opened:

1) Open browser console (choose Network tab) -> Reproduce the issue -> Send us a screenshot; 
2) Open browser console (choose Console tab) -> Reproduce the issue -> Send us a screenshot.

Send us also the screenshot of ONLYOFFICE integration app address settings from NC. Click also on the 'Save' button on the page with address settings to check if there are any errors.

**Comment by Cavesnakes** [comment]
I found some tricks to resolve this problem

1. change language and locale to english in NC
2. Don't use firefox, use chrome 

Don't know why this is happen, maybe NC is problem...
firefox console message is saying that my OODS does not permit cross-origin framing 
(with NC korean language setting)
I use nginx reverse-proxy for OODS

**Comment by Cavesnakes** [comment]
here's the picture that you request :D 
![default](https://user-images.githubusercontent.com/24396573/49512316-ed204080-f8d0-11e8-9a1c-59bf65e80aff.png)
![2](https://user-images.githubusercontent.com/24396573/49512318-ef829a80-f8d0-11e8-9cc6-5374eaa47d4d.png)
![3](https://user-images.githubusercontent.com/24396573/49512320-f27d8b00-f8d0-11e8-90a4-b8389d4ec8de.png)

**Comment by Cavesnakes** [comment]
with english language settings
X-frame-options not specified in the server 

![4](https://user-images.githubusercontent.com/24396573/49512432-45efd900-f8d1-11e8-9d96-e2f3fc387194.png)

**Comment by Cavesnakes** [comment]
both of server are not specified X-Frame-Options SAMEORIGIN in nginx config
i'm curious now...

**Comment by alexanderonlyoffice** [comment]
@Cavesnakes, this is a very odd behavior, could you please give us an access to the account, where we can reproduce the issue. If yes, please send us the credentials with a message to support@onlyoffice.com with a note for technical support.

**Comment by LinneyS** [comment]
We set the `X-Frame-Options` header to the Community Server only. And it applies to Document Server in Enterprise Edition on Windows.
