### ISSUE TITLE
Corrupted file metadata after editing when quota is on

### ISSUE THREAD

**Issue by vianney** [ONLYOFFICE/onlyoffice-nextcloud#310]
### Steps to reproduce

1. Set the user quota to, e.g., 10 GB
2. Set up desktop file sync to, e.g., `~/nextcloud`.
3. Create a new document (e.g., "Test.docx") → let's call the initial template content *v0*
4. Edit the document in onlyoffice, add one line of text.
5. Close the onlyoffice editor
6. Wait for ~10 seconds for the document server to post the updated file → let's call the updated content *v1*
7. Refresh the nextcloud file view
8. Download the document from nextcloud
9. Open the document again in onlyoffice and add one extra line of text.
10. Close the onlyoffice editor.
11. Wait for ~10 seconds for the document server to post the updated file → let's call the final content *v2*
12. Refresh the nextcloud file view
13. Download the document from nextcloud

### Expected result

After step 8:

* The nextcloud file view should show the file size for *v1* (~18 KB).
* The versions pane should show one old version (*v0*)
* The downloaded file should be *v1*.
* `~/nextcloud/Test.docx` should be *v1*.
* On the server, `data/user/files/Test.docx` should be *v1*.

After step 13:

* The nextcloud file view should show the file size for *v2* (~18 KB, slightly larger than *v1*).
* The versions pane should show two old versions (*v1* and *v0*)
* The downloaded file should be *v2*.
* `~/nextcloud/Test.docx` should be *v2*.
* On the server, `data/user/files/Test.docx` should be *v2*.

### Actual result

After step 8:

* The nextcloud file view shows the file size for *v0* (7 KB).
* The versions pane does show one old version: *v0*.
* The downloaded file is *v1* truncated to the file size of *v0* (hence corrupted).
* `~/nextcloud/Test.docx` is *v0*.
* On the server, `data/user/files/Test.docx` is *v1*.

After step 13:

* The nextcloud file view shows the file size for *v1* (18 KB).
* The versions pane shows only one old version: *v0*.
* The downloaded file is *v2* truncated to the file size of *v1* (hence corrupted).
* `~/nextcloud/Test.docx` is *v0*.
* On the server, `data/user/files/Test.docx` is *v2*.

When the user quota is set to *Unlimited*, we do get the expected result.

As a workaround, running `occ files:scan --all` fixes the file sizes, triggering desktop sync and allowing to download the uncorrupted last version. Obviously, it has to be rerun after every edit.

### System information

* PHP-FPM 7.4.3
* Nextcloud 19.0.0.12
* ONLYOFFICE connector 4.3.0
* ONLYOFFICE document server 5.5.3 (debian package 5.5.3-39)
* The Community Document Server app is *not* installed
* Database: PostgreSQL 12.2
* `memcache.local`: APCu
* `memcache.distributed`: redis
* `memcache.locking`: redis

**Comment by LinneyS** [comment]
Fixed in Nextcloud 19.0.1 by nextcloud/server#21065
