### ISSUE TITLE
Feature Request: Own templates/assets

### ISSUE THREAD

**Issue by kleener** [ONLYOFFICE/onlyoffice-nextcloud#311]
It would be great if you could store several Word templates or update the existing ones using the setting.
So e.g. Templates for letterhead or standard template with company logo.

Can you do this?

**Comment by thomasgg23** [comment]
This is also a requested feature, we really need in daily work.
Also requested this feature via helpdesk.onlyoffice.com (paid version)

**Comment by alexanderonlyoffice** [comment]
@thomasgg23, @kleener, could you please describe the usage scenario of the requested feature, i.e. how do you see this feature looks like.

**Comment by kleener** [comment]
We are from the German Red Cross and have several departments there with different design templates and logos. Each department is supposed to use its own corporate design, so we would like to manage the templates centrally and make them available to the helpers as conveniently as possible so that they really do use the templates.
Of course, we could provide everyone with a read-only folder with the templates, but this is much more inconvenient for the members. They would first have to create a copy of the template and move it to the place where it should be, instead of just starting with the document where it should be in the end. 
It would be nice to provide each department with its own templates without them seeing the others. However, it can also happen that some members work in several departments.
If you have any further questions, please do not hesitate to contact me.

Translated with www.DeepL.com/Translator (free version)

**Comment by alexanderonlyoffice** [comment]
@kleener, thank you very much for your feedback. Our Design Department is considering the way this feature will be implemented at the moment and we are planning to release it within one of the next versions of the connector. Unfortunately, I cannot tell you any time frames at the moment.

**Comment by kleener** [comment]
Hi,
with the Nextcloud server something is already in preparation:
https://github.com/nextcloud/server/issues/22426
https://github.com/nextcloud/server/pull/25090

I hope it helps.

**Comment by Nidroide** [comment]
With nextcloud version 21 the above mentioned unified template subsystem was implemented so it should be possible to integrate it and give to users this important feature.

Regards
