### ISSUE TITLE
ONLYOFFICE web editing capabilities limited on snap installation

### ISSUE THREAD

**Issue by pilsnerbeer** [ONLYOFFICE/onlyoffice-nextcloud#314]
This issue is referencing #312 

1 Create new world document using MS World/Libre office and sync it to NC
2 open said document using onlyoffice and perform edits (append something to the bottom etc)
3 Notice that:

- "Modified" data hasn't changed
- If you try to download that edited file it will not download with the changes you made using onlyoffice
- If you're syncing this file with your PC locally, it won't sync with the edited data

Author of issue 312 claims _"on another nextcloud instance that uses a regular file system backend instead of block storage, but is otherwise configured identically, this problem does not exist."_ His issue exists on block storage and he was able to fix it by adding` allow_local_remote_servers' => true`, to the config.php. This however, doesn't fix my issue in any way and according to what the author said, it should be working fine for me anyway considering I dont use block storage on my server.

I would consider this issue important as one can easily lose data by editing documents from both onlyoffice and locally using MsWord/libreoffice - edits made via onlyoffice editor are not respected & synced and thus are immediately overwritten by whatever data is fed from the client.

```
snap 2.45.2
snapd 2.45.2
series 16
ubuntu 20.04
kernel 5.4.0-42-generic

Name Version Rev Tracking Publisher Notes
nextcloud 19.0.1snap1 22327 latest/stable nextcloud✓ -
```

**Comment by LinneyS** [comment]
Which version of ONLYOFFICE Document Server are you using?

**Comment by pilsnerbeer** [comment]
0.1.7

**Comment by LinneyS** [comment]
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).

**Comment by rajibrt** [comment]
I installed ONLYOFFICE on nextcloud on my personal hosting. I can't open or edit an Office file. Showing this error cURL error 3: (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
Any suggestions for this issue. Thanks in advance.
