### ISSUE TITLE
How to disable download button

### ISSUE THREAD

**Issue by cedarice** [ONLYOFFICE/onlyoffice-nextcloud#32]
From the OnlyOffice Api Document, I found it was able to set document download permission. Defines if the document can be downloaded or only viewed or edited online. In case the downloading permission is set to "false" the Download as... menu option will be absent from the File menu. The default value is true.
The onlyoffice Api website: https://api.onlyoffice.com/editors/config/document/permissions
Please tell me which file to modify can implement the function that cannot be downloaded.
Thanks.

**Comment by alexanderonlyoffice** [comment]
Hello @cedarice , unfortunately, there is no possibility to restrict downloading of the file at the moment in integration with Nextcloud. It depends on whether Nextcloud is going to implement such restrictions. When this feature is added in Nextcloud, we will add it in ONLYOFFICE integration app too.

**Comment by LinneyS** [comment]
Nextcloud 15 shared link
nextcloud/server#11898
