### ISSUE TITLE
OnlyOffice doesn't open/edit CSV-files correct 

### ISSUE THREAD

**Issue by configonfi** [ONLYOFFICE/onlyoffice-nextcloud#324]
**Do you want to request a *feature* or report a *bug*?**
Bug!

**What is the current behavior?**
If I click on a CSV-File to open it Openoffice starts with the message "Loading table", but nothing else happens. It doesn't matter if I click on the file, or rightclick on it. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Simple upload a CSV-File (no matter if Comma- or semikolon-seperated) and try to open/edit it with OnlyOffice.

**What is the expected behavior?**
I expect to be able to edit the CSV-File like a XLSX-File.

**Browser version:**
Firefox 76

We use the "Community Document Server 0.1.5" and Nextcloud 18.04.

**Comment by chmanie** [comment]
I'm having this problem, too, as well as others it seems: https://help.nextcloud.com/t/onlyoffice-problem-with-csv-files/79481

I seems to only affect the community server app, not the standalone version.

My installed versions:
NextCloud 21.0.5
Community Document Server 0.1.11
ONLYOFFICE 7.1.2

**Comment by ShockwaveNN** [comment]
> Community Document Server 0.1.11

Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate [GitHub repository](https://github.com/nextcloud/documentserver_community). 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://forum.onlyoffice.com/t/community-document-server-app-in-nextcloud-18/268).

**Comment by chmanie** [comment]
Ah yeah, sorry I didn't realize that. If anyone's coming here looking for that issue, it's here now: https://github.com/nextcloud/documentserver_community/issues/70
