### ISSUE TITLE
Nextcloud Onlyoffice client errors within five minutes "The document could not be accessed right now."

### ISSUE THREAD

**Issue by ryan77627** [ONLYOFFICE/onlyoffice-nextcloud#33]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?** After about 5 minutes of editing a document, firefox's console shows "The connection to wss://[URL] was interrupted while the page was loading. Onlyoffice then proceeds to show "The document could not be accessed"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Demo document: https://hub.stoicproductions.org/s/3TGwLJm3yamXKEe

**What is the expected behavior?** It doesn't error out and keeps the connection

**Did this work in previous versions of DocumentServer?** I do not know

**DocumentServer Docker tag:** latest

**Host Operating System:** Ubuntu 18.04 LTS

**Comment by alexanderonlyoffice** [comment]
Hello @ryan77627, we tried to reproduce the issue on our side, but did not succeed. Could you please give us access to the account where the problem exists, so we detect its reason. If yes, please send us the credentials in a mail to support@onlyoffice.com with a note 'For technical support'.

**Comment by alexanderonlyoffice** [comment]
Hello @ryan77627, 

> On an unrelated note, how many users does the document server support? I have seen conflicting information on the web concerning how many simultaneous users can be editing a document at a time.

Open source version of Document Server has 20 concurrent sessions for editing the file, it means that only 20 sessions can be opened for editing, all follow-up sessions will be opened for viewing only.

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs or we can close the topic?

**Comment by ryan77627** [comment]
I think it stopped shortly after, I believe it was a cookie issue. Shortly after making this issue I transitioned to another document server so I cannot verify anymore. I will close the issue and if someone has this issue they can open another issue.
