### ISSUE TITLE
When you press the download button in the context menu, the file opens in onlyoffice

### ISSUE THREAD

**Issue by gorsing** [ONLYOFFICE/onlyoffice-nextcloud#330]
When you press the download button in the context menu, the file opens in onlyoffice, and the file is expected to be downloaded.

nextcloud 17.02
OO 5.5.3
ONLYOFFICE connector 4.3

It is possible to change it.

**Comment by HelenBelova17** [comment]
Hello @**gorsing**.
Does the problem occur with any specific  file format or all?
Can you attach gif with it?

**Comment by gorsing** [comment]
Hello @HelenBelova17 
[](https://ibb.co/MZXxfHC)

**Comment by HelenBelova17** [comment]
I confused, I have installed Nextcloud 17.0.2, ONLYOFFICE Document Server 5.5.3, ONLYOFFICE connector 4.3.0 and can't reproduce the issue. Is the issue occur only in Firefox browser? Try do this in another brouser or in incognito. Also clear browser cach.

**Comment by gorsing** [comment]
The analysis showed that we have a very large portion of individual changes for integration with internal services. Perhaps somewhere the affectite creates this problem. A clean install of NC17 and NC18 showed no problem. We will megrate and catch the bug. Thank you for your time.

**Comment by gorsing** [comment]
-
