### ISSUE TITLE
Talk integration: open files in chat that already exists in nextcloud files

### ISSUE THREAD

**Issue by markuman** [ONLYOFFICE/onlyoffice-nextcloud#335]
In Nextcloud Talk you can upload office documents and onlyoffice opens in the conversation.  
But you cannot open files that already exists in Nextcloud files. So you have to download the file und re-upload it in talk to have it in the conversation. That's a bit annoying.

**Comment by HelenBelova17** [comment]
Hello @**markuman**,

please specify some additional information:

1. Currently installed version of the Document Server;
2. Version of the ONLYOFFICE integration app for Nextcloud;
3. Version of Nextcloud;
4. Could you please make a video or a .gif of the issue?

**Comment by markuman** [comment]
Hello @HelenBelova17 

> 1.  Currently installed version of the Document Server;

5.4.2.46


> 2. Version of the ONLYOFFICE integration app for Nextcloud;

4.3.0

> 3. Version of Nextcloud;

19.0.1

> 4. Could you please make a video or a .gif of the issue?

I need to download and re-upload the document. It would be better if you can open linked documents inside the conversation.



![talk2](https://user-images.githubusercontent.com/3920157/91081078-da224680-e646-11ea-916e-78c313181fa2.gif)

**Comment by markuman** [comment]
Ok, in the meantime, I've figured out that you need to "share" a document with a conversation. So no down- and re-upload is necessary.
