### ISSUE TITLE
Read-only document changed by remote user despite read-only access

### ISSUE THREAD

**Issue by Niklas-Nitrokey** [ONLYOFFICE/onlyoffice-nextcloud#338]
Hello, 
On our Nextcloud 19 is OnlyOffice app installed. When a remote user access a ODS file through a read-only link, the ODS file gets modified. Only the formatting of the data has changed. For example the time values became fractional values. This must not happen because the link is a read-only link.

![remoteuser](https://user-images.githubusercontent.com/64582081/91036392-8d6b4b00-e607-11ea-952e-74b23c2c73bd.png)

**Comment by HelenBelova17** [comment]
Hello @**Niklas-Nitrokey**,
please specify some additional information:
1. Currently installed version of the Document Server;
2. Version of the ONLYOFFICE integration app for Nextcloud;
3. Could you please make a video or a .gif of the issue?

**Comment by Niklas-Nitrokey** [comment]
Hello,
1. Community Document Server 0.1.7
2. Onlyoffice 4.3.0
3. After more testing I think it is not caused by someone accessing the file over an anonymous read-only link. I can reproduce the issue like this:

First I change the .ods- file in LibreOffice on my desktop, then i save it.

![before](https://user-images.githubusercontent.com/64582081/91435175-3ca55d80-e866-11ea-9d22-75ad4ac20adb.png)
(It looks that way in OO aswell)

After 10-60 minutes i see in the change log "changed by remote user".

![changelog](https://user-images.githubusercontent.com/64582081/91435205-45962f00-e866-11ea-86fe-81dfb0f1c746.png)

When i check the file it looks like that.

![after](https://user-images.githubusercontent.com/64582081/91435248-547ce180-e866-11ea-81b7-7894aafcd673.png)

**Comment by ShockwaveNN** [comment]
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate [GitHub repository](https://github.com/nextcloud/documentserver_community). 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).
