### ISSUE TITLE
Proxy setting from nextcloud not used

### ISSUE THREAD

**Issue by joakimberglund** [ONLYOFFICE/onlyoffice-nextcloud#34]
Background:
Mandatory outgoing proxy from nextcloud.

Ive been trying to setup the nextcloud -> onlyoffice connection and Ive run into the problem that the proxy config from nextcloud isn't used.
Ive verified with curl using HTTPS_PROXY and then everything works great! So the connection through the works as it should.

From config.php in nextcloud
```
/**
 * The URL of your proxy server, for example ``proxy.example.com:8081``.
 *
 * Defaults to ``''`` (empty string)
 */
'proxy' => 'proxy.foo.bar:8080',
```

Now if that setting is used or it's a local advanced setting doesn't matter.

Now I might have missunderstood the functionallity of that parameter but I still have the need of beeing able to specify a outgoing proxy.

**Comment by joakimberglund** [comment]
Adding the following in lib/documentservice.php fixed the issue for me.

In function request:
```
$opts["http"]["proxy"] = "tcp://proxy.foo.bar:8080";
$opts["http"]["request_fulluri"] = True;
```
Ugly...

**Comment by owncloud-lumineau** [comment]
+1
I have the same problem. Hope this enhancement will be included soon.

**Comment by LinneyS** [comment]
799e24a418e16622af349b4d5aa7a00d32ccf1cf must fix this
