### ISSUE TITLE
Layout gets broken with v.5.0.0

### ISSUE THREAD

**Issue by markuman** [ONLYOFFICE/onlyoffice-nextcloud#350]
When open documents, the onlyoffice header is not visible anymore and on the footer are still files from nextcloud visible.

![o500](https://user-images.githubusercontent.com/3920157/92305473-1b402200-ef88-11ea-9ba6-0fb1665ac9b2.png)

That happen both, in firefox and also in chromium - even when the browser cache is cleared.  

It happen not, when the document to open is in one folder with only 1-2 other files.

**Comment by markuman** [comment]
![dafuq](https://user-images.githubusercontent.com/3920157/92306615-c0f78f00-ef90-11ea-941f-88a71aece977.gif)

**Comment by markuman** [comment]
The stange thing is, when I hit "back" in the browser, the layout will be fixed.  
And again, this happen with firefox and also with chromium since update to onlyoffice 5.0.0 with document server 5.6.1.6 on nextcloud 19.0.2

**Comment by rasos** [comment]
Also reported here https://github.com/nextcloud/documentserver_community/issues/100#issuecomment-687649379

**Comment by raneon** [comment]
I have the same issue (but with the community document server 0.1.7). I didn't expect that the upgrade would break opening normal documents in onlyoffice. When I press the back button in Firefox, the for 2 seconds I can see the correct rendering of onlyoffice but then nextcloud will just reload the page to the files list.

**Comment by mvvvmd** [comment]
I've applied the fix manually, works on our NC instance. Users do need to clear their browser cache.

**Comment by sysnotbccrc** [comment]
Have the same issue in all browsers.
Components:
Onlyoffice Document server 5.6.2 Community edition (separate server)
Nextcloud 19.0.2 & PHP 7.4.9
After update OO plugin from 4.3.0 to 5.0.0 layout is broken in some(!) Excel files. 
It shows half of the content of opened file without toolbars, menus and top content but with the list of other files in folder.
Scrolling to see menus and toolbars is not working.

Manually rolled back to 4.3.0 by unpacking downloaded 4.3.0 tar.gz and replacing onlyoffice folder in .\apps\ then rebuilding list of apps as Nextcloud asked.

**Comment by sysnotbccrc** [comment]
Applied fix works. Be careful with syntax when edit main.js, TAB is not working but SPACE is.

**Comment by szaimen** [comment]
I've applied that fix, too.
On desktop it works now but on mobile it looks still a bit off (also after clearing the cache)
![20200909_012002](https://user-images.githubusercontent.com/42591237/92536742-beb85d80-f23a-11ea-8813-b10c8dabbe1d.png)

**Comment by tomtomas99911** [comment]
I can confirm this bug, unfortunately bug fix does not worked for us. Problem still persist. Temporarily solution is to set up Collabora to open files in new tab, in new tab everything works OK.

**Comment by markuman** [comment]
@tomtomas99911 have you cleared you browser cache or try it in a privat tab (because it is cache-less)?

**Comment by tomtomas99911** [comment]
Yes I tried both, but with no result. Is there any chance to fix this without need a cleaning cache?

**Comment by Bolli84** [comment]
Fix works fine for me.

**Comment by 4001982248998** [comment]
Installing the Fix and cleaning the local cache works for me, too.

**Comment by CyberneticCody** [comment]
I can also confirm that applying that fix manually works to resolve the issue :)

**Comment by LinneyS** [comment]
Hi all!
Try v6.0.0
