### ISSUE TITLE
Images from storage cannot be loaded in 5.0.0

### ISSUE THREAD

**Issue by Bolli84** [ONLYOFFICE/onlyoffice-nextcloud#351]
Since the 5.0.0. update yesterday, it is not possible to load images from the nextcloud storage. 
Nextcloud 19.0.2
documentserver 1.7.0
Onlyoffice 5.0.0

Expected behaviour:
Clicking the "Image from storgae" button shoulkd open the select-file-dialog from nextcloud.

Actual behaviour:
Clicking on the button, nothing happens.

**Comment by Bolli84** [comment]
@LinneyS the proposed fix was already included in the release.

However, the fix does not work and the "insert from storage"-button does not result in anything. (the OCA.filepicker.dialog does not open)

**Comment by LinneyS** [comment]
685917825d77a5e22748af4e39b374c04090ebdb  not released yet

**Comment by LinneyS** [comment]
Hi all!
Try v6.0.0

**Comment by Bolli84** [comment]
@LinneyS Works as expected!
