### ISSUE TITLE
Closing a word document with 'X' in top bar, does not close the Onlyoffice view

### ISSUE THREAD

**Issue by erikfdev** [ONLYOFFICE/onlyoffice-nextcloud#353]
When a Word document is opened in the Nextcloud Onlyoffice app, clicking the X in the topbar of the browserpage (next to the sharing button of Nextcloud) does not close the document view. Only the Files lefthandside sidebar appears, but not the contents of the folder in which the document was opened.

Nextcloud 18.0.8
Onlyoffice app 5.0.0

Browser: Firefox 80.0.1 as well as Chrome 84.

**Comment by HelenBelova17** [comment]
Hello @**erikfdev**,
please specify some additional information:
1. Currently installed version of the Document Server;
2. Could you please make a video or a .gif of the issue?

**Comment by erikfdev** [comment]
Community Document Server 0.1.7

Video attached illustrating the problem.
![onlyoffice-bug](https://user-images.githubusercontent.com/51967308/92458771-22ed0a00-f1c6-11ea-8306-d82aed133299.gif)

**Comment by FutureTecSystems** [comment]
Got the exact same issue. Additionally if you create a new document online, it is empty when synced through the client.

Nextcloud 19.0.2
Community Document Server 0.1.7

Issue appeared after an update of the ONLYOFFICE connector from 4.3.0 to 5.0.0

**Comment by HelenBelova17** [comment]
@**erikfdev**, @**FutureTecSystems** 
please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).

**Comment by FutureTecSystems** [comment]
Maybe we were not clear enough....the issue appeared after an update of this plugin.

![Unbenannt](https://user-images.githubusercontent.com/26169809/92464580-a3633900-f1cd-11ea-8d69-8da0791c1072.PNG)

**Comment by mkriegl** [comment]
I got the same issue using a Tablet. In addition the document does not open correctly. I see a small part of the document on top and the list of files remain below. 
The effect started after updating the community document server plugin

NC 19.0.2
DS 0.1.7

**Comment by battosai30** [comment]
> I got the same issue using a Tablet. In addition the document does not open correctly. I see a small part of the document on top and the list of files remain below.
> The effect started after updating the community document server plugin
> 
> NC 19.0.2
> DS 0.1.7

Exactly the same after update to 5.0.0

**Comment by Lozrus** [comment]
I'm seeing exactly this issue on two sites. One of which is using the OnlyOffice document server.
Server 1: NC19.02 with Community Document Server 0.1.7
Server 2: NC17.09 with OnlyOffice document server 5.4.2.46 installed via docker

Both exhibit the same unexpected behaviour as shown in the video by erikfdev above since the 5.0.0 OnlyOffice app update.
The issue appears related to the app, rather than document server.

**Comment by dhrenek** [comment]
Same issue, clicking the X doesnt close the opened document.

Another thing, when i select version control, the message 'Opening Document' appears and the wheel keeps spinning. Nothing can be done from this point except clicking on all files which closes the document and sends me back to the file overview.

**Comment by Endimione** [comment]
Hello, i have the same problem with fresh installation of nextcloud 19.0.3 Community document server and Onlyoffice connector

**Comment by dhrenek** [comment]
>     1. Download release 4.3.0 onlyoffice https://github.com/ONLYOFFICE/onlyoffice-nextcloud/releases/download/v4.3.0/onlyoffice.tar.gz
>     2. Untar and owerwrite ../nextcloud/apps/onlyoffice
>     3. Restart php-fpm&nginx
>     4. goto main page nextcloud and allow update
>     5. Check ... Profit!!!

Made a clone of the NC instance but the trick described as above didn't fix anything. Didn't break it but no "Profit!!!"

**Comment by bluesky-ca** [comment]
I run into the same issue with 18.0.8 - the problem is with 5.0.0.  My temporary fix till this issue is resolved was:
Settings -> ONLYOFFICE -> Open file in the same tab (unchecked)

Related in a way, Nextcloud really really needs a way to be able to revert apps, as the settings are in DB not just files on disk.  I have been running NC for 3 years and have seem my share of bad apps - mistakes happen and there should be a way to go back !!!

**Comment by battosai30** [comment]
> I run into the same issue with 18.0.8 - the problem is with 5.0.0. My temporary fix till this issue is resolved was:
> Settings -> ONLYOFFICE -> Open file in the same tab (unchecked)
> 
> Related in a way, Nextcloud really really needs a way to be able to revert apps, as the settings are in DB not just files on disk. I have been running NC for 3 years and have seen my share of bad apps - mistakes happen and there should be a way to go back !!!

Thanks !! I confirm it's a good workaround ;)

**Comment by FutureTecSystems** [comment]
> Related in a way, Nextcloud really really needs a way to be able to revert apps, as the settings are in DB not just files on disk. I have been running NC for 3 years and have seen my share of bad apps - mistakes happen and there should be a way to go back !!!

I definately agree on this....it's not bearable to wait for another fix if something this important is broken. Customers loose documents and you cannot provide a quick fix by switching back to a working version.

**Comment by bluesky-ca** [comment]
If not a full revert setup, I think in the least if there was an occ command that allowed to install from a tar file, one could do a manual uninstall, and re-install an older version.  As reported above it is possible to put old files in place and use the interface to 'update' after receiving an error message from Nextcloud as things don't match in the DB.  

I think it would be a lot cleaner and allow easier testing with:
occ app:install app.tar.gz
I do understand the limitations of doing this between the major releases that may change the API, so I don't want to suggest this is a trivial problem, but it is a solved issue for yum, apt and many other package management systems.

**Comment by Lozrus** [comment]
@bluesky-ca it makes sense to be concerned that newer database settings may have unexpected results then accessed by an older version of the app. In this case though there don't seem to be significant changes between 4.3.0 and 5.0.0, and  I was able to revert to 4.3.0 on two sites, simply by disabling the app (I used the web UI), then extracting the release package to `nextcloud/apps/onlyoffice`.
A simple page refresh on the web interface was enough to show that my Nextcloud server recognised the 4.3.0 version, and re-enabling it got it all working again. For now, the issue is gone and I'll stay with 4.3.0 until it is resolved.

**Comment by LinneyS** [comment]
Hi all!
Try v6.0.0

**Comment by Lozrus** [comment]
@LinneyS That's quite a version number bump :-), have you changed your release versioning scheme?

Anyway, thank you for the update, I've updated my less critical server which runs NC19 and their Community Document Server. On first test it seems to fix the issue nicely, thanks!

My more mission critical server which runs NC17 and the full OnlyOffice document server I'll update later (outside of it's main usage hours), I'm sure it will be fine.

**Comment by battosai30** [comment]
This bug is corrected for me with v6.0.0 👍
