### ISSUE TITLE
Restore (via Download) from the Nextcloud version context (GUI) of a word (docx) document will fail/hang

### ISSUE THREAD

**Issue by Githopp192** [ONLYOFFICE/onlyoffice-nextcloud#357]
### Steps to reproduce
Happens every time, when trying to restore a word document via Nextcloud versions control.
Direct Restore (not download) will be successful.

Direct open of an Office Document via Browser (word,excel..) without going over the "versions" context, will be opened via OnlyOffice without any issues.

### Expected behavior

OnlyOffice will show Word-Document to be restored in read-only mode, and then the user is able to download / restore the file via Download button (right corner of the Nextcloud GUI)

### Actual behavior
Restore (via Download) from the Nextcloud version context of a word (docx) document, the document will open in OnlyOffice, but the whole process will hang.
Happens every time, when trying to restore a word document via Nextcloud versions control.
Direct Restore (not download) will be successful.

Tried with different browsers - same effect (Opera/Mozilla/Edge/Chrome)

## Server configuration detail

**Operating system:** Linux 4.18.0-193.14.2.el8_2.x86_64 #1 SMP Sun Jul 26 03:54:29 UTC 2020 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 10.3.17

**PHP version:** 

7.4.10
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, intl, json, ldap, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_sqlite, xmlreader, apcu, igbinary, imagick, msgpack, smbclient, zip, memcached, redis, libsmbclient, Zend OPcache

**Nextcloud version:** 19.0.2 - 19.0.2.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** origin Nextcloud, Upgrade from NC 18.0.8

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.5.0
 - activity: 2.12.0
 - analytics: 2.4.1
 - announcementcenter: 3.8.1
 - apporder: 0.11.0
 - audioplayer: 2.11.2
 - audioplayer_editor: 0.2.2
 - audioplayer_sonos: 1.1.1
 - bookmarks: 3.3.4
 - browser_warning: 1.0.0
 - bruteforcesettings: 2.0.1
 - calendar: 2.0.4
 - circles: 0.19.5
 - cloud_federation_api: 1.2.0
 - comments: 1.9.0
 - contacts: 3.3.0
 - contactsinteraction: 1.0.0
 - cookbook: 0.7.6
 - cospend: 1.0.5
 - data_request: 1.6.0
 - dav: 1.15.0
 - deck: 1.0.5
 - documentserver_community: 0.1.7
 - drawio: 0.9.7
 - event_update_notification: 1.0.2
 - extract: 1.2.4
 - federatedfilesharing: 1.9.0
 - federation: 1.9.0
 - files: 1.14.0
 - files_antivirus: 3.0.0
 - files_downloadactivity: 1.8.0
 - files_mindmap: 0.0.22
 - files_pdfviewer: 1.8.0
 - files_photospheres: 1.19.1
 - files_rightclick: 0.16.0
 - files_sharing: 1.11.0
 - files_trashbin: 1.9.0
 - files_versions: 1.12.0
 - files_videoplayer: 1.8.0
 - firstrunwizard: 2.8.0
 - flowupload: 1.0.0
 - forms: 2.0.4
 - groupfolders: 7.0.0
 - issuetemplate: 0.7.0
 - logreader: 2.4.0
 - lookup_server_connector: 1.7.0
 - maps: 0.1.6
 - nextcloud_announcements: 1.8.0
 - notes: 3.6.4
 - notifications: 2.7.0
 - oauth2: 1.7.0
 - onlyoffice: 5.0.0
 - password_policy: 1.9.1
 - photos: 1.1.0
 - polls: 1.4.3
 - privacy: 1.3.0
 - provisioning_api: 1.9.0
 - quicknotes: 0.6.0
 - quota_warning: 1.8.0
 - rainloop: 7.0.2
 - ransomware_protection: 1.7.0
 - recommendations: 0.7.0
 - serverinfo: 1.9.0
 - settings: 1.1.0
 - sharebymail: 1.9.0
 - socialsharing_diaspora: 2.1.0
 - socialsharing_email: 2.1.0
 - socialsharing_facebook: 2.1.0
 - socialsharing_twitter: 2.1.0
 - spreed: 9.0.3
 - support: 1.2.1
 - suspicious_login: 3.2.1
 - systemtags: 1.9.0
 - tasks: 0.13.3
 - terms_of_service: 1.5.1
 - text: 3.0.1
 - theming: 1.10.0
 - timemanager: 0.1.4
 - twofactor_backupcodes: 1.8.0
 - twofactor_totp: 5.0.0
 - updatenotification: 1.9.0
 - video_converter: 0.1.4
 - viewer: 1.3.0
 - workflow_pdf_converter: 1.4.0
 - workflow_script: 1.4.0
 - workflowengine: 2.1.0
Disabled:
 - admin_audit
 - breezedark
 - dashboard
 - dicomviewer
 - drop_account
 - encryption
 - external
 - files_accesscontrol
 - files_external
 - files_fulltextsearch
 - files_markdown
 - fulltextsearch
 - fulltextsearch_elasticsearch
 - impersonate
 - joplin
 - jsloader
 - passman
 - passwords
 - radio
 - registration
 - richdocuments
 - sharerenamer
 - socialsharing_googleplus
 - survey_client
 - user_ldap
 - weather

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "memcache.local": "\\OC\\Memcache\\APCu",
    "filelocking.enabled": true,
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "dbindex": 0,
        "timeout": 1.5,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "REMOVED ",
        "REMOVED",
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/REMOVED ",
    "htaccess.RewriteBase": "\/",
    "overwriteprotocol": "https",
    "dbtype": "mysql",
    "version": "19.0.2.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 0,
    "updater.release.channel": "stable",
    "auth.bruteforce.protection.enabled": true,
    "check_for_working_htaccess": true,
    "data-fingerprint": "aREMOVED 1a",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "REMOVED ",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "REMOVED ",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "REMOVED ",
    "session_lifetime": 1200,
    "session_keepalive": false,
    "logtimezone": "EREMOVED ",
    "logfile": "\/media\/log\/nextcloud.log",
    "knowledgebaseenabled": false,
    "log_rotate_size": REMOVED ,
    "mail_sendmailmode": "REMOVED "
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36 Edg/84.0.522.63

**Operating system:** centos-release-8.2-2.2004.0.1.el8.x86_64

## Logs

<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

do not know .. if these error messages has got something to do with it !? -->

Fatal | webdav | OCA\DAV\Connector\Sabre\Exception\InvalidPath: Der Dateiname enthält mindestens ein ungültiges Zeichen/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 81:OCA\DAV\Connector\Sabre\ObjectTree->getNodeForPath()/var/www/html/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:Sabre\DAV\CorePlugin->httpGet()/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 474:Sabre\DAV\Server->emit()/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 262:Sabre\DAV\Server->invokeMethod()/var/www/html/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:Sabre\DAV\CorePlugin->httpHead()/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 474:Sabre\DAV\Server->emit()/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 251:Sabre\DAV\Server->invokeMethod()/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 319:Sabre\DAV\Server->start()/var/www/html/nextcloud/apps/dav/appinfo/v1/webdav.php - line 82:Sabre\DAV\Server->exec()/var/www/html/nextcloud/remote.php - line 167:require_once("/var/www/ht ... p")
-- | -- | --

```

```
</details>

<details><summary>Browser log</summary>

</details>

Screenshots -->

![ScreenShot3992](https://user-images.githubusercontent.com/32612067/92734497-e1509080-f378-11ea-81c1-3f9d2e131508.jpg)
![ScreenShot3993](https://user-images.githubusercontent.com/32612067/92734530-e9a8cb80-f378-11ea-8c3f-6db09994fd89.jpg)
![ScreenShot3994](https://user-images.githubusercontent.com/32612067/92734536-ec0b2580-f378-11ea-9d4b-d871bdf6ccef.jpg)
![InkedScreenShot3995_LI](https://user-images.githubusercontent.com/32612067/92734549-ee6d7f80-f378-11ea-80bd-91d3d66c5219.jpg)

**Comment by HelenBelova17** [comment]
@**Githopp192**,
please specify some additional information:

1. Currently installed version of the ONLYOFFICE Document Server;
2. Update the ONLYOFFICE integration app to 6.0.0 and specify if the issue persists;
3. Is the issue occures with all DOCX files?

**Comment by Githopp192** [comment]
HelenBelova17

1. installed version of the ONLYOFFICE Document Server: **6.0.0**
2. already on **[6.0.0]
3. Just checked again .. issue persists (with all DOCX files - i tried different ones)

![ScreenShot848](https://user-images.githubusercontent.com/32612067/94827632-f749f200-0408-11eb-92e8-aa6168260bc4.jpg)

**Comment by HelenBelova17** [comment]
@**Githopp192**, 
As far as I know, the latest version of ONLYOFFICE Document Server is 5.6. Where did you get version 6.0 from?

**Comment by Githopp192** [comment]
as you may know .. OnlyOffice is now a fully intergrated App, working together with Nextcloud .. 
Indeed is the "Community Version of OO" .. there you can see/check the version, which is available (it is 6.0.0) on Github for "Nextcloud Hub" 

https://github.com/ONLYOFFICE/onlyoffice-nextcloud

**Comment by Githopp192** [comment]
just save the OO setting into the Nextcloud Gui .. shows this Version: 

![ScreenShot849](https://user-images.githubusercontent.com/32612067/94852083-a7c7ee00-0429-11eb-9066-2a3d1dd2cd09.jpg)

So .. i think the Version 6.0.0 is the Nextcloud Version .. and the OO-Version inside is 5.4

**Comment by LinneyS** [comment]
6.0.0 - [Nextcloud ONLYOFFICE integration app](https://github.com/ONLYOFFICE/onlyoffice-nextcloud)
5.6.5 - [ONLYOFFICE Document Server](https://github.com/ONLYOFFICE/DocumentServer)
5.4 - Community Document Server

Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).

**Comment by LinneyS** [comment]
The analysis showed that Community Document Server does not work with Version History

**Comment by Githopp192** [comment]
Thanks LinneyS for your statement.

BTW .. i did open the request through the official Nextcloud Apps Link -->

https://apps.nextcloud.com/apps/onlyoffice

![ScreenShot850](https://user-images.githubusercontent.com/32612067/94910119-89530880-04a4-11eb-88da-a0c65d19b9bd.jpg)

**Comment by LinneyS** [comment]
You should have done it here
https://apps.nextcloud.com/apps/documentserver_community
