### ISSUE TITLE
onlyoffice editing toolbar hidden by nextcloud bar

### ISSUE THREAD

**Issue by fabnext77** [ONLYOFFICE/onlyoffice-nextcloud#359]
Steps to reproduce
1.Version nextcloud 19.0.3
2. Only office 5.0.0.
3. Docker

Expected behaviour
Editing file online (doc, xls) and use the toolbar to edit characters, size, etc.

Actual behaviour
Onlyoffice toolbar is covered/hidden under nextcloud toolbar

**Comment by CyberneticCody** [comment]
This might be a duplicate of #350?

**Comment by fabnext77** [comment]
Yes, it is, I applied the patch and now working fine.
thank you
