### ISSUE TITLE
Share a link to an editable OO doc

### ISSUE THREAD

**Issue by dosch** [ONLYOFFICE/onlyoffice-nextcloud#364]
can it be made more easy to share the link to the editable document?
Now the flow is:
1. Create a new doc in NC
2. Create a public link
3. Open the public link in another browser
4. Click the button to open the doc in Only Office.

![4583716f7380b0c02f7567a5e4d374987a361797](https://user-images.githubusercontent.com/5372610/93634656-3fbce500-f9f1-11ea-99d9-ab793715570f.png)

5. Copy thát link and send it around.

Ideally the link created in step 2. is already a link to send around and brings people directly to the edit mode of the doc.

**Comment by LinneyS** [comment]
We provide a button to open the file with ONLYOFFICE.
Some applications open the file automatically and a conflict occurs.
pdf: #365
odt/docx: nextcloud/richdocuments#361
txt with the `text` app

**Comment by vouape** [comment]
I would love to have a share button in the document window. 
I've been seen this button in some vídeos on internet, on the right top, near the sandwich menu button.
But here I don't have any share button at all. It seens like it is hidden for me.
Is someone able to show me where is the share button? Or how to enable it?

**Comment by LinneyS** [comment]
@vouape 
![image](https://user-images.githubusercontent.com/8580527/97668681-92c79480-1a93-11eb-956e-a0c07b0af0f4.png)

**Comment by vouape** [comment]
Thank you LinneyS
The problem is that this button doesn't show for me. Look
![image](https://user-images.githubusercontent.com/13707181/97710610-b8a46780-1a9a-11eb-898d-45da965075e3.png)

I'm using Nextcloud online version 19.0.4 and Onlyoffice version 6.1.0.

Is there any configuration for showing this button?	
Thanks

**Comment by LinneyS** [comment]
@vouape 
This is available when you open the editor in the same tab (enabled in the settings)

**Comment by vouape** [comment]
Oh Yes! You're right.
Now it works for me.
Thank you so much @LinneyS
