### ISSUE TITLE
PDF from public links doesn't open in onlyoffice. 

### ISSUE THREAD

**Issue by mastipgithub** [ONLYOFFICE/onlyoffice-nextcloud#365]
Hello, 
Nextcloud version 19.03, onlyoffice 6.0

1. Pdf files from public links does not open in onlyoffice plugin, public links with files like docx, xlsx opens correctly, also with watermarks. Pdfs opens in pdf viewer from public links.
I tried turn off pdf viewer, but without pdf viewer, all files does not open in onlyoffice plugin and there is only option to save file.
In addition the same think is with txt files. I didn't check all formats, only pdf, docx, xlsx, txt.

**Comment by mastipgithub** [comment]
In addition, the same thing is with txt files.

**Comment by HelenBelova17** [comment]
Hello @**mastipgithub**, please specify version of the ONLYOFFICE Document Server.

**Comment by mastipgithub** [comment]
Version 5.6.2 Community Edition

**Comment by LinneyS** [comment]
If the pdf viewer app is disabled, then the `Open in ONLYOFFICE` button is displayed
![Capture](https://user-images.githubusercontent.com/8580527/94411229-00289280-0181-11eb-8c7e-d980ffe41acb.PNG)

**Comment by mastipgithub** [comment]
When I disable pdf viewer app I have other problem. "ONLYOFFICE is not reachable. Contact your Administrator" 
There are no logs. Settings in Only office interation app are fine. Onlyoffice is somehow connected with pdf viewer app in my nextcloud configuration. When pdf viewer is on onlyoffice works with nextcloud like in described in 1st post

**Comment by mastipgithub** [comment]
Ok, You have absolutely right. So pdf viewer should be always disabled when only office integration app is on?

**Comment by LinneyS** [comment]
I think you can ask the `pdf viewer` developers not to open the file automatically, but to give the user the choice of the application.

**Comment by kohlrabi-chan** [comment]
Hi! I read this thread and now disabled PDF Viewer but ONLYOFFICE still can´t open PDF files.
ONLYOFFICE 6.3.0
Community Document Server 0.1.9

Don´t know where to see the Nextcloud version…
Would be cool, if anybody can help me. Thank you!

**Comment by LinneyS** [comment]
@kohlrabi-chan 
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).

**Comment by kohlrabi-chan** [comment]
Hi LinneyS! Thank you for your answer!
It is working now, thank you so much!
Best
Aiko

**Comment by LinneyS** [comment]
https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/365#issuecomment-699968491
