### ISSUE TITLE
Log spamming with "file has no owner" messages

### ISSUE THREAD

**Issue by szaimen** [ONLYOFFICE/onlyoffice-nextcloud#366]
Hey, I think since Onlyoffice-connector 5.0 or 6.0 my log gets spammes with such reports:
Is there a way to suppress those messages? the log isn't readable with this anymore.

![image](https://user-images.githubusercontent.com/42591237/93716066-8f282000-fb6d-11ea-9038-d805c29d9d62.png)

Since it is most likely important: I am using NC 19.0.3 with Onlyoffice-connector 6.0, a dedicated Onlyoffice-documentserver in docker and local external storage mounted via the files_external app for my user in Nextcloud.
If you need more info, please tell!

**Comment by rgl1234** [comment]
same situation here.....

**Comment by cyorps** [comment]
Same situation here. I have the same configuration like szaimen except the Version of OO-Connector. This is 6.0.2

**Comment by ttjaden** [comment]
We have also the problem and are practically not able to use OnlyOffice anymore regarding this bug. When two people open the same file, they don't see each other and all the changes from one person will be lost.

We are using NC 19.0.3 with Onlyoffice 6.0.2 Connector and a dedicated Onlyoffice-documentserver with docker.
