### ISSUE TITLE
Onlyoffice Mail Merge (Serienbrief) not working

### ISSUE THREAD

**Issue by johkon** [ONLYOFFICE/onlyoffice-nextcloud#367]
Hi there,

i have installed nextcloud through the plesk extension and everything works fine.
Onlyoffice and the Community Document Server are working and uptodate.

I’m trying to use mail merge between a spreadsheet and a textdocument, but always get an errormessage when i try to import the xlsx-file: "Fehler beim Laden" (error at loading).
I have created a spreadsheet in the same folder, according to this helppage: https://helpcenter.onlyoffice.com/ONLYOFFICE-Editors/ONLYOFFICE-Document-Editor/UsageInstructions/UseMailMerge.aspx 1

Has anyone else had this error and knows a fix? The error-message is so unspecific, i have no idea what could be the cause.
Thanks for any advice.

**Comment by johkon** [comment]
maybe this helps:
whenever i try to import a spreadsheet, i get this error in my log:

`
OCP\Files\NotFoundException: /appdata_oclqtq2nk8iq/documentserver_community/doc_1698674802/TextDokument.json
0. /var/www/vhosts/URL.com/httpdocs/cloud/lib/private/Files/Node/Folder.php - line 138:
OC\Files\Node\Root->get()

1. /var/www/vhosts/URL.com/httpdocs/cloud/apps/documentserver_community/lib/Document/DocumentStore.php - line 121:
OC\Files\Node\Folder->get()

2. /var/www/vhosts/URL.com/httpdocs/cloud/apps/documentserver_community/lib/Controller/DocumentController.php - line 131:
OCA\DocumentServer\Document\DocumentStore->openDocumentFile()

3. /var/www/vhosts/URL.com/httpdocs/cloud/lib/private/AppFramework/Http/Dispatcher.php - line 170:
OCA\DocumentServer\Controller\DocumentController->documentFile()

4. /var/www/vhosts/URL.com/httpdocs/cloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:
OC\AppFramework\Http\Dispatcher->executeController()

5. /var/www/vhosts/URL.com/httpdocs/cloud/lib/private/AppFramework/App.php - line 137:
OC\AppFramework\Http\Dispatcher->dispatch()

6. /var/www/vhosts/URL.com/httpdocs/cloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:
OC\AppFramework\App::main()

7. <<closure>>
OC\AppFramework\Routing\RouteActionHandler->__invoke()

8. /var/www/vhosts/URL.com/httpdocs/cloud/lib/private/Route/Router.php - line 297:
call_user_func()

9. /var/www/vhosts/URL.com/httpdocs/cloud/lib/base.php - line 1012:
OC\Route\Router->match()

10. /var/www/vhosts/URL.com/httpdocs/cloud/index.php - line 37:
OC::handleRequest()
`

**Comment by HelenBelova17** [comment]
@**johkon** ,
seems you use Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).

**Comment by johkon** [comment]
ok, thank you
