### ISSUE TITLE
editing a document does not change the modification date

### ISSUE THREAD

**Issue by ferdiga** [ONLYOFFICE/onlyoffice-nextcloud#370]
open a document and edit  - nextcloud does not show the modification date

**Comment by HelenBelova17** [comment]
@**ferdiga**,
please specify some additional information:
1. Currently installed version of the ONLYOFFICE Document Server;
2. Version of the ONLYOFFICE integration app for Nextcloud;
3. Version of Nextcloud.

**Comment by ferdiga** [comment]
re "I think - not sure yet - that I have to hit the save button, although autosave is on and "keep intermediate versions .." is on.
closing the tab does not save."

if autosave is on, there is no save button - and the document is not saved to nextcloud.
apparently the save button was in the browser cache.

**Comment by HelenBelova17** [comment]
@**ferdiga**,
please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).
