### ISSUE TITLE
Don't register all mimetypes to viewer app

### ISSUE THREAD

**Issue by SystemKeeper** [ONLYOFFICE/onlyoffice-nextcloud#372]
Currently OnlyOffice registeres itself for all supported formats in the viewer app, see:
https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/dc5082828f943fb0b6cb274447680dbc07451eec/js/viewer.js#L92-L102

Under settings it's possible to select for which filetypes OnlyOffice is the default application. Therefore I'd expect only the filetypes selected there to be registered in the viewer app.

For example:
![image](https://user-images.githubusercontent.com/1580193/94613831-7f16eb80-02a5-11eb-855a-9316ec195f40.png)

OnlyOffice ist not selected as the default application for pdfs. Still when opening a pdf (for example in Nextcloud Talk) OnlyOffice is loading the pdf. 

I guess this could be achived by something like this:

``` javascript
var mimes = $.map(OCA.Onlyoffice.setting.formats, function(format) {
  if (format.def) {
    return format.mime;
  }
});
```

If registering all possible mimetypes is intended, it would be great to have an option in settings to "Only register mimetypes to viewer app, which are selected as default"

**Comment by SystemKeeper** [comment]
Would you be open to a PR for this one @LinneyS ? If yes, would it be ok to do something like explained in the first post or would you rather have a checkbox "Only register mimetypes to viewer app, which are selected as default"?

**Comment by szaimen** [comment]
@LinneyS any update here when this will be fixed?
