### ISSUE TITLE
3 Problems from OnlyOffice

### ISSUE THREAD

**Issue by derdavin** [ONLYOFFICE/onlyoffice-nextcloud#377]
[onlyoffice] Error: GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: self signed certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) at <<closure>>

 0. /snap/nextcloud/23496/htdocs/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 155
    GuzzleHttp\Handler\CurlFactory::createRejection(GuzzleHttp\Handl ... l}, {errno: 60,error ... "})
 1. /snap/nextcloud/23496/htdocs/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 105
    GuzzleHttp\Handler\CurlFactory::finishError(GuzzleHttp\Handler\CurlHandler {}, GuzzleHttp\Handl ... l}, GuzzleHttp\Handler\CurlFactory {})
 2. /snap/nextcloud/23496/htdocs/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php line 43
    GuzzleHttp\Handler\CurlFactory::finish(GuzzleHttp\Handler\CurlHandler {}, GuzzleHttp\Handl ... l}, GuzzleHttp\Handler\CurlFactory {})
 3. /snap/nextcloud/23496/htdocs/3rdparty/guzzlehttp/guzzle/src/Handler/Proxy.php line 28
    GuzzleHttp\Handler\CurlHandler->__invoke("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
 4. /snap/nextcloud/23496/htdocs/3rdparty/guzzlehttp/guzzle/src/Handler/Proxy.php line 51
    GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}("*** sensitive parameters replaced ***")
 5. /var/snap/nextcloud/23496/nextcloud/extra-apps/twofactor_gateway/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php line 37
    GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}("*** sensitive parameters replaced ***")
 6. /snap/nextcloud/23496/htdocs/3rdparty/guzzlehttp/guzzle/src/Middleware.php line 29
    GuzzleHttp\PrepareBodyMiddleware->__invoke("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
 7. /snap/nextcloud/23496/htdocs/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php line 70
    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
 8. /snap/nextcloud/23496/htdocs/3rdparty/guzzlehttp/guzzle/src/Middleware.php line 59
    GuzzleHttp\RedirectMiddleware->__invoke("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
 9. /snap/nextcloud/23496/htdocs/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php line 71
    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
10. /snap/nextcloud/23496/htdocs/3rdparty/guzzlehttp/guzzle/src/Client.php line 361
    GuzzleHttp\HandlerStack->__invoke("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
11. /snap/nextcloud/23496/htdocs/3rdparty/guzzlehttp/guzzle/src/Client.php line 163
    GuzzleHttp\Client->transfer("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
12. /snap/nextcloud/23496/htdocs/3rdparty/guzzlehttp/guzzle/src/Client.php line 183
    GuzzleHttp\Client->requestAsync("get", GuzzleHttp\Psr7\Uri {}, {verify: "/var/s ... }})
13. /snap/nextcloud/23496/htdocs/lib/private/Http/Client/Client.php line 228
    GuzzleHttp\Client->request("get", "https://dirin.i ... k", {verify: "/var/s ... e})
14. /var/snap/nextcloud/23496/nextcloud/extra-apps/onlyoffice/lib/documentservice.php line 357
    OC\Http\Client\Client->get("https://dirin.i ... k", {timeout: 60})
15. /var/snap/nextcloud/23496/nextcloud/extra-apps/onlyoffice/lib/documentservice.php line 246
    OCA\Onlyoffice\DocumentService->Request("https://dirin.i ... k")
16. /var/snap/nextcloud/23496/nextcloud/extra-apps/onlyoffice/controller/settingscontroller.php line 291
    OCA\Onlyoffice\DocumentService->HealthcheckRequest()
17. /var/snap/nextcloud/23496/nextcloud/extra-apps/onlyoffice/controller/settingscontroller.php line 166
    OCA\Onlyoffice\Controller\SettingsController->checkDocServiceUrl()
18. /snap/nextcloud/23496/htdocs/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Onlyoffice\Controller\SettingsController->SaveAddress("https://dirin.i ... /", "", "", false, "", false)
19. /snap/nextcloud/23496/htdocs/lib/private/AppFramework/Http/Dispatcher.php line 100
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Onlyoffice\C ... {}, "saveAddress")
20. /snap/nextcloud/23496/htdocs/lib/private/AppFramework/App.php line 137
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Onlyoffice\C ... {}, "saveAddress")
21. /snap/nextcloud/23496/htdocs/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("SettingsController", "saveAddress", OC\AppFramework\ ... {}, {_route: "onlyof ... "})
22. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "onlyof ... "})
23. /snap/nextcloud/23496/htdocs/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {_route: "onlyof ... "})
24. /snap/nextcloud/23496/htdocs/lib/base.php line 1012
    OC\Route\Router->match("/apps/onlyoffice/ajax/settings/address")
25. /snap/nextcloud/23496/htdocs/index.php line 37
    OC::handleRequest()

PUT /index.php/apps/onlyoffice/ajax/settings/address
from 5.183.92.62 by admin at 2020-10-07T21:48:17+00:00

other error 

[documentserver_community] Error: OCA\DocumentServer\Document\DocumentConversionException: change_code: Eq;Eq.prototype.ea=AscDFH.sYb;Eq.prototype.Oc=function(d){var a=this.Na;a.Cf.He=d.He;a.Cf.Ze=d.Ze;a.Cf.pa=d.pa;a.Cf.fh=d.fh};Eq.prototype.se=function(d){d.cb(this.Ha.He);d.Bb(this.Ha.Ze);!0===this.Ha.Ze?d.cb(this.Ha.pa):d.Ue(this.Ha.pa);d.Bb(!0===this.Ha.fh);d.cb(this.tb.He);d.Bb(this.tb.Ze);!0===this.tb.Ze?d.cb(this.tb.pa):d.Ue(this.tb.pa);d.Bb(!0===this.tb.fh)};Eq.prototype.ge=function(d){this.Ha={};this.tb={};this.Ha.He=d.jb();this.Ha.Ze=d.pb();this.Ha.pa=!0===this.Ha.Ze?d.jb():d.mg();this.Ha.fh=
change: Uncaught TypeError: Cannot set property 'He' of undefined
DoctRenderer:<result><error index="0" /></result>
namespace error : Namespace prefix wp14 on sizeRelH is not defined
rawingml/2006/main"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="margin"
                                                                               ^
namespace error : Namespace prefix wp14 on pctWidth is not defined
ain"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="margin"><wp14:pctWidth
                                                                               ^
namespace error : Namespace prefix wp14 on sizeRelV is not defined
4:pctWidth>0</wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="margin"
                                                                               ^
namespace error : Namespace prefix wp14 on pctHeight is not defined
14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="margin"><wp14:pctHeight
                                                                               ^
namespace error : Namespace prefix wp14 on sizeRelH is not defined
 name="Textfeld 15"/><wp:cNvGraphicFramePr/><wp14:sizeRelH relativeFrom="margin"
                                                                               ^
namespace error : Namespace prefix wp14 on pctWidth is not defined
 15"/><wp:cNvGraphicFramePr/><wp14:sizeRelH relativeFrom="margin"><wp14:pctWidth
                                                                               ^
 at <<closure>>

0. /var/snap/nextcloud/23496/nextcloud/extra-apps/documentserver_community/lib/DocumentConverter.php line 123
   OCA\DocumentServer\Document\ConverterBinary->run("/tmp/oc_tmp_nS4uwF-.xml", null)
1. /var/snap/nextcloud/23496/nextcloud/extra-apps/documentserver_community/lib/DocumentConverter.php line 78
   OCA\DocumentServer\DocumentConverter->runCommand(OCA\DocumentServ ... {})
2. /var/snap/nextcloud/23496/nextcloud/extra-apps/documentserver_community/lib/Document/DocumentStore.php line 155
   OCA\DocumentServer\DocumentConverter->saveChanges("*** sensitive parameter replaced ***", ["78;AgAAADEA//8 ... "], "/var/snap/nextc ... x", "docx")
3. /var/snap/nextcloud/23496/nextcloud/extra-apps/documentserver_community/lib/LocalAppData.php line 100
   OCA\DocumentServer\Document\DocumentStore->OCA\DocumentServer\Document\{closure}("*** sensitive parameters replaced ***")
4. /var/snap/nextcloud/23496/nextcloud/extra-apps/documentserver_community/lib/Document/DocumentStore.php line 175
   OCA\DocumentServer\LocalAppData->getReadWriteLocalPath(OC\Files\SimpleFS\SimpleFolder {}, Closure {})
5. /var/snap/nextcloud/23496/nextcloud/extra-apps/documentserver_community/lib/Document/SaveHandler.php line 56
   OCA\DocumentServer\Document\DocumentStore->saveChanges(2214554193, [OCA\DocumentSer ... }])
6. /var/snap/nextcloud/23496/nextcloud/extra-apps/documentserver_community/lib/BackgroundJob/Cleanup.php line 69
   OCA\DocumentServer\Document\SaveHandler->flushChanges(2214554193)
7. /snap/nextcloud/23496/htdocs/lib/public/BackgroundJob/Job.php line 80
   OCA\DocumentServer\BackgroundJob\Cleanup->run(null)
8. /snap/nextcloud/23496/htdocs/cron.php line 126
   OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2020-10-07T21:48:57+00:00

other error

[onlyoffice] Error: GuzzleHttp\Exception\ClientException: Client error: `GET https://dirin.istmein.de/index.php/apps/documentserver_community/healthcheck` resulted in a `404 Not Found` response:
<!DOCTYPE html>
<html>
<head>
<meta http-equiv=content-type content="text/html; charset=utf-8" />
<meta http-equiv="Cach (truncated...)
 at <<closure>>

 0. /snap/nextcloud/23496/htdocs/3rdparty/guzzlehttp/guzzle/src/Middleware.php line 65
    GuzzleHttp\Exception\RequestException::create(GuzzleHttp\Psr7\Request {}, "*** sensitive parameter replaced ***")
 1. /var/snap/nextcloud/23496/nextcloud/extra-apps/twofactor_gateway/vendor/guzzlehttp/promises/src/Promise.php line 203
    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
 2. /var/snap/nextcloud/23496/nextcloud/extra-apps/twofactor_gateway/vendor/guzzlehttp/promises/src/Promise.php line 156
    GuzzleHttp\Promise\Promise::callHandler(1, "*** sensitive parameter replaced ***", [GuzzleHttp\Prom ... l])
 3. /var/snap/nextcloud/23496/nextcloud/extra-apps/twofactor_gateway/vendor/guzzlehttp/promises/src/TaskQueue.php line 47
    GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}("*** sensitive parameters replaced ***")
 4. /var/snap/nextcloud/23496/nextcloud/extra-apps/twofactor_gateway/vendor/guzzlehttp/promises/src/Promise.php line 246
    GuzzleHttp\Promise\TaskQueue->run(true)
 5. /var/snap/nextcloud/23496/nextcloud/extra-apps/twofactor_gateway/vendor/guzzlehttp/promises/src/Promise.php line 223
    GuzzleHttp\Promise\Promise->invokeWaitFn()
 6. /var/snap/nextcloud/23496/nextcloud/extra-apps/twofactor_gateway/vendor/guzzlehttp/promises/src/Promise.php line 267
    GuzzleHttp\Promise\Promise->waitIfPending()
 7. /var/snap/nextcloud/23496/nextcloud/extra-apps/twofactor_gateway/vendor/guzzlehttp/promises/src/Promise.php line 225
    GuzzleHttp\Promise\Promise->invokeWaitList()
 8. /var/snap/nextcloud/23496/nextcloud/extra-apps/twofactor_gateway/vendor/guzzlehttp/promises/src/Promise.php line 62
    GuzzleHttp\Promise\Promise->waitIfPending()
 9. /snap/nextcloud/23496/htdocs/3rdparty/guzzlehttp/guzzle/src/Client.php line 183
    GuzzleHttp\Promise\Promise->wait()
10. /snap/nextcloud/23496/htdocs/lib/private/Http/Client/Client.php line 228
    GuzzleHttp\Client->request("get", "https://dirin.i ... k", {verify: false,t ... e})
11. /var/snap/nextcloud/23496/nextcloud/extra-apps/onlyoffice/lib/documentservice.php line 357
    OC\Http\Client\Client->get("https://dirin.i ... k", {verify: false,timeout: 60})
12. /var/snap/nextcloud/23496/nextcloud/extra-apps/onlyoffice/lib/documentservice.php line 246
    OCA\Onlyoffice\DocumentService->Request("https://dirin.i ... k")
13. /var/snap/nextcloud/23496/nextcloud/extra-apps/onlyoffice/controller/settingscontroller.php line 291
    OCA\Onlyoffice\DocumentService->HealthcheckRequest()
14. /var/snap/nextcloud/23496/nextcloud/extra-apps/onlyoffice/controller/settingscontroller.php line 166
    OCA\Onlyoffice\Controller\SettingsController->checkDocServiceUrl()
15. /snap/nextcloud/23496/htdocs/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Onlyoffice\Controller\SettingsController->SaveAddress("https://dirin.i ... /", "", "", true, "", false)
16. /snap/nextcloud/23496/htdocs/lib/private/AppFramework/Http/Dispatcher.php line 100
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Onlyoffice\C ... {}, "saveAddress")
17. /snap/nextcloud/23496/htdocs/lib/private/AppFramework/App.php line 137
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Onlyoffice\C ... {}, "saveAddress")
18. /snap/nextcloud/23496/htdocs/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("SettingsController", "saveAddress", OC\AppFramework\ ... {}, {_route: "onlyof ... "})
19. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "onlyof ... "})
20. /snap/nextcloud/23496/htdocs/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {_route: "onlyof ... "})
21. /snap/nextcloud/23496/htdocs/lib/base.php line 1012
    OC\Route\Router->match("/apps/onlyoffice/ajax/settings/address")
22. /snap/nextcloud/23496/htdocs/index.php line 37
    OC::handleRequest()

PUT /index.php/apps/onlyoffice/ajax/settings/address
from 5.183.92.62 by admin at 2020-10-07T21:48:13+00:00

**Comment by LinneyS** [comment]
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).
