### ISSUE TITLE
The document server not longer loads since the update to Onlyoffice 6.02

### ISSUE THREAD

**Issue by poltrian** [ONLYOFFICE/onlyoffice-nextcloud#378]
It always comes, loads, loads, loads, when i try to open a docx file.
Nextcloud 19.03 Community Server 0.18 Onlyoffce 6.02 updatet yesterday. The Android App works well. The problem is since the update. Desktop version works well too

No logs are showing

**Comment by ShockwaveNN** [comment]
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate [GitHub repository](https://github.com/nextcloud/documentserver_community). 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).
