### ISSUE TITLE
Lack of controls in Community DocumentServer in Nextcloud

### ISSUE THREAD

**Issue by ostasevych** [ONLYOFFICE/onlyoffice-nextcloud#379]
In the last version of the Community DocumentServer there are no controls to close document, share document and call the chat.
Nextcloud 20.0.0
Community DocumentServer 0.1.8
OnlyOffice 6.0.2

![image](https://user-images.githubusercontent.com/5199030/95664008-aa72c380-0b4c-11eb-8b46-38d7efe174a5.png)

**Comment by ShockwaveNN** [comment]
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate [GitHub repository](https://github.com/nextcloud/documentserver_community). 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).
