### ISSUE TITLE
Choose username for shared files

### ISSUE THREAD

**Issue by schniewmatz** [ONLYOFFICE/onlyoffice-nextcloud#380]
This is a feature request:

We use Nextcloud and OnlyOffice for great good within our organisation and the collaborative editing works like a charm so far. Nevertheless, we often have to share files or folders with collaborators outside our institution e.g. for project proposals. Here collaborative editing still works very well but comes with on major disadvantage:
All users that are not registered Nextcloud users are shown as anonymous and are hence indistinguishable. There is no option to select a name for editing and not being able to distinguish who did what for 10 editors is a major showstopper so far.
As a user I am not in the position to judge whether this is an issue in onlyoffice, the nextcloud plugin or nextcloud itself, so I hope you can figure it out somehow. For nextcloud there is already a post here:
https://help.nextcloud.com/t/nextcloud-and-onlyoffice-issue-with-anonymous-editing/62107

**In general I would like to see an option, either in advanced settings or the collaboration tab of onlyoffice or - for a shared folder - in Nextcloud, to select an alias you want to be recognized as during your work in the respective file or folder.**

**Comment by LinneyS** [comment]
#92
#361

#115

@juliushaertl nextcloud/server#17147
