### ISSUE TITLE
Data loss in xlsx sheet - maximum number of columns per table was exceeded

### ISSUE THREAD

**Issue by hermann-san** [ONLYOFFICE/onlyoffice-nextcloud#381]
Recently I've updated my NC from 18.0.8.1 to 18.0.9.1. After that I've opened a xlsx document in NC and there is one sheet in that document without content where the previously was content. I don't know if the NC-update has anything to do with the problem of the missing sheet. A few days before, I did update from Onlyoffice 6.0 to 6.0.2. However , there was no issue  with  this document. I've opened, closed and modified it several times. 

I don't know if this is related to the problem or not, but the change date of the file still shows me that I've changed it 6 days ago, even though I've modified it yesterday. This is something I've also noticed for weeks and month, but it was not a problem because there was not missing information from the doc.

In that sheet there were 2 text boxes with formatted text (bold word), full URL's and linked words with URL's. There are also lot's of special characters  like +"%Y%m%d".bak

Then I've downloaded full workbook from NC and opened it with Libreoffice. It gave me the following error message. I believe this is related to the missing sheet because when I completely deleted that faulty, empty sheet (not the entire workbook though), I close the workbook and reopen it and then the error message is gone.

here is the error message:
```
Warning when loading the document filename.xlsx:
The data could not be loaded completely because the maximum number of columns per table was exceeded.
```
[log-entries](https://hastebin.com/ikereyepug.php)

It looks like a bug to me. I did re-upload my backup-workbook to NC and so far no issues with the file. However, I think this bug should be fixed because it happened to me before and I've lost a lot of data.

**Comment by LinneyS** [comment]
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).
