### ISSUE TITLE
Warning: "The document could not be saved"

### ISSUE THREAD

**Issue by kennyparsons** [ONLYOFFICE/onlyoffice-nextcloud#385]
I have nextcloud (apache), redis, postgres all installed with docker-compose ([my compose file here](https://code.datahoarder.dev/qagobowidy.yml))

Versions:
 - nextcloud: Major Version 19
 - postgres: Major Version 12
 - redis: docker hub latest alpine
 - onlyoffice: latest docker hub

I have nginx (non-docker) serving up https with LE. It proxies cloud.example.com to my nextcloud container. I also have onlyoffice proxied with https with https://onlyoffice-connect.mydomain.com.

When I've added my onlyoffice-connect url to the only office settings. 
![settings](https://user-images.githubusercontent.com/5930491/96183418-73a9fe00-0efc-11eb-9599-9b79c4d4ddfd.png)

But when I try to open an xslx doc, I get the following warning/error:
![error](https://user-images.githubusercontent.com/5930491/96183474-89b7be80-0efc-11eb-84b5-d6d974ccc51b.png)

I'm at my wits end trying to figure this out. Any ideas?

**Comment by pktiuk** [comment]
I have the same issue, but with demo ONLYOFFICE docs server (version 7.0.0.132)

**Comment by pktiuk** [comment]
This strange warning doesn't affect functionality.   
When I click `OK` I am not prompted to download document.   
Later after clicking tab `Home` I can freely edit and save this document.

**Comment by ValentinDrean** [comment]
I seem to have same configuration but with Only Office 7.0.1.37 and I do share same problem, which is harsh for non geek users

**Comment by svenseeberg** [comment]
I experienced the same issue in 2 separate environments. In both cases it is very likely the the connection between the Nextcloud and OnlyOffice server was temporarily (few minutes) broken. Can this be the cause? If that is the case I'm wondering if OnlyOffice should with some delay have additional retries to save the document back to the Nextcloud.

**Comment by yokesh22** [comment]
I have pulled docker images "sudo docker run -i -t -d -v onlyoffice_docx_volume:/var/lib/onlyoffice/documentserver-example/files -p 8050:80 --restart=always -e JWT_SECRET=my_jwt_secret onlyoffice/documentserver-de".

when i try to open in localhost:8050, it should the list of documents but when i try open open a document, it shows error as 

"The document could not be saved. Please check connection setting" followed by "Download Failed"

**Comment by dawidkellerman** [comment]
I started receiving this error while I the servers were in production and ultimately not reconnecting . In my case there was a time difference after that was solved everything started working
