### ISSUE TITLE
VAB Function in OnlyOffice and Excel gives different value

### ISSUE THREAD

**Issue by son12710** [ONLYOFFICE/onlyoffice-nextcloud#394]
Do you want to request a feature or report a bug?
VAB Function in OnlyOffice give a different value than Excel
What is the current behavior?
at year 5 and 6, OnlyOffice gave a different value than Excel for F14 and F15 (data was copied and paste from excel to OnlyOffice)
The function that was used on both excel and OnlyOffice

=VDB(B$2,0,B$1,MAX(0,A10-1.5),MIN(B$1,A10-0.5),2)

Excel
![image](https://user-images.githubusercontent.com/45722688/97793653-39f81900-1bc5-11eb-87fd-ae77ed6be748.png)

OnlyOffice
![image](https://user-images.githubusercontent.com/45722688/97793656-3d8ba000-1bc5-11eb-8ada-c297833720f3.png)

What is the expected behavior?
Excel and Only office should give the same result for F14 and F15

Did this work in previous versions of DocumentServer?
Not sure, Noticed it just now

DocumentServer version:
lastest docker version from onlyoffice/documentserver

Operating System:
dockers for OnlyOfficeDocumentServer : onlyoffice/documentserver
OnlyOnlyoffice is integrated with NextCloud

Browser version:
Microsoft Edge

**Comment by ShockwaveNN** [comment]
Closing this issue, since there is duplicate in correct repo https://github.com/ONLYOFFICE/DocumentServer/issues/1050
