### ISSUE TITLE
Using an external Document server with NextCloud on private network

### ISSUE THREAD

**Issue by nickian** [ONLYOFFICE/onlyoffice-nextcloud#4]
I have a Document server running on a public server that I'm trying to use in a local install of NextCloud on a private network. Is this possible, or does the public Document Server need the ability to access the NextCloud files?

**Comment by alexanderonlyoffice** [comment]
Hello @nickian, the Document Server should be accessible for NC and NC should be accessible for the Document Server. Please follow this [link](https://api.onlyoffice.com/editors/nextcloud) to find our API documentation on how the integration works.

**Comment by nickian** [comment]
Thanks! That's helpful. Probably best to just install a document server locally and use that.
