### ISSUE TITLE
feature request : give a name while editing without account, through a public link

### ISSUE THREAD

**Issue by tomdereub** [ONLYOFFICE/onlyoffice-nextcloud#401]
**What is the current behavior?**
When a document is shared with a public link (I use it integrated in Nextcloud), the name of non-connected contributors is "Anonyme" for all of them. So comments or chat messages are all with name anonyme.

**What is the expected behavior?**
On collabora online for example, you can just replace anonyme by the name you want, and so your comments or messages in the chat are linked with that name. I would like the same behaviour in Onlyoffice : be able to give a name instead of Anonyme for non connected users.

**DocumentServer version:**
6.0.1

**Operating System:**
Debian Buster, Yunohost 4.0.8, Nextcloud 19.0.3

**Browser version:**
Firefox 82.0.2

**Comment by shoei101** [comment]
Please!  It would be so helpful!

**Comment by HelenBelova17** [comment]
Hello @**tomdereub** @**shoei101**  , we plan to realize it in the DocumentServer 6.3.

**Comment by SergeyKorneyev** [comment]
Hi @tomdereub @shoei101 
As mentioned in the previous post, the feature is implemented on the Document Server side starting from version 6.3: external users can now choose a name upon opening a document.

**Comment by tomdereub** [comment]
Yes that's right, I've just upgraded, and it's perfect, thanks !
