### ISSUE TITLE
Does federation works for collaborating on a shared document between different servers ?

### ISSUE THREAD

**Issue by ImaCrea** [ONLYOFFICE/onlyoffice-nextcloud#404]
Hi there,
quick question here: I know Nextcloud handles federation between two different instances.

So Leo on instance A can share a document with Camille who's on instance B. But what happens when they want to collaborate on that document, and they both have their Onlyoffice server set. How would that work?

Thanks for your help, 
best

**Comment by alexanderonlyoffice** [comment]
@ImaCrea, please note that the main requirement for collaboration and working on one file shared between different Nextcloud instances is usage of the common Document Server. It means that it will possible to edit the document if the Document Server is the same for both (or more) instances of Nextcloud. You can find this info in our Blog here https://www.onlyoffice.com/blog/2019/12/onlyoffice-connector-for-nextcloud-document-co-editing-between-federated-clouds-is-now-available/

**Comment by ImaCrea** [comment]
Hi @alexanderonlyoffice , thanks for your answer and for pointing me to your blog.

Still, I don't see how it is supposed to make sense on the user side. If people want to federate, it's because they don't share the same server, right?

So it is highly probable that when they want to collaborate they still don't share the same only office server. The need of having the same oo server pushes towards centralization when what we're trying to achieve here is federated decentralization.

Do you have any suggestion on that side as decentralization is a fast growing need?

**Comment by alexanderonlyoffice** [comment]
@ImaCrea, thank you for your suggestion. We will take it into consideration.

**Comment by ImaCrea** [comment]
sure, thanks.
