### ISSUE TITLE
Icons missing in toolbar

### ISSUE THREAD

**Issue by absynth47215** [ONLYOFFICE/onlyoffice-nextcloud#409]
I am running the latest stable onlyoffice release on the internal (via add-on) CODE server on NC 20.0.2. When I open or create office documents with OnlyOffice, the icons are missing from the toolbar. Attached is a screenshot. 
I cannot see any relevant errors in the nc log and/or in the web server error log, especially no 404 errors. I'm a little confused what could be the problem. 
I looked for open issues with "toolbar" in them, but none seem to exist.
<img width="983" alt="Bildschirmfoto 2020-11-25 um 09 00 10" src="https://user-images.githubusercontent.com/3737316/100199350-5d309280-2efd-11eb-977a-04c0d0690e03.png">

**Comment by alexanderonlyoffice** [comment]
@absynth47215, please note that you are talking about Collabora, your screenshot is also related to Collabora. We are not providing technical support for third-party application. Please contact the developers of Collabora.

**Comment by absynth47215** [comment]
Sorry, I got confused. My bad.
