### ISSUE TITLE
xls and doc format should be supported by editor

### ISSUE THREAD

**Issue by doudz** [ONLYOFFICE/onlyoffice-nextcloud#41]
xls and doc format should be supported by editor since onlyoffice supported it

https://helpcenter.onlyoffice.com/fr/ONLYOFFICE-Editors/ONLYOFFICE-Spreadsheet-Editor/HelpfulHints/SupportedFormats.aspx
https://helpcenter.onlyoffice.com/fr/ONLYOFFICE-Editors/ONLYOFFICE-Document-Editor/HelpfulHints/SupportedFormats.aspx

until now we have to convert them to xlsx or docx

**Comment by LinneyS** [comment]
xls, doc and ppt formats are supported for editing with pre-conversion in Office Open XML format.
[Converting back](https://api.onlyoffice.com/editors/conversionapi) to these formats is not possible, and changing the file extension is not allowed.
Therefore, the opening for editing is not implemented.

**Comment by LinneyS** [comment]
We can convert xls to xlsx format.
We can edit xlsx and save to xlsx.
We can convert xls to xlsx format immediately when opened in the editor.
But we cannot convert xlsx to xls format.
We cannot save in xls format after editing.

When opening xls in the editor, we get xlsx after saving.

**Comment by doudz** [comment]
ok... so it's wrong when the onlyoffice helpcenter says xls can be modified.
So sad
I'll will take a look to collabora
