### ISSUE TITLE
Nextcloud 21 beta Exception: Error occurred in the document service: Error while downloading the document file to be converted.

### ISSUE THREAD

**Issue by axheli** [ONLYOFFICE/onlyoffice-nextcloud#418]
{"reqId":"gzEUuaeFHprgQH7XMIuL","level":3,"time":"2020-12-16T01:02:46+00:00","remoteAddr":"10.211.55.2","user":"axheli","app":"onlyoffice","method":"PUT","url":"/index.php/apps/onlyoffice/ajax/settings/address","message":{"Exception":"Exception","Message":"Error occurred in the document service: Error while downloading the document file to be converted.","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/onlyoffice/lib/documentservice.php","line":94,"function":"ProcessConvServResponceError","class":"OCA\\Onlyoffice\\DocumentService","type":"->"},{"file":"/var/www/nextcloud/apps/onlyoffice/lib/documentservice.php","line":432,"function":"GetConvertedUri","class":"OCA\\Onlyoffice\\DocumentService","type":"->"},{"file":"/var/www/nextcloud/apps/onlyoffice/controller/settingscontroller.php","line":168,"function":"checkDocServiceUrl","class":"OCA\\Onlyoffice\\DocumentService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"SaveAddress","class":"OCA\\Onlyoffice\\Controller\\SettingsController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/onlyoffice/lib/documentservice.php","Line":235,"CustomMessage":"GetConvertedUri on check error"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36","version":"21.0.0.8","id":"5fd95cdb06e41"}

**Comment by axheli** [comment]
dup #419

**Comment by LinneyS** [comment]
This issue is not related to version 21.
Check the document server logs.

**Comment by axheli** [comment]
I only get this on the Nextcloud 21 server I have 2 other Nextcloud 20 servers connecting to the onlyoffice server with no issues

**Comment by sebastien691** [comment]
Hello,

I recently setup 2 Nextcloud servers with OnlyOffice. NC and OO are separate VMs on the same LAN. Both based on Debian 10

I chose NC 20 for the first one. It works fine. OnlyOffice plugin version is (still) 6.2.

The second one is NC 21 stable with 6.3 OO plugin enabled from Apps. This one is not working. I have the error message mentioned in this thread : "Exception: Error occurred in the document service: Error while downloading the document file to be converted"

Regards,
Sebastien

**Comment by SergeyKorneyev** [comment]
Hello Sebastien,

The error usually means that the Document Server cannot reach the file storage. Please double-check the addresses you specified in the connector settings

**Comment by owncloud-lumineau** [comment]
Hello Sergey,

I did. Both are on the same LAN so I replaced the FQDN by the IP address. Not better.

**Comment by sebastien691** [comment]
Hello Sergey,

I did. Both are on the same LAN so I replaced the FQDN by the IP address. Not better.

**Comment by sebastien691** [comment]
[SOLVED]

OK, it's working now.

The authentication was not working even though I changed the header to AuthorizationJwt in the local.json file (as described here: https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/153

So I tried not to use authentication. I then realized that the secret box did not empty if you click directly to the save button. If you want to blank the box (ie. do not use authentication) you have to click elsewhere before to validate  and you may click save after that. Blanking then clicking save button directly does not blank the secret value.

One more thing: I added the full chain in my SSL cert because my Debian 10 did not have the CA (wget https could not validate cert then). Not sure this is something that matters here (since I checked the option "do not check cert"), just mentioniong in case.

So my config is just typical with a full chain SSL cert on both sides.
