### ISSUE TITLE
Enable Support for Nextcloud 21

### ISSUE THREAD

**Issue by axheli** [ONLYOFFICE/onlyoffice-nextcloud#419]
Can we get the app version to support nextcloud 21

**Comment by axheli** [comment]
@LinneyS When you have anticipate supporting Nextcloud 21 it currently dose not work on Nextcloud 21

**Comment by axheli** [comment]
{"reqId":"gzEUuaeFHprgQH7XMIuL","level":3,"time":"2020-12-16T01:02:46+00:00","remoteAddr":"10.211.55.2","user":"axheli","app":"onlyoffice","method":"PUT","url":"/index.php/apps/onlyoffice/ajax/settings/address","message":{"Exception":"Exception","Message":"Error occurred in the document service: Error while downloading the document file to be converted.","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/onlyoffice/lib/documentservice.php","line":94,"function":"ProcessConvServResponceError","class":"OCA\Onlyoffice\DocumentService","type":"->"},{"file":"/var/www/nextcloud/apps/onlyoffice/lib/documentservice.php","line":432,"function":"GetConvertedUri","class":"OCA\Onlyoffice\DocumentService","type":"->"},{"file":"/var/www/nextcloud/apps/onlyoffice/controller/settingscontroller.php","line":168,"function":"checkDocServiceUrl","class":"OCA\Onlyoffice\DocumentService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"SaveAddress","class":"OCA\Onlyoffice\Controller\SettingsController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\AppFramework\Http\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\AppFramework\Http\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\AppFramework\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\Route\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/onlyoffice/lib/documentservice.php","Line":235,"CustomMessage":"GetConvertedUri on check error"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36","version":"21.0.0.8","id":"5fd95cdb06e41"}

**Comment by axheli** [comment]
@LinneyS any updates on this?

**Comment by klou** [comment]
Looks like 6.3.0 was pushed to the dev branch recently.  So it probably won't be much longer.
