### ISSUE TITLE
Data loss in files

### ISSUE THREAD

**Issue by altokarev** [ONLYOFFICE/onlyoffice-nextcloud#42]
@altokarev commented on [Tue Jul 17 2018](https://github.com/ONLYOFFICE/DocumentServer/issues/349)

**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
We're losing the information in the files from time to time. I noticed such behavior for xls files at the moment.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Save the document (menu -> Save or Ctrl+S), close it and open it again - half the information is missing.

**What is the expected behavior?**
The information should not be lost.

**Did this work in previous versions of DocumentServer?**
Nope.

**DocumentServer version:**
5.1.4-22

**Operating System:**
Ubuntu 14.04.5 LTS

**Environment**
Node.js v6.14.1

**Browser version:**
Google Chrome 67.*

---

@altokarev commented on [Tue Jul 17 2018](https://github.com/ONLYOFFICE/DocumentServer/issues/349#issuecomment-405539387)

Document Server has connected to the Nextcloud (and we're using Group Folders module).

---

@ShockwaveNN commented on [Tue Jul 17 2018](https://github.com/ONLYOFFICE/DocumentServer/issues/349#issuecomment-405546863)

This issue related to owncloud, so please report it in according repo https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues

**Comment by HelenBelova17** [comment]
Hello, **@altokarev**, which version of nextcloud do you use?

**Comment by altokarev** [comment]
Hi!

`Nextcloud 13.0.1`

**Comment by alexanderonlyoffice** [comment]
@altokarev, it seems that the problem is not in version of Nextcloud, but in URL settings. Send us a screenshot of ONLYOFFICE integration app address settings.  Please specify if there is an error when clicking on the 'Save' button on ONLYOFFICE integration app settings page. 

Please note that version 13 of Nextcloud is not supported any more by the latest versions of ONLYOFFICE integration app.

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs or we can close the topic?

**Comment by altokarev** [comment]
Hey, @LinneyS ! 👋 

Nah, after upgrade to the new version the problem was resolved.

Thanks.
