### ISSUE TITLE
[Feature Request] Mention someone in comment

### ISSUE THREAD

**Issue by pierreozoux** [ONLYOFFICE/onlyoffice-nextcloud#421]
Hi,

currently this is available in OnlyOffice Groupware edition, and it would be nice if this would be available within Nextcloud too.

https://helpcenter.onlyoffice.com/en/onlyoffice-editors/onlyoffice-document-editor/helpfulhints/collaborativeediting.aspx

Thanks for considering this.

One of our user mentionned that this would allow his team's collaboration to reach Google Doc kind of experience.

**Comment by LinneyS** [comment]
Released in 7.1.0

**Comment by samuk** [comment]
This does not appear to work under a Cloudron hosting environment.

I can +Mention people but they do not get a notification of any kind. Is there further info I can provide to help debug? 

[Further here](https://forum.cloudron.io/topic/4650/anyone-got-mentions-working-in-comments/10)

**Comment by lolozere** [comment]
Thanks @pierreozoux for asking and @LinneyS for the feature. I'm going to try it ang give a feedback.
