### ISSUE TITLE
Add back the sharing and close button

### ISSUE THREAD

**Issue by szaimen** [ONLYOFFICE/onlyoffice-nextcloud#422]
Hey, I know that at some point there have been a share and close button in the top bar. 

Would be great if you could bring them back since it is currently not possible to open the sidebar to share the file or close the document except clicking the tiny share or leave buttons in onlyoffice itself.

Installed are onlyoffice-connector 6.2.0 and docker-documentserver 6.2

Here are the buttons that I am talking about: (thats an old screenshot to show which buttons I would like to have)
![image](https://user-images.githubusercontent.com/42591237/104136181-dfcdbe00-5394-11eb-8b8b-a4642ead783d.png)

**Comment by LinneyS** [comment]
In your screenshot, outdated buttons for editors 5.5.
The new buttons from the editor are now used.
![image](https://user-images.githubusercontent.com/8580527/104154182-54384980-53f5-11eb-8552-a315088ae2b4.png)

**Comment by szaimen** [comment]
Hey, thanks for the answer! 

Yes, I know that they are from version 5.5 but I'd like them to come back since the integrazed buttons are currently much too small for beeing a good UX. Also, the top bar is the much better place for them, imo. 

So could you please reopen this issue?

**Comment by LinneyS** [comment]
We do not plan to return these buttons.
If there are problems with buttons in the editors, then create an issue [here](https://github.com/ONLYOFFICE/DocumentServer).

**Comment by szaimen** [comment]
> We do not plan to return these buttons.

Thanks for the clarification.
