### ISSUE TITLE
DOCX and XLSX files download instead of opening

### ISSUE THREAD

**Issue by c0fe** [ONLYOFFICE/onlyoffice-nextcloud#424]
**### What Happens**

When connecting to Nextcloud and trying to open a DOCX and XLSX file that is hosted on there, OnlyOffice tries to download the file instead of opening it.

**Nextcloud Version:** 20.0.4
**Server OS:** Ubuntu 20.04
**Desktop OS:** Windows 10 Professional
**PHP Version:** 7.4
**NGiNX Version:** 1.18
**OnlyOffice Desktop Editor Version:** 6.1.0.90

What is going on? How can I fix this?

**Comment by SergeyKorneyev** [comment]
Hi,
Do you have the latest version of the OnlyOffice connector app in Nextcloud? Also, have you installed the Document Server (OnlyOffice Docs) that's required for it to function? You can follow this guide to set up all the necessary components: https://api.onlyoffice.com/editors/nextcloud

**Comment by c0fe** [comment]
@SergeyKorneyev I had all the connectors and components installed properly. what happened was that the server for some reason the nextcloud server lost the settings but one of the four computers in the office was still able to connect and open the documents properly. simply clicking save again in the connector section in nextcloud settings ended up fixing the issue.
