### ISSUE TITLE
Exception: Bad healthcheck status

### ISSUE THREAD

**Issue by yaott2020-666** [ONLYOFFICE/onlyoffice-nextcloud#427]
I use docker to install onlyoffice and use nginx to configure reverse proxy. I also configure ssl on nginx. But I cannot successfully configure onlyoffice in nextcloud. It shows the error: Bad healthcheck status.

Log:

Exception: Bad healthcheck status
1   /www/wwwroot/nextcloud/apps/onlyoffice/controller/settingscontroller.php - line 168:OCA\Onlyoffice\DocumentService->checkDocServiceUrl(OC\URLGenerator {}, OCA\Onlyoffice\Crypt {})

2  /www/wwwroot/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 169:OCA\Onlyoffice\Controller\SettingsController->SaveAddress("https://office.y***.**l/", "", "", true, "12****ret", false)

3  /www/wwwroot/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:OC\AppFramework\Http\Dispatcher->executeController(OCA\Onlyoffi ... {}, "saveAddress")

4  /www/wwwroot/nextcloud/lib/private/AppFramework/App.php - line 152:OC\AppFramework\Http\Dispatcher->dispatch(OCA\Onlyoffi ... {}, "saveAddress")

5  /www/wwwroot/nextcloud/lib/private/Route/Router.php - line 309:OC\AppFramework\App::main("SettingsController", "saveAddress", OC\AppFramew ... {}, { _route: "o ... "})

6  /www/wwwroot/nextcloud/lib/base.php - line 1008:OC\Route\Router->match("/apps/onlyo ... s")

7  /www/wwwroot/nextcloud/index.php - line 37:OC::handleRequest()

**Comment by igwyd** [comment]
Hello @yaott2020-666
1. Enter in the browser address bar https://(documentserver)/healthcheck. Do you see inscription "true"?
2. Which command do you run onlyoffice-documentserver in docker and which version?
3. Please attach your nginx config and nginx version

**Comment by yaott2020-666** [comment]
Thanks, I have found and solved the problem.
