### ISSUE TITLE
count():Parameter.....onlyoffice/lib/appconfig.php#477 error in logs

### ISSUE THREAD

**Issue by osscombat** [ONLYOFFICE/onlyoffice-nextcloud#43]
OnlyOffice-nextcloud v.2.1.2
onlyoffice-documentserver v.5.2.4
NC 14.0.4

Recently after the upgrades to these versions I noticed that upon every user logon to NC I get this message in the NC log:

`count(): Parameter must be an array or an object that implements Countable at /var/www/html/nextcloud/apps/onlyoffice/lib/appconfig.php#477`

and sometime

`implode(): Invalid arguments passed at /var/www/html/nextcloud/apps/onlyoffice/templates/settings.php#66`

I see no other problems, everything works fine though.

**Comment by LinneyS** [comment]
Fixed
013b9ff113142771e41c3bbc8de94f5d6c5ff55c

**Comment by Wizlonex** [comment]
UPDATE: the error shows up in the Nextcloud log even when I do NOT try to use the document server.

I have no idea if this is a Nextcloud or OnlyOffice issue.  V/R

**Comment by Knot3n** [comment]
Same here NC 15 and got the same Error. 
Updated ONLYOFFICE to the newest brunch.

**Comment by KBlixt** [comment]
yup, entire log is spammed with these errors.

**Comment by Wizlonex** [comment]
> Same here NC 15 and got the same Error.
> Updated ONLYOFFICE to the newest brunch.

I need this in plainer English - what's a 'latest brunch'?  I have latest Nextcloud App but I am not yet running latest server version (that's a more complicated upgrade for me).

**Comment by joekerna** [comment]
I can also confirm the issue is still there for Nextcloud 15.0.2

**Comment by Wizlonex** [comment]
I also still get this in 15.02 as well, and the error happens whether or not the onlyoffice server is being used or not.

Here's my formatted Nextcloud log entry:

[PHP] Error: count(): Parameter must be an array or an object that implements Countable at /var/www/html/apps/onlyoffice/lib/appconfig.php#477

GET /index.php/apps/files/
from 192.168.1.21 by andrew at 2019-01-14T14:16:07+00:00

And here's the raw log entry:

{"reqId":"oTWagKy91bRCnoM0izzU","level":3,"time":"2019-01-14T14:16:07+00:00","remoteAddr":"192.168.1.21","user":"andrew","app":"PHP","method":"GET","url":"/index.php/apps/files/","message":"count(): Parameter must be an array or an object that implements Countable at /var/www/html/apps/onlyoffice/lib/appconfig.php#477","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36","version":"15.0.2.0","id":"5c3c99b9357d1"}

**Comment by monakhv** [comment]
I've the same issue with
Nextcloud 15.0.2
onlyoffice-documentserver-5.2.7

**Comment by nova168168** [comment]
same issue
nextcloud 15

**Comment by joekerna** [comment]
The errors disappear when I restrict the Onlyoffice app to at least one group

**Comment by rollanders** [comment]
I restricted to all my groups (added each one of the9. Now I get another error 
Undefined offset: 2 at /var/www/nextcloud/apps/onlyoffice/controller/editorcontroller.php#434

Anyway it seems this has to do with this function.

**Comment by dpnoworyta** [comment]
Got the same error regarding _Undefined offset: 2 [...]#434_ after limiting access groups for OO.
Docker version: 18.09.1, build 4c52b90
Nextcloud version: 15.0.2
Openoffice version: 5.2.7 CE

**Comment by Wizlonex** [comment]
With reference to Joekerna's post, I too made the error disappear by selecting a group.  Thanks!

**Comment by joekerna** [comment]
But this is still a bug, isn't it? Should this issue be reopened?

**Comment by rollanders** [comment]
The error  
count(): Parameter must be an array or an object that implements Countable at /var/www/nextcloud/apps/onlyoffice/lib/appconfig.php#477
disappeared after selecting groups 

I now get this error instead 
Undefined offset: 2 at /var/www/nextcloud/apps/onlyoffice/controller/editorcontroller.php#434

So the problem remains. I do not know how to reopen an issue.

**Comment by Wizlonex** [comment]
Agree this should be re-opened as the workaround is not a proper solution.  👍

**Comment by RuudschMaHinda** [comment]
same issue
Nextcloud 15.0.2
Latest OO
Ubuntu 16.04
php7.2

last updated all software last week

**Comment by Luckyvb** [comment]
i haves same issue. only office go to external uri and can`t open nextcloud. add to /etc/hosts extarnal uri onternal ip resolve my problem
