### ISSUE TITLE
 editor version has been updated the page will be reloaded

### ISSUE THREAD

**Issue by pmaeter** [ONLYOFFICE/onlyoffice-nextcloud#439]
After updated the Community Document server to 0.1.9 & onlyoffice to 6.3.0 I got this message when trying to open a XLS file.
Any solutions for this?
thanks
Patrick

**Comment by LinneyS** [comment]
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).
