### ISSUE TITLE
App tries to open all version files with ONLYOFFICE no matter on the mimetype

### ISSUE THREAD

**Issue by juliushaertl** [ONLYOFFICE/onlyoffice-nextcloud#441]
Steps to reproduce:
- Setup ONLYOFFICE to not open txt files by default
- Open the versions sidebar of Nextcloud for a txt file
- Click on the download of a version

Actual:
- The file is being opened in ONLYOFFICE

Expected:
- The file gets downloaded

From a quick look at the implementation it seems that [bindVersionClick](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/75b3e9f300667f3454432994209a4d88f5ee8d7e/js/main.js#L324-L346) is just always triggering the open in ONLYOFFICE no matter of the mimetype or configured mimetype default opening settings.

**Comment by szaimen** [comment]
Any update here? Would be great to have this fixed :)
