### ISSUE TITLE
selected mimetypes not exposed in api

### ISSUE THREAD

**Issue by belzebub40k** [ONLYOFFICE/onlyoffice-nextcloud#444]
I opened a bug report https://github.com/nextcloud/android/issues/8004 for the Nextcloud Android app because it does not open all selected file formats with onlyoffice. They found out that not all supported mimetypes are exposed in the api.

![108479152-aa6e9700-7295-11eb-983b-d786fafe4886](https://user-images.githubusercontent.com/915117/109782846-a2a1e180-7c09-11eb-827f-13f234be8d92.png)

```
curl --request GET \
  --url 'https://admin:admin@nextcloud.local/ocs/v2.php/apps/files/api/v1/directEditing?format=json' \
  --header 'OCS-APIRequest: true'

...
        "onlyoffice": {
          "id": "onlyoffice",
          "name": "ONLYOFFICE",
          "mimetypes": [
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "application/vnd.oasis.opendocument.presentation",
            "application/vnd.oasis.opendocument.spreadsheet",
            "application/vnd.oasis.opendocument.text",
            "application/vnd.openxmlformats-officedocument.presentationml.presentation",
            "text/rtf",
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
          ],
          "optionalMimetypes": [
            "text/csv",
            "text/plain"
          ],
...
```

**Comment by LinneyS** [comment]
Hi @tobiasKaminsky and  @juliushaertl 
What action is indicated in the context menu of the Nextcloud mobile application?

A large list of formats is used for the "Open" action only.
For the "Edit" action, we support OOXML formats and several additional formats.
![image](https://user-images.githubusercontent.com/8580527/111144426-1e9c1200-8598-11eb-9cf5-a81253259d5f.png)

**Comment by belzebub40k** [comment]
@LinneyS "Edit" is shown correctly for mime types like OOXML and OpenDocument as they are listed in the mimetypes list of the API. My problem is why aren't all mime types selected in the WebUI exposed in the mimetypes list? For example opening (and editing) legacy Microsoft Office formats like .xls or .doc work without any problem but it does not work in the mobile app as it does not know that these types are supported by onlyoffice.

**Comment by LinneyS** [comment]
Hi @belzebub40k 
Editing is not available for the legacy `.doc` format.
The application does not control the text of the action in the context menu. I cannot replace "Edit" with "View".

**Comment by belzebub40k** [comment]
Okay, so this is works as designed as the Nextcloud App only supports one action (Edit) and view only formats are excluded to not cause any confusions?
