### ISSUE TITLE
Use Viewer API in the Files app

### ISSUE THREAD

**Issue by Thesola10** [ONLYOFFICE/onlyoffice-nextcloud#445]
On the new Dashboard app, when selecting an Office file from the Files widget, OnlyOffice shows up in a window with a black top bar, the same being used on Nextcloud Text.

However, on Files, while NCText still uses that window, OnlyOffice attempts to overlay its editor in a weird way, which can cause graphical issues and obscures options to leave the editor or edit sharing settings, which are more obvious on NCText.

Please consider making it so the OnlyOffice editor uses the NCText-like frame on the Files app as well -- basically everywhere NCText does.

**Comment by violoncelloCH** [comment]
I'd also really like to see Onlyoffice using Nextcloud's viewer frame, as this provides a way more obvious way for the users to close the editor.
Technically this can be done using the viewer API: https://github.com/nextcloud/viewer/
As an example the Text app uses this API here: https://github.com/nextcloud/text/blob/master/src/viewer.js

**Comment by Thesola10** [comment]
@violoncelloCH not like this would take a lot of effort -- as shown above, OnlyOffice does use the viewer API on the Dashboard, it's just a matter of making that behavior universal (and dropping whatever hack they're using on Files)

**Comment by violoncelloCH** [comment]
@Thesola10 I believe that's something that the Dashboard does, not the Onlyoffice-Integration... but yes, would make sense of course to use the proper viewer api everywhere

**Comment by Thesola10** [comment]
I just found out this integration app _already has_ a Viewer API binding under `js/viewer.js`. What exactly is preventing `editor.js` from using the same mechanism?

**Comment by Thesola10** [comment]
Or even better: just discontinue the Editor logic in favor of using Viewer exclusively -- declutters code, removes useless shortcuts from the OnlyOffice interface and fixes most layout issues in the Files app in one go

**Comment by SergeyKorneyev** [comment]
Hello @Thesola10 @violoncelloCH 
Initially, the ONLYOFFICE editor was designed to be opened on top of the file list, but then Nextcloud developers added the viewer interface for opening documents in other sections like Dashboard. We've adapted to support that interface, so the editor can now be opened anywhere where the viewer is used. However, it's not used in Files by default, so the editor still uses the original logic there, at the moment. 
Based on your feedback, we'll consider using the viewer interface in Files.

@Thesola10

> An issue from that approach, caused by simply resizing the window

Is this still reproducible with the latest Document Server and connector versions?

> Or even better: just discontinue the Editor logic in favor of using Viewer exclusively -- declutters code, removes useless shortcuts from the OnlyOffice interface and fixes most layout issues in the Files app in one go

Could you create a dedicated issue for that suggestion and elaborate on it?

**Comment by Thesola10** [comment]
Thanks for the response @SergeyKorneyev

> Is this still reproducible with the latest Document Server and connector versions?

This is the same issue, on the latest release of Nextcloud (23 from NixOS), Document Server (from Docker Hub) and the Onlyoffice connector (from the App Store) on Firefox 95 Flatpak:

![Screenshot](https://user-images.githubusercontent.com/7287268/145607667-b3f728f0-d976-40f7-82a6-d0fa0bd55e92.png)

> elaborate on it?

By "discontinuing the Editor logic", I meant (speculatively) that using the Viewer API on Nextcloud Files would standardize the way the connector works across Nextcloud and potentially allow the current Files overlay to be retired. I don't think it requires a separate issue.

**Comment by Thesola10** [comment]
I've just noticed that, on my latest screenshot, part of the regular Files app's UI also appears to be broken -- I couldn't reproduce this without the OnlyOffice view open.

**Comment by Thesola10** [comment]
Any updates? It looks like the Nextcloud 25 redesign might hinder the current overlay approach, so switching to Viewer everywhere is especially relevant I think

**Comment by LinneyS** [comment]
Fixed in v7.8.0

**Comment by Thesola10** [comment]
Upgraded to 7.8.0 and it doesn't appear to use Viewer API frames on Files... does Document Server need to be updated as well?

**Comment by Thesola10** [comment]
Please consider reopening, the core issue still hasn't been addressed as of 8.x
