### ISSUE TITLE
onlyoffice nextcloud connection not working after upgrade

### ISSUE THREAD

**Issue by PiotrIr** [ONLYOFFICE/onlyoffice-nextcloud#45]
I've successfully upgraded onlyoffice document server to the latest version and after changing config file which was restored to default, I'm able to open openoffice website without any errors and can see message "Document Server is running". 

However when I try to connect from nextcloud - I'm getting error message in logs:

file_get_contents(https://onlyoffice.mydomin.com/ConvertService.ashx): failed to open stream: HTTP request failed! HTTP/1.1 504 Gateway Time-out  at /var/www/nextcloud/apps/onlyoffice/lib/documentservice.php#381
--
and
GetConvertedUri on check error: Bad Request or timeout error

I don't use any security keys and I can connect my nextcloud to another onlyoffice server without any issues. Coudl you advise please?

**Comment by LinneyS** [comment]
@PiotrIr 
May be Conversion Service is not running?

>supervisorctl status all

Run it in Document Server. What is the result?

**Comment by LinneyS** [comment]
The problem seems to be ONLYOFFICE starting up incorrectly.
This issue was closed due to no response.
