### ISSUE TITLE
Allow disabling public link editing with group limitation

### ISSUE THREAD

**Issue by juliushaertl** [ONLYOFFICE/onlyoffice-nextcloud#450]
When ONLYOFFICE is limited to certain groups inside of Nextcloud it would be great to only let public share links being edited with ONLYOFFICE if the share owner is part of those groups. I could imagine a separate setting for this would work, however it might also be sane to just take this behavior as a default if an additional setting is too much.

**Comment by alexanderonlyoffice** [comment]
Hello @juliushaertl, thank you once again for your suggestion.
