### ISSUE TITLE
Feature request: Open in ONLYOFFICE as a "default" option

### ISSUE THREAD

**Issue by vahem2lu** [ONLYOFFICE/onlyoffice-nextcloud#454]
A feature request for non-default behaviour.
A document is shared via link `nextcloudurl.com/s/123blabla`, user opens it in their browser and share link apperas offering:
"Open in ONYLOFFICE" and "Download".

I'd like ONLYOFFICE to open shared link document automatically not to have another "Open in ONLYOFFICE" click.

As not to go conflict with other editors or plugins, maybe this should be configurable in Nextcloud admin menu?

**Comment by alexanderonlyoffice** [comment]
@vahem2lu, thank you for your suggestion, we will consider the way we can implement the described behavior.

**Comment by suparomana** [comment]
This behavior would be very helpful and would fix a major usability issue of onlyoffice in a nexcloud environment. We see a lot of users don't understand the button "Open in ONLYOFFICE". This leads to issues in collaboration in documents and frustrated users. sometimes the document is downloaded, edited locally and sent back by email, resulting in additional and unnecessary management effort. 

It would be great to have an option to disable the preview step and open the document directly on ONLYOFFICE. This would make the user experience of ONLYOFFICE in nextlcoud much better. Hope you decide to implement this behavior/feature/option. 

Thank you very much 🙏
