### ISSUE TITLE
Nextcloud Dashboard Onlyoffice Issues

### ISSUE THREAD

**Issue by andyxheli** [ONLYOFFICE/onlyoffice-nextcloud#455]
I've already created a ticket on the nextcloud github and they said this is an onlyoffice issue. @LinneyS what do you think about this :) 

When you open a doc via the dashboard, it opens fine with OnlyOffice when if you click on the left or right side of the doc it just keep s going throw other documents. Please see attached video. only happens when you open the documents via the dashboard.

Nextcloud 20.0.8, Ubuntu 20.0.4 PHP, Version: 7.4.3, MariaDB Version: 10.3.25, OnlyOffice App Version 6.3.0, OnlyOffice Server version 6.2.1.24

https://user-images.githubusercontent.com/59488153/103297216-7a092b80-49bd-11eb-85ed-ce27793a9b2c.mp4

**Comment by LinneyS** [comment]
Hi @andyxheli 
We will see.

nextcloud/server#24889

**Comment by andyxheli** [comment]
@LinneyS thank you. I'll make the change on m my local sever and test.

**Comment by andyxheli** [comment]
@LinneyS I did manually apply the change and still the same thing. Please see below image there are there aeros and if you make them go away it should fix the issue because when you go anywhere near them it changes the page you can be on the bottom of the page and if you click on it it will switch to the next doc. I hope this helps 
![image](https://user-images.githubusercontent.com/59488153/114883496-972a0480-9dca-11eb-8baf-2992e3c516a2.png)

**Comment by Antipkin-A** [comment]
Hi @andyxheli 
We checked again - this solution is correct. Try to clear browser cache or open it in incognito mode.

**Comment by andyxheli** [comment]
@Antipkin-A thank you sir. I will clear browser cache and try again if it works should I close this ticket and wait for the app release ?

**Comment by andyxheli** [comment]
All fixed with the patch.
