### ISSUE TITLE
Nextcloud 20.0.9 brakes onlyoffice

### ISSUE THREAD

**Issue by andyxheli** [ONLYOFFICE/onlyoffice-nextcloud#456]
Once i updated from Nextcloud 20.0.8 into Nextcloud 20.0.9 the onlyoffice stopped working getting the below errors 
 I dont have issues with any other version i tested Nextcloud 21.0.1 and its working and anyother version besides Nextcloud 20.0.9

exception: error occurred in the document service: error while downloading the document file to be converted.
exception: error occurred in the document service: invalid token

**Comment by SergeyKorneyev** [comment]
Hello,
Please check the Document Server's address in the ONLYOFFICE app settings and make sure the secret key matches the one specified in **local.json**. After that try saving the settings again.

**Comment by andyxheli** [comment]
Everything is correct I checked and triple checked and it still doesn't connect. I have two onlyoffice servers and currently everything is working as soon as I upgraded it stoped working I even removed the key and Re-entered it￼ and stil nothing I tried both onlyoffice server and nothing.
