### ISSUE TITLE
Unable to print an onlyoffice document (nextcloud app)

### ISSUE THREAD

**Issue by HeyWatchOutDude** [ONLYOFFICE/onlyoffice-nextcloud#459]
Hi,

when I try to print a document via the integrated document server (onlyoffice) im getting an "Unknown Error".

![image](https://user-images.githubusercontent.com/61534143/115872667-5b361580-a442-11eb-8f66-a102d5f21b76.png)

In comparison when I print via the standalone "onlyoffice app" from the iOS App Store (https://apps.apple.com/at/app/onlyoffice-documents/id944896972) *also connected to my nextcloud* everything is working fine. 

![image](https://user-images.githubusercontent.com/61534143/115872680-5ec99c80-a442-11eb-9776-841313508d97.png)

Note: It is also not working via browser. (OS: iOS/iPadOS, Windows etc.)

**Comment by HelenBelova17** [comment]
Hello @**HeyWatchOutDude**,
please, specify version of integrated document server?

**Comment by HeyWatchOutDude** [comment]
Hi @HelenBelova17 

version "0.1.9" is currently installed.

**Comment by LinneyS** [comment]
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).
