### ISSUE TITLE
Node.JS ssl error at ONLYOFFICE 5.2.2

### ISSUE THREAD

**Issue by vvl-rulez** [ONLYOFFICE/onlyoffice-nextcloud#46]
Hello!
I'm upgraded onlyoffice-documentserver from 5.1.5 to 5.2.2 version. 5.2.2 requires node.js = 8 version, so I compiled with it. In additional, I merged new nginx config and default.json config file. All three services started successfull. But Nextcloud app doesn't working:

![screenshot_20181022_162005](https://user-images.githubusercontent.com/13856385/47295054-6876ad00-d617-11e8-9b19-9e928394f1dd.png)
```
journalctl -efuonlyoffice-fileconverter

node[28356]: [2018-10-22 16:21:45.018] [ERROR] nodeJS - error downloadFile:url=https://mycloud/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.talDYzgiy66nRHTJnjcBBk5cyMJcCH2_lFB8FxMpvig;attempt=3;code:EPROTO;connect:undefined;(id=conv_check_2136992374_docx)

node[28356]: Error: write EPROTO 140360910474176:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:802:

node[28356]:     at WriteWrap.afterWrite [as oncomplete] (net.js:868:14)
```
I'm using lets'encrypt certificate and https.

Seems like this [error](https://github.com/nodejs/node/issues/19359), but onlyoffice doesnt work with node.js>8

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs with the last version?

**Comment by vvl-rulez** [comment]
> 
> 
> Could you please specify if the problem recurs with the last version?

Now it doesnt recurs. All works fine.
