### ISSUE TITLE
Error: Undefined index: isTemplate at /var/www/nextcloud/apps/onlyoffice/templates/editor.php#36

### ISSUE THREAD

**Issue by andyxheli** [ONLYOFFICE/onlyoffice-nextcloud#476]
Onlyoffice App 6.4.2

{"reqId":"udpgSumMjwgevwoZucoN","level":3,"time":"2021-05-24T02:14:04+00:00","remoteAddr":"10.241.202.218","user":"--","app":"PHP","method":"GET","url":"/apps/files/directEditing/PQ8apbk2YWGGBWF9mcSDRrSCjsLw7ER6ZyRYHoBHxW5EggyJa6YQREjEko4wbSky","message":{"Exception":"Error","Message":"Undefined index: isTemplate at /var/www/nextcloud/apps/onlyoffice/templates/editor.php#36","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/onlyoffice/templates/editor.php","line":36,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/private/Template/Base.php","line":178,"args":["/var/www/nextcloud/apps/onlyoffice/templates/editor.php"],"function":"include"},{"file":"/var/www/nextcloud/lib/private/Template/Base.php","line":150,"function":"load","class":"OC\\Template\\Base","type":"->"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Template.php","line":180,"function":"fetchPage","class":"OC\\Template\\Base","type":"->"},{"file":"/var/www/nextcloud/lib/public/AppFramework/Http/TemplateResponse.php","line":210,"function":"fetchPage","class":"OC_Template","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":123,"function":"render","class":"OCP\\AppFramework\\Http\\TemplateResponse","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (iPhone) Mobile Nextcloud-iOS/3.4.2","version":"20.0.8.1","id":"60abd9747c65e"}

**Comment by LinneyS** [comment]
#474
