### ISSUE TITLE
Notifications about comments or changes for realtime collaboration in documents

### ISSUE THREAD

**Issue by thomiel** [ONLYOFFICE/onlyoffice-nextcloud#479]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
someone comments on a part I wrote in a collaborative document or even replies on a comment of mine and I don't notice it.

**What is the expected behavior?**
I would like some kind of notification, e.g. via email or rss.

**Did this work in previous versions of DocumentServer?**
no

**DocumentServer version:**
6.1.0.83

**Operating System:**
Debian

**Comment by ShockwaveNN** [comment]
Moving this issue to `onlyoffice-nextcloud` repo

DocumentServer has no email or rss capabilites and this should be implemented on dms or connector side, as far as I'm aware

**Comment by naresh97** [comment]
The "mentions" functionality seems to be talked about in the documentation, but it seems it is not available in-app.

**Comment by LinneyS** [comment]
Released in 7.1.0
