### ISSUE TITLE
Close and Share buttons not visible

### ISSUE THREAD

**Issue by acsfer** [ONLYOFFICE/onlyoffice-nextcloud#482]
See https://help.nextcloud.com/t/how-to-close-onlyoffice-window/70866/19 and https://github.com/nextcloud/documentserver_community/issues/174

![image](https://user-images.githubusercontent.com/12234510/121157351-c482b400-c849-11eb-9120-8d7c76a5d605.png)

Here with Nextcloud 21.0.2 and OnlyOffice EE 6.3.0 we can't see it either, but it was visble some time ago.
Is this a bug or some setting we can't find?

**Comment by SergeyKorneyev** [comment]
Hi,
The "close" button from your screenshot no longer exists. Please refer to the following method: https://api.onlyoffice.com/editors/config/editor/customization#goback

**Comment by acsfer** [comment]
That's fine, thanks.

**Comment by ostasevych** [comment]
> Hi, The "close" button from your screenshot no longer exists. Please refer to the following method: https://api.onlyoffice.com/editors/config/editor/customization#goback

Can you explain in basics, how to edit the configuration? Sadly, I have'nt found enough explanations. Thanks.
