### ISSUE TITLE
when refresh page, main.js will not reload /apps/onlyoffice/ajax/settings 

### ISSUE THREAD

**Issue by feizhoulv** [ONLYOFFICE/onlyoffice-nextcloud#484]
**Steps to reproduce**
1. use nextcloud 20.0.2 with onlyoffice installed
2. open directory that contains *.docx, the doc file url should be [/index.php/apps/files?dir=/abc.docx]， and editable.
3. refresh page, the doc url changed to [/remote.php/webdav/abc.docx] and can't edit.
4. disable cache then refresh page, docs can edit again, and url changed back.

**Expected behaviour**
when refresh page the doc url should always be [/index.php/apps/files?dir=/abc.docx]

**Actual behaviour**
when main.js loaded from browsers memory cache ，it will not reload [/apps/onlyoffice/ajax/settings] ，then docs can't edit.

also report here  https://github.com/nextcloud/server/issues/27434

**Comment by HelenBelova17** [comment]
Hello @**feizhoulv** ,
please specify some additional information:
- currently installed version of the Document Server;
- version of the ONLYOFFICE integration app.

**Comment by feizhoulv** [comment]
ONLYOFFICE Document Server: [onlyoffice-documentserver             6.3.1-32                          amd64]
ONLYOFFICE integration app:  [ 6.1.0 ]

**Comment by feizhoulv** [comment]
I found the reason :
Sometimes I cannot access the app store in my area . When I upgraded the ONLYOFFICE integration app to 7.0.2, the problem was solved. THX
