### ISSUE TITLE
Layout gets broken (iPad/Safari)

### ISSUE THREAD

**Issue by Shen** [ONLYOFFICE/onlyoffice-nextcloud#485]
Hello there,
I currently have a problem with OnlyOffice in Nextcloud on iPad with Safari. When scrolling down in a folder and opening a document, a folder view appears covering most of it, see screenshot. 

Nextcloud 20.0.4.0
OO Document Editor V 6.3.1
OO App in Nextcloud V 6.4.2

![nc-only-office-problem](https://user-images.githubusercontent.com/81589/121805010-8c181700-cc49-11eb-9325-697ca40b7786.png)

Seems to be the same like this (not) fixed issue: https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/350

**Comment by ShockwaveNN** [comment]
@nav-fess Please take a look

**Comment by nav-fess** [comment]
Hello @Shen. The problem was reproduced. Bug in the process of fixing the developer

**Comment by Shen** [comment]
@LinneyS 
When will this bug fix be integrated and released? As a paying customer for mobile support, this is really massively limiting.

**Comment by Shen** [comment]
@LinneyS 
Sorry, this issue is still not fixed
Nextcloud 21.0.3.1
Only-Office App 7.1.2
Document Editor 6.3.1
