### ISSUE TITLE
Automaticly save file on Nextcloud 

### ISSUE THREAD

**Issue by tanguy-opendsi** [ONLYOFFICE/onlyoffice-nextcloud#487]
Hi
Is there the option to automatically save a file to nextcloud while users are working on the document?
Currently the user must close the browser's TAB for save. 

Best regards

**Comment by SergeyKorneyev** [comment]
Hi,
You can enable force saving to allow users to save a document without closing the editing session. The option can be found in the ONLYOFFICE connector app settings: 
![chrome_2021-06-15_12-40-19](https://user-images.githubusercontent.com/77327210/122031123-1477f280-cdd7-11eb-9c61-baddfddd6bd6.png)

**Comment by tanguy-opendsi** [comment]
Thx for your fast reply
Best regards
