### ISSUE TITLE
Invited user (guest) cannot change its name

### ISSUE THREAD

**Issue by biva** [ONLYOFFICE/onlyoffice-nextcloud#498]
The new feature enabling invited users (guest external to the organisation) to add their name (instead of anonymous) is great. In some cases, users cannot change their name. For example, an invited user is stuck with the name TuneMe. Clicking on the icon on the top left doesn't allow him to change his name.
![image](https://user-images.githubusercontent.com/9964305/125939961-d968c538-29bb-4913-87e5-239f62b42458.png)

Would you have a suggestion?

Server: Debian
OO version: 6.3.0.111 (Docker) within Nextcloud
Application :Spreadsheet editor

**Comment by ShockwaveNN** [comment]
I'm not 100% sure but I think problem actual only for nextcloud integration, so I've moved issue to correct repo

**Comment by biva** [comment]
@ShockwaveNN Thanks for your quick reply. I wasn't able to reproduce it. On the same installation, using Brave browser, I was able to change the name. Unfortunately, I can't share much more information.

**Comment by ShockwaveNN** [comment]
So to be clear - on same DocumentServer instance with same nextcloud - on some browsers you can change name, but on other you cannot ?

**Comment by biva** [comment]
Yes, this is it

**Comment by ShockwaveNN** [comment]
Maybe some errors in JS console?
Maybe some extensions are blocking this

Try same browser where error happens - and open it in incognito mode and compare behavior

**Comment by biva** [comment]
I rebooted the server and the user was able to change its name. No idea how it happened.

Is there a way to clear something on the server, in order to remove guest users and force them to reconnect? In general, is there a way to force users to disconnect?

**Comment by ShockwaveNN** [comment]
> Is there a way to clear something on the server, in order to remove guest users and force them to reconnect?

You can run `documentserver-prepare4shutdown.sh` script - this force disconnection of ALL active users and reboot server after that

**Comment by biva** [comment]
Thanks! Is it possible to disconnect ALL active users but without rebooting the server?

**Comment by biva** [comment]
For the script above, where can I find the source code?

And for information and for the record, the user also cleared its browser's cache and cookies.

**Comment by ShockwaveNN** [comment]
I think you can type `supervisorctl start all` to start all DocumentServer services

**Comment by biva** [comment]
Thanks, I let you close this issue if you want. It's solved on my side with the clearing of the browser's cache and cookies.

**Comment by ShockwaveNN** [comment]
Ok I think I'll do that, thanks )
