### ISSUE TITLE
Change default of copied link

### ISSUE THREAD

**Issue by shushugah** [ONLYOFFICE/onlyoffice-nextcloud#499]
## Current behaviour
Currently, whenever I select 'Copy to clipboard' for an OnlyOffice document (for example .docx file), I need to specify whatever I want to download the file (why would I do that if I am copying a link that's already open?) or specify an OnlyOffice link which adds an extra step when all I want to do is copy/paste a link without opening a file. 

## Request behaviour 
When I click copy link I get something like 
* `https://cloud.example.com/s/34s6` 
* but I want it to be `https://cloud.example.com/apps/onlyoffice/s/34s6`. 

I searched the issues to see if this was discussed before, but couldn't find anything.

**Comment by SergeyKorneyev** [comment]
Hi @shushugah 
Starting from version 7.2.0 of the ONLYOFFICE connector app, opening a link will open the shared document directly in the editor.
