### ISSUE TITLE
Feature Enhancement - allow and support custom port usage in nextcloud settings

### ISSUE THREAD

**Issue by mistergibson** [ONLYOFFICE/onlyoffice-nextcloud#5]
Dear OnlyOffice:

Some of us cannot afford to purchase two hosts with a static ip and certificate EACH. Many, you will find if you look, have a single dynamic ip address to serve up their home-stack with. If you were to pass not just the hostname, but the hostname+port within your code - we could use a custom port (say 4430) on our outside routers using port forwarding and utilize that SINGLE ip address for both OnlyOffice and NextCloud servers. Additionally, we cannot make a paid-for cert work with a dynamic ip address. If you would also support self-signed certs in all your code it would help impoverished home-admins everywhere. There was talk in the support forums of making this happen 'within a month' - and I've seen NO ACTION on it as a feature in over a year.

Please make this happen. Some of us simply cannot afford the hosting fees.

Thanks,

mistergibson
A fan.

**Comment by alexanderonlyoffice** [comment]
@mistergibson, please follow this [link](https://github.com/ONLYOFFICE/docker-onlyoffice-nextcloud) to find our docker-compose (Nextcloud and Document Server installed via docker containers and configured). There is only one entry port, which is listened by Nginx. Nginx then redirects all requests, so you can have only one certificate for one domain name for Nextcloud. 

You can look how the proxy is configured in docker-compose. There will be no need in separate port for the document server and certificate.
