### ISSUE TITLE
Only Office not starting in Android Nextcloud App Exception in Log Files after Update to 7.1.0

### ISSUE THREAD

**Issue by florom** [ONLYOFFICE/onlyoffice-nextcloud#503]
Hi Devs,

First of all Great Work!

After updateing OnlyOffice to 7.1.0 I can no longer open Documents in Nextcloud app.
It continues to spin forever.

I saw an excpetion in the nextcloud log files:

Here is the complete report:
Steps to reproduce

1, Open nextcloud app on android
2, Click .xlsx document
3, Only Office opens
4, Continues to spin without loading Document Server
Expected behaviour

1, Open nextcloud app on android
2, Click .xlsx document
3, Only Office opens
4, Only Oiffces Loads document server und xlsx file ist shown
Actual behaviour

File is not shown only Spinning after a while the message Loading takes very long … Back appears
Server configuration detail

Operating system: Linux 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64

Webserver: Apache/2.4.38 (Debian) (apache2handler)

Database: mysql 10.3.29

PHP version:

7.3.29-1~deb10u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, exif, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

Nextcloud version: 21.0.3 - 21.0.3.1

Updated from an older Nextcloud/ownCloud or fresh install:

Where did you install Nextcloud from:
Signing status
List of activated apps
Configuration (config/config.php)

Are you using external storage, if yes which one: local/smb/sftp/…

Are you using encryption: 1

Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/Webdav/…
Client configuration

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0

Operating system:
Logs
Web server error log

Nextcloud log

[index] Error: Exception: Call to a member function getTagsForObjects() on null at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/App.php line 157
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Onlyoffice\C ... {}, "config")
1. /var/www/nextcloud/lib/private/Route/Router.php line 302
   OC\AppFramework\App::main("OCA\\Onlyoffice ... r", "config", OC\AppFramework\ ... {}, {fileId: "0",_ro ... "})
2. /var/www/nextcloud/lib/base.php line 993
   OC\Route\Router->match("/apps/onlyoffice/ajax/config/0")
3. /var/www/nextcloud/index.php line 37
   OC::handleRequest()

GET /index.php/apps/onlyoffice/ajax/config/0?filePath=%2Fggg.xlsx&directToken=eyJ0eXAiJhbGciOiJXOiJKASDFGHJHV1QilkIjoyNzI1ODcsImFjdGlvbIUzI1NiJ9.eyJ1c2VySWQiOiJmbG9uZiI6ImRpcmVjdCIsImlhdCzk4MASDFGHZXoxNjI3OI6MTYyNTgwNDYzfQ.dqwG4aDV6GASDFGHjBLKMKhoD8JTkawL-wgPr2a8&inframe=true
from 1.1.1.1 at 2021-08-03T08:47:15+00:00

Caused by Error: Call to a member function getTagsForObjects() on null

    /var/www/nextcloud/apps/onlyoffice/controller/editorcontroller.php - line 1271:

    OCA\Onlyoffice\Controller\EditorController->isFavorite(272587)

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 218:

    OCA\Onlyoffice\Controller\EditorController->config(272587, "/test.xlsx", null, "eyJ0eXAiOiJ ... 0", 0, true, false, null, false, null)

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 127:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Onlyoffi ... {}, "config")

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 157:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Onlyoffi ... {}, "config")

    /var/www/nextcloud/lib/private/Route/Router.php - line 302:

    OC\AppFramework\App::main("OCA\\Onlyof ... r", "config", OC\AppFramew ... {}, { fileId: "0 ... "})

    /var/www/nextcloud/lib/base.php - line 993:

    OC\Route\Router->match("/apps/onlyo ... 0")

    /var/www/nextcloud/index.php - line 37:

    OC::handleRequest()

[no app in context] Info: Deprecated event type for {"[object] (OCP\SabrePluginEvent)":{"*statusCode":200,"*message":"","*server":{"[object] (OCA\DAV\Connector\Sabre\Server)":{"tree":"[object] (OCA\DAV\Connector\Sabre\ObjectTree)","*baseUri":"/remote.php/webdav/","httpResponse":"[object] (Sabre\HTTP\Response)","httpRequest":"[object] (Sabre\HTTP\Request)","sapi":"[object] (Sabre\HTTP\Sapi)","*plugins":[],"transactionType":null,"protectedProperties":{"...":"Over 20 items, aborting normalization"},"debugExceptions":false,"resourceTypeMapping":[],"enablePropfindDepthInfinity":true,"xml":"[object] (Sabre\DAV\Xml\Service)","*logger":null,"*listeners":{"...":"Over 20 items, aborting normalization"},"*wildcardListeners":[],"*listenerIndex":[]}},"Symfony\Contracts\EventDispatcher\EventpropagationStopped":false}}: null

PROPFIND /remote.php/webdav/test.xlsx
from 1.1.1.1 by user at 2021-08-03T08:48:49+00:00

Browser log

Thank you.
Any hints would be welcome.

Also there is a topic in nextcloud:
https://help.nextcloud.com/t/only-office-not-starting-in-android-nextcloud-app-exception-in-log-files-after-update-to-7-1-0/121202

At last: Still Great Work!

**Comment by bluesky-ca** [comment]
Same problem - both iPad OS and Android Nextcloud app will not open files assigned to Onlyoffice - other file types open fine.   In my case I tried docx, pptx and xlsx.
When using a browser from the same devices, Onlyoffice opens files correctly.
Tested with 2 servers, both running v21.0.3.1, Onlyoffice v 7.1.0, php 7.3

``[index] Error: Exception: Call to a member function getTagsForObjects() on null at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/App.php line 157
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Onlyoffice\C ... {}, "config")
1. /var/www/nextcloud/lib/private/Route/Router.php line 302
   OC\AppFramework\App::main("OCA\\Onlyoffice ... r", "config", OC\AppFramework\ ... {}, {fileId: "0",_ro ... "})
2. /var/www/nextcloud/lib/base.php line 993
   OC\Route\Router->match("/apps/onlyoffice/ajax/config/0")
3. /var/www/nextcloud/index.php line 37
   OC::handleRequest()

**Comment by florom** [comment]
@LinneyS

Thank you Devs for fast fix and release.
It works again.

**Comment by bluesky-ca** [comment]
I tested on both iPad and Android and it now works - thanks.   
On the iPad one gets 2 back arrows - one clearly takes one back to the Nextcloud app, the other to the Nextcloud login page - a bit confusing but not too bad.  On Android one really only can see one arrow that takes back to Nextcloud login - to get back to the Nextcloud app one has to press the built in Android back button ie <  - this does not see like very intuitive design.   It could be my settings or just the limitations of the Android on a phone.
