### ISSUE TITLE
Convert error - Host violates local access rules

### ISSUE THREAD

**Issue by mvvvmd** [ONLYOFFICE/onlyoffice-nextcloud#508]
Nextcloud version: 22.1.0
ONLYOFFICE connector version: 7.1.2

When converting a ODF file from the context menu this fails with the error "Host violates local access rules"

**Comment by china-live** [comment]
Same question

**Comment by acsfer** [comment]
Try https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/293#issuecomment-640095603

**Comment by mvvvmd** [comment]
Great, that works, perhaps the app can show a message for the admin if this is set to false.

**Comment by LinneyS** [comment]
Probably this is a question for Nextcloud team
