### ISSUE TITLE
Onlyoffice not update

### ISSUE THREAD

**Issue by rungis86** [ONLYOFFICE/onlyoffice-nextcloud#509]
Hello,

I'm sorry for my english level.
I have onlyoffice installed on nextcloud 20.0.12

I note that on the nextcloud applications management, onlyoffice version is 7.1.2 but when I open onlyoffice, its version is 6.1.0

I always make updates but I had not checked before in onlyoffice and I think 6.1.0 is the version that I have installed at beginning.

Do someone know this problem ?

Thanks

Rémi

**Comment by acsfer** [comment]
Please note that Application at Nextcloud (the connector) and OnlyOffice Document Server are separate products, so they have different versions.

The first, you can update at Nextcloud GUI, the 2nd, you must upgrade it where it is installed, but it very depends on how it is installed (Docker, Binaries...)

**Comment by rungis86** [comment]
Thank you, I understand.
Onlyoffice run in docker on thé same server that nextcloud (debian).
I will see how update onlyoffice in docker.

**Comment by acsfer** [comment]
See https://helpcenter.onlyoffice.com/installation/docs-community-update-docker.aspx
