### ISSUE TITLE
Error PHP implode(): Invalid arguments passed at /var/www/html/nextcloud/apps/onlyoffice/templates/settings.php#66

### ISSUE THREAD

**Issue by Githopp192** [ONLYOFFICE/onlyoffice-nextcloud#51]
### Steps to reproduce
Setup ONLYOFFICE in the Nextcloud GUI - PHP ERROR will pop-up

Info	onlyoffice	Set groups: null	2019-01-04T14:47:14+0100
Info	onlyoffice	Set opening in a same tab: false	2019-01-04T14:47:14+0100
Info	onlyoffice	Set editing formats: {"csv":"true","odp":"false","ods":"false","odt":"false","rtf":"false","txt":"true"}	2019-01-04T14:47:14+0100
Info	onlyoffice	Set default formats: {"csv":"false","doc":"false","docm":"false","docx":"true","dotx":"false","epub":"false","html":"false","odp":"false","ods":"false","odt":"false","pdf":"false","potm":"false","potx":"false","ppsm":"false","ppsx":"true","ppt":"false","pptm":"false","pptx":"true","rtf":"false","txt":"true","xls":"false","xlsm":"false","xlsx":"true","xltm":"false","xltx":"false"}	2019-01-04T14:47:14+0100
Info	onlyoffice	Set secret key	2019-01-04T14:47:11+0100
Info	onlyoffice	SetStorageUrl: 	2019-01-04T14:47:11+0100
Info	onlyoffice	SetDocumentServerInternalUrl: 	2019-01-04T14:47:11+0100
Info	onlyoffice	SetDocumentServerUrl: https://xxxxxx/	2019-01-04T14:47:11+0100
Error	PHP	implode(): Invalid arguments passed at /var/www/html/nextcloud/apps/onlyoffice/templates/settings.php#66	2019-01-04T14:47:07+0100

Logs-entries from /var/log/Messages -->

Jan  4 14:40:01 xxxsystemd: Started Session 13415 of user root.
Jan  4 14:42:30 xxxx journal: Flushing stats at  Fri Jan 04 2019 13:42:30 GMT+0000 (UTC)#015
Jan  4 14:42:30 xxxx journal: { counters: #015
Jan  4 14:42:30 xxxx journal:   { 'statsd.bad_lines_seen': 0,#015
Jan  4 14:42:30 xxxx journal:     'statsd.packets_received': 0,#015
Jan  4 14:42:30 xxxx journal:     'statsd.metrics_received': 0 },#015
Jan  4 14:42:30 xxxx journal:  timers: {},#015
Jan  4 14:42:30 xxxx journal:  gauges: { 'statsd.timestamp_lag': -1 },#015
Jan  4 14:42:30 xxxx journal:  timer_data: {},#015
Jan  4 14:42:30 xxxx journal:  counter_rates: #015
Jan  4 14:42:30 xxxx journal:   { 'statsd.bad_lines_seen': 0,#015
Jan  4 14:42:30 xxxx journal:     'statsd.packets_received': 0,#015
Jan  4 14:42:30 xxxx journal:     'statsd.metrics_received': 0 },#015
Jan  4 14:42:30 xxxx journal:  sets: {},#015
Jan  4 14:42:30 xxxx journal:  pctThreshold: [ 90 ] }#015

On The Docker-Document-Server are no relevant error Messages seen.

### Expected behaviour
no PHP Errors; ONLYOFFICE is functional

### Actual behaviour
the ONLYOFFICE Application will run on another Document Server (Docker Installation). 
This Server can be properly reached through https://xxxx
The Nextcloud ONLYOFFICE APP can be enabled;
The Configuration wizard will successfully complete; but PHP Errors will Show into the Nextcloud Log

Office Documents cannot be opened by the Nextcloud Onlyoffice APP; message "ONLYOFFICE is currently not reachable" .. 

## Server configuration detail

**Operating system:** Linux 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64

**Webserver:** Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.1.24 (apache2handler)

**Database:** mysql 5.5.60

**PHP version:** 

7.1.24
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, apcu, bcmath, bz2, calendar, ctype, curl, dba, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, ldap, exif, mcrypt, mysqli, PDO, pdo_mysql, pdo_sqlite, Phar, posix, redis, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, wddx, xmlreader, xmlwriter, xsl, memcached, zip, Zend OPcache

**Nextcloud version:** 14.0.4 - 14.0.4.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** Nextcloud Source (Upgrade) from NC 13.0.7

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.0.1
 - activity: 2.7.0
 - announcementcenter: 3.3.1
 - apporder: 0.6.0
 - audioplayer: 2.5.1
 - bookmarks: 0.15.1
 - bruteforcesettings: 1.3.0
 - calendar: 1.6.4
 - circles: 0.15.2
 - cloud_federation_api: 0.0.1
 - comments: 1.4.0
 - contacts: 2.1.8
 - data_request: 1.1.0
 - dav: 1.6.0
 - deck: 0.5.2
 - drop_account: 0.0.13
 - federatedfilesharing: 1.4.0
 - federation: 1.4.0
 - files: 1.9.0
 - files_antivirus: 1.4.2
 - files_fulltextsearch: 1.1.1
 - files_pdfviewer: 1.3.2
 - files_rightclick: 0.8.4
 - files_sharing: 1.6.2
 - files_texteditor: 2.6.0
 - files_trashbin: 1.4.1
 - files_versions: 1.7.1
 - files_videoplayer: 1.3.0
 - firstrunwizard: 2.3.0
 - flowupload: 0.0.9
 - fulltextsearch: 1.1.0
 - gallery: 18.1.0
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.2.0
 - mindmaps: 0.1.0
 - mood: 0.4.0
 - nextcloud_announcements: 1.3.0
 - notes: 2.5.1
 - notifications: 2.2.1
 - oauth2: 1.2.1
 - onlyoffice: 2.1.2
 - ownbackup: 18.11.0
 - passman: 2.2.1
 - password_policy: 1.4.0
 - polls: 0.9.5
 - provisioning_api: 1.4.0
 - quicknotes: 0.1.5
 - quota_warning: 1.3.0
 - radio: 0.6.4
 - rainloop: 6.0.2
 - ransomware_protection: 1.2.0
 - serverinfo: 1.4.0
 - sharebymail: 1.4.0
 - sharerenamer: 2.3.0
 - socialsharing_diaspora: 1.0.3
 - socialsharing_email: 1.0.4
 - socialsharing_facebook: 1.0.3
 - socialsharing_googleplus: 1.0.3
 - socialsharing_twitter: 1.0.3
 - spreed: 4.0.2
 - support: 1.0.0
 - survey_client: 1.2.0
 - systemtags: 1.4.0
 - tasks: 0.9.8
 - theming: 1.5.0
 - twofactor_backupcodes: 1.3.1
 - twofactor_totp: 1.5.0
 - updatenotification: 1.4.1
 - workflowengine: 1.4.0
Disabled:
 - admin_audit
 - carnet
 - cms_pico
 - encryption
 - external
 - files_external
 - files_markdown
 - impersonate
 - jsloader
 - phonetrack
 - richdocuments
 - user_external
 - user_ldap
 - weather

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "memcache.local": "\\OC\\Memcache\\APCu",
    "filelocking.enabled": true,
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "dbindex": 0,
        "timeout": 1.5
    },
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "xxxxx",
        "xxxxx"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/xxxxx",
    "htaccess.RewriteBase": "\/",
    "overwriteprotocol": "https",
    "dbtype": "mysql",
    "version": "14.0.4.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 1,
    "updater.release.channel": "production",
    "auth.bruteforce.protection.enabled": true,
    "check_for_working_htaccess": true,
    "data-fingerprint": "0xxxxxx65",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "xxx",
    "session_lifetime": 1200,
    "session_keepalive": false,
    "logtimezone": "Europe\/xxxx",
    "logfile": "\/media\/log\/nextcloud.log",
    "knowledgebaseenabled": false,
    "log_rotate_size": 3145728,
    "onlyoffice": {
        "verify_peer_off": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** 
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134

**Operating system:** Windows 10

**Comment by LinneyS** [comment]
Fixed 013b9ff113142771e41c3bbc8de94f5d6c5ff55c

**Comment by teodorch85** [comment]
Same issue here!
First time install so can't wait for a fixed release!

**Comment by Githopp192** [comment]
I do get the same (new) error (php#444) and (php#66) still occrs ..
What i did:
download the ZIP from 013b9ff
replace NC-App (onlyoffice) in orginal place
changed owner to Apache (-R flag)
enabled the onlyoffice app
ReRun the onlyoffice configuration wizard (was successful)
tried to open an MS-Office Document
and check the nextcloud.log --->>
Info | onlyoffice | Set groups: null | 2019-01-09T18:10:33+0100
Error | PHP | Undefined variable: limitGroups at /var/www/html/nextcloud/apps/onlyoffice/lib/appconfig.php#444 | 2019-01-09T18:10:33+0100
Info | onlyoffice | Set opening in a same tab: false | 2019-01-09T18:10:33+0100
Info | onlyoffice | Set editing formats: {"csv":"true","odp":"false","ods":"false","odt":"false","rtf":"false","txt":"true"} | 2019-01-09T18:10:33+0100
Info | onlyoffice | Set default formats: {"csv":"false","doc":"false","docm":"false","docx":"true","dotx":"false","epub":"false","html":"false","odp":"false","ods":"false","odt":"false","pdf":"false","potm":"false","potx":"false","ppsm":"false","ppsx":"true","ppt":"false","pptm":"false","pptx":"true","rtf":"false","txt":"true","xls":"false","xlsm":"false","xlsx":"true","xltm":"false","xltx":"false"} | 2019-01-09T18:10:33+0100
Info | onlyoffice | Set secret key | 2019-01-09T18:10:24+0100
Info | onlyoffice | SetStorageUrl: | 2019-01-09T18:10:24+0100
Info | onlyoffice | SetDocumentServerInternalUrl: | 2019-01-09T18:10:24+0100
Info | onlyoffice | SetDocumentServerUrl: https://xxxx:yyyy/ | 2019-01-09T18:10:24+0100
Error | PHP | implode(): Invalid arguments passed at /var/www/html/nextcloud/apps/onlyoffice/templates/settings.php#66 | 2019-01-09T18:10:16+0100

**Comment by LinneyS** [comment]
@Githopp192 thx
Try now

**Comment by Githopp192** [comment]
LinneyS .. you'r the BEST :-) Thx a lot .. now it works without any error since.
Thx for your great help and support. 

(was the first time .. i succeeded with Integration of OnlyOffice in my productive Environment)

Great !

Wish you a nice day
Best Regards
Mike

**Comment by MorrisJobke** [comment]
@LinneyS @CarlOnlyoffice Mind to close this ticket then? So it's properly identifiable as resolved. Thanks
