### ISSUE TITLE
how to disable https address for document server

### ISSUE THREAD

**Issue by kyhuynhduc** [ONLYOFFICE/onlyoffice-nextcloud#512]
Dear team,
can we change seting to disable https address ? we setup local service and don't need to user ssl 
please addvise
![Ảnh chụp Màn hình 2021-08-26 lúc 15 15 38](https://user-images.githubusercontent.com/36893030/130927239-bb0ecdeb-370b-4123-968c-759095913b9d.png)

**Comment by SergeyKorneyev** [comment]
Hello,
It's not possible to use HTTP for the Document Server if Nextcloud is accessed via HTTPS. That would create mixed content, which is blocked in most browsers for security reasons.
