### ISSUE TITLE
Mention feature doesn't respect privacy rules in place

### ISSUE THREAD

**Issue by ImaCrea** [ONLYOFFICE/onlyoffice-nextcloud#514]
Hello there,

Thanks for the implementation of mention in comments ! It's a great new feature which will add a lot of value.

Not sure if it's a bug or a feature request, but at the moment I noticed the autocompletion doesn't respect privacy rules set in Nextcloud.

For example, we have an instance that is shared between different organisations. For that reason, in the "privacy" section in Nextcloud Administration panel we disabled autocompletion and also restricted sharing between members of a same group.

That would be great if the onlyofffice mention module in the comment section of a document could also apply the same rules. Because at the moment, it reveals all the users (and their emails!) with an account on our instance :/

Thanks for your help

**Comment by pierreozoux** [comment]
And is there a way to deactivate this feature in the mean time?
(I searched without success)

**Comment by pierreozoux** [comment]
Search to "deactivate" it with css, no luck.

Looks like related to this issue:
https://github.com/nextcloud/server/issues/27478

**Comment by wilkis3** [comment]
> And is there a way to deactivate this feature in the mean time? (I searched without success)

Yes, you can use the `develop` branch.
```
cd nextcloud
cd apps # Go into your Nextcloud apps directory
mv onlyoffice onlyoffice.bak # Rename or delete your old onlyoffice app folder
git clone https://github.com/ONLYOFFICE/onlyoffice-nextcloud.git
mv onlyoffice-nextcloud/ onlyoffice
cd onlyoffice
git checkout develop # Checkout develop branch
```
If you update the onlyoffice App, all changes will probably be overwritten.

**Comment by ClundXIII** [comment]
Hello,

we have a very similar Problem. The Email Addresses are being shown for every user. Since we have a lot of user who should not have access to everyones Email Address, this is a huge issue.
