### ISSUE TITLE
No mention autocomplete

### ISSUE THREAD

**Issue by LucaOverflow** [ONLYOFFICE/onlyoffice-nextcloud#515]
Hello,

I'm using Onlyofiice for a few days now and the mention feature is not working like it should in my case. Initially I tried the document-server app in nextcloud. In the comments i could mention fellow nextcloud users and they would get a notification. Sadly this version didn't save any of the edited files, which I had to find out the hard way.
Now I'm using a seperate document server in a docker container. My Nextcloud instance is running in the same docker environment. Everything seems to be working now, but when I type a "+" or "@" There is no popup with users. If i type the full email-address manually nextcloud will send a notification.

Could there be a misconfiguration?
Thanks in advance.
Greetings Luca

**Comment by SergeyKorneyev** [comment]
Hello Luca,
Do users in your Nextcloud instance have email addresses attached? At the moment, mentions do not work with users with the empty "email" attribute.

Also, regarding your first attempt: note that the document-server app you mentioned is developed by Nextcloud, not us, so it may not have all the features that the standalone ONLYOFFICE Document Server has.

**Comment by LucaOverflow** [comment]
Yes the users have email addresses atatched. Actually both in the user settings and as an contact since those dont sync over to the mail app for whatever reason. With the document-server-app the mention feature worked like intended. It's with the standalone server that is's not working properly anymore. Or iss this behavior expected?

**Comment by LucaOverflow** [comment]
I'm on a new Nextcloud install now and it's working like it should. I guess there was some problem with the old installation.
Thanks for the help.
