### ISSUE TITLE
Cannot save docx documents

### ISSUE THREAD

**Issue by cabrillo** [ONLYOFFICE/onlyoffice-nextcloud#525]
Hi Guys,
  I just install onlyoffice document server app (0.1.11) and onlyoffice (7.1.2) in our nextcloud suit with 20.0.6 v.
  Documents are opened fine and we can edit, but docx documents can be save the is no error on dashboard but document is not saved, even autosave is forced but does not work...xls files are saved fine.

Any Idea About this error. Any help is welcomed.

I attach a pic with the selected conf options for onlyoffice app.
![Selección_136](https://user-images.githubusercontent.com/7745602/134057203-db1f01bc-5d8f-4882-8e5b-ce75591103a2.png)

Regards, I

**Comment by ShockwaveNN** [comment]
> I just install onlyoffice document server app (0.1.11)

Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate [GitHub repository](https://github.com/nextcloud/documentserver_community). 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://forum.onlyoffice.com/t/community-document-server-app-in-nextcloud-18/268).
