### ISSUE TITLE
Navigation panel not showing full TOC

### ISSUE THREAD

**Issue by enyusmile** [ONLYOFFICE/onlyoffice-nextcloud#526]
https://github.com/ONLYOFFICE/DocumentServer/issues/1368

Has onlyoffice nextcloud fixed this problem?

**Comment by enyusmile** [comment]
nextcloud 21.0.1
ONLYOFFICE	7.1.2
chrome 93.x及以上版本

还有这个问题

**Comment by ShockwaveNN** [comment]
Yes, we fixed this problem, you should upgrade your DocumentServer to latest stable v6.4.0 (you didn't specify version of DocumentServer in your post)

But if you using Community Document Server:

Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate [GitHub repository](https://github.com/nextcloud/documentserver_community). 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://forum.onlyoffice.com/t/community-document-server-app-in-nextcloud-18/268).
