### ISSUE TITLE
Error when trying to connect (Bad Request or timeout error).... NO WAY :(

### ISSUE THREAD

**Issue by cartenca** [ONLYOFFICE/onlyoffice-nextcloud#53]
I've 2 server, both with Ubuntu 16.04.5 LTS, 
the first has Nextcloud 14 working on, ...https://cloud.tenca.com
in the second is installed Docker Onlyoffice Enterprise Edition with trial license....https://testfarm.tenca.cloud
both servers have SSL with letsencrypt.
I've installed onlyoffice-owncloud 2.1.2.
I tried to configure onlyoffice-owncloud, but I have always "Error when trying to connect (Bad Request or timeout error)" ...

wget Docker OO -> NC is ok
wget NC --> Docker OO is ok

anyway I've tried:   
'onlyoffice' =>
  array (
    'verify_peer_off' => TRUE,
  )

on config.php ... 
and than

"rejectUnauthorized": true

.... :(

PLEASE HELP ME!  
Because I had a Enterprise Edition license but I cannot renew it if my server doesn't work....
Carlo

![2019-01-02_14-20-30](https://user-images.githubusercontent.com/30172009/50594716-f388e480-0e9d-11e9-9aa7-abc469966aa8.png)
![2019-01-02_14-19-37 1](https://user-images.githubusercontent.com/30172009/50594718-f4217b00-0e9d-11e9-9e1c-40314f20649b.png)
![2019-01-02_14-19-37](https://user-images.githubusercontent.com/30172009/50594719-f4217b00-0e9d-11e9-8547-40e212c122b8.png)
![2019-01-02_14-17-30](https://user-images.githubusercontent.com/30172009/50594720-f4217b00-0e9d-11e9-8404-c89c0b4d79ea.png)
![2019-01-02_14-16-56](https://user-images.githubusercontent.com/30172009/50594721-f4217b00-0e9d-11e9-928e-ce5f4dca14dc.png)
![2019-01-02_14-16-31](https://user-images.githubusercontent.com/30172009/50594722-f4217b00-0e9d-11e9-8f5c-e59cf9545691.png)
![2019-01-02_14-15-59](https://user-images.githubusercontent.com/30172009/50594723-f4ba1180-0e9d-11e9-8ecf-63a4799079b5.png)

**Comment by ibnpetr** [comment]
@cartenca Please change the to **https://servername/ds-vpath/** in case you are going to connect your NC instance to the Enterprise Edition.
