### ISSUE TITLE
How can I enable version history in Nextcloud OO

### ISSUE THREAD

**Issue by nicedevil007** [ONLYOFFICE/onlyoffice-nextcloud#535]
Heya, I just read that the version history was implemented in the Nextcloud integration of OnlyOffice at the end of last year.
Just want to reference to this issue => https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/194

Unfurtunately I can't find an option to activate it?

I'm using the latest version of the docker image => onlyoffice/documentserver

The Versions app of nextcloud is in use and is working for normal documents as it shoud.

Anything I can provide to debug this?

**Comment by SergeyKorneyev** [comment]
Hi,
If you have at least version 5.0.0 of the ONYLOFFICE connector app installed, the version history accessed from the editor should always be enabled regardless of the Versions app.
