### ISSUE TITLE
Safari gives "An error has occured while opening the file"

### ISSUE THREAD

**Issue by catorghans** [ONLYOFFICE/onlyoffice-nextcloud#541]
Our client had onlyoffice 6.3.1 and nextcloud 22.2.0.

They got with safari for every office document a popup with
"An error has occured while opening the file.
Press "OK" to return to document list"

We had no such issues, but also an older nextcloud.
After we upgraded we can confirm these version have a safari issue.

**Comment by SergeyKorneyev** [comment]
Hello,
Could you post a screenshot of the error?

**Comment by catorghans** [comment]
![OnlyofficeSafari](https://user-images.githubusercontent.com/961049/140900235-7bd3c552-6fda-44f0-bcc5-230067313c0b.jpeg)

Similar in an English version of nextcloud.

**Comment by SergeyKorneyev** [comment]
Document Server logs should contain errors that might explain this. Could you share them here?

**Comment by catorghans** [comment]
in nextcloud.log I see:
`{"reqId":"Rafv0G4gXf7SDVTo8vRR","level":3,"time":"2021-11-10T10:55:27+00:00","remoteAddr":"","user":"--","app":"documentserver_community","method":"","url":"--","message":{"Exception":"OCA\\DocumentServer\\Document\\DocumentConversionException","Message":"Uncaught TypeError: Cannot read property 'uOe' of undefined\nDoctRenderer:<result><error index=\"56090\" /></result>\n","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/documentserver_community/lib/DocumentConverter.php","line":125,"function":"run","class":"OCA\\DocumentServer\\Document\\ConverterBinary","type":"->","args":["/tmp/oc_tmp_4ikWf2-.xml",null]},{"file":"/var/www/nextcloud/apps/documentserver_community/lib/DocumentConverter.php","line":80,"function":"runCommand","class":"OCA\\DocumentServer\\DocumentConverter","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Document\\ConvertCommand"}]},{"file":"/var/www/nextcloud/apps/documentserver_community/lib/Document/DocumentStore.php","line":156,"function":"saveChanges","class":"OCA\\DocumentServer\\DocumentConverter","type":"->","args":["*** sensitive parameter replaced ***",["78;AgAAADEA//8BAIKs7i7m1QAApwAAAAMAAAAYAAAAGAAAABgAAACCAAAAggAAABwAAAA2AC4AMwAuADEALgAzADIALgBAAEAAUgBlAHYA","76;DAAAADMAXwAyADAANQA4AAIAHAAEAAAAXgAAAAEAAAB0AAAAXgAAAAEAAABoAAAAXgAAAAEAAABlAAAAXgAAAAIAAAAgAAAAAAAAAA==","40;DAAAADMAXwAyADAANQA4AAEAHAABAAAAXgAAAAIAAAAgAAAAAwAAAA==","40;DAAAADMAXwAyADAANQA4AAEAHAABAAAAXgAAAAEAAABhAAAAAwAAAA=="],"/var/www/nextcloud/data/appdata_f202f3ab842c4/documentserver_community/doc_4044320922/saved.docx","docx"]},{"file":"/var/www/nextcloud/apps/documentserver_community/lib/LocalAppData.php","line":102,"function":"OCA\\DocumentServer\\Document\\{closure}","class":"OCA\\DocumentServer\\Document\\DocumentStore","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/documentserver_community/lib/Document/DocumentStore.php","line":176,"function":"getReadWriteLocalPath","class":"OCA\\DocumentServer\\LocalAppData","type":"->","args":[{"__class__":"OC\\Files\\SimpleFS\\SimpleFolder"},{"__class__":"Closure"}]},{"file":"/var/www/nextcloud/apps/documentserver_community/lib/Document/SaveHandler.php","line":58,"function":"saveChanges","class":"OCA\\DocumentServer\\Document\\DocumentStore","type":"->","args":[4044320922,[{"__class__":"OCA\\DocumentServer\\Document\\Change"},{"__class__":"OCA\\DocumentServer\\Document\\Change"},{"__class__":"OCA\\DocumentServer\\Document\\Change"},{"__class__":"OCA\\DocumentServer\\Document\\Change"},{"__class__":"OCA\\DocumentServer\\Document\\Change"},"And 56210 more entries, set log level to debug to see all entries"]]},{"file":"/var/www/nextcloud/apps/documentserver_community/lib/BackgroundJob/Cleanup.php","line":71,"function":"flushChanges","class":"OCA\\DocumentServer\\Document\\SaveHandler","type":"->","args":[4044320922]},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/Job.php","line":80,"function":"run","class":"OCA\\DocumentServer\\BackgroundJob\\Cleanup","type":"->","args":[null]},{"file":"/var/www/nextcloud/cron.php","line":127,"function":"execute","class":"OCP\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/var/www/nextcloud/apps/documentserver_community/lib/Document/ConverterBinary.php","Line":66,"CustomMessage":"Error while applying changes for document 4044320922"},"userAgent":"--","version":"20.0.9.1"}
`

**Comment by LinneyS** [comment]
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://forum.onlyoffice.com/t/community-document-server-app-in-nextcloud-18/268).
