### ISSUE TITLE
Previews no longer available since update to 7.2.0

### ISSUE THREAD

**Issue by Chartman123** [ONLYOFFICE/onlyoffice-nextcloud#544]
I'm not sure, if it's really related to the latest update to 7.2.0, but since then all my previews of office files have disappeared from my Nextcloud and don't get created for new files. The setting to create preview files with Onlyoffice is still set.

However, there are no log entries in the browser console or the Nextcloud log.

**Comment by hobbsecky** [comment]
Same problem. Integrated OO 7.2.0 on NC 22.2.0.

**Comment by hobbsecky** [comment]
Reverting to OO 7.1.2 resolves this issue. Something broke previews in the latest update.

**Comment by hobbsecky** [comment]
Updated to 7.2.0 and made the modifications to application.php from Fix #544 and everything is working. Thanks!

**Comment by jakobroehrl** [comment]
In the nextcloud dashboard the previews are there, but not in the file view.

**Comment by Chartman123** [comment]
I can confirm that it has been fixed now. Thank you!
