### ISSUE TITLE
Onlyoffice app error, unable to load editor

### ISSUE THREAD

**Issue by Engineer-of-Stuff** [ONLYOFFICE/onlyoffice-nextcloud#55]
I'm having some problems with the Onlyoffice app. It won't load the document and throws an error.

I've installed the document server docker on a different machine than my Nextcloud server. The document server shows the green status page. I have the document server behind a reverse proxy so I can do HTTPS easier.

In the settings page I put https://office.mydomain.com in the "Document Editing Service address" field. The page accepts it. In the file manager I can create a docx and open it. The editor loads and then presents an unknown error. In the console it loaded a resource from the document server, but the resource wasn't from the https://office.mydomain.com domain but was the document server's HTTP IP address. I think this is where the error is coming from.

```
Blocked loading mixed active content “http://192.168.0.66/cache/files/3370126106/Editor.bin/Editor.bin?md5=MWbCCzUtKBel-zNjvbozaA==&expires=1549760571&disposition=attachment&ooname=output.bin”
```

How do I fix this?

---
I'm on NC v14.0.4.2 and have whatever the most recent version of the Onlyoffice app is.

**Comment by alexanderonlyoffice** [comment]
Hello @Engineer-of-Stuff, it seems the problem is that X-Forwarded-Proto and X-Forwarded-Host headers are not forwarded to the Document Server by your proxy server. Please follow this [link](https://github.com/ONLYOFFICE/document-server-proxy) to find the examples of configs for different web servers.

**Comment by Engineer-of-Stuff** [comment]
That fixed it. If anyone needs my Nginx config, [here it is](https://gitlab.com/drakepanzer/drake-examples/blob/master/Other/Nginx/nginx-onlyoffice-documentserver.conf).
