### ISSUE TITLE
the documenttype parameter for the config object is invalid

### ISSUE THREAD

**Issue by wuast94** [ONLYOFFICE/onlyoffice-nextcloud#551]
when trying to open a document i get the error: "the documenttype parameter for the config object is invalid"

Nextcloud version: 22.2.2
OO Version: latest docker tag from official oo repo
APP Version: 7.2.0

when using the dicument server direct i have no problems open files etc

edit: updated to 22.2.3 - same problem

**Comment by SergeyKorneyev** [comment]
Hi,
Could you specify the exact Document Server version you have installed?

**Comment by wuast94** [comment]
dont know why, but its working again, the "Over Night Magic", i didnt change anything, versions are all the same as before. 

I close this issue for now, when there are any new infos we can reopen it.

**Comment by tutle** [comment]
Hello
Just update the onlyoffice plugin to 7.2.0 in my 22.2.0 nextcloud instance on yunohost server (with onlyoffice application).
It was perfectly working before
Any suggestion ?
![onlyoffice error](https://user-images.githubusercontent.com/23037149/144298757-a2311220-ccc1-4b27-bc09-686d5a57f1eb.jpg)
e.

**Comment by LinneyS** [comment]
Hi all
[document server v6.0 and earlier is no longer supported](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/master/CHANGELOG.md#changed-1)

**Comment by tutle** [comment]
my release of document server is 6.4.0~ynh2. any newer release ?

**Comment by SergeyKorneyev** [comment]
Hello @tutle 
Judging by the "ynh2" in your response, I assume you're using [this](https://github.com/YunoHost-Apps/onlyoffice_ynh) package, which is created by a third party and is not officially supported by us.
