### ISSUE TITLE
Users on share link get "not permitted" instead of document downloading

### ISSUE THREAD

**Issue by putt1ck** [ONLYOFFICE/onlyoffice-nextcloud#557]
Since 7.2, users accessing a share link (when OnlyOffice is set to restricted use) get "not permitted" when they click on a document, instead of the document downloading. While I can see some people wanted it documents to open in OnlyOffice directly, it's equally valid to want to restrict access to the OnlyOffice functionality; suggested fix would be to still return the "not permitted" screen but within that have a link to download the document. Additionally the not permitted message should be more verbose e.g. "direct editing not permitted, please download document instead" with the latter containing the download link.

**Comment by alphafalcon** [comment]
Might be caused by f8ed80bd5000987b49e55119f6126b4aa26696c2 

Maybe @Antipkin-A could chime in if this was intended.

I believe that disallowing guests from using the document editor is logical when restricting OO to groups but in that case guests should no be redirected to the editor.

**Comment by LinneyS** [comment]
The problem with "not permitted" has been fixed
