### ISSUE TITLE
Browser takes me to ppreedme/talk app

### ISSUE THREAD

**Issue by Pisoko** [ONLYOFFICE/onlyoffice-nextcloud#57]
Hey,

since nexctloud 15 I have the following issue.
When creating or editing a document in onlyoffice some users use the "back to page" button of the browser to navigate back to nextcloud files. Since upgrading to nextcloud 15 it takes them to https://URL/apps/spreed (nextcloud talk).

Can someone reproduce this?

**Comment by alexanderonlyoffice** [comment]
Hello @Pisoko, we will try to reproduce the described issue and I will notify you about the result.

**Comment by alexanderonlyoffice** [comment]
@Pisoko, please specify step-by-step scenario in details. Specify also if the setting "Open in the same tab" is enabled or disabled on ONLYOFFICE integration app settings page in Nextcloud (see this [screenshot](https://monosnap.com/file/5H2pOzS7F0Huabp4PeElEafMk3dE7u)). 

Specify also which browser you use.

**Comment by Pisoko** [comment]
Nextcloud version: 15.0.2
OnlyOffice version: 2.1.2

[Settings screenshot](https://cloud.lis.school/s/onlyoffice)

With any user:

1. Create a new Document/ExcelSheet/Presentation (URL: _https://**********/apps/files/_)

2. Wait until the document is created - now you're inside the document (URL: _https://*********.school/apps/onlyoffice/4526315_

3. Use the "Go back on page" button of the browser (URL: _https://********.school/apps/spreed_ )


Tested with current firefox and chrome.
(and it doesn't matter if you creating or just editing a document)

**Comment by alexanderonlyoffice** [comment]
@Pisoko, unfortunately, we cannot reproduce the mentioned issue on our side. Could you please specify what catalogue _school_ presents in the URL address, this is not a folder, but something different. Might it be some application?

**Comment by Pisoko** [comment]
I recorded it:
https://cloud.lis.school/s/record

**Comment by alexanderonlyoffice** [comment]
@Pisoko, we succeded to reproduce the issue. Its reason is in Spreed application.

**Comment by LinneyS** [comment]
The problem does not repeat with version [5.0.1](https://github.com/nextcloud/spreed/releases/tag/v5.0.1)
