### ISSUE TITLE
Feature request: open files in new tab/window

### ISSUE THREAD

**Issue by ferfebles** [ONLYOFFICE/onlyoffice-nextcloud#572]
Please, add a new setting to edit files in a new tab. Or at least using ctrl+click as it was done in https://github.com/nextcloud/richdocuments/issues/31

**Comment by SergeyKorneyev** [comment]
Hi,
The option already exists in the connector settings
![chrome_2021-12-16_15-00-16](https://user-images.githubusercontent.com/77327210/146368072-f1856e67-f5f1-4ac6-8de3-2cb59870b92f.png)
:

**Comment by ferfebles** [comment]
Tested and working!!

Thank you very much and please forgive me for not reading carefully all the options :-(
