### ISSUE TITLE
Added: check document server version

### ISSUE THREAD

**Issue by VladoPortos** [ONLYOFFICE/onlyoffice-nextcloud#573]
What is that supported version of ONLYOFFICE... I can't find it mentioned anywhere... I get message: 
`Error when trying to connect (Not supported version) (version 5.6.4.20)`

But that's not very helpful without knowing what is the supported version...

**Comment by Antipkin-A** [comment]
Hi @VladoPortos 
Document server v6.0 and earlier is no longer supported.
You can find information to changelog: https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/master/CHANGELOG.md#changed-1
