### ISSUE TITLE
Adapt to new script loading mechanism (NC >= 23)

### ISSUE THREAD

**Issue by eneiluj** [ONLYOFFICE/onlyoffice-nextcloud#575]
Hey there.

From Nextcloud 23, it is possible to indicate a dependency (an app ID) when telling the backend to load a script. When using this dependency system, It is not needed to wait for the DOM to be loaded to call some registration functions. Script loading trees should make sure things are loaded and executed in the right order.

OnlyOffice script loading still works fine in NC 23 but is broken in NC 24.

For example, `onlyoffice/js/viewer.js` is loaded like that:
https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/1a51c8e8a7323341d6fdd7b9b9901e95a2d57da9/lib/listeners/viewerlistener.php#L58

This should now be done like that:
``` php
Util::addScript("onlyoffice", "viewer", "viewer");
```
because this script requires the viewer app's scripts to be loaded first.

In `onlyoffice/js/viewer.js`, `initPage()` can be called without waiting for document to be ready.
`$(document).ready(function() {` can be removed.

We can provide more explanation/insights if needed.
Cheers

cc @juliushaertl @mejo- @azul @luka-nextcloud

**Comment by LinneyS** [comment]
nc23 - #705 
nc24 - #637
