### ISSUE TITLE
DOCX editor opens files in readonly mode

### ISSUE THREAD

**Issue by biware-repo** [ONLYOFFICE/onlyoffice-nextcloud#576]
All docx files are opened or new created in read only mode. All controls in editor are visible, but disabled.

Other file types (pptx, xlsx) are opened properly and can be edited and saved.

Onlyoffice version: 6.2.2.21
Onlyoffice running: in docker
OS: UBUNTU 20.04.3 LTS (Linux 4.15.0-163-generic x86_64)
PHP: 7.4.27
MariaDB: 10.6.5
Nextcloud: 22.2.3

**Comment by LinneyS** [comment]
What mode do you have enabled in the editor?
![image](https://user-images.githubusercontent.com/8580527/150548578-07f6752e-d808-49a5-8c1f-9589427e5d52.png)

Possibly the administrator set the mode to open by default:
![image](https://user-images.githubusercontent.com/8580527/150548689-e048ff49-6e3a-4f25-b6b0-ec730d6648e5.png)

**Comment by DeepCollors** [comment]
[AtaZ991](https://github.com/AtaZ991) Thank you great friend
