### ISSUE TITLE
To show menu in toolbar

### ISSUE THREAD

**Issue by rarapost** [ONLYOFFICE/onlyoffice-nextcloud#58]
In the onlyofice online demo (see here: https://www.onlyoffice.com/cs/integration-demo.aspx) there is a menu shown on top of the editor are (something like "ribbon" in MS office), whichs organizes icons to logical groups and is very useful for quick orientation. 

But in "nextcloud" integration application, only one fixed toolbar is shown with all icons in a single "heap", which is hard for orientation. Also icons have to be smaller to fit on the screen on smaller displays (??). 

It would be great if this option (= top menu) were enabled in nextcloud integration.

**Comment by alexanderonlyoffice** [comment]
Hello @rarapost, open source version (free) has an old interface, the interface shown on demo page is available only in paid versions of Document Server.

**Comment by alexanderonlyoffice** [comment]
@rarapost, yes, this question is being internally discussed at the moment, but we cannot guarantee that it will be implemented in the nearest releases.

**Comment by ciderpunx** [comment]
This feature would make me very happy too.

**Comment by LinneyS** [comment]
Hi @rarapost @ciderpunx 
It is released at 5.3.0
https://github.com/ONLYOFFICE/DocumentServer/blob/master/CHANGELOG.md#530
