### ISSUE TITLE
[UX] Insert link to document on mention notification

### ISSUE THREAD

**Issue by ImaCrea** [ONLYOFFICE/onlyoffice-nextcloud#589]
Hello, here is a ux suggestion :)

At the moment, when one mention someone else in a comment, a notification is sent and can be seen in the notification center of nextcloud:
![2022-02-02-mises-a-jour-rentree-22-7](https://user-images.githubusercontent.com/764332/152811201-2cc5231f-9d63-4a50-80b4-39eda7f9ad09.png)

This is cool, but at the moment, the element doesn't seem to be clickable. (or is it a bug on NC 21 ? 🤔)

It would be greater if **a click on it could redirect to the document** (and 🍒 on the 🧁 : open it and go directly to the comment 💫).

**Comment by LinneyS** [comment]
Fixed 8038cfa5dfd529c66cd70a06fdbe8368567bf849

**Comment by ImaCrea** [comment]
cc @pierreozoux fyi
