### ISSUE TITLE
Feature Enhancement - provide ODT/ODP/ODS editing capabilities

### ISSUE THREAD

**Issue by mistergibson** [ONLYOFFICE/onlyoffice-nextcloud#6]
I love the product you've provided, but it is missing ODT/ODP/ODS editing functionality. I found getting your product working was far easier than getting Collabora going. I STILL can't get Collabora working for love or money - just won't work.  If you add this set of editing features, you'd wipe Collabora out of the market.

Please add this functionality to your product.

Thanks,

mistergibson
A fan.

**Comment by LinneyS** [comment]
[Please note](https://api.onlyoffice.com/editors/nextcloud#editable)

**Comment by varac** [comment]
@LinneyS Can you please be more verbose with what you're trying to say and why this issue got closed?

**Comment by ibnpetr** [comment]
@varac Latest version of ONLYOFFICE connector allows you to work with a source ODF file without creating a copy and to save it to the same file. (it may seem that you edit your source ODF file)
![settings](https://user-images.githubusercontent.com/16033936/45879836-96659900-bdae-11e8-93ab-4dd2e82756d9.png)
Please note that Office Open XML is a native format for ONLYOFFICE Document Server. Even if you enable "open ODT files with ONLYOFFICE" they still will be converted to OOXML for editing and then converted back to ODT when you close the editing session.
