### ISSUE TITLE
onlyoffice unable to open any document

### ISSUE THREAD

**Issue by m3shat** [ONLYOFFICE/onlyoffice-nextcloud#60]
in line 477 of `lib/appconfig.php`:
there's a bug where when there's no group defined in the settings of the Onlyoffice' app it prevents opening any document by throwing the following exception:

> [PHP] Error: count(): Parameter must be an array or an object that implements Countable at /path/to/nextcloud/apps/onlyoffice/lib/appconfig.php#477

this can be (hot)fixed by suppressing the error:
```if (@count($group) === 0)```

but should be fixed by making the object countable (even if empty/no groups selected).

**Comment by LinneyS** [comment]
#43
