### ISSUE TITLE
changing core/js/mimetypelist.js breaks core file integrity check

### ISSUE THREAD

**Issue by brrrrrrrt** [ONLYOFFICE/onlyoffice-nextcloud#600]
[lib/Migration/MimeRepair.php](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/e0c50a5a0d33013520dd66e06a3d5864f635a4d6/lib/Migration/MimeRepair.php) changes the file core/js/mimetypelist.js 

this change breaks the core file intergrity check, see:
https://github.com/nextcloud/server/issues/30732#issuecomment-1054247544

**Comment by kilrau** [comment]
Can we prio this since it's causing quite a bit of trouble, please check linked nextcloud issues

**Comment by eguindos** [comment]
Hello
Also having this issue.
Any fix?
Thanks

**Comment by tazire** [comment]
Getting this issue since the last update to 23.0.2 and it has continued into 23.0.3. Informed its an issue with OO integration so any help would be great.

**Comment by jplivingston08** [comment]
Experiencing the same issue.

**Comment by carlang59** [comment]
idem ...

**Comment by kaktoforum** [comment]
Same here.

**Comment by Padl3xx** [comment]
Same here.

**Comment by markusdd** [comment]
is there any feedback on a fix yet...I just ran into this as well and I really hate having broken stuff in my integrity check and server status...

**Comment by masterwishx** [comment]
Having this for first time after nextcloud 24.0 update in Unraid Linux linuxserver/nextcloud .

**Comment by masterwishx** [comment]
after copyed file from lasted nextcloud arhve v24 there is no error.
but if running occ maintenance:mimetype:update-js the problem return ...

**Comment by masterwishx** [comment]
its becose thouse lines in file :  
(
    "image/targa": "image/tga",
    "": "x-office/document",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document.docxf": "x-office/document",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document.oform": "x-office/document"

)

**Comment by flavienbwk** [comment]
This is still a problem in Nextcloud 21.0.9.1 and onlyoffice `onlyoffice/documentserver:7.2.1.34`.

**Comment by Githopp192** [comment]
same on NC 28.0.0

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- core/js/mimetypelist.js

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/js/mimetypelist.js] => Array
                        (
                            [expected] => 550ab566d30693bfa24ec4b15d9df87731ae8a3be8f79dabf94757e5b8b20eec6e4b678f17af1718297f2872f6b04519eeb024d1dff11947f29da431c7f11201
                            [current] => 24e6faa4a1361e51ff70027024f41c4b37fdb5f6f347ceb095450ddbde2d0a6b6dd1403be92a912d2889064a9736a9bed89d7dc62470035fc1299d4b977c5f46
                        )

                )

        )

)
