### ISSUE TITLE
Language interface doesn't follow nextcloud setting

### ISSUE THREAD

**Issue by Omaha2002** [ONLYOFFICE/onlyoffice-nextcloud#602]
After upgrading Enterprise Edition to Version: 7.0.1.37 the language defaults to english, even with the locale of the user set to home language.

![image](https://user-images.githubusercontent.com/3179748/157659283-63f31afd-7608-4969-a35c-d760b3417048.png)

![image](https://user-images.githubusercontent.com/3179748/157659382-7d212e93-b0cb-4cea-a548-9567fe3211a0.png)

Nextcloud version: 23.0.2
onlyofficeapp: 7.3.2

Seems like a similar issue I had a few years back: #108 

BTW this time firefox isnt working either..https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/108#issuecomment-513145512

**Comment by wanthalf** [comment]
I have just installed the same version into NC 22.2.5. switched to the Czech language and both the plugin configuration and the OO interface were showed in German. After switching NC between Czech and English localization forth and back, I finally ended up with a Czech NC with English OO.
Anyway, there should be Czech localisation of the OO as well, I guess..?

**Comment by wanthalf** [comment]
OK. I have just created a cs.json (and translated it) and now Czech localisation works both in the plugin settings and in OnlyOffice.
However, I still don't understand the meaning of some of the settings, so that I should not offer it yet.

**Comment by Omaha2002** [comment]
Interesting, changing language in profile settings nextcloud to spanish or german does change the UI of OO in Nextcloud to Spanish and German, only setting it to Dutch changes it to English.

Maybe something wrong with language code in the new OO enterprise update? NL or DUTCH?

**Comment by brievenbusalex** [comment]
> Interesting, changing language in profile settings nextcloud to spanish or german does change the UI of OO in Nextcloud to Spanish and German, only setting it to Dutch changes it to English.
> 
> Maybe something wrong with language code in the new OO enterprise update? NL or DUTCH?

Same behaviour here, no Dutch OnlyOffice menu's etc with Nextcloud 23.0.3 Onlyoffice App 7.3.2 and Docker Document Server 6.2.2.

**Comment by Omaha2002** [comment]
Is this issue being addressed? Or is there a workaround to get the dutch language back?

**Comment by Omaha2002** [comment]
I can confirm above commit fixes the issue.

https://github.com/ONLYOFFICE/onlyoffice-nextcloud/commit/291057b2dc1eb8e17bd15f4a16d24b79376e810f
