### ISSUE TITLE
Version compatibility matrix documentation

### ISSUE THREAD

**Issue by ClundXIII** [ONLYOFFICE/onlyoffice-nextcloud#605]
Hello,

is there any chance, that you could put in a small matrix of the latest few versions (Nexctloud Plugin vs Onlyoffice version) that are supported into the readme?

We are currently on onlyoffice version 7.0 and app version 7.3.2 with the error message "Not supported version". And I have no idea where to find the compatible version information.

**Comment by SergeyKorneyev** [comment]
Hi,
Document Server versions 7.0.0 and 7.0.1 should work with connector version 7.3.2, there is no incompatibility here. What exactly works incorrectly in your case?

**Comment by ClundXIII** [comment]
Hi,

I have to apologize, I messed up. A docker update caused the old IE Edition to start up which was still on 6.x.

I suspect the same major version is in general compatible with each other, is that correct?

**Comment by SergeyKorneyev** [comment]
The latest version of the connector is usually compatible only with a couple of versions of the Document Server. For example, connector version 7.3.2 does not support Document Server 6.0 or lower.
