### ISSUE TITLE
Layout gets broken

### ISSUE THREAD

**Issue by ZID-TU-Graz** [ONLYOFFICE/onlyoffice-nextcloud#606]
similar to #485, #350 

Onlyoffice app Version: 7.3.2
Nextcloud-Version: 22.2.5
OS/browser:  
- Win11, Firefox 98.0.1
- MacOS, Chrome (Version 99.0.4844.51)

When scrolling down in a folder and opening a document, a folder view appears covering most of it, see screenshots.
The browser window was maximized but not full screen (F11).

![screenshot-onlyoffice-geteilterbildschirm](https://user-images.githubusercontent.com/100593683/158810321-a8387612-44ac-490f-96ed-6e083c0fc5b9.png)
![screenshot-onlyoffice-geteilterbildschirm_2](https://user-images.githubusercontent.com/100593683/158833709-aa710bfd-ed0e-471f-99e9-5bd994609ef2.png)

**Comment by ZID-TU-Graz** [comment]
The problem still occurs, randomly. This time the problem occured after a notebook standby.

Onlyoffice app Version: 7.3.2
Nextcloud-Version: 22.2.5
OS/browser: Win11, Firefox 98.0.2

![screenshot-onlyoffice-geteilterbildschirm_3](https://user-images.githubusercontent.com/100593683/161565032-cf2ce2ce-d1c0-4cc5-bbc5-d1fe636ea4dc.png)

**Comment by ImaCrea** [comment]
Same here. I made a video to make it clearer.

https://user-images.githubusercontent.com/764332/162934984-60733da0-6a68-4b8a-8d1d-98b4a707219d.mp4

Users are lost when it happens and not all of them understant they can refresh to fix that. They're just stuck and frustrated :/

**Comment by ImaCrea** [comment]
Hello, any news around here please ? 🙏  This keeps happening unfortunately and make the experience quiet frustrating.

**Comment by ZID-TU-Graz** [comment]
Hello,


Microsoft Edge Version 102.0.1245.25 (Offizielles Build) beta (64-Bit)

Using this version, user repoert he is able to **reliably** reproduce the issue, by

* Marking some cells and Pressing CTRL+C
* Layout is restored after clicking somewhere on the table grid.

Maybe this helps somehow.

**Comment by djohnson1865** [comment]
Did some quick playing around to try and get some more info on this issue. It seems like in Chrome, the "top" css value for the iframe is being calculated based on hidden items, specifically I believe the search results, and then that value is not recalculated in any way, which is causing the iframe to be pushed down.

I don't know much about Nextcloud or Onlyoffice from a dev perspective so I don't have much helpful as far as potential source culprits at the moment.

**Comment by unteem** [comment]
Hello

There is a regression on this issue. We are having the same problem on NC 25 and OnlyOffice 7.8.0

This commit https://github.com/ONLYOFFICE/onlyoffice-nextcloud/commit/8c15df8ca5fc181dc332f5d0be552895c3921659 reverts how position of the iframe is calculated and it seems it is causing this issue. Are there any reason to calculate top position of the iframe ? 

Thanks for your help

**Comment by unteem** [comment]
Ok so yes it seems to be needed to calculate top position. I forced position to 0 and now a part of the onlyoffice menu is hidden behind nextcloud nav bar. 

The way it is calculated seems wrong though
