### ISSUE TITLE
"Open file location" stays on the Dashboard

### ISSUE THREAD

**Issue by julien-nc** [ONLYOFFICE/onlyoffice-nextcloud#613]
Hi,
When opening a file with OnlyOffice while being on the Dashboard, hitting "Open file location" in OO's file menu does not redirect to the Files app but stays on the Dashboard.
Issue has been seen on Nextcloud 23 and 22 with the OnlyOffice app v7.3.2.

**Comment by alexanderonlyoffice** [comment]
Hello @eneiluj, thank you for the provided information. We are analyzing it.
