### ISSUE TITLE
No Text when i Print or export to PDF

### ISSUE THREAD

**Issue by wiemax95** [ONLYOFFICE/onlyoffice-nextcloud#614]
Hi together,
I noticed that in my OnlyOffice installed in Nextcloud, I can't print files or export to PDF without losing the text. As soon as I save something Print/PDF in Document/Table/Presentation all text is lost.

Versions:
Nextcloud Hub II (23.0.3)
Community Document Server 0.1.12
ONLYOFFICE 7.3.2

![grafik](https://user-images.githubusercontent.com/63787421/161824276-19c6b893-e2d4-4f7a-9595-1f4bb4c3536d.png)
![grafik](https://user-images.githubusercontent.com/63787421/161824374-0ae4b873-796e-4515-b901-1555a1466cf5.png)

**Comment by ShockwaveNN** [comment]
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate [GitHub repository](https://github.com/nextcloud/documentserver_community). 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://forum.onlyoffice.com/t/community-document-server-app-in-nextcloud-18/268).
