### ISSUE TITLE
Load settings synchronously

### ISSUE THREAD

**Issue by vinicius73** [ONLYOFFICE/onlyoffice-nextcloud#620]
**Actual behavior:** 
When we open a file/document in a new tab, sometimes this file will be downloaded.

**Expected behavior:**
When we open a file/document in a new tab, onlyoffice app will open the file.

Related to: #592 #572 

**Reason:**
Onlyoffice register itself in `OCA.Files.fileActions` after loading its settings.
When [files app](https://github.com/nextcloud/server/blob/master/apps/files/js) tries to open the document, no handlers are properly configured.

https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/ea6ba9a811bbbbc92bc591674352a007decf547b/js/main.js#L333

https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/ea6ba9a811bbbbc92bc591674352a007decf547b/js/main.js#L315-L331

**Possible solution:**
Use [`@nextcloud/initial-state`](https://www.npmjs.com/package/@nextcloud/initial-state) to have settings already loaded before onlyoffice scripts.

**Comment by LinneyS** [comment]
Now we use `InitialState`
https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/b58253d9b5f48bead5a527e0b37ff34753a1235f/js/main.js#L28

Thank you

**Comment by alexanderonlyoffice** [comment]
@vinicius73, we are analyzing the possibility to make it work for NC23. I cannot say for sure right now.

**Comment by vinicius73** [comment]
Hi @alexanderonlyoffice any update about backport to NC23?

**Comment by LinneyS** [comment]
Hi @vinicius73 
Yes
We did it in #705

**Comment by vinicius73** [comment]
Thanks @LinneyS

**Comment by pierreozoux** [comment]
I was searching terms like `OCA.Onlyoffice.setting` but I missed this issue, because it is embeded code :/
(That's why I comment, so the next person to research might find it :) )

Thanks a lot for the fixing \o/
