### ISSUE TITLE
Document cannot be saved / German screenshot inside

### ISSUE THREAD

**Issue by kangaroo72** [ONLYOFFICE/onlyoffice-nextcloud#63]
Hi all ...

Here my setup ...

Nextcloud 15.0.2 (beta) / PHP 7.2 / OnlyOffice 5.2.7CE

When I try to open a document following message appears ...

![onlyoffice-error-in-nextcloud](https://user-images.githubusercontent.com/6906390/51872181-d50cf080-2358-11e9-97f5-29ae34aba4cf.jpg)

free translated it says, Document cannot be saved, check the connections settings. I really don't what to do. Can someone help please.

Thanks a lot.

**Comment by kangaroo72** [comment]
1. Ubuntu 18.04 LTS
2. Installation type is docker
3. NC and DS are on the same server
4. Screenshot attached, is that right, what you mean with wget?
![screenshot-wget](https://user-images.githubusercontent.com/6906390/51920545-ec45ef80-23e5-11e9-8dbb-4746b16df12e.JPG)

**Comment by alexanderonlyoffice** [comment]
@kangaroo72, please send us a screenshot of ONLYOFFICE integration application address settings in Nextcloud.

**Comment by elbartl** [comment]
Hello,

I encountered the same issue after upgrading to NC15.0.2. I also have config with document server running in docker container. My NC instance is running inside LXC container.  Now I cannot edit any documents from nextcloud

**Comment by kangaroo72** [comment]
Here we go ... screenshot from Nextcloud ...
![onlyoffice-setup](https://user-images.githubusercontent.com/6906390/52006598-d7905700-24cc-11e9-8966-37ac0e40b869.jpg)

**Comment by alexanderonlyoffice** [comment]
@elbartl, we received the screenshot, I will check it and contact you. 

@kangaroo72, what message do you get when clicking on the 'Save' button on this settings page? Try to clear the field 'Serveradresse für interne Anforderungen vom Dokumentbearbeitung-Service' and save the settings. 

I can see also that you entered JWT secret, please make sure that the same secret is specified in local.json of Document Server. Local.json is placed in /etc/onlyoffice/documentserver/ inside the container with Document Server. Copy also JWT header from local.json and paste it with JWT secret in Nextcloud config.php by adding the section below: 

'onlyoffice' =>
  array (
    "jwt_secret" => "JwtSecret",
    "jwt_header" => "JwtHeader"
	)

**Comment by alexanderonlyoffice** [comment]
@elbartl, please note that Document Server should be accessed by the address you enter in 'Document Editing Service address'. This is the address by which you Nextcloud instance refers to the Document Server. Please follow this [link](https://api.onlyoffice.com/editors/nextcloud#settings) to find more information of how to set up integration of Nextcloud with ONLYOFFICE Document Server.

**Comment by elbartl** [comment]
OK, I have managed to solve the issue by filling in the "Advanced server settings" local addresses to both NC and document server.

**Comment by kangaroo72** [comment]
For me it worked now ...

I've added the documentserver like marked in red in the screenshot. That was NOT needed before.
Thanks a lot for your help.

![only-office-settings nextcloud 15](https://user-images.githubusercontent.com/6906390/52044907-8bccc480-2543-11e9-9707-cc633c749d7b.jpg)
