### ISSUE TITLE
Setting default language for new document independent of Nextcloud-language

### ISSUE THREAD

**Issue by jbrrrr** [ONLYOFFICE/onlyoffice-nextcloud#64]
Hi
My Problem:
I am using OnlyOffice with Nextcloud in Switzerland. There seems to be no way to open a new document with language de-CH (German (Switzerland)) instead of de-DE (German (Germany)). Nextcloud has only de-DE option and this is used as default for OnlyOffice. It would be great, if this default could be overruled by a setting (document server config or OnlyOffce-NC-App).
Maybe there is another already existing solution or workaround for this issue?
Thanks!

**Comment by alexanderonlyoffice** [comment]
Hello @jbrrrr, we will analyze the issue you described and think about possible workarounds.

**Comment by alexanderonlyoffice** [comment]
@jbrrrr, as a workaround you can replace the files in [assets/de_DE](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/tree/master/assets/de_DE) with the files in required language and when you click on the button to create the file in interface, the new file will be taken from there. 

Please note that if you use this workaround the digital signature of the integration app will be lost and you will get notifications about it in interface of Nextcloud.

**Comment by LinneyS** [comment]
@jbrrrr 
Please help
How can I enable de_CH lang in Nextcloud?

**Comment by jbrrrr** [comment]
@LinneyS 
At the moment there is no de_CH lang in Nextcloud. Just use de_DE or de.

**Comment by LinneyS** [comment]
Then we cannot programmatically select a file with de_CH. You can replace the files in assets/de_DE

**Comment by jbrrrr** [comment]
The language is de or de_DE, but there is the language locale defined
'default_locale' => 'de_CH',
The locale is probably the setting you're looking for?
