### ISSUE TITLE
Disable split view between OnlyOffice and Files

### ISSUE THREAD

**Issue by solracsf** [ONLYOFFICE/onlyoffice-nextcloud#640]
One of my users has, somehow, activate this mode and i can't find where to disable it.
Where can I find this setting?

![image](https://user-images.githubusercontent.com/12234510/172427343-b1abff4e-74d4-43ad-b940-cb847cf71c40.png)

**Comment by bthall** [comment]
I was able to reproduce this issue using the keyboard shortcut `Ctrl+X` on Windows using both Chrome and Edge. I was not able to reproduce this issue using Chrome on my Debian workstation.
