### ISSUE TITLE
"Download as" button provides alway original document instead of selected format

### ISSUE THREAD

**Issue by ZID-TU-Graz** [ONLYOFFICE/onlyoffice-nextcloud#641]
- Nextcloud: 22.2.8
- Nextcloud-App OnlyOffice: 7.3.4
- OnlyOffice 7.1.0 (Docker)

We reproduced this issue on MacOS X 12.4 and Chrome 102.0.5 and Safari Version 15.5 (17613.7.1.8):
1. Login in to nextcloud
2. Click on the file menu of a "OnlyOffice" document
3. Select "download as" (in german "Herunterladen als") and select a format
4. The original document instead of the selected format will be downloaded

![onlyoffice-herunterladenals2](https://user-images.githubusercontent.com/100593683/172581909-5e1ff67b-6772-4868-8d7a-19e97a38d133.png)
![onlyoffice-herunterladenals1](https://user-images.githubusercontent.com/100593683/172581902-76408e2f-848f-4c7d-aac9-96780ae91472.png)

A workaround is to open the "download as" dialog twice. On the second try the right format was downloaded.

**Comment by SergeyKorneyev** [comment]
Hello,
Could you reproduce the issue and check the Document Server logs? Any relevant errors should be in the "converter" subdirectory.

**Comment by ZID-TU-Graz** [comment]
thanks, we can confirm the fix is working with app version 7.5.4
