### ISSUE TITLE
Inserting an image in the Nextcloud mobile app does not work.

### ISSUE THREAD

**Issue by Zandt73** [ONLYOFFICE/onlyoffice-nextcloud#644]
Hello all,
inserting an image does not work in the mobil Android app of Nextcloud. If you call the function for inserting an image from a directory, the file selection is not called, unfortunately nothing happens and you jump back to the document.
If I do the whole thing in the mobile browser, inserting an image works without any problems.

**Comment by Zandt73** [comment]
logfile Nextcloud App
[logcatOutput.txt](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/files/9591415/logcatOutput.txt)

**Comment by alexanderonlyoffice** [comment]
Hello @Zandt73, please refer to the issue https://github.com/nextcloud/android/issues/10744 where we described the reason of the problem.
