### ISSUE TITLE
NextCloud 24.0.1

### ISSUE THREAD

**Issue by majcher999** [ONLYOFFICE/onlyoffice-nextcloud#645]
Hi.
OnlyOffice 7.3.4 is not compatible witch NextCloud 24.0.1 ?

**Comment by mdenis35** [comment]
Hi,
I have the same problem.
OnlyOffice 7.3.4 doesn't seem compatible with nextcloud 24.0.1.

**Comment by LinneyS** [comment]
v7.5.0 released
Can you check it ?

**Comment by mdenis35** [comment]
It works like a charm !

Thanks a lot.
