### ISSUE TITLE
Nextcloud | onlyoffice cannot be reached

### ISSUE THREAD

**Issue by mudasaryasin** [ONLYOFFICE/onlyoffice-nextcloud#65]
We have deployed next cloud with openoffice on separate machines, behind the firewall. Only OpenOffice has public access. In internal network it is working fine. When we try to open any document for editing over the internet, i got error "OnlyOFFICE cannot be reached". In browser's debug mode, it is not able to resolve host(only.abc.co), and it is obvious because this entry is only accessible within local network.
As per documentation it is possible https://api.onlyoffice.com/editors/nextcloud

Only office configurations

> Document Editing Service address
> https://only.abc.co/    --> running Onlyoffice on separate machine on docker
> 
> Document Editing Service address for internal requests from the server
> https://only.abc.co/
> 
> Server address for internal requests from the Document Editing Service
> https://ncloud.abc.co/   --> actual URL of nextcloud

There are no more error in any logs. Is there any other configurations. Or we should publicly expose only office.

**Comment by CarlOnlyoffice** [comment]
@mudasaryasin Hello,

Have you tried to disable the Advanced server settings and save the settings?

Also please check if Nextcloud and ONLYOFFICE can reach each other using wget command:
run `wget https://ncloud.abc.co/` on ONLYOFFICE server
run `wget https://only.abc.co/` on Nextcloud server

**Comment by LinneyS** [comment]
This issue was closed due to no response.
