### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by majcher999** [ONLYOFFICE/onlyoffice-nextcloud#651]
Hi. OnlyOffice v 7.5.2 not working nextcloud 24.0.1 :(

occ onlyoffice:documentserver --check
Error connection: cURL error 28: Connection timed out after 60001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://xxx.com/index.php/apps/documentserver_community/healthcheck

Community Document Server  v 0.1.12

**Comment by LinneyS** [comment]
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://forum.onlyoffice.com/t/community-document-server-app-in-nextcloud-18/268).
