### ISSUE TITLE
Update JWT / fetch through through composer

### ISSUE THREAD

**Issue by fancycode** [ONLYOFFICE/onlyoffice-nextcloud#653]
The version of JWT in the repository is rather old (unknown version from 2017).

If would be great if this could be updated to a more recent version to avoid conflicts with other apps that use a more recent version of JWT (https://github.com/nextcloud/spreed/pull/7372 being an example). The call arguments of ` JWT::sign`  have changed in that the algorithm is now mandatory.

Another possibility would be to use [composer](https://getcomposer.org/) to track the dependency and automatically get notified about updates (e.g. through [dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#enabling-dependabot-version-updates) or [renovate](https://docs.renovatebot.com/)).

**Comment by LinneyS** [comment]
Released in v8.2.0
