### ISSUE TITLE
OnlyOffice ignores editor theme-settings in NC

### ISSUE THREAD

**Issue by DerDino** [ONLYOFFICE/onlyoffice-nextcloud#656]
After updating to 7.4.2 OnlyOffice ignores the changes to the editor theme settings. It makes no difference if you choose between the dark theme or the classic light theme. It's always loading the editor in the classic light theme.

**Comment by SergeyKorneyev** [comment]
Hi,
The global theme settings (https://api.onlyoffice.com/editors/config/editor/customization#uiTheme) can be overwritten if a user changes them manually in the editor. In this case the new settings will be saved in the local storage of the user's browser, and the global settings will be ignored unless the local storage is cleared.
