### ISSUE TITLE
Checkbox *Open file in the same tab* is not respected

### ISSUE THREAD

**Issue by timm2k** [ONLYOFFICE/onlyoffice-nextcloud#658]
Dear Onlyofficers,

since onlyoffice-nextcloud 7.5.0 / 7.4.0 checkbox *Open file in the same tab* is not respected. Files get always opened in the same tab.

Kind regards
Timm

**Comment by quentinDupont** [comment]
Same issue here : https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/652
You can close this one
