### ISSUE TITLE
ConvertService.ashx Error

### ISSUE THREAD

**Issue by schklom** [ONLYOFFICE/onlyoffice-nextcloud#664]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
https://<onlyoffice_ip>/ConvertService.ashx is requested by Nextcloud, but the page results in
![image](https://user-images.githubusercontent.com/23263086/178320071-6b7d6869-bda2-45b3-84a1-24ef30d85b4a.png)

even without going through a reverse-proxy (I mean that http://<onlyoffice_ip>/ConvertService.ashx returns the same result).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Docker instance
- the examples work well
- connect to http://<onlyoffice_ip>/ConvertService.ashx
- response above

**What is the expected behavior?**
Not this

**Did this work in previous versions of DocumentServer?**
First time

**DocumentServer Docker tag:**
`latest-arm64`

**Host Operating System:**
Ubuntu 20.04

**Comment by ShockwaveNN** [comment]
So I've moved it, most important info is located at https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/664#issuecomment-1182886622

Seems that DocumentServer works fine by itself, but fails with Nextcloud combo

**Comment by SergeyKorneyev** [comment]
Hi @schklom,
This could be caused by the fact that the public Document Server address is not reachable by Nextcloud. Could you try specifying the `http://docserver_LAN_ip` address in the "ONLYOFFICE Docs address for internal requests from the server" field in the Advanced server settings?

**Comment by Setsaria** [comment]
Hello
I've got the same problem: 
on nextcloud : Server error: `POST https://******.com/ConvertService.ashx` resulted in a `504 Gateway Time-out

On the onlyoffice logs : 

[2023-02-21T14:35:32.046] [ERROR] [localhost] [conv_check_1149903374_docx] [userId] nodeJS - error downloadFile:url=https://*****.com/index.php/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.sAUrBs3XZjVaKZawZ_V4lOvO8WgRrFm7HdQwk0ziPfE;attempt=1;code:ETIMEDOUT;connect:undefined Error: Error: whole request cycle timeout
    at raiseError (/snapshot/server/build/server/Common/sources/utils.js)
    at Timeout._onTimeout (/snapshot/server/build/server/Common/sources/utils.js)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)

But on both server I can, ping, telnet 443, curl and wget each other.
It was working until this morning, the service stop without explanation..

**Comment by schklom** [comment]
I am not sure exactly why, but I forced Traefik (my reverse-proxy) to add the headers `X-Forwarded-Proto: https` and `access-control-allow-origin: *` using a middleware and it worked.
I hope it helps someone else who had a similar problem.

Thank you @ShockwaveNN and @SergeyKorneyev for the replies :)
