### ISSUE TITLE
open files in new tab/window not working 

### ISSUE THREAD

**Issue by rosa2** [ONLYOFFICE/onlyoffice-nextcloud#666]
Hello and thanks for OnlyOffice
Sorry my bad English.

I have just updated to NextCloud 24.0.2 and OnlyOffice app  7.5.2. Since then the documents open in the same tab.
I have tried in the settings to select and deselect "Open file in the same tab" but always opens in the same tab.
My users are very fan of this and it would be great that it works again.

Have a good day!

**Comment by LinneyS** [comment]
duplicate with #652
