### ISSUE TITLE
Peculiar "Bad Request" Issue in Nextcloud

### ISSUE THREAD

**Issue by heavyelement** [ONLYOFFICE/onlyoffice-nextcloud#67]
I've installed the ONLYOFFICE Docker image on the same server as my Nexcloud instance.

Both Nextcloud and the document server are accessible via subdomains. Both domains are accessible from a wget on the server.

When I go to set up the ONLYOFFICE app in Nextcloud, I get the following error:
```
Error when trying to connect (Bad Request or timeout error)
```

I enabled debug logging in Nextcloud and the associated error I get is:

```
    {
        "reqId": "xxxx",
        "level": 3,
        "time": "February 08, 2019 05:24:30",
        "remoteAddr": "xxxx",
        "user": "xxxx",
        "app": "PHP",
        "method": "PUT",
        "url": "\/index.php\/apps\/onlyoffice\/ajax\/settings",
        "message": "file_get_contents(https:\/\/office.domain.com\/healthcheck): failed to open stream: HTTP request failed! HTTP\/1.1 502 Bad Gateway\r\n at \/srv\/nextcloud\/apps\/onlyoffice\/lib\/documentservice.php#385",
        "userAgent": "Mozilla\/5.0 (X11; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0",
        "version": "15.0.2.0"
    },
```

It seems like `office.domain.com/healthcheck` is throwing a 502 error. It does when I try to visit the page in my browser. Any idea how to resolve this?

**Comment by alexanderonlyoffice** [comment]
Hello @heavyelement, please specify some more information about the issue: 

1. Send us a screenshot of ONLYOFFICE integration app address settings from Nextcloud; 
2. Specify also what exact ONLYOFFICE product you are using (open source Document Server, Integration Edition, Developer Edition, Community Edition or Enterprise Edition); 
3. Please send us also all logs of Document Server to support@onlyoffice.com with a note for technical support. Logs should be in /app/onlyoffice/DocumentServer/logs/documentserver/ for Docker installation;
4. Do you see 'Welcome' page of Document Server when entering its subdomain in browser?

**Comment by LinneyS** [comment]
This issue was closed due to no response.

**Comment by anderl80** [comment]
I'm seeing the same behavior, should we reopen this issue?

**Comment by alexanderonlyoffice** [comment]
@anderl80, please open the new issue and describe the detailed information about your environment and the problem with screenshots.

**Comment by anderl80** [comment]
In the meanwhile I found why I was getting the bad request. I have a complete OO installation inluding Community Server. I then need to specify `https://myhost/ds-vpath/` as document server in NextCloud.

https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/258

**Comment by bruennlein** [comment]
Hi folks. I think I have the same problem. After updating the document-server and the plugin, I get
Server error: `GET https://home.mydomain.xyz/healthcheck` resulted in a `502 Bad Gateway` response: 502 Bad Gateway 502 Bad Gateway ngin (truncated...) ).

I have the onlyoffice-server and nextcloud on sepparate machines and both behind a reverse-proxy. Calling https://my-document-server.xyz/ds-vpath ends-up with a 502 bad gateway from the nginx of the document-server,

Any ideas?
