### ISSUE TITLE
Disabled buttons when edit docx files in nextcloud

### ISSUE THREAD

**Issue by AtaZ991** [ONLYOFFICE/onlyoffice-nextcloud#676]
I have NC, install Community Document Server App, install OnlyOffice App. With excel files all work good, but in docx editor all buttons disabled, I only can read document. What I do wrong?

**Comment by ShockwaveNN** [comment]
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate [GitHub repository](https://github.com/nextcloud/documentserver_community). 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://forum.onlyoffice.com/t/community-document-server-app-in-nextcloud-18/268).
