### ISSUE TITLE
Add mentionShare checkbox setting 

### ISSUE THREAD

**Issue by natoponen** [ONLYOFFICE/onlyoffice-nextcloud#679]
Hello!

I'm using ONLYOFFICE app 7.5.4 with Nextcloud 24.0.1.

I'd like to control mentionShare setting because when working with nextcloud groupfolders mentionSharing creates unnecessary copies of shared file in user's folder.

As I can see from [ONLYOFFICE Api Documentation](https://api.onlyoffice.com/editors/config/editor/customization#mentionShare) there is such editor customization setting, which allows to control this behaviour, but there is no option to change it anywhere in the ONLYOFFICE app settings or editor settings.

Maybe I'm wrong and there is such setting somewhere, then could you please show it to me. Otherwise, I think it would be great to have such editor customization option both in ONLYOFFICE app settings in Nextcloud for default value and in editor's File->Advanced Settings to change it while editing.

Thanks!

**Comment by natoponen** [comment]
@Antipkin-A @LinneyS what about #683?

**Comment by LinneyS** [comment]
Hi @natoponen 
Please check if PR #758 fixed your issue?
