### ISSUE TITLE
Error Opening Document in Browser

### ISSUE THREAD

**Issue by Man-in-Black** [ONLYOFFICE/onlyoffice-nextcloud#68]
Hello all together,

I'm running Nextcloud V14 in my production environment with Onlyoffice as a fresh install with docker.
I have a problem after a restart of my Nextcloud-Server.

Within Nextcloud I got the following errors for each document I want to open in the browser:
![image](https://user-images.githubusercontent.com/9048534/53392533-f1bd3800-3999-11e9-8095-e39c476b4617.png)
In the docker container the logfile from onlyoffice looks like this:
`[2019-02-26T06:27:38.629] [ERROR] nodeJS - postData error: docId = 2150112335;url = https://cloud-ulm.wilken.de/index.php/apps/onlyoffice/track?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaWxlSWQiOjE0MzM2NSwib3duZXJJZCI6ImluZnJhc3RydWN0dXJlLXNlcnZpY2VzIiwidG9rZW4iOm51bGwsImFjdGlvbiI6InRyYWNrIn0.UOpRJliL12jyqxrAYDrbxi_clraoOwWjoycbs6mkdyA;data = {"key":"2150112335","status":1,"users":["sjelinek"],"actions":[{"type":1,"userid":"sjelinek"}]}
Error: Error response: statusCode:403 ;body:
{"message":"Access denied"}
    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:283:18)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
`

I've set the token on the configuration page
![image](https://user-images.githubusercontent.com/9048534/53392621-3cd74b00-399a-11e9-98bb-b4fedc7dfb3f.png)
and I've set the following array in my Nextcloud configration:
`  array (
    'jwt_secret' => '*******',
    'jwt_header' => 'Authorization',
  ),
`

But I'm still not able to open a document.
I've searched through every open issue, but did not find a similar error description.

I hope that anyone can help me.

Kind regards

Sascha

**Comment by alexanderonlyoffice** [comment]
Hello @Man-in-Black, please specify if you can edit files when JWT is disabled in Nextcloud and Document Server.

JWT secret and header should match each other in Nextcloud and Document Server. JWT parameters are set in local.json for Document Server. This file can be found in /etc/onlyoffice/documentserver/ in container with Document Server. Please check the values of JWT secret and header.

Do you get any errors when clicking on the 'Save' button on the ONLYOFFICE integration app address settings page?

Please check also logs of Docservice and Converter for errors in /app/onlyoffice/DocumentServer/logs/documentserver/

**Comment by Man-in-Black** [comment]
Hello @alexanderonlyoffice, thank you for your answer.

I will try to connect it without a secret.
But it doesn't matter which way I try (with or without a secret), evertime I get the following error on the settings page for ONLYOFFICE:
![image](https://user-images.githubusercontent.com/9048534/53686424-0e08fe00-3d27-11e9-85f4-16365602144d.png)
In english: Error while connecting. An error has occurred in the document service: ...

I hope this helps.

**Comment by alexanderonlyoffice** [comment]
@Man-in-Black, this error means that Nextcloud is inaccessible for Document Server, as it cannot download the file for conversion.  

Did you check the Document Server logs? 

Please send us local.json, default.json, Nextcloud config.php and logs of Document Server to support@onlyoffice.com with a note 'For technical support'.

**Comment by Man-in-Black** [comment]
@alexanderonlyoffice, I sent the information to support@onlyoffice.com
I cannot check the Document Server logs, because I'm not able to connect to the Onlyoffice instance anymore and therefore are not able to generate new logfiles.

**Comment by Man-in-Black** [comment]
I managed it to get Onlyoffice to work, but without a JWT Secret.

**Comment by alexanderonlyoffice** [comment]
@Man-in-Black, I checked the provided logs and there are no error related to JWT. Please specify what you did exactly to make it work. Please send us also a screenshot of URL address settings.

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs or we can close the topic?

**Comment by Man-in-Black** [comment]
> Could you please specify if the problem recurs or we can close the topic?

This issue can be closed.
The problem did not occur any more.
Thank you for your help.
