### ISSUE TITLE
Cannot load documents

### ISSUE THREAD

**Issue by SaschaMuehl** [ONLYOFFICE/onlyoffice-nextcloud#688]
Hallo, 
I installed Onlyoffice (Version 7.1.1) on Docker via a subdomain (of.xxx.de). The document server works and the example runs well [1]. 
After saving successful the document server URL (of.xxx.de) in my Nextcloud instance nc.xxx.de [2] I cannot open the documents [3]. 

**Trying to open a document it loads endless but doesn’t open [3]. Does anybody know why? **

I use the Nextcloud version 24.0.5. (Edit: updated from 23.0.3; same issue)

nginx.log
[nginx.log](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/files/9505659/nginx.log)

No Errors in NGINX Docker Log:
`sudo docker exec -it ONLYOFFICEDOCKER bash`
`nano /var/log/nginx/error.log`

The docker logs show me sth. but I've no clue:
`docker inspect --format='{{.LogPath}}' ONLYOFFICEDOCKER` (looked direct in the docker container)

[Docker_OnlyofficeLog.log](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/files/9505560/Docker_OnlyofficeLog.log)

Alternatively cia cmd-line:
`docker logs ONLYOFFICEDOCKER`
[Docker_OnlyofficeLog_viacmd-line.log](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/files/9505631/Docker_OnlyofficeLog_viacmd-line.log)

[1]
![image](https://user-images.githubusercontent.com/62723171/188863895-df4e379a-3d00-4f2e-81b4-0829950c1ac0.png)

[2]
![image](https://user-images.githubusercontent.com/62723171/188864005-f2992d6b-b500-4113-ab49-a4505b2b381a.png)

[3]
![image](https://user-images.githubusercontent.com/62723171/188864138-9ef7c880-1344-4c0a-945c-40649d95b25a.png)

**Comment by SaschaMuehl** [comment]
still have the problem. Does sbd. have an idea?

**Comment by vagner-dias** [comment]
Hi,

I struggled to get onlyoffice working here. It is definetively not a follow-this-step-by-step thing.

I ended up realizing that I had to run onlyoffice with some extra parameters behind a NGINX reverse proxy to get everything working correctly.

Here is what i did:

1. Docker command:
================================================
sudo docker run -i -t -d -p 9980:80 -e JWT_ENABLED=true -e JWT_SECRET=<<create a password and put it here>> -e USE_UNAUTHORIZED_STORAGE=true --restart=always onlyoffice/documentserver
================================================

The <<create a password and put it here>> is the "Secret key" that you insert in the OnlyOffice configuration section, in NextCloud (remove the brackets!).


2. NGINX reverse proxy configuration:

================================================
upstream docservice {
  server localhost:9980; #### Here I assume you are running docker and the reverse proxy in the same server ###
}

map $http_host $this_host {
    "" $host;
    default $http_host;
}

map $http_x_forwarded_proto $the_scheme {
     default $http_x_forwarded_proto;
     "" $scheme;
}

map $http_x_forwarded_host $the_host {
    default $http_x_forwarded_host;
    "" $this_host;
}

map $http_upgrade $proxy_connection {
  default upgrade;
  "" close;
}


proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Forwarded-Host $the_host;
proxy_set_header X-Forwarded-Proto $the_scheme;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;


server {
	listen 443 ssl;
	server_name <<the DNS address of your server goes here>>;  ### remove the brackets!
	server_tokens off;
	root /usr/share/nginx/html;

	ssl_certificate <<your SSL Certificate full path goes here>>   ### I am using a Letsencrypt certificate here and works well (remove the brackets!)
	ssl_certificate_key <<your SSL Certificate Key full path goes here>>  ### I am using a Letsencrypt certificate here and works well (remove the brackets!)

	ssl_verify_client off;

	ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";

	ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
	ssl_session_cache  builtin:1000  shared:SSL:10m;

	ssl_prefer_server_ciphers   on;
	add_header X-Content-Type-Options nosniff;

	ssl_stapling on;
	ssl_stapling_verify on;
	resolver 208.67.222.222 208.67.222.220 valid=300s; # Can change to your DNS resolver if desired
	resolver_timeout 10s;


 
	location / {
		proxy_pass http://docservice;
		proxy_http_version 1.1;
	}
}

================================================



In the reverse proxy configuration above, you just have to adjust the lines:
  server localhost:9980;
  server_name <<the DNS address of your server goes here>>; 
  ssl_certificate <<your SSL Certificate full path goes here>>
  ssl_certificate_key <<your SSL Certificate Key full path goes here>>




Reference:
https://helpcenter.onlyoffice.com/installation/docs-community-install-docker.aspx
and
https://github.com/ONLYOFFICE/document-server-proxy/blob/master/nginx/minimal.conf

**Comment by SergeyKorneyev** [comment]
Hi @SaschaMuehl,

The third screenshot in your original message shows the attempt to open the file with another application, not the ONYLOFFICE editor. Please try to right-click on a document in Nextcloud and select "Open in ONLYOFFICE" to check if you have any issues.

**Comment by SaschaMuehl** [comment]
@SergeyKorneyev this helped! Thank you. 
It seems to be that a parallel coworking with the Nextcloud-Office isn't possible. 

**I deactivated the Collabora server in Docker and in the Nexcloud Apps and now it's fine.**
