### ISSUE TITLE
Content-Security-Policy frame-src error

### ISSUE THREAD

**Issue by jjasoncool** [ONLYOFFICE/onlyoffice-nextcloud#693]
Refused to frame 'http://mydomain/' because it violates the following Content Security Policy directive: "frame-src 'self'".

Mixed Content: The page at 'https://mydomain/apps/onlyoffice/375943?filePath=%2F%E5%85%89%2F%E6%9B%BE%E7%B6%93%E7%9A%84%E9%81%8E%E5%8E%BB%2F%E6%96%87%E4%BB%B6%2F116%E8%A9%B9%E5%8B%9D%E5%85%89.doc' was loaded over HTTPS, but requested an insecure resource 'http://mydomain/ds-vpath/6.4.2-6/web-apps/apps/documenteditor/main/index_loader.html?_dc=6.4.2-6&lang=zh-TW&customer=ONLYOFFICE&frameEditorId=iframeEditor&mode=view&compact=true&parentOrigin=https://mydomain&uitheme=theme-classic-light'. This request has been blocked; the content must be served over HTTPS.

![圖片](https://user-images.githubusercontent.com/24731867/190305953-2f80a1a1-b5bc-4f36-aacf-037a2a4380c1.png)

I use the same settings before.

Maybe browser security update?

Can add any Content-Security-Policy settings in the apps?

![圖片](https://user-images.githubusercontent.com/24731867/190306570-aba71896-5431-49ae-a47f-60068883ec2a.png)

**Comment by jjasoncool** [comment]
maybe can add field in settings?

https://docs.nextcloud.com/server/24/developer_manual/basics/controllers.html#modifying-the-content-security-policy

**Comment by jjasoncool** [comment]
if I modify /www//lib/public/AppFramework/Http/ContentSecurityPolicy.php

Add my domain to Highlight area, the browser error to "Mixed content"

Maybe app can add https options and CSP fields to setting?

![圖片](https://user-images.githubusercontent.com/24731867/190539608-f29f596e-0ae1-4857-95ad-a4fd6527b25f.png)

**Comment by jjasoncool** [comment]
https://github.com/ONLYOFFICE/docker-onlyoffice-nextcloud/issues/22#issuecomment-1248929521

**Comment by jjasoncool** [comment]
Problem solved.

**Comment by johnjaylward** [comment]
I ran into this issue as well... Is there a setting in the UI for configuring this? I'd rather not have to patch the file after every upgrade
