### ISSUE TITLE
Change of cookie when requesting version history

### ISSUE THREAD

**Issue by natoponen** [ONLYOFFICE/onlyoffice-nextcloud#694]
Hello!

I'm using ONLYOFFICE app (ver. 7.5.4) in Nextcloud (ver. 24.0.1) and SSO & SAML authentication app (ver. 5.0.3) for authentication.

The problem is that when the user authenticates through SSO, and tries to get revisions of any version of file, in the response with the .zip archive of changes server sets new cookies 'oc_sessionPassphrase' and server session cookie (in my case 'oc66xlkkbm3j') to new ones. After that the user gets 401 'Unauthorized' for any request, so he needs to re-login.

Steps to reproduce:

1. Log into Nextcloud through SSO (using SSO & SAML authentication app)
2. Open any file with revisions in it's version history
3. Go to *Collaboration -> Version history*
4. Open any version with revisions
5. Refresh the page
6. You need to login again

As I understand, such request is being processed in the **download()** method of callbackcontroller. It doesn't set any cookies itself, but respond has the *set-cookie* headers, which break everything.

Any ideas how this can be solved, or where the new cookies is set?

Thanks in advance!

**Comment by LinneyS** [comment]
#700
