### ISSUE TITLE
Comments containing Umlauts

### ISSUE THREAD

**Issue by TobiasReich** [ONLYOFFICE/onlyoffice-nextcloud#696]
Even with the latest version when creating comments that contain (german) umlauts (like Ä Ö Ü ...) the comments are broken.
They tend to disappear and cause trouble. Anyone who can confirm that?

**Comment by TobiasReich** [comment]
Is there nobody else having these issues? Not necessarily only with German accents. Could be French / Spanish accents like é or è...

**Comment by SergeyKorneyev** [comment]
Hello,

We're not currently aware of such an issue. Could you provide a more detailed scenario? Screenshots or a video would also be appreciated.

**Comment by TobiasReich** [comment]
Well there is not much to see. When ever I create a comment with umlauts the comment is not rendered - just as if nothing happened.
Note that umlauts and accents work perfectly fine in the document. Just not when contained in a comment.

![1](https://user-images.githubusercontent.com/10375845/193933312-68f353e4-8c5c-44ab-bc38-984488a1377a.png)
![2](https://user-images.githubusercontent.com/10375845/193933328-921310bc-9b1e-42fc-bd09-536e42f14ca4.png)
![3](https://user-images.githubusercontent.com/10375845/193933346-8c2ac03a-315a-4305-8850-b9540147e73b.png)

**Comment by SergeyKorneyev** [comment]
That is not the ONLYOFFICE editor you've got on the screenshots. If you have installed Docs and configured the connector, you should see the "Open in ONLYOFFICE" button if you right-click on a document in Nextcloud.
