### ISSUE TITLE
Only one NC Instance for one OO Instance possible?

### ISSUE THREAD

**Issue by ExaconAT** [ONLYOFFICE/onlyoffice-nextcloud#7]
Hello,

i've tried to connect two NC 13.0.6 Servers to one (updated) Onlyoffice Documentserver (Community Edition), but then the documents didn't load?

***Edit***
Working now, but sometimes it's slow (not a connection problem)

**Comment by ibnpetr** [comment]
> but sometimes it's slow (not a connection problem)

Do you see any errors in the browser console log? Do you have that issue with all types of documents? 
Any errors in the DocumentServer's logs?
