### ISSUE TITLE
Exception: Database error when running migration latest for app onlyoffice

### ISSUE THREAD

**Issue by JWHBerlin** [ONLYOFFICE/onlyoffice-nextcloud#708]
Error while running Update Nextcloud to 23.0.9 - OnlyOffice-Error  
Exception: Database error when running migration latest for app onlyoffice

Is there any idea, what I can do?

---German protocol of web based updater:
Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Reparaturschritt: Repair MySQL collation

Reparaturinformation: Not a mysql database -> nothing to do

Reparaturschritt: Repair SQLite autoincrement

Reparaturschritt: Copy data from accounts table when migrating from ownCloud

Reparaturschritt: Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert

Datenbank aktualisiert

Exception: Database error when running migration latest for app onlyoffice

Das Update ist fehlgeschlagen. Bitte melde dieses Problem an die [Nextcloud Community](https://github.com/nextcloud/server/issues).

**Comment by alexanderonlyoffice** [comment]
Hello @JWHBerlin, we have fixed the issue and the solution will be introduced in the next connector version. 

As of now, please try to execute the following occ command to update the database to the latest indexes on Nextcloud: 

`occ db:add-missing-primary-keys`

**Comment by JWHBerlin** [comment]
Thanks a lot. I have no access to the console, so I have to try to restart the update. This doesn't works, but I try by asking the provider.
