### ISSUE TITLE
Possible to remove protect permission.

### ISSUE THREAD

**Issue by j7126** [ONLYOFFICE/onlyoffice-nextcloud#712]
If I share a document with someone and give the editing permission, they can go to file -> protect -> add password and add a password, making it so that I cannot access the document anymore. I can't seem to see any way to disable this, and am wondering if it would be possible to add a way to disable this ability.

I can see here https://api.onlyoffice.com/editors/config/document/permissions there is the ability to set protect to false to disable this function, however I am not exactly sure how this is implemented.

**Comment by LinneyS** [comment]
Made in #759
