### ISSUE TITLE
The downloaded docx document content is empty

### ISSUE THREAD

**Issue by xiaoche6690** [ONLYOFFICE/onlyoffice-nextcloud#714]
Hi team;
 I encountered a problem, I added onlyoffice and Community Document Server plugins to Nextcloud, I created a docx or xlsx document online and added the text, it prompted to save and choose to download, then the content of the docx document I downloaded was empty, but When I open the newly created docx or xlsx document online again, the online document has content;
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/104224501/194802945-cba74969-9a21-447a-ba32-dbcf6d46759c.png">

nextcloud 23.0.0、onlyoffice7.4.4、Community Document Server 0.1.2

**Comment by ShockwaveNN** [comment]
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate [GitHub repository](https://github.com/nextcloud/documentserver_community). 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://forum.onlyoffice.com/t/community-document-server-app-in-nextcloud-18/268).
