### ISSUE TITLE
Fix Onlyoffice Overlay on NC 25 

### ISSUE THREAD

**Issue by andyxheli** [ONLYOFFICE/onlyoffice-nextcloud#715]
When opening files via dashboard 
![image](https://user-images.githubusercontent.com/59488153/194944480-3100c374-da0c-4c41-8614-a61fdfb95ec2.png)

When Opening files on the same tab

![image](https://user-images.githubusercontent.com/59488153/194944981-6287b5ad-0aaf-4baf-ba5d-4a71389de4f1.png)

**Comment by serverless83** [comment]
This affects especially Excel files with multiple sheets 'cause the tabs are in the bottom area and now they are hidden.

**Comment by andyxheli** [comment]
This is how it looks when using Nextcloud Office App integrate with Collabora Can Onlyoffice do something similar ? 


When opening a document via dashboard
 ![image](https://user-images.githubusercontent.com/59488153/195172504-078d1276-386a-42be-9291-0e88d185bf82.png)
When opening a document on same tab
![image](https://user-images.githubusercontent.com/59488153/195172504-078d1276-386a-42be-9291-0e88d185bf82.png)

**Comment by andyxheli** [comment]
Fixed https://github.com/ONLYOFFICE/onlyoffice-nextcloud/releases/tag/v7.6.6

**Comment by LinneyS** [comment]
Fixed at 954b9f88f4f19814efd392ecaaea4e9b2887f0bf
