### ISSUE TITLE
3+ users editing same document increases input lag significantly

### ISSUE THREAD

**Issue by RuudschMaHinda** [ONLYOFFICE/onlyoffice-nextcloud#72]
I don't know if this is a bug of the app, the document server, or nextcloud itself. So I am asking right now, where would I start tracking what is happening?

When more than two people access a document at the same time, it becomes tediously slow to wait for input. Typing, or deleting letters can literally take many seconds, up to half a minute.

I am running the document server on the same machine as the nextcloud install in it's seperate subdomain office.example.com

Nextcloud is using the latest nginx, mysql 5.7, php7.2
The users are connected via LAN 1 Gbit/s connection to the server
the server is on a VM, 6 cores @ 2.4GHz, 12 GB of RAM assigned

more concise stats (german):
Nextcloud
Version: 15.0.7.0

PHP
Version: 7.2.16
Arbeitspeicher-Grenzwert: 512 MB
Maximale Ausführungszeit: 3600
Maximale Größe zum Hochladen: 511 MB

Database
Art: mysql
Version: 5.7.25
Größe: 386,4 MB

**Comment by alexanderonlyoffice** [comment]
Hello @RuudschMaHinda, please specify the following information: 

1. OS of the server where Document Server is installed;
2. Its installation type (docker or deb/rpm);
3. Does the problem with efficiency occurs on only one client PC or the same behavior can be seen on all work stations? 
4. Does the issue occur in all browsers?

Please note that we do not recommend to install package version of Document Server on the same machine with other applications. 

Check the console of the browser for errors when the file is opened for co-editing. Open console tab in browser console -> refresh the page. Then open network tab and refresh the page. If there are any errors, please send us screenshots. 

I would also recommend to check logs of Document Server: 

For docker installation: /app/onlyoffice/DocumentServer/logs/documentserver/
For package installation: /var/log/onlyoffice/documentserver/logs

**Comment by LinneyS** [comment]
This issue was closed due to no response.
