### ISSUE TITLE
"Save as" (File Conversion) not shown for shared files

### ISSUE THREAD

**Issue by Io-Qo** [ONLYOFFICE/onlyoffice-nextcloud#724]
Currently, if a file is shared by another Nextcloud user, the user who isn't the owner can't see the download/coonversion options in the menu (file editing works just fine).

Running:
Nextcloud 24.0.5
OnlyOffice-Nextcloud 7.5.6
OnlyOffice Document Server  7.2.1-34

**Comment by Io-Qo** [comment]
This bug extends to printing as printing shared documents is not possible. Seem like a lot of operations are not allowed anymore.

**Comment by djsime1** [comment]
Also experiencing this issue, seems like it was introduced with #702. This occurs on both files shared through folders, and files shared directly.
