### ISSUE TITLE
copy/ paste not working in shared documents since 7.5.6

### ISSUE THREAD

**Issue by selyod-ka** [ONLYOFFICE/onlyoffice-nextcloud#725]
Hi,

after updating from 7.5.4 to 7.5.6 it's not possible to copy from or paste to shared documents. It works with own documents, though.
I guess that #724 is related to this issue, as we also cannot "Save as" since the update.

Thanks.

**Comment by Arakmar** [comment]
Same here. After reverting 540eff48cc661da02338d44f94c8c467ab5a070f, it's working again.
It's also fixing #724
