### ISSUE TITLE
After update NC25, OnlyOffice 7.6.6 documents not opening from NC android app

### ISSUE THREAD

**Issue by sebaxakerhtc** [ONLYOFFICE/onlyoffice-nextcloud#735]
Updated Nextcloud to 25.0.0
Onlyoffice app updated to 7.6.6
docker container onlyoffice/documentserver:latest

Can't open documents anymore.
Have tried to downgrade onlyoffice app, but NC not work this way and want update of app.
Admin log:
![fatal](https://user-images.githubusercontent.com/32651506/198874005-9f429395-fb77-4afe-80b3-e052d66aa246.png)

Android app:
![app](https://user-images.githubusercontent.com/32651506/198874167-2671c6fb-4aae-4563-b2d3-f0870c368f8d.jpg)

**Comment by SergeyKorneyev** [comment]
Hello,
We haven't been able to reproduce this yet. 
Could you describe the scenario in more detail? Does this happen with any document or with specific ones? Is the file shared with you or did you create it yourself?

**Comment by sebaxakerhtc** [comment]
In the log i can see this:

```
GET /ocs/v2.php/apps/onlyoffice/api/v1/config/0?filePath=my-path-to-document.docx&directToken=bla-bla-bla**&guestName=null**&inframe=true
```
Very strange this: `&guestName=null&inframe=true`

**Comment by sebaxakerhtc** [comment]
So, i found a problem. 
The problem is your OnlyOffice app is not compotable with app named "Terms of service"
I don't know why, but... that's true. After disabling "Terms of service" app all works just fine!
Thank you for your tries to help!
