### ISSUE TITLE
Collaboration in Word Documents causes jumping view in NC25

### ISSUE THREAD

**Issue by arnowelzel** [ONLYOFFICE/onlyoffice-nextcloud#743]
Starting with Nextcloud 25 the OnlyOffice integration has a strange problem: When another persion starts typing in the document, the whole view jumps and and down while the view is updated.

To reproduce this problem:

1. Create a an empty Word document in a shared folder
2. Open the document
3. Ask the other user to open the document as well
4. Enter a number of paragraphs
5. As soon as the other use also starts typing on one of the lower paragraphs, the whole view starts jumping and and down

OnlyOffice version: Document editor 7.2.1.34 (Community Edition, running in a Docker container)
Nextcloud integration app: 7.6.8
Nextcloud server: 25.0.1

**Comment by Antipkin-A** [comment]
fixed https://github.com/ONLYOFFICE/DocumentServer/issues/1955
