### ISSUE TITLE
Page title only updated after reload

### ISSUE THREAD

**Issue by Mezgrman** [ONLYOFFICE/onlyoffice-nextcloud#749]
I am running Nextcloud 25.0.2 and OnlyOffice document server community edition 7.2.2.56. When opening a file (e.g. a .xlsx spreadsheet), it loads with the nextcloud title bar on top and OnlyOffice in a frame below with rounded corners. The browser page title, however, stays at "Files", only the favicon changes to that of OnlyOffice. If I now reload the page, the OnlyOffice frame has no rounded corners anymore and the page title updates to the name of the open file.
I would appreciate if the page title always updated and, if possible, the rounded corners are gone. This seems to be some sort of issue of loading content dynamically.

**Comment by LinneyS** [comment]
updating title fixed
Corners issue: #777
