### ISSUE TITLE
auto force save setting

### ISSUE THREAD

**Issue by YuanZhencai** [ONLYOFFICE/onlyoffice-nextcloud#751]
I want to save the source file automatically and don't want to wait for the callback method.

Is there an option to automatically force saving

**Comment by SergeyKorneyev** [comment]
Hello,
There are two main force saving methods available for our Nextcloud integration:
1. Manual force saving which you can turn on in the ONLYOFFICE connector settings in Nextcloud: the option is "Keep intermediate versions when editing (forcesave)". This allows users to press the "Save" button in the editors to create a version of the document.
2. Automatic force saving that can be enabled in the Document Server's config. Here are the parameters: https://helpcenter.onlyoffice.com/installation/docs-developer-configuring.aspx#AutoAssembly. Enabling this option will allow creating intermediate versions after the specified interval.

Note that using force saving doesn't disable the default saving method, so the final version of the file will be created in ~10 seconds after all the editing sessions for that file are closed.
