### ISSUE TITLE
Problem opening files from Nextcloud

### ISSUE THREAD

**Issue by dasbenjo** [ONLYOFFICE/onlyoffice-nextcloud#755]
### Operating System

Windows 10 / 8.1 / 7

### Version information

7.2.134

### Expected Behavior

the document should open, using the whole height of the document space. When I open documents locally it works as expected:
![korrekt onlyoffice](https://user-images.githubusercontent.com/25540682/207361229-cc543e32-ca07-4a43-b7c8-377216f3cfa0.jpg)

### Actual Behavior

there is a rectangle at the bottom 60px high and 100% width, displayed with the custom theme colour (in my case blue) from Nextcloud (the problem started when changing to the newest version of Nextcloud 25, which included a complete overhaul of the standard Nextcloud theme). On the server is also the latest docker version of the Onlyoffice Document server installed, which itself used in the browser, is opening the documents from nextcloud normally and uses all of the height.
![problem onlyoffice](https://user-images.githubusercontent.com/25540682/207361191-84b14ec3-8913-442c-930f-d1bc92b47f60.jpg)

**Comment by dasbenjo** [comment]
which would be the correct project to raise this problem? The core server? What is kind of strange, that this problem only occurs in the onlyoffice editor app, not the onlyoffice variant in the browser 🤔

**Comment by LuckySpecialist** [comment]
> which would be the correct project to raise this problem? The core server?

I can't tell you.
I think it's better to ask NC support, they are better oriented in their product and will be able to redirect the problem where it is needed.
