### ISSUE TITLE
Stuck at Loading Document 

### ISSUE THREAD

**Issue by octavsly** [ONLYOFFICE/onlyoffice-nextcloud#762]
I have two instance of nextcloud, document_server and onlyoffice on the same machine. 
Machine is running:
apache 2.4.54
php 8.1.12

Both nextcloud instalations have the same version: 
**nextcloud 25.0.3, 
Community Document Server 0.1.13
OnlyOffice 7.6.8**

On one installation I can open the documents with OnlyOffice, 
on the second one I cannot, it is stuck at "Loading Document"
On the second one I see the following error

`{"reqId":"Y-yEB3y1SczcR4EfTh6MxwAAjAA","level":0,"time":"2023-02-15T07:05:05+00:00","remoteAddr":"192.168.1.5","user":"root","app":"PHP","method":"POST","url":"/apps/documentserver_community/3rdparty/onlyoffice/documentser
ver/doc/3125220476/c/639/pzhin0ac/xhr?t=1676444679906","message":"Return type of OCA\\DocumentServer\\Document\\Lock::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice at /var/www/domain.domain/htdocs/nextcloud/apps/documentserver_community/lib/Document/Lock.php#61","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0","version":"25.0.3.2","exception":{"Exception":"Error","Message":"Return type of OCA\\DocumentServer\\Document\\Lock::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice at /var/www/domain.domain/htdocs/nextcloud/apps/documentserver_community/lib/Document/Lock.php#61","Code":0,"Trace":[{"file":"/var/www/domain.domain/htdocs/nextcloud/apps/documentserver_community/lib/Document/Lock.php","line":26,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/domain.domain/htdocs/nextcloud/lib/composer/composer/ClassLoader.php","line":571,"args":["/var/www/domain.domain/htdocs/nextcloud/apps/documentserver_community/lib/Document/Lock.php"],"function":"include"},{"file":"/var/www/domain.domain/htdocs/nextcloud/lib/composer/composer/ClassLoader.php","line":428,"function":"Composer\\Autoload\\includeFile"},{"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->"},{"file":"/var/www/domain.domain/htdocs/nextcloud/apps/documentserver_community/lib/Document/LockStore.php","line":83,"function":"array_map"},{"file":"/var/www/domain.domain/htdocs/nextcloud/apps/documentserver_community/lib/Document/LockStore.php","line":123,"function":"releaseLocksByQuery","class":"OCA\\DocumentServer\\Document\\LockStore","type":"->"},{"file":"/var/www/domain.domain/htdocs/nextcloud/apps/documentserver_community/lib/XHRCommand/LockExpire.php","line":39,"function":"expireLocksForDocument","class":"OCA\\DocumentServer\\Document\\LockStore","type":"->"},{"file":"/var/www/domain.domain/htdocs/nextcloud/apps/documentserver_community/lib/XHRCommand/CommandDispatcher.php","line":55,"function":"handle","class":"OCA\\DocumentServer\\XHRCommand\\LockExpire","type":"->"},{"file":"/var/www/domain.domain/htdocs/nextcloud/apps/documentserver_community/lib/Channel/Channel.php","line":91,"function":"idleWork","class":"OCA\\DocumentServer\\XHRCommand\\CommandDispatcher","type":"->"},{"file":"/var/www/domain.domain/htdocs/nextcloud/apps/documentserver_community/lib/Controller/SessionController.php","line":101,"function":"getResponse","class":"OCA\\DocumentServer\\Channel\\Channel","type":"->"},{"file":"/var/www/domain.domain/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"xhr","class":"OCA\\DocumentServer\\Controller\\SessionController","type":"->"},{"file":"/var/www/domain.domain/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/domain.domain/htdocs/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/domain.domain/htdocs/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/domain.domain/htdocs/nextcloud/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/domain.domain/htdocs/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/domain.domain/htdocs/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
`

Spent several hours trying to find out why this error appears but without any success. 

if I add #[\\ReturnTypeWillChange] then it does not print any message but still is stuck at "Loading Document"

**Comment by LinneyS** [comment]
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://forum.onlyoffice.com/t/community-document-server-app-in-nextcloud-18/268).
