### ISSUE TITLE
[SOLVED] - CentOS RPM at the moment broken after 7.1

### ISSUE THREAD

**Issue by ant0nwax** [ONLYOFFICE/onlyoffice-nextcloud#763]
Hi developers

please take a look at this:
https://github.com/ONLYOFFICE/DocumentServer/issues/2115

```
[root@onlyoffice etc]# grep 12:0 /var/log/onlyoffice/documentserver/nginx.error.log | cut -d" " -f 3,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,22,23,25,26,27,28 | sort -u
[error] connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.proxyserver, server: , request: "GET HTTP/1.1", upstream: host: "192.168.1.onlyofficeserver:443"
[error] connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.proxyserver, server: , request: "GET HTTP/1.1", upstream: host: "192.168.1.onlyofficeserver", referrer: "https://onlyoffice.REMOVED.COM/7.3.2-8/web-apps/apps/spreadsheeteditor/main/index_loader.html?_dc=7.3.2-8&lang=en&customer=ONLYOFFICE&frameEditorId=iframeEditor&compact=true&parentOrigin=https://antcloud.NEXTCLOUDREMOVED.UK&uitheme=theme-classic-light"
[error] open() "/var/www/onlyoffice/documentserver/web-apps/vendor/socketio/socket.io.min.js.map" failed (2: No such file or directory), client: 192.168.1.proxyserver, server: , request: "GET HTTP/1.1", host:
```

it seems to be a link generated by Nextcloud 

it is missing a file called `socket.io.min.js.map`, which was renamed to `socket.io.min.js` according to this post:

https://github.com/socketio/socket.io/issues/3768

please could you find a method to integrate this change into the code in the Integration App if it is somewhere there the file does not exist on the onlyoffice server and if i copy the `socket.io.min.js` to `socket.io.min.js.map` it does not solve it?

```
[root@onlyoffice etc]# ls -la /var/www/onlyoffice/documentserver/web-apps/vendor/socketio/socket.io.min.js.map
ls: cannot access '/var/www/onlyoffice/documentserver/web-apps/vendor/socketio/socket.io.min.js.map': No such file or directory
[root@onlyoffice etc]# ls -la /var/www/onlyoffice/documentserver/web-apps/vendor/socketio
total 44
dr-xr-xr-x.  2 ds ds    30 Feb 19 10:50 .
dr-xr-xr-x. 12 ds ds   167 Feb 19 10:53 ..
-r--r-----.  1 ds ds 44004 Feb  9 04:11 socket.io.min.js
[root@onlyoffice etc]#
```

at /var/www/onlyoffice i searched for expression `socket.io.min.js.map`

```
[root@onlyoffice onlyoffice]#  find . -type f | xargs grep socket.io.min.js.map
grep: ./documentserver/sdkjs/slide/themes/src/05_green: No such file or directory
grep: leaf.pptx: No such file or directory
grep: ./documentserver/web-apps/apps/documenteditor/main/resources/help/fr/images/right: No such file or directory
grep: heaterfooter.png: No such file or directory
./documentserver/web-apps/vendor/socketio/socket.io.min.js://# sourceMappingURL=socket.io.min.js.map
[root@onlyoffice onlyoffice]# cd ./documentserver/web-apps/vendor/socketio/
```

**Comment by igwyd** [comment]
Hello @ant0nwax, we have a bug 61138 in our private issue tracker.

**Comment by ant0nwax** [comment]
Hi @igwyd thank you for confirming that you have a private issue tracker for an open source software ;-) i like this world

**Comment by Gspohu** [comment]
> Hello @ant0nwax, we have a bug 61138 in our private issue tracker.

And it is planned to fix it in a next release quite soon?
Because the last release is quite old

**Comment by ant0nwax** [comment]
For me this "secret bug" does not allow to use Nextcloud with OnlyOffice newer than 7.1

**Comment by Gspohu** [comment]
> For me this "secret bug" does not allow to use Nextcloud with OnlyOffice newer than 7.1
Same here

**Comment by ant0nwax** [comment]
@igwyd could you maybe be so kind and please share the status, the estimated release date and the planned fix version for the bug?
Background, My nextcloud / Onlyoffice is unusable for 1 week now because I am fed up with restoring, I would like to see if I should restore in order to use only office 7.1 or just wait... but without any OPEN information on your planned release dates, this task is problematic to see, I am not asking you to disclose more private information, but those are information that in my opinion are not a problem to see a bug fixes implementations planned release date for public... correct me if I did not think about some aspects.
Thank you very much and I wish you a very nice ongoing weekend and start of the week,

**Comment by ant0nwax** [comment]
As the Nextcloud OnlyOffice Integration seems to be not important to OnlyOffice, nor Nextcloud, I think I will change the scope to Collabora. I give the two App Developer Teams one more week for Integrating a bugfix, basically there was no work done on the bugfix which is visible, even no release date was shared... Thank you for keeping us posted and not hiding in your private bug tracker...

**Comment by ant0nwax** [comment]
Restored OnlyOffice 7.1 - works like a charm

**Comment by igwyd** [comment]
Our Developers answered in the bug that this message is for debugging, it does not affect the performance of the application in any way. Problems with your integration in something else. I recommend installing the docker version for the test and connecting it to your cloud.

**Comment by ant0nwax** [comment]
If on your webpage you write that some of the packaged versions are unsupported after version 7.1 then i will do that, but i did not see that yet on your official releases, so I am waiting for the official version of your comment... actually CentOS / RedHat OnlyOffice Packaged RPM is ONLY SUPPORTED UNTIL 7.1, i do not see any effort of any developers to work on that task, or the priority on that tasks is minimal, it was asked about a planned release, there was no answer from your side for that... just a please install docker.... i bet on CentOS docker version will ALSO NOT WORK, or did you test that with Nextcloud on CENTOS and OnlyOffice Docker on CentOS?

**Comment by igwyd** [comment]
ONLYOFFICE-Docs 7.3.2 works in Centos 7, 8 and 9, we tested it, you can verify this by installing on a clean server, on a virtual machine, for example. I recommended you to test with docker to make sure the warn message in dev-tools and error message in nginx.error.log about missing socket.io.min.js.map doesn't affect the documentserver.

**Comment by igwyd** [comment]
Your problem is something else. And the simplest solution in my opinion is to reinstall the document server.

**Comment by ant0nwax** [comment]
yes, indeed, my problem is that you have a private bug tracker, that is the main reason why i will not reinstall but consider an OPEN SOURCE software

**Comment by Gspohu** [comment]
> Our Developers answered in the bug that this message is for debugging, it does not affect the performance of the application in any way. Problems with your integration in something else. I recommend installing the docker version for the test and connecting it to your cloud.

Hi, 
Thank you for providing answers.
I was also on packages, but when the update broke everything, I switched to docker and it doesn't work any better. I have tested all versions post 7.1.

But it is possible that something has changed in the configuration and I am not aware of it. Maybe you should check the documentation too?

**Comment by ant0nwax** [comment]
@Gspohu lets stick o 7.1 and consider migrating to Collabora i heard it shall be Open Source more than OnlyOffice

**Comment by igwyd** [comment]
@Gspohu i will check. Can you provide links to the documentation you used and provide the documentserver log with errors?
@ant0nwax i can't discuss having a private tracker, but I can try to help with the document server issue. As soon as I have more time, I will take a closer look at your issue https://github.com/ONLYOFFICE/DocumentServer/issues/2115. How do you change http to https?

**Comment by igwyd** [comment]
@ant0nwax I checked your [case](https://github.com/ONLYOFFICE/DocumentServer/issues/2115#issue-1590633931) and everythings works fine on my centos 8 steam server, include enabled SELinux and disabled ipv6. Follow this scenario and see it yourself. 
1. Disable ipv6 and install ONLYOFFICE-Docs 7.1.1, this installation [guid](https://helpcenter.onlyoffice.com/installation/docs-enterprise-install-centos.aspx). NOTE: After installation documentserver in ```/etc/nginx/conf.d/ds.conf``` comment out ipv6 string ```listen [::]:80 default_server;``` and restart nginx server and run ```sudo service supervisord start``` ```sudo systemctl enable supervisord```
2. Open a browser and go to your server HTTP address. On ```welcome page``` follow instruction to enable the integrated test exaple. Create a document in integrated test exaple. Make sure the document is created and can be edited.
3. Switching ONLYOFFICE Docs to HTTPS protocol, this [guid](https://helpcenter.onlyoffice.com/installation/docs-community-https-linux.aspx) and after in ```/etc/nginx/conf.d/ds.conf``` comment out ipv6 strings ```listen [::]:80 default_server;``` ```listen [::1]:80;``` and ```listen [::]:443 ssl default_server;```. Restart nginx ```service nginx restart```
4. Open a browser and go to your server HTTPS address. On ```welcome page``` follow instruction to enable the integrated test exaple. Create a document in integrated test exaple. Make sure the document is created and can be edited.
5. Update documentserver to 7.3.2 vesion from repo ```yum update -y```
6. Open a browser and clear browser cache, go to your server HTTPS address. On ```welcome page``` follow instruction to enable the integrated test exaple. Create a document in integrated test exaple. Make sure the document is created and can be edited.
7. On other server install nextcloud 25, i use this HTTPS [example](https://github.com/nextcloud/docker/tree/master/.examples) with-nginx-proxy.
8. Install onlyoffice connector from nextcloud interface: app - ONLYOFFICE 7.6.8 and settings up it.
9. Create and open new document
![NC+DS](https://user-images.githubusercontent.com/67538082/223434304-89bdf1a3-bb0c-4a48-ab53-20a6ed3df32e.png)

PS We test our installations on default clean updated servers because we can't know all of the user's custom settings. Ports https://helpcenter.onlyoffice.com/installation/docs-community-open-ports.aspx. I guess that where on previous installations was somehow lost local.json, its important because default.json must be update from version to new version - [I want to change some Document Server parameters from the default.json configuration file. How can I do that so that my changes were not lost after update?](https://api.onlyoffice.com/editors/faq/general)

**Comment by igwyd** [comment]
@ant0nwax try this way:
1. On version 7.1.1 run ```documentserver-configure.sh```
2. Make sure the documentserver is work with integrated test exaple on HTTP, if not watch logs and fix the errors. You can ask here.
3. Switch installation to HTTPS and make sure the documentserver is work
4. Connect to Nextcloud.

**Comment by ant0nwax** [comment]
@igwyd I shared my tries in the referenced issue https://github.com/ONLYOFFICE/DocumentServer/issues/2115
everything worked fine, but as said there is one problem OPEN and this is the OnlyOffice app add on on CentOS for Nextcloud

please take a look at this:

the app still has a reference for a file called socket.io.min.js.map, which was renamed to socket.io.min.js according to this post:

PLEASE READ IT!

https://github.com/socketio/socket.io/issues/3768

please could you find a method to integrate this change into the code in the Integration App

**Comment by igwyd** [comment]
@ant0nwax i seen it https://github.com/socketio/socket.io/issues/3768 and already answer to you https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/763#issuecomment-1445739334, the opinion of our developers has not changed since that moment - this does NOT affect the operation of the application ONLYOFFICE-Docs or connector onlyoffice in nexcloud, we did a lot of tests to make sure. This bug is not a priority now.

**Comment by ant0nwax** [comment]
I state:

the reference to this renamed file is in the files of the onlyoffice
add-on, at least that is what i remember , could you please show a proof
that the reference to this file is inside nextcloud and not in the add on?

I need something to open an issue at nextcloud then.

but i remember that i checked and i found the reference inside the
mentioned files in the beginning of the issue.

for my understanding nextcloud on centos 8 stream will never work with only
office if you update everything to latest with yum update -y

Kind Regards From Phoneland

**Comment by ant0nwax** [comment]
I will stay on 7.1.23 until i hear your result, it is not urgent, but please do not ask me to install docker ;) i am running rpm based and it shall stay like that

**Comment by ant0nwax** [comment]
solved by something like 5 hours which can be reduced to:

```
cp /etc/onlyoffice/documentserver/nginx/ds.conf /etc/onlyoffice/documentserver/nginx/ds.conf-backup42
sudo yum reinstall onlyoffice-documentserver
cp /etc/onlyoffice/documentserver/nginx/ds.conf-backup42 /etc/onlyoffice/documentserver/nginx/ds.conf
/usr/bin/documentserver-configure.sh
documentserver-jwt-status.sh # with this you get a secret that is needed for the nextcloud olyoffice integration
systemctl restart ds-docservice.service 
systemctl restart nginx
```
add the JWT secret to nextcloud only office integration and VOILA

**Comment by ant0nwax** [comment]
I think the socket thing is still in the console, but it was never an Error but one of the million Warnings ;)

**Comment by igwyd** [comment]
Hello @ant0nwax, it's solved, can you close this issue?

**Comment by hahaxd35** [comment]
getting the same error in 7.5.1 debian 12 fresh install

**Comment by ant0nwax** [comment]
I confirm its still broken with nextcoud on my setup.
I just was lazy to login, I tried an upgrade and needed to fall back again, restore the backup before the upgrade
I will stop writing and really consider Collabora instead, sorry I wanted really to support OnlyOffice, but it seems there is something not used enough by many so I must let it go

**Comment by ant0nwax** [comment]
ad SOLVED in that case, was just my fall back / restore the backup :) that was difficult enough, or reinstall, but upgrading is not possible since a certain time... details are in post: https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/763#issuecomment-1469954202

I am sure we could setup an online meeting with on of your software quality assurance tessters, but I am not sure if you would like to help me as a non paying customer... I am really just a private user and I am in my second year without microsoft and google :)
