### ISSUE TITLE
viewing spreadsheet sends notification it was edited

### ISSUE THREAD

**Issue by kevev** [ONLYOFFICE/onlyoffice-nextcloud#778]
I notice that on a shared spreadsheet in Nextcloud when opening the spreadsheet for viewing but not making any changes, we get notifications that it was changed. I am guessing that the spreadsheet is being auto saved. Is there any way to prevent this?

**Comment by HelenBelova17** [comment]
Hello @**kevev,** please specify some additional information, so we are able to reproduce the issue on our side:
1. Currently installed version of the Document Server;
2. Version of the ONLYOFFICE integration app;
3. Version of Nextcloud;
4. Describe your actions in steps.

**Comment by kevev** [comment]
Collabora Online - Built-in CODE Server: 22.5.802
Nextcloud Office: 7.1.1
Nextcloud: 25.0.4

**Comment by SergeyKorneyev** [comment]
> Collabora Online - Built-in CODE Server: 22.5.802
> Nextcloud Office: 7.1.1
> Nextcloud: 25.0.4

This is the ONLYOFFICE repo, and apparently your issue is with Collabora. Please reach out to them.

**Comment by kevev** [comment]
Very sorry. Thank You.
