### ISSUE TITLE
Enable automated Let's Encrypt SSL for connection

### ISSUE THREAD

**Issue by Niclas-sol** [ONLYOFFICE/onlyoffice-nextcloud#78]
It would be great if I can just tick a box to enable Let's Encrypt for the communtication between Nextcloud and OnlyOffice.
I use a container with a self signed certificate, but Firefox don't accept it without opening the domain.com:8443/welcome page and confirm the certificate manually

**Comment by CarlOnlyoffice** [comment]
Hello @Niclas-sol,
I'd recommend using certbot utility for automated certificate creation:
https://certbot.eff.org/
