### ISSUE TITLE
errorlogs filling because space in l10n/de.js  l10n/de.json at the beginning of the files

### ISSUE THREAD

**Issue by hellblue** [ONLYOFFICE/onlyoffice-nextcloud#8]
Warning | l10n | Failed to load /var/www/html/apps/onlyoffice/l10n/de.json - json error code: 4 | 2018-08-31T19:40:44+0200
-- | -- | -- | --
Warning | l10n | Failed to load /var/www/html/apps/onlyoffice/l10n/de.json - json error code: 4 | 2018-08-31T19:40:22+0200
Warning | l10n | Failed to load /var/www/html/apps/onlyoffice/l10n/de.json - json error code: 4 | 2018-08-31T19:40:20+0200
Warning | l10n | Failed to load /var/www/html/apps/onlyoffice/l10n/de.json - json error code: 4 | 2018-08-31T19:40:20+0200
Warning | l10n | Failed to load /var/www/html/apps/onlyoffice/l10n/de.json - json error code: 4 | 2018-08-31T19:40:05+0200

if i remove the space at the beginning the error is gone away but then nextcloud fails the integrity check because new hash

**Comment by LinneyS** [comment]
Thank you
