### ISSUE TITLE
APP not accessible after installation

### ISSUE THREAD

**Issue by Toysman** [ONLYOFFICE/onlyoffice-nextcloud#814]
Hello,

Onlyoffice is not callable after installation and when I try to get into the settings I get an error message about an internal server error.

I cannot find any entries in the nextcloud.log.

Thanks for support

Nextcloud 25.0.2.3
Nextcloud Hub 4 (26.0.1)
Onlyoffice 7.8.0

**Comment by SergeyKorneyev** [comment]
Hello,
Could you provide a little bit more details? Did you install the connector app from the web interface or manually on the server? A video or some screenshots demonstrating the issue would also be of great help.
