### ISSUE TITLE
real times changes not updated (collaboration)

### ISSUE THREAD

**Issue by MARTINrichard05** [ONLYOFFICE/onlyoffice-nextcloud#818]
since some time, when i edit a document with someone, the person desnt see the changes in real time
i opened dev console, and he did the same and he is receiving changes (network tab) but they doesnt show on the screen

**Comment by ferdiga** [comment]
same issue here
to reproduce
- open the same document in 2 different browser windows
- edit in one window
- changes not visible in the other

BTW this works in collabora and I use this setup often in large spreadsheets to monitor changes in detail sheets on the summary sheet
NC 7.1.3 
ONLYOFFICE 8.2.4
community document server 0.1.13

**Comment by LinneyS** [comment]
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://forum.onlyoffice.com/t/community-document-server-app-in-nextcloud-18/268).
