### ISSUE TITLE
Display a warning to the user before open a file which is already locked by another user

### ISSUE THREAD

**Issue by vagner-dias** [ONLYOFFICE/onlyoffice-nextcloud#819]
If a user locks a file in Nextcloud and another user tries to edit the same file online using OnlyOffice, OnlyOffice currently allows the edit to occur. 

It would be helpful if OnlyOffice could check if the file is locked before opening it. If the file is locked, OnlyOffice could display a warning or open the file in read-only mode

Regards,

**Comment by vagner-dias** [comment]
Hello, Team.

Do you have plans to implement this feature in some point?

It seems that NextCloud Office (collabora) has already implemented it.

Regards.

**Comment by LinneyS** [comment]
#465
