### ISSUE TITLE
Onlyoffice Document Server not working with NC 13.0.1

### ISSUE THREAD

**Issue by ExaconAT** [ONLYOFFICE/onlyoffice-nextcloud#82]
BUG

NC Protocol:
file_get_contents(https://oo.xx.net/ConvertService.ashx): failed to open stream: HTTP request failed! HTTP/1.0 504 Gateway Time-out at /var/www/clients/client1/web16/web/apps2/onlyoffice/lib/documentservice.php#351

16.04 LTS - All upgraded

Firefox latest

```
curl https://oo.xxx.net
<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
```

curl https://oo.xx.net/ConvertService.ashx
<?xml version="1.0" encoding="utf-8"?><FileResult><Error>-8</Error></FileResult>
```

**Comment by LinneyS** [comment]
Closed by author https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/82#issuecomment-400653952
