### ISSUE TITLE
modification in collaborate files doesn't showed

### ISSUE THREAD

**Issue by Sicoval31** [ONLYOFFICE/onlyoffice-nextcloud#829]
Nextcloud 25.0.7 (snap auto upgrade)
office nextcloud 7.8.0
Community document server 0.1.13

since few months, when editing a file (docx, xlsx) with OO and many partners, the collaborate editing mode doesn't work fine :
Partner A add info in a Excel cell, partner B show wich cell, but never see what is added, even if Partner A save the file.

Need to quit OO and reload the file.
try with Firefox, edge or chrome .. same problem
try with other computer : same problem

No error message

It's not a collaborate mode

Thanks to repair or explain why coediting is not allow

**Comment by HelenBelova17** [comment]
Hello @Sicoval31 
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).
