### ISSUE TITLE
broken after update to nxcl 27 and 8.0 version

### ISSUE THREAD

**Issue by insound** [ONLYOFFICE/onlyoffice-nextcloud#832]
<html>
<body>

Information | Value
-- | --
Document Server version | 7.40
Connector version | 8.0.0
OnlyOffice Server | Docker
Nextcloud Server OS | Oracle linux 8
Client Browser | Chrome latest

</body>
</html>

Error log:
OC\AppFramework\Utility\QueryNotFoundException: Could not resolve OCA\Onlyoffice\AppInfo\Application! Class "OCA\Onlyoffice\AppInfo\Application" does not exist at <<closure>>

 0. cloud/lib/private/AppFramework/Utility/SimpleContainer.php line 142
    OC\AppFramework\Utility\SimpleContainer->resolve("OCA\\Onlyoffice\\AppInfo\\Application")
 1. cloud/lib/private/ServerContainer.php line 171
    OC\AppFramework\Utility\SimpleContainer->query("OCA\\Onlyoffice\\AppInfo\\Application", true)
 2. cloud/apps/onlyoffice/lib/AdminSettings.php line 41
    OC\ServerContainer->query("OCA\\Onlyoffice\\AppInfo\\Application")
 3. cloud/apps/settings/lib/Controller/CommonSettingsTrait.php line 129
    OCA\Onlyoffice\AdminSettings->getForm()
 4. cloud/apps/settings/lib/Controller/AdminSettingsController.php line 83
    OCA\Settings\Controller\AdminSettingsController->formatSettings([[["OCA\\Onlyoffice\\AdminSettings"]]])
 5. cloud/apps/settings/lib/Controller/CommonSettingsTrait.php line 149
    OCA\Settings\Controller\AdminSettingsController->getSettings("onlyoffice")
 6. cloud/apps/settings/lib/Controller/AdminSettingsController.php line 68
    OCA\Settings\Controller\AdminSettingsController->getIndexResponse("admin", "onlyoffice")
 7.cloud/lib/private/AppFramework/Http/Dispatcher.php line 230
    OCA\Settings\Controller\AdminSettingsController->index("onlyoffice")
 8. cloud/lib/private/AppFramework/Http/Dispatcher.php line 137
    OC\AppFramework\Http\Dispatcher->executeController(["OCA\\Settings\ ... "], "index")
 9. cloud/lib/private/AppFramework/App.php line 183
    OC\AppFramework\Http\Dispatcher->dispatch(["OCA\\Settings\ ... "], "index")
10. cloud/lib/private/Route/Router.php line 315
    OC\AppFramework\App::main("OCA\\Settings\\ ... r", "index", ["OC\\AppFramewo ... "], ["onlyoffice","s ... "])
11. cloud/lib/base.php line 1064
    OC\Route\Router->match("/settings/admin/onlyoffice")
12. cloud/index.php line 36
    OC::handleRequest()

GET /cloud/settings/admin/onlyoffice   at 2023-06-14T14:53:30+00:00  

Connector doenst work.

**Comment by piiskop** [comment]
I confirm that after upgrading to _27_, there is no option to open any files with ONLYOFFICE but only do download.

**Comment by SergeyKorneyev** [comment]
Could you try restarting PHP and the web server like mentioned [here](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/830#issuecomment-1591805947)?

**Comment by insound** [comment]
It really helped. Smth strange becouse i had cleaned opcache and thats have no succcess. Thanks.

**Comment by piiskop** [comment]
> Could you try restarting PHP and the web server like mentioned [here](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/830#issuecomment-1591805947)?

I guess you did not read my comment there:

> This is not a fix for me as I am not using docker and Nextcloud is running on apache2.
