### ISSUE TITLE
SSL issues are found while connecting My Next Cloud and OnlyOffice

### ISSUE THREAD

**Issue by Lucas-Baek-HYU** [ONLYOFFICE/onlyoffice-nextcloud#839]
**Hello,**

I succeeded in building an onlyoffice server and applying the ssl certificate.
I checked the ‘welcome’ page by connecting to HTTPS and checked the healthcheck for ‘true’.

Perhaps the deployment itself doesn’t seem to be a problem.
But the problem occurred in the process of connecting to my cloud.

Error Msg:
Error when trying to connect (cURL error 60: SSL certificate problem: unable to get local issuer certificate (see [libcurl - Error Codes](https://curl.haxx.se/libcurl/c/libcurl-errors.html)) for https://my_onlyoffice_page/healthcheck)

When I accessed the web page, I saw that the certificate chain was applied normally (letscrypt), default.json and local.Checked json.

I checked my port settings and secret key creation normally, and I also checked the token’s enable value (true) change.

But my problem still exists.
Please help me :frowning:

**With Best Regard,
Thank you 😎**

**Comment by SergeyKorneyev** [comment]
Hello,
Does checking the "Disable certificate verification" box in the connector's settings help in your case?

**Comment by Lucas-Baek-HYU** [comment]
Hello,

No, The same message is still checked.
I created docs for testing on the example page, where I see the message "Doc Security Token is not configured correctly".
But I'm already local.json enabled token on json and checked true permissions on inbox, outbox and browser.

**Comment by Lucas-Baek-HYU** [comment]
안녕하세요,

아니요, 같은 메시지가 계속 확인됩니다.
"문서 보안이 거의 구성되지 않았습니다"라는 메시지가 표시되는 예제 페이지에서 테스트용 문서를 만들었습니다.
하지만 저는 이미 json에서 local.json을 활성화하고 전압을 편지함, 보낸 편지함 및 브라우저에서 손상된 권한을 확인했습니다.

**Comment by Lucas-Baek-HYU** [comment]
Hello,

No, the same message is still being printed.
And I ran an example test, and when I created and clicked docs, I got the message "Doc Security Token is not configured correctly." (The file will not open)

But I'm already local.json enabled token and checked true permissions on inbox, outbox and browser.

**Comment by Lucas-Baek-HYU** [comment]
Hello, @SergeyKorneyev 

I have not yet successfully connected the OnlyOffice server to my Next Cloud.

I would appreciate it if you could let me know how to solve the problem I'm experiencing right now.
If this issue is currently under way, please let me know if there is any update that I can refer to :)
