### ISSUE TITLE
Impossible to open files from SMB share

### ISSUE THREAD

**Issue by Jason-Linux** [ONLYOFFICE/onlyoffice-nextcloud#849]
Hello, 

i use Nextcloud with onlyoffice CE.
and i use remote storage from smb shares but i can't open theses files from nextcloud GUI

**Comment by SergeyKorneyev** [comment]
Hello,

Are you able to open files that are not stored in SMB shares without issues?
Please also provide more details on the issue: what kind of error do you get? Some screenshots might also help.

**Comment by Jason-Linux** [comment]
FYI, its impossible with credentials stored for the session and only with credentials stored in database when you choose methode for your SMB Share.

**Comment by SergeyKorneyev** [comment]
> FYI, its impossible with credentials stored for the session and only with credentials stored in database when you choose methode for your SMB Share.

This is actually one of the known issues with external storage: https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/master/README.md#known-issues
