### ISSUE TITLE
Feature Request: Support Nextcloud standard Server Side Encryption

### ISSUE THREAD

**Issue by sunjam** [ONLYOFFICE/onlyoffice-nextcloud#85]
As noted here in the [OnlyOffice Nextcloud Connector](https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/26), **default Nextcloud server side encryption is not supported by OnlyOffice**.   [Click here for documentation on how the encryption is set up server side](https://docs.nextcloud.com/server/10/admin_manual/configuration_files/encryption_configuration.html).  Please consider adding support: Nextcloud administrators have to choose between offering basic encryption or OnlyOffice.

**Comment by PackElend** [comment]
this request might be obsolete as server-side encryption is supported if _master key_ based encryption is enabled see https://api.onlyoffice.com/editors/nextcloud --> known issues.
Moreover, at least ownlcloud plans to remove User key-based encryption from ownCloud in the near future, see https://doc.owncloud.com/server/admin_manual/maintenance/encryption/migrating-from-user-key-to-master-key.html

**Comment by ibnpetr** [comment]
@sunjam @PackElend  We are currently analyzing a situation with the default NC encryption.
Could you please let us know if using a connector from [that branch](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/tree/feature/encryption) will fix the issue with opening encrypted files.

**Comment by PackElend** [comment]
@ibnpetr sorry for my late reply I left the project, what used server-side encryption but I mentioned it in the NC forum https://help.nextcloud.com/t/onlyoffice-and-or-collabora-server-side-encryption/21290
