### ISSUE TITLE
Onlyoffice on nextcloud - print or save as blank pages

### ISSUE THREAD

**Issue by PustyB** [ONLYOFFICE/onlyoffice-nextcloud#856]
Hello!
I have nextcloud along with onlyoffice installed via snap. When printing or saving doc/docx files as PDF, the page is blank. Lines such as from tables or highlights print, but not fonts. 

I tried to add a font using the command `sudo nextcloud.occ documentserver:fonts --add /usr/share/fonts/truetype/liberation/LiberationMono-Bold.ttf` but got the response _Font not found: /usr/share/fonts/truetype/liberation/LiberationMono-Bold.ttf_ , even though the file exists and has permissions of 777

NexCloud - 26
Onlyoffice - 7.8.0
Document Server - 0.1.13

**Comment by LinneyS** [comment]
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://forum.onlyoffice.com/t/community-document-server-app-in-nextcloud-18/268).
