### ISSUE TITLE
Bug disable background check

### ISSUE THREAD

**Issue by busch1982** [ONLYOFFICE/onlyoffice-nextcloud#865]
If you want to disable the background check, enter 0.
This does not work if I add in the Nextcloud config.php

if I enter the following parameter 
Nextcloud config.php

'onlyoffice' => 
  array (
    'editors_check_interval' => 0,
    'verify_peer_off' => true,
    'jwt_header' => 'AuthorizationJwt',
),
the background check is still executed every 24 hours and I get the message that Onlyoffice is not available.

Now I have to press save every 24 hours (without any change) to get Onlyoffice running again.

**Comment by eeuak** [comment]
see my open issue from yesterday https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/864

**Comment by chromefinch** [comment]
This isn't working for me.
I have to identical setups and both are doing this
