### ISSUE TITLE
How to add translation files?

### ISSUE THREAD

**Issue by ostasevych** [ONLYOFFICE/onlyoffice-nextcloud#868]
Hi! I have translated the webUI interface in Ukrainian, added uk.json and uk.js files to the folder l10n, however the settings webUI is still in English, and only UI in context menu in Files changed into Ukrainian. How to make them visible in Ukrainian?

PS I've also submitted relevant PRs.

**Comment by SergeyKorneyev** [comment]
Hi,
Thanks for the contribution! The translation will be added in the next update of the connector, along with the following fixes: https://github.com/ONLYOFFICE/onlyoffice-nextcloud/commit/1682ea48dc5b777b1b98186a7cb2485a78dfd2d1#diff-5ed35a4baa7e7e21a6e782cc730b6d03ea002f67eb2dc52bb068b4c5eec2d4cfR108-R109.
