### ISSUE TITLE
ONLYOFFICE cannot be reached. Please contact admin

### ISSUE THREAD

**Issue by piiskop** [ONLYOFFICE/onlyoffice-nextcloud#870]
I have two instances of Nextcloud on the same machine. I configured the connector of both cases to use the same settings. The configuring was successful - I saw the message with the green label:

> Settings have been successfully updated (version 7.4.1.36)

However, one instance of Nextcloud opens files with ONLYOFFICE successfully whereas the other instance does not:

> ONLYOFFICE cannot be reached. Please contact admin

**Comment by sjkhsl** [comment]
I have the same problem. The connection can be set up, but when I open the document, it prompts an error that cannot be contacted.

**Comment by SergeyKorneyev** [comment]
Please make sure that the Document Server's address that you specify in the connector's settings is reachable from your browser. It could be that the Nextcloud server can reach it, but your client machine cannot, which would explain the issue.

**Comment by piiskop** [comment]
They are in the same machine. The address is correct or it would not have worked for the other instance of Nextcloud in the same machine.

After upgrading Nextcloud lately, ONLYOFFICE started to work with the new instance.

**Comment by SergeyKorneyev** [comment]
@piiskop
So does everything work fine at the moment?

@sjkhsl 
Have you been able to resolve this as well?

**Comment by piiskop** [comment]
It does.
