### ISSUE TITLE
Only office keeps timing throwing error and disconnects

### ISSUE THREAD

**Issue by tltglitch** [ONLYOFFICE/onlyoffice-nextcloud#882]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.4.1

### Expected Behavior

document server used to be connected to nextcloud and worked with no issues until update. 

### Actual Behavior

A couple of times a day the only office server disconnects from nextcloud with the error : 

GuzzleHttp\Exception\ServerException: Server error: `POST https://docs.tt.com/ConvertService.ashx` 

Searched online and some others have had a similar issue using onlyoffice with other document servers but we only use Onlyoffice document  server and app with nextcloud.

### Additional information

Full log : 

{"reqId":"CsURITgE9f7OPR0eAJSN","level":3,"time":"2023-09-27T20:26:03+00:00","remoteAddr":"","user":"--","app":"onlyoffice","method":"","url":"--","message":"GetConvertedUri on check error","userAgent":"--","version":"27.1.1.0","exception":{"Exception":"GuzzleHttp\\Exception\\ServerException","Message":"Server error: `POST https://docs.tt.com/ConvertService.ashx` resulted in a `504 Gateway Timeout` response:\n<html>\n<head><title>504 Gateway Time-out</title></head>\n<body>\n<center><h1>504 Gateway Time-out</h1></center>\n<hr><cente (truncated...)\n","Code":504,"Trace":[{"file":"/var/www/cloud.tt.com/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":69,"function":"create","class":"GuzzleHttp\\Exception\\RequestException","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/cloud.tt.com/3rdparty/guzzlehttp/promises/src/Promise.php","line":204,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/cloud.tt.com/3rdparty/guzzlehttp/promises/src/Promise.php","line":153,"function":"callHandler","class":"GuzzleHttp\\Promise\\Promise","type":"::"},{"file":"/var/www/cloud.tt.com/3rdparty/guzzlehttp/promises/src/TaskQueue.php","line":48,"function":"GuzzleHttp\\Promise\\{closure}","class":"GuzzleHttp\\Promise\\Promise","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/cloud.tt.com/3rdparty/guzzlehttp/promises/src/Promise.php","line":248,"function":"run","class":"GuzzleHttp\\Promise\\TaskQueue","type":"->"},{"file":"/var/www/cloud.tt.com/3rdparty/guzzlehttp/promises/src/Promise.php","line":224,"function":"invokeWaitFn","class":"GuzzleHttp\\Promise\\Promise","type":"->"},{"file":"/var/www/cloud.tt.com/3rdparty/guzzlehttp/promises/src/Promise.php","line":269,"function":"waitIfPending","class":"GuzzleHttp\\Promise\\Promise","type":"->"},{"file":"/var/www/cloud.tt.com/3rdparty/guzzlehttp/promises/src/Promise.php","line":226,"function":"invokeWaitList","class":"GuzzleHttp\\Promise\\Promise","type":"->"},{"file":"/var/www/cloud.tt.com/3rdparty/guzzlehttp/promises/src/Promise.php","line":62,"function":"waitIfPending","class":"GuzzleHttp\\Promise\\Promise","type":"->"},{"file":"/var/www/cloud.tt.com/3rdparty/guzzlehttp/guzzle/src/Client.php","line":187,"function":"wait","class":"GuzzleHttp\\Promise\\Promise","type":"->"},{"file":"/var/www/cloud.tt.com/lib/private/Http/Client/Client.php","line":301,"function":"request","class":"GuzzleHttp\\Client","type":"->"},{"file":"/var/www/cloud.tt.com/apps/onlyoffice/lib/DocumentService.php","line":372,"function":"post","class":"OC\\Http\\Client\\Client","type":"->"},{"file":"/var/www/cloud.tt.com/apps/onlyoffice/lib/DocumentService.php","line":177,"function":"Request","class":"OCA\\Onlyoffice\\DocumentService","type":"->"},{"file":"/var/www/cloud.tt.com/apps/onlyoffice/lib/DocumentService.php","line":91,"function":"SendRequestToConvertService","class":"OCA\\Onlyoffice\\DocumentService","type":"->"},{"file":"/var/www/cloud.tt.com/apps/onlyoffice/lib/DocumentService.php","line":446,"function":"GetConvertedUri","class":"OCA\\Onlyoffice\\DocumentService","type":"->"},{"file":"/var/www/cloud.tt.com/apps/onlyoffice/lib/Cron/EditorsCheck.php","line":144,"function":"checkDocServiceUrl","class":"OCA\\Onlyoffice\\DocumentService","type":"->"},{"file":"/var/www/cloud.tt.com/lib/public/BackgroundJob/Job.php","line":81,"function":"run","class":"OCA\\Onlyoffice\\Cron\\EditorsCheck","type":"->"},{"file":"/var/www/cloud.tt.com/lib/public/BackgroundJob/TimedJob.php","line":103,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/cloud.tt.com/lib/public/BackgroundJob/TimedJob.php","line":93,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->"},{"file":"/var/www/cloud.tt.com/cron.php","line":152,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/cloud.tt.com/3rdparty/guzzlehttp/guzzle/src/Exception/RequestException.php","Line":113,"message":"GetConvertedUri on check error","CustomMessage":"GetConvertedUri on check error"},"id":"6514db61132c1"}

**Comment by igwyd** [comment]
Hello @tltglitch, provide more information please: Nexcloud version, connector app version, Nextcloud and ONLYOFFICE installed on the same or separate servers? Are there any errors in the ONLYOFFICE log?

**Comment by SergeyKorneyev** [comment]
This is most likely related to the new background check functionality. Here's some context and our plans and recommendations for fixing it: https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/864#issuecomment-1743257243

**Comment by SergeyKorneyev** [comment]
The version that includes the fixes (7.9.2/8.2.2) has just been released. Please try updating the connector and check if that helps.

**Comment by LinneyS** [comment]
This issue was closed due to no response.
