### ISSUE TITLE
Behaviour of protection changed

### ISSUE THREAD

**Issue by pierreozoux** [ONLYOFFICE/onlyoffice-nextcloud#883]
Hi!

UserA share (with write permission) internally a document to UserB.

Before, UserB was able to set "protection".

![Screenshot 2023-10-02 at 15-01-09 Annuaire salles LYON - réservations xlsx - Nuage EELV RA](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/assets/1863453/bf596eac-79d4-4f07-9d64-b7240212e374)

Now this tab isn't available any more.

It seems this is due to this commit:
https://github.com/ONLYOFFICE/onlyoffice-nextcloud/commit/06a027e4f7b4936a8fe49695459c641202146d4f

I don't know what is the intended behavior:
 - only the owner should be able to protect?
 - only people with "write" rights should be able to protect?

Thanks for the clarification.

**Comment by SergeyKorneyev** [comment]
Hello,
We've added an option to the connector settings that allows the administrator(s) to choose whether the protection feature can be used only by the file's owner or by any user. By default, it's set to the owner:
![image](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/assets/77327210/87c47631-1e99-4318-9f60-682e19213888)

**Comment by pierreozoux** [comment]
Thanks a lot for your reply, I'll close then!
