### ISSUE TITLE
[HELP NOT ISSUE] Commentary mode ?

### ISSUE THREAD

**Issue by Jason-Linux** [ONLYOFFICE/onlyoffice-nextcloud#899]
Hi I would like to add commentary in my pdf but i can't when i would like to save my file i have : 

![image](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/assets/72259326/6831a977-4770-45b4-842b-41fa87d20be8)

Can you help me to activate it can't find in all document

**Comment by SergeyKorneyev** [comment]
Hello,
This should be fixed with version 7.5.1 of the Document Server.
