### ISSUE TITLE
[EXCEPTION] App "ONLYOFFICE" cannot be installed because it is not compatible with this version of the server.

### ISSUE THREAD

**Issue by nextcloudvmtester** [ONLYOFFICE/onlyoffice-nextcloud#9]
Hi, I'm new to Nextcloud, and am trying to set up a private server.

I've used the VM scripts, and currently use DDNS + SSL (from LetsEncrypt) on an Ubuntu 18.04 server. I am trying to install OnlyOffice using the script available from the nextcloud/vm/apps GitHub page. 

When running the script, I am able to get past the SSL cert step until I get an error message stating that the app is not compatible with the server.

Please advise on how to proceed, or let me know what additional information may be required to debug.

Additional info:
Nextcloud expertise level: Low
Linux expertise: Medium/Low

OS: Ubuntu 18.04
Nextcloud: 13.

Previously installed Collabora (older sources suggested it was possible to run Collabora and OnlyOffice in parallel). I did what I could to remove it (disable + remove from Nextcloud web UI, docker rm -f to remove the docker image). I also manually deleted the Collabora folder that the OnlyOffice install script checks for. When running the vm OnlyOffice install script, it used to complain that Collabora was also installed, but after above changes proceeded without hesitation.

VM is relatively fresh; some apps installed on top of default (ex. Talk, Contacts, Calendar, etc.)

The last lines of output are:
```
Certs are generated!
Site <...> already enabled
Cloning into 'onlyoffice'...
remote: Counting objects: 1411, done
remote: Compressing objects: 100% (143/143), done
remote: Total 1411 (delta 146), reused 197 (delta 108), pack-reused 1160
Receiving objects: 100% (1411/1411), 1.27 MiB | 1.07 MiB/s, done.
Resolving deltas: 100% (826/826), done

[Exception]
App "ONLYOFFICE" cannot be installed because it is not compatible with this version of the server.

app:enable [-g|--groups GROUPS] [--] <app-id>

Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!

sudo -u www-data php /var/www/nextcloud/occ app:enable onlyoffice failed
```
I saw there was already an issue similar to this there, and they suggested to report it here as well (instead?).

I tried to reinstall Collabora, and now it wasn't willing to be installed due to OnlyOffice being installed. I wasn't able to delete the OnlyOffice folder as before.

Thanks in advance for your time/help!

**Comment by maartenw8** [comment]
I've got exactly the same problem here!

**Comment by ibnpetr** [comment]
@nextcloudvmtester @maartenw8 
Could you please confirm that the problem is resolved
https://github.com/nextcloud/vm/issues/641
 nextcloud/vm@847d9072cec5ce590058353b37f4c5dad08bd189

**Comment by alexdaums** [comment]
@ibnpetr It's fixed
