### ISSUE TITLE
Error with opening documents in Nextcloud Mobile App with Groupfolders Advanced Permissions

### ISSUE THREAD

**Issue by Fabi1926** [ONLYOFFICE/onlyoffice-nextcloud#900]
### Problem
Documents in a Groupfolder cant be open in the Nextcloud Mobile App if with the Groupfolders advanced permissions option "Share" is denied. In the Webbrowser the same documents can be opened without any problems.

### System Details

- Nextcloud 27.1.3
- OnlyofficePlugin 8.2.4
- Onlyoffice 7.5.0.125
- Groupfolders Plugin 15.3.1

### Log Message

{"reqId":"QKEbGPuypE0m2XXXXXXX","level":3,"time":"2023-11-09T15:12:30+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"--","app":"onlyoffice","method":"GET","url":"/apps/files/directEditing/36pQZTexHs65H4bfjxW8F2Nysxsxxxxxxxxxxxxxxxxx4mcxgmzYJsF3Szpxz","message":"{\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"/2b021b14-9341-103d-90c7-ad6fdc5e7eb0/files/2025d/Path/to/file.xlsx\",\"Code\":0,\"Trace\":[{\"file\":\"/nix/store/i3kxkcvkqkzg425045lwk1c2wlqfk6l1-nextcloud-27.1.3/lib/private/Files/Node/LazyUserFolder.php\",\"line\":74,\"function\":\"get\",\"class\":\"OC\\\\Files\\\\Node\\\\Root\",\"type\":\"->\"},{\"file\":\"/nix/store/i3kxkcvkqkzg425045lwk1c2wlqfk6l1-nextcloud-27.1.3/lib/private/DirectEditing/Manager.php\",\"line\":311,\"function\":\"get\",\"class\":\"OC\\\\Files\\\\Node\\\\LazyUserFolder\",\"type\":\"->\"},{\"file\":\"/nix/store/i3kxkcvkqkzg425045lwk1c2wlqfk6l1-nextcloud-27.1.3/lib/private/DirectEditing/Token.php\",\"line\":50,\"function\":\"getFileForToken\",\"class\":\"OC\\\\DirectEditing\\\\Manager\",\"type\":\"->\"},{\"file\":\"/nix/store/agg6z9mpdbmdcc4h3jr88sda402axymn-nc-app-onlyoffice-8.2.4/lib/DirectEditor.php\",\"line\":208,\"function\":\"getFile\",\"class\":\"OC\\\\DirectEditing\\\\Token\",\"type\":\"->\"},{\"file\":\"/nix/store/i3kxkcvkqkzg425045lwk1c2wlqfk6l1-nextcloud-27.1.3/lib/private/DirectEditing/Manager.php\",\"line\":211,\"function\":\"open\",\"class\":\"OCA\\\\Onlyoffice\\\\DirectEditor\",\"type\":\"->\"},{\"file\":\"/nix/store/i3kxkcvkqkzg425045lwk1c2wlqfk6l1-nextcloud-27.1.3/apps/files/lib/Controller/DirectEditingViewController.php\",\"line\":65,\"function\":\"edit\",\"class\":\"OC\\\\DirectEditing\\\\Manager\",\"type\":\"->\"},{\"file\":\"/nix/store/i3kxkcvkqkzg425045lwk1c2wlqfk6l1-nextcloud-27.1.3/lib/private/AppFramework/Http/Dispatcher.php\",\"line\":230,\"function\":\"edit\",\"class\":\"OCA\\\\Files\\\\Controller\\\\DirectEditingViewController\",\"type\":\"->\"},{\"file\":\"/nix/store/i3kxkcvkqkzg425045lwk1c2wlqfk6l1-nextcloud-27.1.3/lib/private/AppFramework/Http/Dispatcher.php\",\"line\":137,\"function\":\"executeController\",\"class\":\"OC\\\\AppFramework\\\\Http\\\\Dispatcher\",\"type\":\"->\"},{\"file\":\"/nix/store/i3kxkcvkqkzg425045lwk1c2wlqfk6l1-nextcloud-27.1.3/lib/private/AppFramework/App.php\",\"line\":183,\"function\":\"dispatch\",\"class\":\"OC\\\\AppFramework\\\\Http\\\\Dispatcher\",\"type\":\"->\"},{\"file\":\"/nix/store/i3kxkcvkqkzg425045lwk1c2wlqfk6l1-nextcloud-27.1.3/lib/private/Route/Router.php\",\"line\":315,\"function\":\"main\",\"class\":\"OC\\\\AppFramework\\\\App\",\"type\":\"::\"},{\"file\":\"/nix/store/i3kxkcvkqkzg425045lwk1c2wlqfk6l1-nextcloud-27.1.3/lib/base.php\",\"line\":1068,\"function\":\"match\",\"class\":\"OC\\\\Route\\\\Router\",\"type\":\"->\"},{\"file\":\"/nix/store/i3kxkcvkqkzg425045lwk1c2wlqfk6l1-nextcloud-27.1.3/index.php\",\"line\":36,\"function\":\"handleRequest\",\"class\":\"OC\",\"type\":\"::\"}],\"File\":\"/nix/store/i3kxkcvkqkzg425045lwk1c2wlqfk6l1-nextcloud-27.1.3/lib/private/Files/Node/Root.php\",\"Line\":206,\"message\":\"DirectEditor open\",\"CustomMessage\":\"DirectEditor open\"}","userAgent":"Mozilla/5.0 (Android 14) Mobile Nextcloud-android/3.26.0","version":"27.1.3.2"}

**Comment by Fabi1926** [comment]
Problem still exists with Onlyoffice Version 7.5.1

**Comment by alexanderonlyoffice** [comment]
@Fabi1926,  thank you for reporting this issue. This is a known problem and the reason is in the incorrect handling of the token on Nextcloud side. We have forwarded the description of the issue to Nextcloud team.

**Comment by joshtrichards** [comment]
Fixed in nextcloud/server#44295
