### ISSUE TITLE
Support for Nextcloud 28

### ISSUE THREAD

**Issue by Pilzinsel64** [ONLYOFFICE/onlyoffice-nextcloud#915]
The current version have an error on opening a document and also floods the log with this error:
![grafik](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/assets/23138465/457b7a37-354f-4158-bbd0-4a246938ad22)

**Comment by GVLLIFESTYLE** [comment]
I need this too.
Since update it won't work anymore.

**Comment by martinsautosvc** [comment]
We discovered this incompatibility upon upgrade to NC28 today.  Had to roll back to v27.  Will watch for updates on resolution!

**Comment by LinneyS** [comment]
Hi all
Support for version 28 released
https://github.com/ONLYOFFICE/onlyoffice-nextcloud/releases/tag/v9.0.0
