### ISSUE TITLE
Open app full screen

### ISSUE THREAD

**Issue by arnowelzel** [ONLYOFFICE/onlyoffice-nextcloud#937]
Some Nextcloud apps (like the PDF viewer, photo viewer or Nextcloud Office) don't use the regular app frame but a modal frame which covers the whole browser viewport.

Example for the PDF viewer (content blurred, but you should get the idea):

![image](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/assets/6613614/0916cec9-04ce-4c33-a0b1-227adc7f8399)

A big advantage of this is, that you have more usable space (instead of having the office app inside the smaller app frame with the rounded corners) and you can switch to full screen mode using F11 and do presentations of PowerPoint files directly in the browser without the Nextcloud icon bar at the top.

**Comment by LinneyS** [comment]
#395
