### ISSUE TITLE
Invalid method check

### ISSUE THREAD

**Issue by ChristophWurst** [ONLYOFFICE/onlyoffice-nextcloud#94]
```
Use of undefined constant getHideDownload - assumed 'getHideDownload' (this will throw an Error in a future version of PHP) at \/www\/nextcloud\/apps\/onlyoffice\/controller\/editorcontroller.php#533
```

-> https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/28a6310a3e4f7c0114e8887329315cb65fe3f599/controller/editorcontroller.php#L533

it should be `method_exists($share, "getHideDownload")`

**Comment by LinneyS** [comment]
Thanks @ChristophWurst
