### ISSUE TITLE
Version History in shared view

### ISSUE THREAD

**Issue by glebov21** [ONLYOFFICE/onlyoffice-nextcloud#943]
Hello
In menu i can see "Version History" of document. Buy when i share file link and another use view this document, he can't view "Version History". There is no button in menu. How can i fix this?

**Comment by SergeyKorneyev** [comment]
Hello,
We removed version history for documents opened via external links in 2021. Nextcloud itself does not display it in such cases, so we figured the editor should not do it either.

Are there a lot of cases when you need the person that your share the document with to view its version history? Do you need an option in the connector to enable this?

**Comment by LinneyS** [comment]
#539

**Comment by glebov21** [comment]
I was think more and has concluded what this history have many small changes and they not need for end users. Thanks :)
