### ISSUE TITLE
Nextcloud 15 not Compatible (Serverversion 10 or lower is required)

### ISSUE THREAD

**Issue by hesty98** [ONLYOFFICE/onlyoffice-nextcloud#96]
Hey *,
i am the admin of a nextcloud and recently tried to install onlyoffice using following manual:
https://www.linuxbabe.com/ubuntu/integrate-nextcloud-onlyoffice

I installed Onlyoffice on my server successfully using nginx and apache since i have one server only. However, when wanting to enable onlyoffice via the browser i get the following errors and am not able to enable it....

This app has no minimum Nextcloud version assigned. This will be an error in the future.
This app has no maximum Nextcloud version assigned. This will be an error in the future.
This app cannot be installed because the following dependencies are not fulfilled:
Server version 10 or lower is required.

Server: Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-46-generic x86_64)
Nextcloudversion: 15
Onlyoffice: 2.2.1

EDIT:
My guess is, that i should 'downgrade' onlyoffice version to 2.1 but i couldnt find anything on how to do that.

**Comment by ibnpetr** [comment]
Hello 

> Onlyoffice: 2.2.1

That's a version for ownCloud 
[Here](https://github.com/ONLYOFFICE/onlyoffice-nextcloud) you can find latest version of the NC connector (2.1.10)

**Comment by hesty98** [comment]
> Hello
> 
> > Onlyoffice: 2.2.1
> 
> That's a version for ownCloud
> [Here](https://github.com/ONLYOFFICE/onlyoffice-nextcloud) you can find latest version of the NC connector (2.1.10)

it still says 2.3 in the info.xml under <onlyoffice> ..

**Comment by LinneyS** [comment]
You can not use ownCloud connector for Nextcloud
