### ISSUE TITLE
OnlyOffice Document Editor (web) doesn’t resume auto-save after being offline

### ISSUE THREAD

**Issue by thobach** [ONLYOFFICE/onlyoffice-nextcloud#971]
Nextcloud version (eg, 20.0.5): Nextcloud 24.0.11.1

OnlyOffice version: DOCUMENT EDITOR Version 6.4.0

Steps to replicate it:

1. Create a word document in NextCloud
2. enter some text having auto-save enabled and observer the message in the status bar that changes have been changed
3. go offline (e.g. disable wifi) and online again (e.g. enable wifi again)
4. enter more text and observe that in the status bar there are no more messages like all changes have been changed, also when you press the save button there is no response or error message shown
5. refresh the page and observer that the text entered in step 4 is lost

Workaround: After you went offline, refresh the page and only then start making changes to the document again.

This issue caused not only me, but also my team members a lot of frustration as one assumes auto-save works and then large changes to documents get lost.

**Comment by ostasevych** [comment]
Catching this annoying issue all the time (

**Comment by SergeyKorneyev** [comment]
The issue does not seem to persist with the latest version of Docs (8.0.1). Please try updating your installation to see if that resolves it.
