### ISSUE TITLE
After Upgrade to 9.1.0 Nextcloud not connected to onlyoffice server

### ISSUE THREAD

**Issue by syntezit** [ONLYOFFICE/onlyoffice-nextcloud#977]
After Upgrade to 9.1.0, Nextcloud not connected to onlyoffice server.
Nextcloud 28.0.4
Onlyoffice 8.0.1

Errors
**Could not find resource onlyoffice/js/onlyoffice-template.js to load**
{"reqId":"t1ol3FPfmGk44gNOLLZ2",
"level":3,
"time":"2024-04-08T17:34:56+03:00",
"remoteAddr":"172.16.0.20",
"user":"12345",
"app":"jsresourceloader",
"method":"GET",
"url":"/settings/admin/onlyoffice","message":"Could not find resource onlyoffice/js/onlyoffice-template.js to load",
"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
"version":"28.0.4.1",
"data":{"app":"jsresourceloader"},
"id":"661400959c75b"}

**Comment by JacobMembrino** [comment]
Having this issue as well. I noticed that restoring the lost files (the entire JS directory under nextcloud/apps/onlyoffice/js) from a backup does not work. These files seem to be generated at install in previous versions but this no longer works.

**Comment by Nikos-Mennecy** [comment]
Same problem After Upgrade to 9.1.0
Nextcloud 28.0.4

In the Nextcloud logs : 

Could not find resource onlyoffice/js/onlyoffice-listener.js to load 
Could not find resource onlyoffice/js/onlyoffice-viewer.js to load 
Could not find resource onlyoffice/js/onlyoffice-template.js to load
Could not find resource onlyoffice/js/onlyoffice-main.js to load 
Could not find resource onlyoffice/js/onlyoffice-desktop.js to load 
Could not find resource onlyoffice/js/desktop.js to load 

Thanks !

**Comment by blcetux** [comment]
Same problem after upgrade to 9.1.0

We've reverted to 8.2.4 in the meantime.

**Comment by alyfilipe** [comment]
Some problem here

**Comment by JacobMembrino** [comment]
> Same problem after upgrade to 9.1.0
> 
> We've reverted to 8.2.4 in the meantime.

how can you revert versions?

**Comment by waja** [comment]
Downgrade to the app version 9.0.0 fixed the issue for now.

**Comment by arnowelzel** [comment]
Same issue here. Something went wrong with the 9.1.0 release. But even after downgrading to 9.0.0 it does not work any longer :-(

**Comment by JacobMembrino** [comment]
> I tried everything including restoring the last known working version from my backup - it does not work any longer.

Run these commands:
``` 
$ sudo -u www-data php occ app:disable onlyoffice
$ sudo -u www-data php occ app:remove onlyoffice
$ sudo -u www-data php occ maintenance:repair
```
Then install the last release, unpack it to the /apps/ directory of nextcloud, and change its ownership to your web hosting user (www-data).

I am getting the "Error connection: Error occurred in the document service: Error while downloading the document file to be converted."' error but I can get the plugin to almost work at least.

**Comment by arnowelzel** [comment]
> I am getting the "Error connection: Error occurred in the document service: Error while downloading the document file to be converted."' error but I can get the plugin to almost work at least.

See my last comment edit - I had to remove the URL setting from the appconfig table in Nextcloud, but after that I was able to configure OnlyOffice again.

**Comment by JacobMembrino** [comment]
> See my last comment edit - I had to remove the URL setting from the appconfig table in Nextcloud, but after that I was able to configure OnlyOffice again.

Any thoughts on the `Error connection: Error occurred in the document service: Error while downloading the document file to be converted` error?

**Comment by arnowelzel** [comment]
> > See my last comment edit - I had to remove the URL setting from the appconfig table in Nextcloud, but after that I was able to configure OnlyOffice again.
> 
> Any thoughts on the `Error connection: Error occurred in the document service: Error while downloading the document file to be converted` error?

Sorry - no. I don't have this error here. Neither with DOCX nor with ODT or other formats. But there is an older issue which mentions this: https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/895

**Comment by stepcellwolf** [comment]
Same here!

**Comment by a0g83agbc84** [comment]
I unfortunately am experiencing the same issue...

**Comment by a0g83agbc84** [comment]
This guy seems to be onto something but not even clearing the values from the db empties them from the onlyoffice configuration page, not even after deleting and reinstalling the app: https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/956#issuecomment-2043295196

**Comment by arnowelzel** [comment]
> This guy seems to be onto something but not even clearing the values from the db empties them from the onlyoffice configuration page, not even after deleting and reinstalling the app: [#956 (comment)](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/956#issuecomment-2043295196)

The database table `oc_appconfig` is the only place where the app stores the configuration. If removing the value there does not work, then maybe you need to clear the browser cache, so it has to load the value from the DB.

**Comment by a0g83agbc84** [comment]
@arnowelzel something seems off, because I cleared the browser data (even tried on incognito mode) and I can see the previous values every time. Those values are clearly empty in the db: https://i.imgur.com/KzWHEIn.jpeg

**Comment by t3cneo** [comment]
It does work after copying 9.0.0 js folder as @Nikos-Mennecy pointed out

on your server :

1 grab the 9.0 relaease
```shell
wget https://github.com/ONLYOFFICE/onlyoffice-nextcloud/releases/download/v9.0.0/onlyoffice.tar.gz
```
2 expend
```shell
tar -xf onlyoffice.tar.gz
```
3 copy js folder to where it should be 
```shell
sudo cp -R onlyoffice/js/ /var/lib/docker/volumes/nextcloud_aio_nextcloud/_data/custom_apps/onlyoffice/js
```
4 change ownership
```shell
sudo chown -R www-data:www-data /var/lib/docker/volumes/nextcloud_aio_nextcloud/_data/custom_apps/onlyoffice/js
```
5 cleanup a bit 
```shell
rm -rf onlyoffice onlyoffice.tar.gz
```
6 go to NC webUI > admin settings > OnlyOffice and hit save

**Comment by a0g83agbc84** [comment]
> > @arnowelzel something seems off, because I cleared the browser data (even tried on incognito mode) and I can see the previous values every time. Those values are clearly empty in the db: https://i.imgur.com/KzWHEIn.jpeg
> 
> Strange - for me that worked fine and I have no idea from where else OnlyOffice should get the value from.
> 
> Maybe restart php-fpm just to be sure, that also the PHP opcache is flushed?

I use docker compose with the nextcloud instance, its db, nginx, onlyoffice and redit. I take it `down` and then back `up -d`. Strange.

**Comment by alyfilipe** [comment]
> It does work after copying 9.0.0 js folder as @Nikos-Mennecy pointed out
> 
> on your server :
> 
> 1 grab the 9.0 relaease
> 
> ```shell
> wget https://github.com/ONLYOFFICE/onlyoffice-nextcloud/releases/download/v9.0.0/onlyoffice.tar.gz
> ```
> 
> 2 expend
> 
> ```shell
> tar -xf onlyoffice.tar.gz
> ```
> 
> 3 copy js folder to where it should be
> 
> ```shell
> sudo cp -R onlyoffice/js/ /var/lib/docker/volumes/nextcloud_aio_nextcloud/_data/custom_apps/onlyoffice/js
> ```
> 
> 4 change ownership
> 
> ```shell
> sudo chown -R www-data:www-data /var/lib/docker/volumes/nextcloud_aio_nextcloud/_data/custom_apps/onlyoffice/js
> ```
> 
> 5 cleanup a bit
> 
> ```shell
> rm -rf onlyoffice onlyoffice.tar.gz
> ```
> 
> 6 go to NC webUI > admin settings > OnlyOffice and hit save
> 
> Edit : I guess the [new gitignore](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/commit/d2e42377202f19c5280d3cf4a9828432a5b88c1f#) file is the explanation...

Using this option it saves the onlyoffice configuration, but when I try to open a document, it keeps trying forever....
Direct tests on the onlyoffice server work normally. Only the integration has a problem following the plugin update.

**Comment by kiwiradler** [comment]
Wouldn't it be better to release an update to v.9.1.1 or whatever instead of finding workarounds? Not everyone is able to do all this stuff on his server...

**Comment by JacobMembrino** [comment]
> Any thoughts on the `Error connection: Error occurred in the document service: Error while downloading the document file to be converted` error?

If anyone experiences this error, I was able to fix it after adding this line to my config file in nextcloud:
```  'onlyoffice' => array (
    'verify_peer_off' => false,
  ),```
  
  And rebooting the server.

**Comment by arnowelzel** [comment]
> Wouldn't it be better to release an update to v.9.1.1 or whatever instead of finding workarounds? Not everyone is able to do all this stuff on his server...

Of course - but until then it might help people what to do to get their installation back running.

**Comment by a0g83agbc84** [comment]
@arnowelzel the fact that onlyoffice kept the configuration even though I was deleting the values from the db remains a mystery, but at least I could fix my setup. I could have saved myself almost 1 hour or trial and error if I had gotten enough sleep last night and use the `custom_apps` directory :) Thanks for your help.

**Comment by vagner-dias** [comment]
Same problem here. OnlyOffice is down after the latest upgrade.

**Comment by Nordlead75** [comment]
same problem for me too

**Comment by genius-rst** [comment]
> It does work after copying 9.0.0 js folder as @Nikos-Mennecy pointed out
> 
> on your server :
> 
> 1 grab the 9.0 relaease
> 
> ```shell
> wget https://github.com/ONLYOFFICE/onlyoffice-nextcloud/releases/download/v9.0.0/onlyoffice.tar.gz
> ```
> 
> 2 expend
> 
> ```shell
> tar -xf onlyoffice.tar.gz
> ```
> 
> 3 copy js folder to where it should be
> 
> ```shell
> sudo cp -R onlyoffice/js/ /var/lib/docker/volumes/nextcloud_aio_nextcloud/_data/custom_apps/onlyoffice/js
> ```
> 
> 4 change ownership
> 
> ```shell
> sudo chown -R www-data:www-data /var/lib/docker/volumes/nextcloud_aio_nextcloud/_data/custom_apps/onlyoffice/js
> ```
> 
> 5 cleanup a bit
> 
> ```shell
> rm -rf onlyoffice onlyoffice.tar.gz
> ```
> 
> 6 go to NC webUI > admin settings > OnlyOffice and hit save
> 
> Edit : I guess the [new gitignore](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/commit/d2e42377202f19c5280d3cf4a9828432a5b88c1f#) file is the explanation...

It's works!!! Thank you so much!!

**Comment by masterwishx** [comment]
same issue :  

![image](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/assets/28630321/8fe6f306-643a-497f-a181-77e1bcd49fed)

**Comment by JacobMembrino** [comment]
> same issue :

Luckily all you have to do is uninstall the new version of the connector app and install the last release. The commands to do so are above

**Comment by HB9HIL** [comment]
same issue here...

**Comment by HB9HIL** [comment]
> Wouldn't it be better to release an update to v.9.1.1 or whatever instead of finding workarounds? Not everyone is able to do all this stuff on his server...

absolutely! hotfix release please

**Comment by jdaviescoates** [comment]
I find it completely bonkers that such an important and widely used plugin that so many people and organisations depend on was not properly tested before being released :man_facepalming:

**Comment by jdaviescoates** [comment]
> Luckily all you have to do is uninstall the new version of the connector app and install the last release. The commands to do so are above

For many people that is evidently not all you have to do.  

An fixed update to this needs to be released urgently.

**Comment by Leprazoriy** [comment]
Urgently withdraw version 9.1.0! Stopped our office work.

**Comment by DragDrop69** [comment]
same thing.. Nextcloud Snap can't work with Onlyoffice Docs Server
Onlyoffice app version -  9.1.0
Nextcloud Snap version 27.1.7

maybe give me manual about downgrade Onlyoffice app in Nextcloud Snap

**Comment by Scriptkiddi** [comment]
Onlyoffice 7.10 is also affected

**Comment by phreaker0** [comment]
just installed v9.1.2 from the release page and can confirm that it works, thx.

**Comment by Leprazoriy** [comment]
9.1.2 work for me.

**Comment by SergeyKorneyev** [comment]
Version 9.1.2 should resolve this issue. If it does not, please let us know.

**Comment by PifPof73** [comment]
> > @arnowelzel something seems off, because I cleared the browser data (even tried on incognito mode) and I can see the previous values every time. Those values are clearly empty in the db: https://i.imgur.com/KzWHEIn.jpeg
> 
> Strange - for me that worked fine and I have no idea from where else OnlyOffice should get the value from.
> 
> Maybe restart php-fpm just to be sure, that also the PHP opcache is flushed?

I had the same problem and restarting php-fpm solved it. I could reach the admin page again and type the old value into it. Since than it is running again with Version 9.0.0

**Comment by stepcellwolf** [comment]
Even with the latest version, 9.1.2 having a issue:
`Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.) (version 7.5.1.23)`

**Comment by W3XTR1337** [comment]
Upgrade to 9.1.2 didn't work. Running cloud 27.1.8 on Ubuntu 20.04. Common settings reappeared and I can change them, but now I have missing area with extensions which OnlyOffice should open and he is still downloading files.
![Screenshot 2024-04-09 at 10 54 03](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/assets/79478776/067a6f4c-826d-4060-a51d-aa1c039dd578)

**Comment by mmallejac** [comment]
I have reverted to app v9.0.0 and now is ok
https://github.com/ONLYOFFICE/onlyoffice-nextcloud/releases/download/v9.0.0/onlyoffice.tar.gz
v9.1.2 does not have a js subfolder ??

**Comment by arnowelzel** [comment]
It seems, 9.1.2 fixes the issue and also brings back the missing `js` folder (at least on my test instances). You may have to completely disable and remove your existing installation first (maybe remove the folder `apps/onlyoffice` from your Nextcloud installation top be sure) and then reinstall 9.1.2 as a new app. If configuration fails, try removing the URL setting, so OnlyOffice allows you reconfigure the URL of the backend in the administrative settings:

```
update oc_appconfig set configValue='' where appid='onlyoffice' and configKey='DocumentServerUrl';
```

Thanks for the quick response to @LinneyS.

**Comment by jdaviescoates** [comment]
Just updating to 9.1.2 worked for me. Thanks @LinneyS

**Comment by stepcellwolf** [comment]
> > It does work after copying 9.0.0 js folder as @Nikos-Mennecy pointed out
> > on your server :
> > 1 grab the 9.0 relaease
> > ```shell
> > wget https://github.com/ONLYOFFICE/onlyoffice-nextcloud/releases/download/v9.0.0/onlyoffice.tar.gz
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 2 expend
> > ```shell
> > tar -xf onlyoffice.tar.gz
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 3 copy js folder to where it should be
> > ```shell
> > sudo cp -R onlyoffice/js/ /var/lib/docker/volumes/nextcloud_aio_nextcloud/_data/custom_apps/onlyoffice/js
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 4 change ownership
> > ```shell
> > sudo chown -R www-data:www-data /var/lib/docker/volumes/nextcloud_aio_nextcloud/_data/custom_apps/onlyoffice/js
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 5 cleanup a bit
> > ```shell
> > rm -rf onlyoffice onlyoffice.tar.gz
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 6 go to NC webUI > admin settings > OnlyOffice and hit save
> > Edit : I guess the [new gitignore](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/commit/d2e42377202f19c5280d3cf4a9828432a5b88c1f#) file is the explanation...
> 
> Using this option it saves the onlyoffice configuration, but when I try to open a document, it keeps trying forever.... Direct tests on the onlyoffice server work normally. Only the integration has a problem following the plugin update.

This is the only solution that worked for me in yunohost and manually install the app to `/var/www/nextcloud/apps/` and `chown -R nextcloud:www-data onlyoffice` and enable it via admin in NC settings and it should work.

**Comment by rchaconmolero** [comment]
After updating from 9.0.0 to 9.1.2 we got this message.

After uninstalling the app and reinstalling, this message continues to appear.

jsresourceloader error
Could not find resource onlyoffice/js/desktop.js to load

**Comment by osm-frasch** [comment]
Does anyone still have the following error message in the Nextcloud log? 
jsresourceloader 
Could not find resource onlyoffice/js/desktop.js to load

We have installed the hotfix. 
In general, OnlyOffice is running again. (Nextcloud 28.0.4)

**Comment by MichaelHeimann** [comment]
fixed by:
1) disable onlyoffice addon in nextcloud
2) remove onlyoffice addon in nextcloud
3) "sudo mysql nextcloud" on nextcloud server
4) "update oc_appconfig set configValue='' where appid='onlyoffice' and configKey='DocumentServerUrl';" to remove the url
5) sudo apache2ctl reload
6) sudo restart php-fpm
7) add onlyoffice addon and configure it again

**Comment by masterwishx** [comment]
> Version 9.1.2 should resolve this issue. If it does not, please let us know.

Thanks , working Fine now

**Comment by vagner-dias** [comment]
> @LinneyS - Please help on this issue - is cause massive problems

V9.1.2 fixed my issue. Thanks @LinneyS !

**Comment by Petersoj** [comment]
Thanks for releasing a fast patch release! `9.1.2` fixes this issue on my NC instance.

**Comment by alyfilipe** [comment]
For me not funcition. Save configuration with sucess, but if i try open a document:

Error    richdocuments      GuzzleHttp\Exception\ConnectException: cURL error 28: Connection timed out after 45001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)   2024-04-10T02:37:49+00:00
                              for http://onlyoffice.gigacandanga.com.br:9980/hosting/discovery at .../guzzlehttp/guzzle/src/Handler/CurlFactory.php line 210

With 9.0.0 plugin work fine.

**Comment by LinneyS** [comment]
Thanks to everyone for reporting the problem.
Release 9.1.2 fixes this issue
A separate issue #981 has been created regarding the problem with the desktop file.

**Comment by joskapista44** [comment]
> We also have the following error message in the Nextcloud log
> 
> _jsresourceloader Could not find resource onlyoffice/js/desktop.js to load_
> 
> We have installed the hotfix. In general, OnlyOffice is running again. (Nextcloud 28.0.4)

Yes, I still have this in my log. The app works, but I get the error message in my log really often.

**Comment by arnowelzel** [comment]
I created a pull request yesterday for the fix. Hopefully this will be sorted out with the next update. It seems only to affect widgets not the regular application.

**Comment by stephan1827** [comment]
Anybody knows when the docker is updated?
