### ISSUE TITLE
 After Upgrade to 7.10 Nextcloud not connected to onlyoffice server

### ISSUE THREAD

**Issue by Scriptkiddi** [ONLYOFFICE/onlyoffice-nextcloud#979]
We are experiencing the same issue as with the 9.1.0 version (#977 )
And as the 9.1.2 was released I just wanted to track this somewhere as well for the 7.10 version

**Comment by SergeyKorneyev** [comment]
Since version 7.10 is used for Nextcloud 26, it's built differently from version 9.1.0 for Nextcloud 28, so it should not be the same issue. Could you provide more information about your particular scenario?

**Comment by Scriptkiddi** [comment]
We upgraded to version 9
