### ISSUE TITLE
presenter mode not working

### ISSUE THREAD

**Issue by laopisai** [ONLYOFFICE/onlyoffice-nextcloud#98]
Cannot get presenter view to working for slides.

Found error messages in /var/log/onlyoffice/documentserver/docservice:
```
checkJwt error: docId = 123456789 name = JsonWebTokenError message = invalid signature token
```

I am using a self signed SSL cert and node version is 6.16

**Comment by HelenBelova17** [comment]
Hello, @**laopisai**, what version Nextcloud and Document Server do you use?

**Comment by laopisai** [comment]
Nextcloud: 16.0.1
Nextcloud onlyoffice connector: 2.3.0
document server: 5.3.1

**Comment by HelenBelova17** [comment]
@**laopisai**, unfortunately, I cannot reproduce the issue on our side. Did this issue occur before the updating Nextcloud onlyoffice connector from version 2.1.0 to 2.3.0?

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs or we can close the topic?

**Comment by laopisai** [comment]
Issue fixed after we changed to docker version. 
I will close this issue
