### ISSUE TITLE
can't save saettings of nextcloud client

### ISSUE THREAD

**Issue by shuraka** [ONLYOFFICE/onlyoffice-nextcloud#989]
Fresh client (9.2.0) install on nextcloud (28.0.5).
Trying to save settings but nothing happen.
Console output:
Uncaught TypeError: Cannot read properties of undefined (reading 'collection')
    at HTMLDocument.<anonymous> (settings.js:91:23)
    at u (jquery.js:3489:29)
    at d (jquery.js:3557:12)

**Comment by svenkampe** [comment]
Exactly the same Problem here.
Update nextcloud 28.04 -> 28.05 and onlyoffice client settings do not respond on any changes.
The Save button is not working.

**Comment by g0ha1** [comment]
Same problem NC29, client 9.2.0

**Comment by Emergency1999** [comment]
same problem here, NC28.0.5, Client 9.2.0.
still works on NC27.1.5, Client 8.2.4

**Comment by khau99** [comment]
Same issue while using TrueChart's app after upgraded from 28 to 29. All works except this save button. 

What drives me nuts is that if i fresh install Nextcloud V29 directly, the button works

**Comment by ostasevych** [comment]
The same issue at 28.0.5. I've rolled back to 9.1.0.

**Comment by mherrb** [comment]
Hi, same issue here using Hetzner's your-storageshare.de hosting... I hope a fix can be found as one of the main use of this instance would be shared editing (I have an external document server for this). Hetzner doesn't allow customers to roll back the applications.

**Comment by cleuenberg** [comment]
Same issue on NextCloud 28.0.3 with OnlyOffice 9.2.0.
<img width="1085" alt="Bildschirmfoto 2024-05-15 um 16 03 50" src="https://github.com/ONLYOFFICE/onlyoffice-nextcloud/assets/3812126/657286d1-0efd-4720-b2a7-a2bf50760894">

**Comment by Misokados** [comment]
Hello,
We are checking the situation. We will update this thread as soon as possible.

**Comment by kgraefe** [comment]
I have the same issue, but different error messages: 
```
Uncaught TypeError: o.SystemTags is undefined
    <anonymous> settings.js:91
```

However, it's the same line, so probably due to a different browser or sth.? I use Firefox

**Comment by kgraefe** [comment]
Enabling the app "Collaborative tags" fixes it for me.

**Comment by Misokados** [comment]
We have prepared test build of the connector app for Nextcloud v.29: [Artifact · ONLYOFFICE/onlyoffice-nextcloud@e4f9234 · GitHub 2](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/actions/runs/9163130956)
It resolves the described situation.
You need to disable and remove current connector app and after that install the test build manually: [ONLYOFFICE Api Documentation - Nextcloud ONLYOFFICE integration app 1](https://api.onlyoffice.com/editors/nextcloud#install)
After that clear browser cache and check the situation.
The official fix release is planned for the next version of the connector app.

**Comment by scgf** [comment]
How do I manually install an app when I have Nextcloud running in a Docker container? The advice I have read online tells me to drop the unzipped folder into nextcloud/apps - I have no such directory with Docker. Any ideas?
