### ISSUE TITLE
Nextcloud App settings can not be saved

### ISSUE THREAD

**Issue by xbluemonkx** [ONLYOFFICE/onlyoffice-nextcloud#991]
Hi,
we are running NC 29.0.0 and OnlyOffice App 9.2.0.

At the moment office documents are not opened with the app instead they are downloaded immediately.

Going into the App settings in NC the "Common Settings" section is missing. When I try to change / update the only office server and clik "save" button, the changes are not saved.

Is this a known bug? Is this a duplicate of this - https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/956 ?

This is very critical to us as most of our users work exclusively in the browser and are not able to work on their files at the moment.

**Comment by NSO73** [comment]
Same.
I manually installed 9.1.2 version and it's working on NC 29.

`cd apps/`
`wget https://github.com/ONLYOFFICE/onlyoffice-nextcloud/releases/download/v9.1.2/onlyoffice.tar.gz`
`tar -xf onlyoffice.tar.gz`
`rm onlyoffice.tar.gz`

**Comment by isaacte** [comment]
Same problem here.
`PUT https://cloud_instance.com/apps/onlyoffice/ajax/settings/address 400 (Bad Request)`
