### ISSUE TITLE
ONLYOFFICE is currently not available

### ISSUE THREAD

**Issue by georgy62** [ONLYOFFICE/onlyoffice-nextcloud#993]
Hello everyone, 

I'm running nexctcloud 29 and ONLYOFFICE 9.2.0 together with the documentserver_community on a rented server. Unfortunately, when I open a document in *docx format, I get the following error message: "ONLYOFFICE is currently not available. Please contact your administrator". 

SSL and HSTS are activated on the server. Under the ONLYOFFICE settings, the path to the document server has been set and confirmed with https://[domain]/index.php/apps/documentserver_community/. 

The file [domain]/config/config.php contains, among others, the following lines: 

'overwrite.cli.url' => 'https://[domain]',
'overwriteprotocol' => 'https',
'allow_local_remote_servers' => true,

Is there a compatible version of ONLYOFFICE or is there something I can do to get it working?

Thank you for your response
georgy62

**Comment by LinneyS** [comment]
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://forum.onlyoffice.com/t/community-document-server-app-in-nextcloud-18/268).
